const groups=[
['Foundational Stories','Genesis',50],['Psalms & Prayer','Psalms',30],['Life of Jesus','John',21],
['Practical Christian Living','Galatians',6],['Practical Christian Living','Ephesians',6],['Practical Christian Living','Philippians',4],['Practical Christian Living','Colossians',4],['Practical Christian Living','James',5],['Practical Christian Living','Hebrews',13]
];
const studies={
'Genesis 1':{theme:'God orders creation and gives image-bearing humanity a vocation within His good world.',key:'Genesis 1:26–28',body:`
<h3>Chapter at a glance</h3><p>Genesis opens with God already present. The chapter moves from an unformed, unfilled world toward ordered fullness: light and darkness, waters and sky, land and vegetation, heavenly lights, living creatures, and finally humankind. Again and again God speaks, creation answers, and God calls His work good. The repeated pattern makes the chapter feel deliberate rather than hurried.</p>
<h3>Look closely</h3><p>The first chapter is structured by repeated phrases: “God said,” “it was so,” “God saw that it was good,” and numbered days. Days 1–3 establish ordered realms; days 4–6 populate those realms. The literary shape keeps the reader's attention on the sovereign Speaker. Creation is not portrayed as God struggling to gain control. His word is sufficient.</p><p>The climax is not the sun or stars but humanity. Male and female are made in God's image and likeness and are blessed to be fruitful and exercise dominion. In the Bible's developing story, bearing God's image is tied to representing His rule in the world. That gives human life dignity, but also responsibility: dominion is delegated, never independent ownership.</p>
<h3>Word & idea notes</h3><p><strong>Image / likeness (1:26–27).</strong> The text distinguishes humanity from the creatures made “according to their kind.” Humans are patterned in relation to God and commissioned to rule beneath Him. BibleProject summarizes this as humanity serving as God's representatives or co-rulers in creation.</p><p><strong>Good / very good.</strong> “Good” accumulates through the chapter; after humanity and the completed provision of the earth, God sees the whole as “very good” (1:31). The biblical story therefore begins with creation as gift and ordered good, not as something inherently evil.</p>
<h3>Follow the thread</h3><div class="xref"><strong>John 1:1–3</strong> — John deliberately opens with “In the beginning” and presents the Word as active in creation. Read Genesis 1 beside John 1 to see creation language become the doorway into John's presentation of Christ.</div><div class="xref"><strong>Colossians 1:15–17</strong> — Paul calls Christ the image of the invisible God and locates all creation in, through, and for Him. This deepens both Genesis's creation theme and its language of image.</div><div class="xref"><strong>Hebrews 11:3</strong> — Hebrews looks back to creation by God's word as something apprehended by faith.</div><div class="xref"><strong>Revelation 4:11</strong> — Creation becomes a reason for worship: all things exist by God's will.</div>
<h3>Why this matters</h3><p>Genesis 1 gives the rest of Scripture its starting grammar: God is Creator; the world belongs to Him; His word brings order and life; human beings possess God-given dignity; and our authority is accountable to the One whose image we bear. Before Scripture tells us what went wrong, it tells us what God intended and repeatedly calls good.</p>
<h3>For your notebook</h3><div class="note"><strong>Notice:</strong> What changes in the chapter each time God speaks?<br><strong>Trace:</strong> Follow “image” from Genesis 1:26–27 to Colossians 1:15 and Hebrews 1:3.<br><strong>Reflect:</strong> How is “the world belongs to God” different from treating creation—or your own life—as something you possess absolutely?</div>
<h3>Research trail</h3><p class="sources">Checked against Genesis 1; BibleProject, <em>Genesis 1</em> visual commentary and <em>Image of God</em> theme study; cross-reference sets checked against John 1:1–3, Colossians 1:15–17, Hebrews 11:3, and Revelation 4:11. Interpretive claims are paraphrased rather than copied. Pastor material is not included without verified source and permission.</p>`},
'Genesis 2':{theme:'God gives holy rest, meaningful work, moral boundaries, and human companionship within Eden.',key:'Genesis 2:7, 15, 18, 24',body:`
<h3>Chapter at a glance</h3><p>Genesis 2 begins where the first creation account was heading: completion and rest. It then narrows the lens from the whole cosmos to the human vocation in Eden. The LORD God forms the man from dust, breathes life into him, plants a garden, gives him work and a command, and declares for the first time that something is “not good”: the man's aloneness. The chapter ends with woman and man together, one flesh and unashamed.</p>
<h3>Look closely</h3><p>God's rest in 2:1–3 is not presented as recovery from weakness; creation is finished, and the seventh day is blessed and made holy. Later Scripture explicitly reaches back to this passage when explaining Sabbath (Exodus 20:8–11) and develops the motif of entering God's rest (Hebrews 4:4–11).</p><p>The man is both humble and honored: formed from <em>dust</em>, yet living by breath God gives. He is placed in the garden “to tend and keep it” (2:15). Work therefore appears before the fall. Genesis 3 will make work painful; Genesis 2 does not make work itself a curse.</p>
<h3>Word & idea notes</h3><p><strong>Adam / ground.</strong> The Hebrew narrative uses a wordplay between <em>’adam</em> (human/man) and <em>’adamah</em> (ground). The human creature is earthbound and dependent, yet receives life from God.</p><p><strong>Helper corresponding to him (2:18).</strong> The point is not that the woman is an assistant of lesser worth. The narrative stresses correspondence: among the animals no fitting counterpart is found; the woman is recognized as “bone of my bones and flesh of my flesh.”</p>
<h3>Follow the thread</h3><div class="xref"><strong>Exodus 20:8–11</strong> — The Sabbath command grounds Israel's rhythm of work and rest in God's creation pattern.</div><div class="xref"><strong>Matthew 19:4–6</strong> — Jesus joins Genesis 1:27 and Genesis 2:24 when speaking about marriage, treating the creation texts as belonging together.</div><div class="xref"><strong>Ephesians 5:31–32</strong> — Paul quotes Genesis 2:24 and then uses marriage as a sign pointing beyond itself to Christ and the church.</div><div class="xref"><strong>Hebrews 4:4–11</strong> — Genesis 2:2 becomes part of a larger biblical theology of God's rest and the call to enter it.</div>
<h3>Why this matters</h3><p>Genesis 2 portrays creaturely life as received rather than self-made. Breath, place, food, vocation, moral limits, rest, and relationship all come from God. The boundary around the tree also shows that abundance and obedience belong together: human freedom in Eden is real, but it is not autonomy from the Creator.</p>
<h3>For your notebook</h3><div class="note"><strong>Notice:</strong> List everything God gives before He gives the prohibition in verses 16–17.<br><strong>Compare:</strong> Read Genesis 2:24 beside Matthew 19:4–6. Notice which parts of Genesis Jesus brings together.<br><strong>Reflect:</strong> Which is harder to receive as a gift rather than control—work, rest, limits, or relationship?</div>
<h3>Research trail</h3><p class="sources">Checked against Genesis 2; Exodus 20:8–11; Matthew 19:4–6; Ephesians 5:31–32; Hebrews 4:4–11; and BibleProject's wilderness/Eden study for the garden-to-wilderness pattern. Hebrew observations are kept modest and tied to the text. Pastor material remains excluded pending verified source and permission.</p>`}
};
const chapters=[];for(const [collection,book,count] of groups){for(let n=1;n<=count;n++)chapters.push({collection,book,n,id:`${book} ${n}`})}
const cards=document.querySelector('#cards'),dlg=document.querySelector('#study'),body=document.querySelector('#studyBody');
function render(filter='all'){cards.innerHTML='';chapters.filter(c=>filter==='all'||c.collection===filter).forEach(c=>{const s=studies[c.id],el=document.createElement('button');el.className='card '+(s?'ready':'pending');el.disabled=!s;el.innerHTML=`<span class="status">${s?'Study ready':'Research in progress'}</span><h3>${c.id}</h3><p>${s?s.theme:c.collection}</p>`;if(s)el.onclick=()=>openStudy(c,s);cards.appendChild(el)})}
function openStudy(c,s){body.innerHTML=`<p class="eyebrow">${c.collection}</p><h2>${c.id}</h2><p class="key"><strong>Key passage:</strong> ${s.key}</p><p>${s.theme}</p>${s.body}`;dlg.showModal();dlg.scrollTop=0}
document.querySelector('.close').onclick=()=>dlg.close();dlg.addEventListener('click',e=>{if(e.target===dlg)dlg.close()});document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');render(t.dataset.filter)});render();