const groups=[
['Foundational Stories','Genesis',50],['Psalms & Prayer','Psalms',30],['Life of Jesus','John',21],
['Practical Christian Living','Galatians',6],['Practical Christian Living','Ephesians',6],['Practical Christian Living','Philippians',4],['Practical Christian Living','Colossians',4],['Practical Christian Living','James',5],['Practical Christian Living','Hebrews',13]
];
const studies={
'Genesis 1':{theme:'Selected places to pause in the opening chapter of Scripture.',key:'Genesis 1:1–3, 26–31',body:`
<h3>Bookmarks</h3>
<div class="note"><strong>🔖 Genesis 1:1 — Start with God.</strong><p>Scripture does not begin by arguing its way toward God. It begins with Him: before the heavens and earth, God is. The first verse also establishes the basic distinction that runs through the Bible—God is Creator; everything else is creation.</p><p><strong>Follow it:</strong> Psalm 90:2; John 1:1–3; Hebrews 11:3.</p></div>
<div class="note"><strong>🔖 Genesis 1:2–3 — The Spirit, the Word, and light.</strong><p>Before the ordered world appears, the Spirit of God is present over the deep; then God speaks. Notice how often the chapter repeats “God said.” Creation answers His word. Spurgeon returned to Genesis 1:2 and 1:4 when preaching about God's work of new creation in a person—not as a replacement meaning for Genesis, but because Scripture itself later uses creation-and-light language for God's saving work (2 Corinthians 4:6).</p><p><strong>Follow it:</strong> Psalm 33:6, 9; 2 Corinthians 4:6.</p></div>
<div class="note"><strong>🔖 Genesis 1:26–27 — “In Our image.”</strong><p>Human beings are not merely another creature “according to its kind.” Male and female receive a unique God-given dignity and calling. Matthew Henry lingered here: humanity resembles the Creator rather than the creatures that came before, while still remaining infinitely beneath God. The next verse ties this image-bearing life to delegated rule.</p><p><strong>Follow it:</strong> Genesis 5:1–3; Genesis 9:6; Colossians 1:15; James 3:9.</p></div>
<div class="note"><strong>🔖 Genesis 1:31 — “Very good.”</strong><p>Earlier works are called good; after the completed creation, God sees the whole and calls it “very good.” Before Genesis tells us what sin damages, it makes us look carefully at what God made and how He regarded it.</p></div>
<h3>Sources beside the open Bible</h3><p class="sources">Primary: Genesis 1 and the cross-references above. Historic companions checked: Matthew Henry on Genesis 1:26–28; John Gill on Genesis 1; C. H. Spurgeon, “The Spirit's Work in the New Creation” (Genesis 1:2) and “The First Day of Creation” (Genesis 1:4). These voices are used selectively, not as substitutes for the text. Pastor Brian material remains excluded pending a verifiable source and permission.</p>`},
'Genesis 2':{theme:'Selected places to pause: rest, received life, vocation, limits, and companionship.',key:'Genesis 2:2–3, 7, 15–18, 24–25',body:`
<h3>Bookmarks</h3>
<div class="note"><strong>🔖 Genesis 2:2–3 — The first thing called holy.</strong><p>The seventh day is blessed and sanctified because God's creative work is complete. Later Scripture deliberately reaches back here when speaking about Sabbath and God's rest.</p><p><strong>Follow it:</strong> Exodus 20:8–11; Hebrews 4:4–11.</p></div>
<div class="note"><strong>🔖 Genesis 2:7 — Dust and breath.</strong><p>The picture holds humility and dignity together. The man is formed from the dust of the ground, yet life is personally received from God. Our life is neither self-created nor self-sustaining.</p><p><strong>Notice:</strong> Genesis will return to the dust in 3:19.</p></div>
<div class="note"><strong>🔖 Genesis 2:15 — Work is older than the curse.</strong><p>Adam is placed in Eden to tend and keep it before sin enters the story. Genesis 3 makes labor painful and resistant; it does not introduce work itself. That small distinction matters whenever work is treated as though it were inherently a punishment.</p></div>
<div class="note"><strong>🔖 Genesis 2:18 — The first “not good.”</strong><p>After the repeated goodness of Genesis 1, these words stand out: “It is not good that man should be alone.” Matthew Henry's old phrase is useful here: the promised helper is one “of the same nature and the same rank of beings.” The animals cannot provide the corresponding human companionship God intends.</p></div>
<div class="note"><strong>🔖 Genesis 2:24 — Jesus comes back here.</strong><p>When questioned about marriage, Jesus joins Genesis 1:27 and Genesis 2:24. Paul later quotes this verse while speaking about Christ and the church. A short verse near the beginning of Scripture develops a remarkably long biblical thread.</p><p><strong>Follow it:</strong> Matthew 19:4–6; Ephesians 5:31–32.</p></div>
<h3>Sources beside the open Bible</h3><p class="sources">Primary: Genesis 2 and the cross-references above. Historic companions checked: Matthew Henry on Genesis 2, especially 2:18; John Gill on Genesis 2. Historic observations are included only where they illuminate a selected bookmark. Pastor Brian material remains excluded pending a verifiable source and permission.</p>`}
};
const chapters=[];for(const [collection,book,count] of groups){for(let n=1;n<=count;n++)chapters.push({collection,book,n,id:`${book} ${n}`})}
const cards=document.querySelector('#cards'),dlg=document.querySelector('#study'),body=document.querySelector('#studyBody');
function render(filter='all'){cards.innerHTML='';chapters.filter(c=>filter==='all'||c.collection===filter).forEach(c=>{const s=studies[c.id],el=document.createElement('button');el.className='card '+(s?'ready':'pending');el.disabled=!s;el.innerHTML=`<span class="status">${s?'Bookmarks ready':'Research in progress'}</span><h3>${c.id}</h3><p>${s?s.theme:c.collection}</p>`;if(s)el.onclick=()=>openStudy(c,s);cards.appendChild(el)})}
function openStudy(c,s){body.innerHTML=`<p class="eyebrow">${c.collection}</p><h2>${c.id}</h2><p class="key"><strong>Places to pause:</strong> ${s.key}</p><p>${s.theme}</p>${s.body}`;dlg.showModal();dlg.scrollTop=0}
document.querySelector('.close').onclick=()=>dlg.close();dlg.addEventListener('click',e=>{if(e.target===dlg)dlg.close()});document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');render(t.dataset.filter)});render();
