// John 10 — Living Bookmark card.
Object.assign(studies,{
 'John 10':{body:''}
});

Object.assign(studyMeta,{
 'John 10':{
  oneLine:'Jesus presents Himself as the Door and the Good Shepherd who knows His sheep, gives His life for them, gathers one flock, keeps them securely in the Father’s hand, and answers a blasphemy charge by pressing His opponents to take Scripture and His works seriously.',
  write:[
   {ref:'John 10:9',title:'Jesus is not merely standing near the door.',text:'He says, “I am the door,” and ties safety, freedom, and pasture to entering through Him.'},
   {ref:'John 10:10',title:'Abundant life is life under the Shepherd, not a promise of luxury.',text:'Jesus contrasts His life-giving care with the thief who steals, kills, and destroys.'},
   {ref:'John 10:11',title:'The Good Shepherd does not save Himself at the sheep’s expense.',text:'He gives His life for the sheep.'},
   {ref:'John 10:14',title:'Jesus knows His sheep personally.',text:'The Shepherd’s care is not anonymous: “I know my sheep, and am known of mine.”'},
   {ref:'John 10:28',title:'The sheep are held by more than their own grip.',text:'Jesus gives eternal life and says no one will snatch them from His hand.'},
   {ref:'John 10:30',title:'The Son’s work cannot be separated from the Father’s.',text:'After speaking of the Father’s hand and His own, Jesus says, “I and my Father are one.”'}
  ],
  underline:{ref:'John 10:11',reason:'Jesus defines the Good Shepherd by self-giving love: He lays down His life for the sheep.'},
  notice:[
   {ref:'John 10:1-6',title:'The shepherd picture continues the conflict of John 9 rather than beginning a disconnected sermon.',text:'Jesus has just condemned leaders who claim to see while casting out the man He healed. He now contrasts the true shepherd, whose sheep know his voice, with thieves and strangers. The chapter is about both the Shepherd and the kind of leadership that either serves or uses God’s flock.'},
   {ref:'John 10:7-10',title:'Jesus shifts the picture and calls Himself the Door.',text:'A parable does not have to assign one fixed meaning to every object. Jesus first speaks as Shepherd and then as the Door through whom the sheep enter for safety and pasture. “Life more abundantly” belongs to this shepherding context: fullness of life in Him, not a blank check for wealth, health, comfort, or an easy life.'},
   {ref:'John 10:11-15',title:'The Good Shepherd is defined by laying down His life, not merely by being kind.',text:'The hired hand runs when the wolf comes because the sheep are not his own. Jesus knows His sheep and stays when danger costs Him everything. He then compares the mutual knowing between Shepherd and sheep with His own relationship to the Father—a startlingly deep picture of belonging and communion.'},
   {ref:'John 10:16',title:'The “other sheep” widen the horizon beyond the present fold.',text:'The immediate setting is Israel, yet Jesus speaks of sheep not presently in “this fold” whom He also must bring. The early church naturally heard the Gentile mission in this widening promise. There will be one flock under one Shepherd. The KJV says “one fold,” but the Greek changes words: the final term means flock, not the enclosure itself. Unity is in the Shepherd, not in making every sheep enter one old boundary.'},
   {ref:'John 10:17-18',title:'The cross is not presented as Jesus losing control of events.',text:'He says no one takes His life from Him in the ultimate sense; He lays it down willingly and has authority to take it again. Human agents will truly kill Him, but His death also belongs to the Father’s command and the Son’s willing obedience.'},
   {ref:'John 10:22-30',title:'The Feast of Dedication setting places this argument in Jerusalem during winter.',text:'The feast later known as Hanukkah remembered the temple’s rededication after its desecration. In Solomon’s porch Jesus is pressed to speak plainly about being Messiah. He points again to His works and then speaks of His sheep hearing His voice, eternal life, and the inseparable keeping power of His hand and the Father’s hand.'},
   {ref:'John 10:30-33',title:'“I and my Father are one” is heard by Jesus’ opponents as far more than agreement of opinion.',text:'The Greek word for “one” is neuter, so Jesus is not saying He and the Father are the same person. Yet the surrounding claim is stronger than two teachers agreeing: the Son gives eternal life, no one can snatch from His hand, the Father’s hand is likewise secure, and His opponents answer by accusing Him of making Himself God.'},
   {ref:'John 10:34-36',title:'Psalm 82 does not function as Jesus backing away from His claim.',text:'Jesus quotes “I said, Ye are gods” from Psalm 82. Interpreters differ over exactly whom the psalm calls “gods”—human judges, Israel receiving God’s word, or heavenly rulers—but Jesus’ argument works from lesser to greater: if Scripture can use that startling title in a subordinate case, calling the One the Father sanctified and sent “Son of God” cannot simply be dismissed as blasphemy. “The scripture cannot be broken” makes the wording of Scripture part of His argument.',cross:[{ref:'Psalm 82:6',label:'Direct quotation',reason:'Jesus quotes this verse when answering the charge that His Son-of-God claim is blasphemous.'}]},
   {ref:'John 10:37-39',title:'Jesus tells them to examine the works rather than believe a bare claim detached from evidence.',text:'If He does not do the Father’s works, He says not to believe Him; if He does, then even reluctant hearers should let those works press the question of the Father in Him and He in the Father. John’s signs are never meant to be stage tricks. They testify to identity.'},
   {ref:'John 10:40-42',title:'The chapter closes where John the Baptist had ministered, and his witness keeps bearing fruit after his own ministry has ended.',text:'John performed no sign, but people remember that everything he said about Jesus was true. The witness has disappeared from center stage; the truth he pointed to remains.'}
  ],
  reflections:['When I think of “abundant life,” have I let comfort or possessions define it more than the presence and care of Christ?','Whose voice most easily competes with the Shepherd’s voice in my daily decisions?'],
  commentary:{voice:'Alexander Maclaren',identity:'Scottish Baptist preacher and expositor, 1826–1910',quote:'God’s flock was wider than God’s fold.',plain:'Maclaren catches the force of Jesus’ “other sheep.” God’s saving purpose is wider than the boundary Jesus’ first hearers assumed contained the whole flock. The goal is not several rival shepherds or permanent separated flocks, but one flock gathered around the one Shepherd.',source:'Expositions of Holy Scripture — John 10',url:'https://biblehub.com/commentaries/maclaren/john/10.htm'},
  question:{q:'Why does Jesus quote “Ye are gods” from Psalm 82?',short:'He is answering a blasphemy charge with Scripture: if the biblical text can use “gods” in a lesser, derivative sense, His opponents cannot reject the title “Son of God” merely because it sounds too exalted.',more:'Psalm 82 itself is interpreted in more than one serious way. Some understand the “gods” as unjust human rulers or judges; others see a heavenly council; another old line of interpretation connects the wording with people who received God’s word. John 10 does not require Bookmark to settle every detail of Psalm 82 before following Jesus’ argument. He reasons from the lesser case to Himself—the One the Father sanctified and sent into the world—and then immediately points back to His works as evidence of the Father in Him. He is not saying, “Everyone is divine, so my claim means nothing.” The controversy continues precisely because His claim remains exceptional.'}
 }
});
render();