// Acts 14 — Living Bookmark card.
Object.assign(studies,{
 'Acts 14':{body:''}
});

Object.assign(studyMeta,{
 'Acts 14':{
  oneLine:'Paul and Barnabas preach boldly in Iconium until threatened violence sends them into Lycaonia; at Lystra Paul heals a man unable to walk from birth, refuses the crowd’s attempt to worship the missionaries as Zeus and Hermes, and calls them to the living Creator, but the same crowd is soon persuaded to stone Paul; after surviving, the missionaries retrace the dangerous route to strengthen the new churches, appoint elders, and return to Antioch reporting that God has opened a door of faith to the Gentiles.',
  write:[
   {ref:'Acts 14:3',title:'The message is called “the word of his grace.”',text:'Signs confirm a gospel whose center is God’s grace, not the greatness of the messengers.'},
   {ref:'Acts 14:9-10',title:'Paul sees faith, but the healing remains God’s gift.',text:'The man’s response matters; his disability is never treated as proof that he had previously failed to believe enough.'},
   {ref:'Acts 14:15',title:'Real servants of God refuse worship that belongs to God.',text:'Paul and Barnabas run into the crowd insisting, “We also are men.”'},
   {ref:'Acts 14:17',title:'Ordinary rain and food are witnesses of extraordinary kindness.',text:'God’s providence has been speaking even where Scripture was not yet known.'},
   {ref:'Acts 14:22',title:'The road into God’s kingdom is not advertised as painless.',text:'New believers are strengthened with the truth that many tribulations will come.'},
   {ref:'Acts 14:27',title:'The missionaries report what God did, not what they built.',text:'He opened the door of faith to the Gentiles.'}
  ],
  underline:{ref:'Acts 14:22',reason:'Paul returns to places where he has just been persecuted to strengthen new believers with a sober promise: “we must through much tribulation enter into the kingdom of God.”'},
  notice:[
   {ref:'Acts 14:1-2',title:'Iconium begins with both Jewish and Greek believers—and with specific opponents from the same city.',text:'A great multitude of Jews and Greeks believe, while unbelieving Jews stir Gentiles against the brothers. Luke’s repeated distinctions matter: conflict with some Jewish opponents must not be turned into a story in which “the Jews” as a whole reject Jesus. Jews are among the converts and among the opponents.'},
   {ref:'Acts 14:3',title:'Opposition does not immediately drive Paul and Barnabas away.',text:'They remain “a long time,” speaking boldly in the Lord. God bears witness to “the word of his grace” through signs and wonders. Their courage is not recklessness; they stay while fruitful ministry remains possible and leave when a violent plot becomes concrete.'},
   {ref:'Acts 14:4-7',title:'Fleeing an attempted stoning is not a failure of faith.',text:'When rulers and crowds prepare to abuse and stone them, Paul and Barnabas learn of it and escape to Lystra and Derbe, where they keep preaching. Christian courage can mean staying under pressure, and it can also mean moving out of avoidable danger so the mission continues.',cross:[{ref:'Matthew 10:23',label:'Jesus allowed strategic flight',reason:'Jesus told His disciples that when persecuted in one city they could flee to another.'}]},
   {ref:'Acts 14:8-10',title:'The man at Lystra has never walked; Luke makes the lifelong condition explicit.',text:'He is described as disabled from birth and never having walked. Paul looks intently at him, perceives that he has faith to be healed, and commands him to stand. The man leaps and walks, leaving little room for a gradual recovery explanation.'},
   {ref:'Acts 14:9',title:'“Faith to be healed” must not be turned into a weapon against sick people who remain sick.',text:'Luke tells us what Paul perceived in this man at this moment; he does not teach that every unhealed person lacks faith. Acts has already shown faithful James dying while Peter is rescued, and the wider New Testament includes faithful believers who remain ill or suffer. Healing is God’s gift, not a test by which Christians may shame the sick.'},
   {ref:'Acts 14:11-12',title:'The crowd interprets a Christian miracle through its own pagan story world.',text:'Speaking in their Lycaonian language, they cry that gods have come down in human form. They call Barnabas Zeus and Paul Hermes because Paul is the chief speaker. Local worship of Zeus and Hermes is historically well attested in the region, and later literary tradition also preserves stories of those gods visiting the area in human disguise. That background helps explain how quickly the crowd reaches its conclusion without proving one particular legend caused the reaction.'},
   {ref:'Acts 14:13-14',title:'The attempted sacrifice is not a harmless compliment to the apostles.',text:'The priest of Zeus brings oxen and garlands to the gates. When Paul and Barnabas understand what is happening, they tear their clothes and rush into the crowd in distress. They do not accept worship and then quietly redirect it later; they urgently stop an act that belongs to God alone.'},
   {ref:'Acts 14:15',title:'“Men of like passions” means fellow human beings, not a confession that apostles share every sinful impulse.',text:'The older English word “passions” can mislead modern readers. The Greek means people of the same nature or condition—mortal human beings like the Lystrans. Paul’s point is precisely that he and Barnabas are not gods and should not receive sacrifice.'},
   {ref:'Acts 14:15',title:'Paul’s sermon starts differently in a pagan setting than it did in the synagogue.',text:'In Pisidian Antioch Paul could begin with Israel’s Exodus, David, Scripture, and the promised Messiah. In Lystra he begins with Creator and creation: the living God made heaven, earth, sea, and everything in them. The gospel does not change, but wise witness begins with truths the audience can actually understand.'},
   {ref:'Acts 14:15-17',title:'Calling idols “vanities” does not make creation itself empty or worthless.',text:'The “vain things” are false gods that cannot give life. Paul contrasts them with the living Creator and then points to a world full of His generosity—rain, fruitful seasons, food, and gladness. Created gifts matter because they witness to the living God who gives them.'},
   {ref:'Acts 14:16',title:'God “suffered all nations to walk in their own ways” describes divine patience, not approval of every path.',text:'Before the gospel’s widening mission, God allowed Gentile nations to continue without Israel’s special covenant revelation. Paul immediately says God still left witness to Himself, and he is presently telling the crowd to turn from idols. Permission in providence is not the same thing as moral endorsement.'},
   {ref:'Acts 14:17',title:'Paul appeals to general revelation: God’s goodness can be witnessed in providence before a hearer knows Israel’s Scriptures.',text:'Rain, harvest, food, and gladness are not a complete gospel message, but they are evidence that the Creator has not left Himself without witness. Paul will use a similar creation-and-providence argument in Athens, and Romans 1 will likewise speak of God’s power being perceived through what has been made.',cross:[{ref:'Romans 1:19-20',label:'Creation as witness',reason:'Paul later says God’s invisible power and divine nature are perceived through the created order.'}]},
   {ref:'Acts 14:18-19',title:'The crowd moves with frightening speed from attempted worship to attempted murder.',text:'Paul and Barnabas barely stop the sacrifice. Then opponents arrive from Antioch and Iconium, persuade the crowd, and Paul is stoned and dragged outside the city as though dead. Popular acclaim is therefore shown to be a dangerously unstable foundation for ministry.'},
   {ref:'Acts 14:19-20',title:'Luke says the attackers supposed Paul was dead; he does not explicitly say Paul died and was resurrected.',text:'Some Christians have wondered whether Paul actually died here, especially when comparing later passages about extraordinary heavenly experiences. Acts itself only says the crowd thought he was dead. When the disciples gather around him, he rises and enters the city. The recovery is remarkable without adding a resurrection Luke does not claim.',cross:[{ref:'2 Corinthians 11:25',label:'Paul later remembers a stoning',reason:'Paul says plainly that he was stoned once, almost certainly referring to this event.'}]},
   {ref:'Acts 14:20-21',title:'Paul goes back into Lystra, then later returns again through the very cities that persecuted him.',text:'After being stoned outside Lystra, he enters the city before leaving for Derbe the next day. After making disciples in Derbe, Paul and Barnabas retrace the route through Lystra, Iconium, and Pisidian Antioch. Their return is deliberate pastoral courage: new churches matter enough to revisit dangerous ground.'},
   {ref:'Acts 14:22',title:'“Through many tribulations” is preparation, not a way of earning entrance into the kingdom.',text:'Paul strengthens people who have already believed and urges them to continue in the faith. Suffering does not purchase salvation; it belongs to the road of discipleship in a world resistant to God’s kingdom. The promise is not that every day will be miserable, but that hardship should not surprise believers into thinking God has abandoned them.'},
   {ref:'Acts 14:23',title:'Paul and Barnabas establish local elders instead of keeping every church dependent on visiting apostles.',text:'The Greek verb cheirotoneō can mean appoint or choose and originally carried the picture of extending the hand in a vote. Interpreters differ over how much congregational participation is implied here because Paul and Barnabas are the grammatical subjects. What is clear is that each young church receives recognized local leadership, accompanied by prayer and fasting.'},
   {ref:'Acts 14:23',title:'The elders are finally commended to the Lord, not to the missionaries’ control.',text:'Paul and Barnabas appoint leaders, pray, fast, and entrust them to the Lord in whom they have believed. The churches are not franchises belonging to the missionary team. Their lasting security rests in Christ.'},
   {ref:'Acts 14:24-26',title:'The return to Antioch completes the work for which the church had commended them to God’s grace.',text:'They travel back through Pisidia and Pamphylia, preach at Perga, descend to Attalia, and sail to Syrian Antioch. Luke describes the mission as “fulfilled,” not because every person believed or every city became safe, but because the assigned work was faithfully carried through.'},
   {ref:'Acts 14:27',title:'Their missionary report gives God the verbs.',text:'They gather the church and rehearse “all that God had done with them” and how He had opened the door of faith to the Gentiles. Paul and Barnabas really labored, traveled, preached, suffered, and organized churches, yet their report interprets all of it as God’s action through them.'},
   {ref:'Acts 14:27-28',title:'The “door of faith” is now visibly open to Gentiles, setting up the question Acts 15 must answer.',text:'Gentile churches exist, Gentiles have believed without first becoming Jews, and Antioch has heard the report. The next chapter will face the practical theological question that can no longer be postponed: must these Gentile believers be circumcised and keep the law of Moses in order to be saved?'}
  ],
  reflections:['Do I know when faithfulness calls me to remain under pressure and when wisdom allows me to move out of avoidable danger?','If God used me in a visible way, would I be as urgent as Paul and Barnabas about redirecting admiration toward Him?','Am I prepared for hardship as part of following Christ without interpreting every hardship as evidence that I missed God’s will?'],
  commentary:{voice:'Adam Clarke',identity:'British Methodist theologian and biblical commentator, c. 1762–1832',quote:'we are truly human beings, with the same powers and appetites as your own',plain:'Clarke clarifies the older phrase “men of like passions.” Paul and Barnabas are not telling the crowd that apostles are secretly divine-but-flawed beings; they are insisting on ordinary human creatureliness. The miracle does not elevate the messenger into an object of worship. God alone is the living Creator to whom the crowd must turn.',source:'Commentary on the Bible — Acts 14:15',url:'https://biblehub.com/commentaries/clarke/acts/14.htm'},
  question:{q:'Does Acts 14:9 mean a sick person will be healed if they have enough faith?',short:'No. Luke tells us that Paul perceived faith in this particular man and God healed him, but Scripture never turns that observation into a universal rule that unhealed people are at fault for lacking faith.',more:'The man in Lystra really does respond in faith, and Luke wants us to notice it. But the healing still happens through God’s power, not because faith functions like a lever that forces God to act. In the same book, faithful disciples suffer, James is killed, Paul is stoned, and later Paul will live with weakness rather than receiving every desired deliverance. Elsewhere the New Testament even records believers such as Timothy, Trophimus, and Paul himself dealing with physical weakness or illness. Christians differ over how miraculous healing gifts operate today, but blaming an unhealed person is not a faithful use of Acts 14. The passage invites trust in the living God; it does not give us permission to measure someone else’s faith by their medical outcome.'}
 }
});
render();
