// Acts 8 — Living Bookmark card.
Object.assign(studies,{
 'Acts 8':{body:''}
});

Object.assign(studyMeta,{
 'Acts 8':{
  oneLine:'Persecution scatters Jerusalem believers into Judea and Samaria, where Philip proclaims Christ, heals, and baptizes; Peter and John come so the Samaritan believers receive the Holy Spirit, Simon the magician is sharply rebuked for trying to buy God’s gift, and the Spirit then sends Philip to a Scripture-reading Ethiopian official whom he teaches about Jesus and baptizes on the road.',
  write:[
   {ref:'Acts 8:4',title:'What scattered the believers also scattered the gospel.',text:'They carried the good news into the places persecution forced them to go.'},
   {ref:'Acts 8:12',title:'Philip’s message has a center: God’s kingdom and the name of Jesus Christ.',text:'The signs serve the gospel; they do not replace it.'},
   {ref:'Acts 8:20',title:'God’s gift cannot be bought, controlled, or turned into a spiritual business.',text:'Peter exposes Simon’s desire to possess power rather than receive grace.'},
   {ref:'Acts 8:30-31',title:'A sincere reader can still need help understanding Scripture.',text:'The eunuch’s humility opens the door for Philip to sit beside him and explain.'},
   {ref:'Acts 8:35',title:'Philip begins where the man is reading and leads him to Jesus.',text:'Good teaching listens to the question and then opens the Scriptures toward Christ.'},
   {ref:'Acts 8:39',title:'The teacher disappears, but the new believer goes on rejoicing.',text:'His joy is finally anchored in Christ, not in permanent access to Philip.'}
  ],
  underline:{ref:'Acts 8:35',reason:'Philip does not merely give a detached interpretation of Isaiah; beginning with that Scripture, he proclaims Jesus.'},
  notice:[
   {ref:'Acts 8:1-4',title:'Saul’s persecution becomes the unwanted human cause of the next stage in Acts 1:8.',text:'Believers are scattered into Judea and Samaria, exactly the next regions named in Jesus’ mission outline. Luke does not call persecution good: homes are invaded and believers suffer. But hostile power still cannot keep the gospel inside Jerusalem.',cross:[{ref:'Acts 1:8',label:'The mission map advances',reason:'Jesus had named Jerusalem, Judea, Samaria, and then the ends of the earth as the widening circles of witness.'}]},
   {ref:'Acts 8:2-3',title:'Stephen is mourned while Saul attacks both men and women.',text:'Devout men give Stephen a real burial and make great lamentation. Christian hope does not require pretending death is emotionally small. At the same time Saul enters houses and drags away men and women, showing how deliberate and personal the persecution has become.'},
   {ref:'Acts 8:4-5',title:'The scattered believers evangelize; mission is no longer carried only by the Twelve.',text:'Luke says those who were scattered went about preaching the word, then singles out Philip, one of the Seven from Acts 6. The expansion of the gospel involves ordinary displaced believers and Spirit-gifted servants as well as apostles.'},
   {ref:'Acts 8:5-8',title:'Samaria is a theologically loaded destination, not simply the next town down the road.',text:'Jews and Samaritans carried generations of religious and ethnic hostility. Jesus had already crossed that boundary in John 4 and had specifically named Samaria in Acts 1:8. Philip’s preaching and the city’s joy show the gospel beginning to heal a divide that human history had made deep.',cross:[{ref:'John 4:9',label:'The old hostility',reason:'John explicitly notes that Jews and Samaritans ordinarily did not associate freely.'}]},
   {ref:'Acts 8:9-13',title:'Simon’s old influence was built on amazement, and his first response to Philip is still fascinated by power.',text:'Simon had astonished Samaria with magic and received grand claims from the people. Luke says he believed and was baptized, but also emphasizes that he was amazed by Philip’s signs. Peter’s later rebuke reveals that Simon’s heart still relates to spiritual power as something to possess.'},
   {ref:'Acts 8:13, 20-24',title:'Christians disagree about whether Simon’s “belief” was genuine saving faith, and Acts does not resolve his final condition for us.',text:'Some interpreters understand Simon’s faith as temporary, merely intellectual, or false because Peter says his heart is not right and calls him to repent. Others take Luke’s “believed and was baptized” at face value and see a real believer falling into grave sin. Either way, baptism and outward association are not permission to treat a corrupt heart as harmless, and the passage never tells us Simon’s ultimate destiny.'},
   {ref:'Acts 8:14-17',title:'The Samaritan reception of the Spirit comes in an unusual sequence.',text:'They have received the word and been baptized in Jesus’ name, yet Peter and John pray and lay hands on them before the Holy Spirit “falls” upon them. Christians explain the sequence differently. Many see a unique transition in salvation history that visibly joins Samaritan believers to the Jerusalem church; some traditions also see a pattern related to confirmation or apostolic laying on of hands. Acts later shows other sequences, so this one episode should not be forced into a single mechanical formula for every conversion.'},
   {ref:'Acts 8:14-17',title:'Peter and John do not own the Holy Spirit.',text:'The apostles pray for the Samaritan believers; the Spirit is God’s gift. Their presence publicly confirms that the Samaritan mission is not a rival church breaking away from Jerusalem but part of the same work of Christ across an old boundary.'},
   {ref:'Acts 8:18-23',title:'Simon wants the ability to dispense spiritual power, and Peter exposes the transaction underneath the request.',text:'The later word “simony”—buying or selling church office or spiritual privilege—comes from this episode. Simon’s money is not the central problem by itself; the deeper corruption is imagining that God’s gift can become a commodity controlled by the person who can afford it.'},
   {ref:'Acts 8:22-24',title:'Peter’s severe rebuke still contains a call to repent.',text:'“Thy money perish with thee” is not Peter announcing that repentance is impossible. He immediately tells Simon to repent and pray that the thought of his heart may be forgiven. Strong warning and an open door to mercy stand together.'},
   {ref:'Acts 8:25',title:'Peter and John return to Jerusalem while evangelizing Samaritan villages on the way.',text:'The apostles who once wanted to call down fire on a Samaritan village now preach the gospel in many Samaritan villages. Luke does not point out the contrast, but the change is striking: disciples can be transformed in the way they see people they once regarded as enemies.',cross:[{ref:'Luke 9:52-55',label:'A striking earlier contrast',reason:'John was among the disciples who once asked whether fire should fall on a Samaritan village that rejected Jesus.'}]},
   {ref:'Acts 8:26-29',title:'After a citywide awakening, Philip is sent to one traveler on a sparsely traveled road.',text:'An angel directs Philip toward the road from Jerusalem to Gaza, and then the Spirit tells him to join the chariot. Acts refuses the idea that ministry importance is measured only by crowd size. The same evangelist who preached to a city runs alongside one person’s carriage.'},
   {ref:'Acts 8:27',title:'The Ethiopian official stands at several social and covenant boundaries at once.',text:'He is a high-ranking treasury official from the kingdom south of Egypt, serving under “Candace,” a dynastic title associated with its queens. If “eunuch” is literal, Deuteronomy 23 placed a bodily restriction on entry into Israel’s assembly, while Isaiah 56 promised a future welcome and enduring name for faithful eunuchs. Luke does not explicitly quote Isaiah 56 here, but the resonance is hard to miss.',cross:[{ref:'Isaiah 56:3-5',label:'Promise to eunuchs',reason:'Isaiah promises faithful eunuchs a place and an everlasting name in God’s house.'}]},
   {ref:'Acts 8:28-31',title:'The eunuch is reading Isaiah aloud and is humble enough to admit he needs a guide.',text:'Ancient reading was often vocal, which explains how Philip can hear the passage as he approaches. The man has wealth, education enough to read a Greek scroll, and high office, yet he answers plainly: “How can I, except some man should guide me?” Scripture is not dishonored when a reader receives help from a faithful teacher.'},
   {ref:'Acts 8:32-35',title:'The passage is from Isaiah’s suffering Servant song, and Philip says its good news reaches Jesus.',text:'The official asks whether the prophet speaks about himself or someone else. Philip begins with Isaiah 53 and proclaims Jesus. Luke does not record the whole explanation, but the Christian reading sees the rejected, humiliated, innocent sufferer reaching fulfillment in Jesus’ death and vindication.',cross:[{ref:'Isaiah 53:7-8',label:'The text in the chariot',reason:'The eunuch is reading the section about the silent, humiliated servant led like a sheep to slaughter.'}]},
   {ref:'Acts 8:36-38',title:'The eunuch’s question “what doth hinder me?” fits the chapter’s widening boundaries.',text:'A Samaritan city has just received the gospel; now a foreign court official asks whether anything prevents his baptism. Philip finds no barrier once the gospel of Jesus has been received. Luke’s story keeps moving outward toward people previously held at social or covenant distance.'},
   {ref:'Acts 8:37',title:'The KJV includes a confession of faith here that is absent from many of the earliest and strongest Greek manuscripts.',text:'The familiar sentence—Philip requiring whole-hearted faith and the eunuch confessing Jesus Christ as the Son of God—appears in later manuscript tradition and likely reflects a very early baptismal confession used by Christians. Its theology agrees with New Testament teaching, but most modern editions bracket or omit the verse because it was probably not part of Luke’s earliest recoverable text. This is a textual-history question, not evidence that Christian confession was invented late.'},
   {ref:'Acts 8:38',title:'Both Philip and the eunuch go down into the water; the wording by itself does not settle every later baptism-mode debate.',text:'The verse clearly describes a real water baptism immediately following instruction in Jesus. Christians who practice immersion see the movement into and out of the water as fitting that mode; traditions practicing pouring or sprinkling note that the phrase can describe entering the water area without specifying precisely how water was applied. Acts’ central point here is the eunuch’s unhindered incorporation as a disciple.'},
   {ref:'Acts 8:39-40',title:'Philip’s sudden removal is narrated as an act of the Spirit, not as abandonment of the new believer.',text:'The verb can mean snatch or carry away. Some read it as miraculous transportation; others emphasize an irresistible Spirit-directed departure. Either way, Luke moves Philip north through Azotus toward Caesarea, while the eunuch continues his journey rejoicing. The gospel has given him more than dependence on a particular human teacher.'}
  ],
  reflections:['When circumstances scatter or interrupt my plans, am I able to ask where faithfulness is possible in the new place?','Do I ever want God’s gifts mainly for the influence, control, or recognition they might give me?','Am I humble enough both to read Scripture for myself and to welcome wise help when I do not understand it?'],
  commentary:{voice:'Matthew Henry',identity:'English Nonconformist minister and biblical commentator, 1662–1714',quote:'they thought … to have put it out, but instead of this they did but help to spread it',plain:'Henry sees the great irony of Acts 8: persecution is intended to extinguish the church, yet the scattered believers carry the gospel farther. That does not make persecution good or erase the suffering. It shows that human hostility cannot guarantee the outcome it intends when God is still at work.',source:'Commentary on the Whole Bible — Acts 8:1–4',url:'https://biblehub.com/commentaries/mhcw/acts/8.htm'},
  question:{q:'Why did the Samaritan believers receive the Holy Spirit after baptism instead of immediately?',short:'Acts presents this as a special transition as the gospel crosses the old Jew–Samaritan boundary. The delay allows the apostles from Jerusalem to witness and affirm that Samaritans are included in the same Spirit-given people of God.',more:'Acts does not give one conversion sequence every time. At Pentecost the hearers are told to repent and be baptized with the promise of the Spirit; in Samaria people believe and are baptized before Peter and John arrive; Cornelius’ household will receive the Spirit before water baptism; and disciples in Acts 19 receive further instruction before Paul lays hands on them. Because Samaritans and Jews carried deep historical hostility, many interpreters see Acts 8 as a deliberate, visible joining of the Samaritan believers to the apostolic church so neither side can claim a separate Spirit or a separate gospel. Catholic, Orthodox, Anglican, and some other traditions also see this passage as relevant to later practices of confirmation or laying on of hands, while many Protestants treat the sequence as a unique salvation-historical event rather than a required second stage for every believer. What the text makes unmistakable is that the Spirit is God’s gift, not Philip’s or the apostles’ property.'}
 }
});
render();
