// Acts 23 — Living Bookmark card.
Object.assign(studies,{
 'Acts 23':{body:''}
});

Object.assign(studyMeta,{
 'Acts 23':{
  oneLine:'Paul stands before the Sanhedrin with a clear conscience but is struck at the high priest Ananias’ command; recognizing the council is divided between Pharisees and Sadducees, he puts the resurrection hope at the center and the hearing erupts into such violence that Roman soldiers rescue him again; that night the Lord stands beside Paul and promises that he will testify in Rome, while more than forty men bind themselves to kill him, only for the plot to be uncovered by Paul’s nephew and defeated through an overwhelming Roman transfer to Governor Felix in Caesarea.',
  write:[
   {ref:'Acts 23:1',title:'A clear conscience is not the same thing as a flawless past.',text:'Paul can speak honestly before God because his life is now lived in the light, not because he has never sinned.'},
   {ref:'Acts 23:5',title:'Paul still acknowledges the authority of Scripture when he is treated unjustly.',text:'He cites the command not to speak evil of a ruler of the people.'},
   {ref:'Acts 23:6',title:'The resurrection is not a side issue in Paul’s gospel.',text:'He identifies the hope of resurrection as the heart of the dispute.'},
   {ref:'Acts 23:11',title:'Jesus stands beside Paul before Paul knows how the danger will end.',text:'“Be of good cheer” comes in the barracks, not after every problem is solved.'},
   {ref:'Acts 23:16',title:'God’s providence can work through one ordinary person overhearing a plot.',text:'Paul’s unnamed nephew becomes the human link that preserves Paul’s life.'},
   {ref:'Acts 23:24',title:'The road to Rome begins under armed guard.',text:'God’s promise is fulfilled through ordinary government procedures as well as dramatic interventions.'}
  ],
  underline:{ref:'Acts 23:11',reason:'The Lord gives Paul both comfort and direction: his witness in Jerusalem is not the end; Rome is still ahead.'},
  notice:[
   {ref:'Acts 23:1',title:'Paul’s “good conscience” does not erase his former persecution.',text:'He has already confessed his violence against Christians. Here he means that before God he is acting with integrity in the present matter. A conscience can be sincere and still need correction—as Paul’s own past proves—so “my conscience feels clear” is not a substitute for truth.'},
   {ref:'Acts 23:2-3',title:'Paul’s “whited wall” accusation targets hypocrisy in an unlawful order.',text:'Ananias commands Paul to be struck before guilt has been established, and Paul protests that the judge is violating the law he is supposed to administer. “Whited wall” pictures an outwardly respectable surface covering corruption. Paul’s words are fierce, but the issue is abuse of judicial authority rather than personal annoyance.'},
   {ref:'Acts 23:2',title:'This Ananias is the high priest Ananias son of Nedebaeus, not Ananias of Damascus.',text:'Josephus also knows this high priest, who served in the mid-first century and later died violently during the Jewish revolt. Luke’s Ananias here is a powerful Jerusalem official, entirely different from the disciple who received Paul after his conversion.'},
   {ref:'Acts 23:4-5',title:'“I wist not, brethren, that he was the high priest” has several plausible explanations.',text:'Interpreters have suggested that Paul did not recognize Ananias in an irregular hearing, that poor eyesight played a role, or that his words carry irony: conduct this lawless hardly looks like high-priestly behavior. Acts does not tell us which explanation is correct. What is clear is that Paul immediately quotes Exodus and acknowledges the scriptural rule against reviling a ruler.',cross:[{ref:'Exodus 22:28',label:'Paul’s quotation',reason:'The law forbids cursing a ruler of the people.'}]},
   {ref:'Acts 23:6-8',title:'Paul identifies the resurrection as the decisive theological fault line.',text:'He knows part of the council is Sadducee and part Pharisee. Sadducees reject resurrection, angels, and spirits, while Pharisees affirm them. Paul’s appeal is strategically sharp, but it is not a fabricated distraction: the resurrection of Jesus and the future resurrection really are central to the charge against his preaching.'},
   {ref:'Acts 23:6',title:'“I am a Pharisee” can describe Paul’s continuing theological alignment on resurrection without denying his Christian identity.',text:'Paul is not returning to a pre-Christian life or claiming that Pharisaic law-keeping saves him. He identifies himself with the Pharisaic side of this specific dispute because they share belief in resurrection against the Sadducees.'},
   {ref:'Acts 23:7-10',title:'The council becomes so divided that the Roman commander fears Paul will be torn apart.',text:'Some Pharisaic scribes even say they find no evil in Paul and wonder whether a spirit or angel has spoken to him. The commander again uses soldiers to remove Paul physically from a crowd that has become dangerous.'},
   {ref:'Acts 23:11',title:'The Lord’s encouragement comes after a chaotic hearing, not after an obvious victory.',text:'Jesus stands by Paul at night and tells him to take courage. The promise is specific: as Paul has testified in Jerusalem, he must testify in Rome. That does not promise an easy route; the next verses immediately reveal a murder conspiracy.'},
   {ref:'Acts 23:11',title:'“So must thou bear witness also at Rome” turns Rome from a hope into a divine promise.',text:'Paul had already wanted to see Rome, but now Christ assures him that he will get there. From this point onward, dangers can delay, wound, imprison, or redirect Paul, but they cannot cancel the destination Jesus has named.'},
   {ref:'Acts 23:12-15',title:'More than forty men bind themselves under a curse not to eat or drink until Paul is dead.',text:'This is not a spontaneous angry crowd but an organized assassination plot involving an oath and cooperation with leaders who are asked to request another hearing. The plot shows how far hostility has moved from argument into planned murder.'},
   {ref:'Acts 23:16-22',title:'Paul’s unnamed nephew becomes the crucial human means of deliverance.',text:'Luke never tells us how the young man hears of the plot or much about Paul’s wider family. He simply reports that the nephew tells Paul, Paul sends him to the commander, and the commander takes him seriously. Providence in Acts often works through ordinary information and responsible action rather than spectacle.'},
   {ref:'Acts 23:19',title:'The commander takes the young man by the hand and hears him privately.',text:'It is a small human detail in a chapter full of soldiers and conspirators. The powerful officer does not dismiss the report because it comes through a young relative of the prisoner; he listens, verifies the danger enough to act, and orders secrecy.'},
   {ref:'Acts 23:23-24',title:'The escort is enormous because the commander treats the assassination threat as real.',text:'Luke lists two hundred soldiers, seventy horsemen, and two hundred dexiolaboi, a rare term often translated spearmen. That produces a force of 470 if all are counted separately. Scholars debate the precise meaning of the rare troop term, but the basic point is unmistakable: Paul is moved under heavy protection.'},
   {ref:'Acts 23:23',title:'The departure at the third hour of the night means about 9 p.m.',text:'Roman night-hour reckoning places the third hour roughly three hours after sunset. Moving Paul under darkness and strong guard reduces the chance that the conspirators can intercept him in Jerusalem.'},
   {ref:'Acts 23:25-30',title:'Claudius Lysias’ letter tells the truth selectively and makes his own conduct look better.',text:'He accurately reports the plot, Paul’s Roman citizenship, and the lack of a capital charge. But he writes as though he rescued Paul after learning he was Roman, whereas Acts shows he learned of Paul’s citizenship only after arresting and nearly scourging him. Ancient official correspondence could be self-protective too.'},
   {ref:'Acts 23:29',title:'The Roman commander finds no charge deserving death or imprisonment.',text:'He sees the dispute as questions about Jewish law rather than a Roman capital offense. This begins a repeated pattern in the final chapters of Acts: Roman officials may keep Paul in custody, but the narrative repeatedly records that the accusations do not establish a crime worthy of death.'},
   {ref:'Acts 23:31-33',title:'Paul is taken first to Antipatris and then on to Caesarea.',text:'Antipatris lay on the route from Jerusalem toward the coastal plain. Once the most dangerous terrain is behind them, the infantry can return while the cavalry continues with Paul to Caesarea, the administrative center where Governor Felix resides.'},
   {ref:'Acts 23:34-35',title:'Felix places Paul in Herod’s praetorium while waiting for the accusers.',text:'The “judgment hall” or praetorium refers to Herod the Great’s former palace complex in Caesarea, now used by the Roman governor. Paul is not free, but the conspiracy has failed, he is under official protection, and the Lord’s promise of Rome remains alive.'}
  ],
  reflections:['When I am treated unfairly, can I name the wrong clearly without letting anger become my only guide?','Do I recognize God’s providence only in dramatic miracles, or also in ordinary people, information, laws, and timely decisions?','What promise or calling from God helps me keep perspective when the route toward it looks nothing like I expected?'],
  commentary:{voice:'Charles Spurgeon',identity:'Baptist preacher, 1834–1892',quote:'From the midnight whisper of the Lord to Paul we may draw forth sweet encouragement.',plain:'Spurgeon notices where the encouragement arrives: at night, after Paul has twice needed Roman soldiers to rescue him and before the murder plot is even exposed. Jesus does not wait until danger disappears to strengthen Paul. He gives him enough certainty for the next step: Jerusalem is not the end, because Rome still lies ahead.',source:'Paul Cheered in Prison by His Lord — Acts 23:10–13',url:'https://www.spurgeon.org/sermons/paul-cheered-in-prison-by-his-lord/'},
  question:{q:'Why did Paul say, “I did not know that he was the high priest,” after insulting Ananias?',short:'Acts does not tell us, so several explanations remain possible. Paul may not have recognized Ananias in that setting, poor eyesight may have contributed, or his words may contain irony about a man acting contrary to the law while holding the office.',more:'Ananias orders Paul struck before a legal judgment, and Paul responds, “God shall smite thee, thou whited wall.” When bystanders tell him he has reviled God’s high priest, Paul says he did not know the man was high priest and immediately quotes Exodus 22:28. Some interpreters think this was an irregular meeting where Ananias was not visually identifiable by formal vestments or position. Others connect the remark with Paul’s possible eyesight problems. Still others hear irony: Paul is effectively saying that conduct so unlawful did not look like the conduct of a true high priest. None of those explanations can be proven from Acts itself. What Luke does make clear is that Paul recognizes the authority of the scriptural command even while protesting an abusive order.'}
 }
});
render();
