// John 12 — Living Bookmark card.
Object.assign(studies,{
 'John 12':{body:''}
});

Object.assign(studyMeta,{
 'John 12':{
  oneLine:'As Jesus approaches His final Passover, Mary anoints Him for burial, Jerusalem welcomes Him as King, Greeks come seeking Him, and Jesus explains that His hour of glory will come through death like a grain of wheat falling into the ground, while John closes the public ministry by confronting unbelief, fear, and love of human praise.',
  write:[
   {ref:'John 12:3',title:'Mary pours out something costly because Jesus is worth more to her than the cost.',text:'Her worship fills the house with fragrance.'},
   {ref:'John 12:24',title:'The path to much fruit runs through the death of the grain.',text:'Jesus interprets His coming death not as defeat but as the way the harvest comes.'},
   {ref:'John 12:26',title:'Serving Jesus means following where He goes.',text:'His servant cannot demand a road entirely different from the Master’s.'},
   {ref:'John 12:27',title:'Jesus does not face the cross without real inward trouble.',text:'He names the anguish and still chooses the Father’s purpose.'},
   {ref:'John 12:32',title:'The lifted-up Christ draws attention toward Himself through the cross.',text:'John immediately says Jesus is signifying the kind of death He will die.'},
   {ref:'John 12:43',title:'Human praise can become a spiritual prison.',text:'Some believe, yet fear confession because they love people’s approval more than God’s.'}
  ],
  underline:{ref:'John 12:24',reason:'Jesus explains the paradox of His hour: like a grain of wheat, death becomes the path to abundant fruit.'},
  notice:[
   {ref:'John 12:1-8',title:'Mary’s anointing is extravagant, but John refuses to let Judas define it as waste.',text:'Mary uses costly ointment and wipes Jesus’ feet with her hair. Judas objects in the language of concern for the poor, but John tells us his motive is corrupt. Jesus does not dismiss the poor; He interprets Mary’s act in light of His approaching burial. A real duty toward the poor must not be weaponized to make devotion to Christ look shameful.'},
   {ref:'John 12:3',title:'The house being filled with fragrance gives the scene a quiet physical vividness.',text:'John remembers not only the cost but the smell. The Gospel is theological without becoming disembodied: feet, hair, perfume, dinner, grief, hunger, blood, water, bread, and touch all belong to the story of the Word made flesh.'},
   {ref:'John 12:9-11',title:'Lazarus becomes a target because his living presence is evidence.',text:'Crowds come not only for Jesus but to see the man He raised. The chief priests then discuss killing Lazarus too because many are believing on account of him. John shows how far resistance can harden: even a living sign can become something a person wants removed rather than reconsidered.'},
   {ref:'John 12:12-16',title:'The triumphal entry combines royal celebration with a deliberately humble King.',text:'The crowd takes palm branches and cries “Hosanna” and “King of Israel.” Jesus rides a young donkey, fulfilling Zechariah’s picture of Zion’s king coming humbly. John admits the disciples did not understand the significance at first; they remembered it after Jesus was glorified.',cross:[{ref:'Zechariah 9:9',label:'Direct fulfillment',reason:'John explicitly connects Jesus’ entry on the young donkey with Zechariah’s promise of Zion’s coming King.'}]},
   {ref:'John 12:20-24',title:'The arrival of Greeks becomes the signal for Jesus to speak of His hour.',text:'Some Greeks who have come to worship at the feast ask to see Jesus. Instead of treating this as a publicity opportunity, Jesus says the hour has come for the Son of man to be glorified and immediately talks about a grain of wheat dying. The widening reach to the nations will come through the cross, not around it.'},
   {ref:'John 12:24-26',title:'The grain-of-wheat saying begins with Jesus before it becomes a pattern for disciples.',text:'His death is the seed that produces the harvest. Only then does He speak of losing one’s life and following Him. This should not be turned into praise of needless misery or self-destruction. Christian self-denial is allegiance to Christ above self-preservation, not contempt for the life God gave.'},
   {ref:'John 12:27-28',title:'John gives us Jesus’ troubled soul before the cross just as the Synoptics give us Gethsemane.',text:'He does not approach suffering as though pain cannot touch Him. He asks what He should say—“Father, save me from this hour?”—then answers that this hour is the very purpose for which He came and prays, “Father, glorify thy name.” Obedience here is costly, conscious, and real.'},
   {ref:'John 12:31-33',title:'“Lifted up” in John carries crucifixion and exaltation together.',text:'Jesus says the ruler of this world will be cast out and that when He is lifted up He will draw “all” to Himself. John immediately explains that this signifies the kind of death He will die. The cross looks like public humiliation, but John keeps calling it the hour of glory and the means by which Christ’s reach extends beyond one people.'},
   {ref:'John 12:37-41',title:'John explains persistent unbelief through Isaiah without making human responsibility disappear.',text:'He first quotes Isaiah 53: “Lord, who hath believed our report?” Then he quotes Isaiah 6 about blinded eyes and hardened hearts. Scripture can speak of judicial hardening after repeated resistance without portraying unbelief as innocent. John’s startling comment is that Isaiah “saw his glory, and spake of him,” placing Jesus inside Isaiah’s vision of divine glory.',cross:[{ref:'Isaiah 53:1',label:'Direct quotation',reason:'John uses Isaiah’s lament over unbelief to interpret the rejection of Jesus despite His signs.'},{ref:'Isaiah 6:9-10',label:'Direct quotation',reason:'John also uses Isaiah’s commission language to describe hardened refusal to see and turn.'}]},
   {ref:'John 12:42-43',title:'Private belief can be strangled by love of reputation.',text:'John says even some rulers believed in Jesus but would not confess Him because they feared exclusion and loved human praise more than God’s praise. The warning is not that every timid believer is false. It is that approval can become an idol strong enough to keep conviction hidden.'},
   {ref:'John 12:44-50',title:'Jesus closes His public teaching by joining Father and Son, light and judgment, salvation and accountability.',text:'To believe in Jesus is to believe in the One who sent Him; to see Him is to see the One who sent Him. He says His mission is to save the world rather than delight in condemnation, yet refusing His words still carries judgment. Mercy does not make His revelation optional.'}
  ],
  reflections:['What costly act of love toward Christ might look “wasteful” to someone who measures only efficiency?','Where am I tempted to keep conviction private because somebody’s approval feels too important to lose?'],
  commentary:{voice:'John Gill',identity:'English Baptist pastor and commentator, 1697–1771',quote:'his death would be productive of much fruit',plain:'Gill is commenting on Jesus’ grain-of-wheat saying. The cross is not an accidental interruption before the real victory; Jesus presents His death itself as the seed from which the harvest comes. John places that truth exactly where Greeks begin asking to see Him—the widening fruit comes through the crucified Christ.',source:'Exposition of the Entire Bible — John 12',url:'https://biblehub.com/commentaries/gill/john/12.htm'},
  question:{q:'What does Jesus mean when He says, “If I be lifted up… I will draw all men unto me”?',short:'John tells us “lifted up” refers to Jesus’ crucifixion. In context, the arrival of Greeks shows the widening reach of the cross: Jesus’ death will draw people beyond the boundaries of Israel toward Him.',more:'The word “men” is supplied in English; the Greek says “all.” Christians differ over how precisely to define the scope—every individual person, all kinds of people, or all those finally gathered to Christ. The immediate context helps: Greeks have just asked to see Jesus, Jesus says His hour has come, and He speaks of the grain of wheat dying to bear much fruit. At minimum, John is showing that the cross will not shrink Jesus’ mission; it becomes the means by which His saving claim reaches outward to the world. The verse should not be detached from John’s equally strong teaching that people can resist light and remain in unbelief.'}
 }
});
render();