// John 19 — Living Bookmark card.
Object.assign(studies,{
 'John 19':{body:''}
});

Object.assign(studyMeta,{
 'John 19':{
  oneLine:'Pilate repeatedly recognizes Jesus’ innocence yet yields to pressure, the true King is crucified under a three-language title, Jesus entrusts His mother to the beloved disciple, completes His work with “It is finished,” and John emphasizes eyewitness fulfillment as the unbroken and pierced body of Jesus is taken down and buried by Joseph and Nicodemus.',
  write:[
   {ref:'John 19:5',title:'The mocked King is displayed in a crown of thorns.',text:'Pilate says, “Behold the man,” without understanding the depth of what stands before him.'},
   {ref:'John 19:11',title:'Earthly power is never ultimate power.',text:'Jesus tells Pilate he could have no authority at all unless it were given from above.'},
   {ref:'John 19:19',title:'The charge over the cross becomes a proclamation Pilate does not intend.',text:'“Jesus of Nazareth the King of the Jews” is written for the passing world to read.'},
   {ref:'John 19:26-27',title:'Even from the cross Jesus makes provision for His mother.',text:'His suffering does not erase His attention to the person standing beneath Him.'},
   {ref:'John 19:30',title:'Jesus dies with the language of completion.',text:'“It is finished.”'},
   {ref:'John 19:35',title:'John stops and insists on eyewitness testimony.',text:'The details of Jesus’ death are given so the reader may believe.'}
  ],
  underline:{ref:'John 19:30',reason:'The final cry in John is not “I am finished,” but “It is finished”: the work given to the Son reaches its appointed completion.'},
  notice:[
   {ref:'John 19:1-7',title:'The soldiers turn kingship into a cruel joke, while John lets the irony tell the truth.',text:'Purple cloth and a crown of thorns are meant to humiliate. Pilate presents the beaten Jesus with “Behold the man,” and the chief priests answer with crucifixion. Yet the Gospel has spent nineteen chapters showing that this rejected Man really is the Word made flesh and the King whose glory appears in self-giving love.'},
   {ref:'John 19:7-11',title:'Pilate becomes more afraid when he hears the charge that Jesus made Himself the Son of God.',text:'His question “Whence art thou?” touches one of John’s central themes: Jesus’ true origin is from the Father. When Pilate boasts of his authority, Jesus relativizes it without pretending it is unreal: the governor’s power exists only because authority has been permitted “from above,” and moral responsibility remains.'},
   {ref:'John 19:12-16',title:'“We have no king but Caesar” is one of the Passion narrative’s bitterest ironies.',text:'Leaders seeking Jesus’ death invoke loyalty to Caesar against the One John presents as Israel’s true King. The sentence should not be turned into a slur against Jewish people. It is the speech of particular leaders in a trial also controlled by Roman power; Pilate knowingly hands an innocent Jewish man over to Roman crucifixion.'},
   {ref:'John 19:17-22',title:'The title above Jesus is written in Hebrew, Greek, and Latin.',text:'Pilate intends an identifying charge and perhaps a final insult toward the leaders who pressured him. John sees something larger: the crucified Jesus is publicly named King in the languages of the local religious world and the wider imperial world. Pilate refuses to rewrite it: “What I have written I have written.”'},
   {ref:'John 19:23-24',title:'The soldiers’ ordinary division of clothing becomes another point where John recognizes Scripture.',text:'Four soldiers divide the garments, but the seamless tunic is too valuable to tear, so they cast lots. John connects the scene to Psalm 22. The soldiers are not consciously acting out a script; their normal behavior becomes part of the pattern Scripture had already voiced.',cross:[{ref:'Psalm 22:18',label:'Scripture fulfilled',reason:'John explicitly connects the division of garments and casting lots with this verse.'}]},
   {ref:'John 19:25-27',title:'The women and the beloved disciple remain near enough for Jesus to speak to them.',text:'Jesus entrusts His mother to the beloved disciple and the disciple takes her into his own home. The scene is tender without becoming sentimental: the Son who is completing the saving work still honors a concrete family responsibility in the middle of agony.'},
   {ref:'John 19:28-30',title:'“I thirst” is real bodily suffering and also a scriptural fulfillment.',text:'John says Jesus knows all things are now accomplished and speaks so Scripture may be fulfilled. That does not make His thirst theatrical. Crucifixion produces real physical torment, and Psalm 69 had already given language to the righteous sufferer receiving sour wine in his thirst.',cross:[{ref:'Psalm 69:21',label:'Scripture fulfillment',reason:'John connects Jesus’ thirst and the sour wine with the psalm’s suffering language.'}]},
   {ref:'John 19:30',title:'“It is finished” means completion, not collapse.',text:'The Greek tetelestai comes from the verb “to complete” or “bring to its goal.” Popular preaching sometimes says the word itself literally means “paid in full” because similar forms appear on receipts, but that is too narrow for the word’s meaning here. John has repeatedly spoken of Jesus finishing the work the Father gave Him; the cry gathers that completed mission into one word.'},
   {ref:'John 19:31-37',title:'The unbroken legs and pierced side become two more scriptural witnesses.',text:'Because Jesus is already dead, the soldiers do not break His legs; one pierces His side instead. John solemnly emphasizes eyewitness testimony and then connects the scene both with the unbroken-bone language and with Zechariah’s pierced figure. The blood and water have received physical, sacramental, and symbolic interpretations across Christian history; John’s first insistence is that the witness truly saw it.',cross:[{ref:'Exodus 12:46',label:'Passover background',reason:'The Passover lamb’s bones were not to be broken, an important background to John’s unbroken-bone emphasis.'},{ref:'Zechariah 12:10',label:'Direct prophetic connection',reason:'John quotes the expectation that people will look on the one whom they pierced.'}]},
   {ref:'John 19:38-42',title:'Joseph and Nicodemus move from hidden or cautious discipleship into public care for Jesus’ body.',text:'Joseph asks Pilate for the body; Nicodemus brings an enormous quantity of burial spices. Their act cannot reverse the death, but it honors Jesus when public association with Him is costly. John closes the chapter with a real body placed in a real nearby tomb.'}
  ],
  reflections:['Where am I tempted to treat human authority as absolute instead of remembering Jesus’ words that power is accountable to what is “from above”?','What does “It is finished” change about my instinct to add something of my own before I can trust Christ’s completed work?'],
  commentary:{voice:'Alexander Maclaren',identity:'Scottish Baptist preacher and expositor, 1826–1910',quote:'Christ’s work is finished. It needs no supplement.',plain:'Maclaren hears “It is finished” as the completion of the task Jesus came to accomplish. The cross is not a half-built foundation waiting for us to make it effective by adding our merit; disciples receive and live from a work Christ has brought to its appointed goal.',source:'Expositions of Holy Scripture — John 19',url:'https://biblehub.com/commentaries/maclaren/john/19.htm'},
  question:{q:'Does “It is finished” literally mean “paid in full”?',short:'The Greek word means “it has been completed” or “brought to its goal.” Payment imagery can fit the theology of the cross, but “paid in full” is not the word’s one literal dictionary meaning.',more:'The word is tetelestai, a perfect form of teleō, “finish, complete, accomplish.” Forms of this verb could certainly appear in commercial settings when an obligation was completed, which helps explain the popular receipt illustration. But John himself gives us the safest context: just before the cry he says Jesus knew that “all things were now accomplished,” and throughout the Gospel Jesus speaks about finishing the work the Father gave Him. The cross truly deals with sin’s debt, but the word itself is broader and richer: the mission has reached completion.'}
 }
});
render();