// Acts 20 — Living Bookmark card.
Object.assign(studies,{
 'Acts 20':{body:''}
});

Object.assign(studyMeta,{
 'Acts 20':{
  oneLine:'Paul strengthens believers through Macedonia and Greece, travels with a diverse group of companions, restores Eutychus after a fatal fall during a long gathering at Troas, and then summons the Ephesian elders to Miletus for a tearful farewell: he reminds them of his humble public and house-to-house ministry, declares his determination to finish the course Jesus gave him, charges the elders to shepherd God’s flock against wolves from outside and distortion from within, commends them to God and the word of His grace, and leaves them with Jesus’ saying that it is more blessed to give than to receive.',
  write:[
   {ref:'Acts 20:7',title:'The church gathers around word and table.',text:'Teaching and breaking bread belong together in the Troas gathering.'},
   {ref:'Acts 20:20',title:'Paul did not keep back what was useful because it was difficult.',text:'He taught publicly and from house to house.'},
   {ref:'Acts 20:24',title:'Finishing faithfully matters more to Paul than preserving comfort.',text:'His aim is to complete the ministry he received from Jesus.'},
   {ref:'Acts 20:27',title:'Love does not edit out difficult truth.',text:'Paul says he did not shrink from declaring the whole counsel of God.'},
   {ref:'Acts 20:28',title:'Leaders must watch themselves before they watch the flock.',text:'Paul begins, “Take heed therefore unto yourselves.”'},
   {ref:'Acts 20:35',title:'Christian strength bends toward the weak.',text:'Paul remembers Jesus’ words: “It is more blessed to give than to receive.”'}
  ],
  underline:{ref:'Acts 20:24',reason:'Paul knows suffering is ahead, yet measures his life by whether he finishes the course and ministry Jesus entrusted to him.'},
  notice:[
   {ref:'Acts 20:1-3',title:'Paul’s response to the Ephesian riot is to encourage believers and keep moving.',text:'He travels through Macedonia and into Greece, strengthening disciples rather than allowing the uproar in Ephesus to become the final story. Acts repeatedly shows ministry continuing after disruption rather than pretending disruption never hurts.'},
   {ref:'Acts 20:3-4',title:'The travel party represents several regions touched by the gospel.',text:'Luke names companions connected with Berea, Thessalonica, Derbe, and Asia. Many interpreters connect this group with the collection Paul was organizing for poor believers in Jerusalem. Traveling with representatives from contributing churches would also provide visible accountability for handling donated money.',cross:[{ref:'2 Corinthians 8:19-21',label:'Financial accountability',reason:'Paul describes a brother chosen by the churches to travel with the gift and stresses taking precautions so the collection is handled honorably before God and people.'}]},
   {ref:'Acts 20:5-6',title:'Luke’s “we” narration resumes as the group sails from Philippi.',text:'The first-person language again suggests that the narrator has rejoined the traveling company. They leave after the Days of Unleavened Bread and reach Troas in five days, where they remain a week.'},
   {ref:'Acts 20:7',title:'The believers gather on the first day of the week to break bread.',text:'This is important evidence for early Christian gathering on Sunday, the day associated with Jesus’ resurrection. “Breaking bread” can include an ordinary fellowship meal and can also carry Eucharistic significance. Christians differ over precisely how formal this Troas meal was, but the verse clearly shows word, fellowship, and table gathered into one Christian assembly.'},
   {ref:'Acts 20:7',title:'Paul’s long speech is connected to departure, not offered as a model that every sermon should last until midnight.',text:'He plans to leave the next day and keeps talking because this is a farewell gathering. The chapter celebrates his care and urgency; it does not make extreme sermon length a test of faithfulness.'},
   {ref:'Acts 20:8-10',title:'Luke presents Eutychus as actually dead, not merely embarrassed after a nap.',text:'The young man falls from the third story and is “taken up dead.” Paul goes down, embraces him, and then says his life is in him. Some readers have tried to reduce the event to unconsciousness, but Luke narrates death followed by restoration and later says the believers were greatly comforted.'},
   {ref:'Acts 20:9',title:'Eutychus’ sleepiness is not turned into a moral failure by Luke.',text:'It is late, Paul has spoken at length, and the young man is sitting in a window. The story does not scold him for insufficient spiritual enthusiasm. A tragic accident becomes the setting for mercy, not a sermon about lazy listeners.'},
   {ref:'Acts 20:10',title:'Paul’s embrace recalls earlier biblical stories of prophets and restored life.',text:'Elijah and Elisha both stretch themselves over dead children before God restores life. Luke does not explicitly call this a fulfillment of those scenes, but the resemblance places Paul’s ministry within the biblical pattern of God giving life through His servants.',cross:[{ref:'1 Kings 17:21-22',label:'Elijah and the widow’s son',reason:'Elijah stretches himself upon the child and cries to the LORD before the child’s life returns.'},{ref:'2 Kings 4:34-35',label:'Elisha and the Shunammite’s son',reason:'Elisha similarly embraces the child before the boy revives.'}]},
   {ref:'Acts 20:11-12',title:'The gathering continues after Eutychus is restored.',text:'They return upstairs, break bread, eat, and talk until daybreak. Luke’s closing emphasis is not on shock but comfort: the young man is brought home alive.'},
   {ref:'Acts 20:13-16',title:'Luke gives unusually detailed travel notes because this is a remembered journey toward Jerusalem.',text:'Paul travels part of the route on foot while the others sail, then rejoins them. He deliberately bypasses Ephesus because he hopes to reach Jerusalem by Pentecost. Urgency shapes the route without erasing his affection for the Ephesian church.'},
   {ref:'Acts 20:17',title:'Paul calls the Ephesian elders to Miletus rather than entering Ephesus itself.',text:'The meeting gives Acts its fullest picture of Paul speaking directly to Christian leaders rather than to an evangelistic audience. The tone is personal because these people have watched his life as well as heard his teaching.'},
   {ref:'Acts 20:18-21',title:'Paul points first to the manner of his ministry: humility, tears, endurance, and useful teaching.',text:'He does not defend his work only by listing results. He reminds them how he lived among them and that he taught what was profitable both publicly and in homes. Ministry in Acts is truth embodied over time, not merely platform performance.'},
   {ref:'Acts 20:20-21',title:'“Anything that was profitable” is defined by repentance and faith, not material prosperity.',text:'Paul explains the profitable message as repentance toward God and faith toward the Lord Jesus Christ. The verse cannot honestly be turned into a promise that faithful teaching is whatever increases wealth or earthly success.'},
   {ref:'Acts 20:22',title:'“Bound in the spirit” can be understood in more than one way.',text:'The Greek can refer to Paul’s own spirit inwardly constrained or to the Holy Spirit compelling him. The next verse explicitly names the Holy Spirit as the One testifying about coming imprisonment. Either way, Paul experiences the Jerusalem journey as an obligation he cannot casually abandon.'},
   {ref:'Acts 20:23-24',title:'Knowing suffering is coming does not mean Paul knows every detail of what will happen.',text:'The Holy Spirit testifies that bonds and afflictions await him, while Paul says he does not know the precise events ahead. Biblical guidance can provide enough certainty for obedience without supplying a complete preview.'},
   {ref:'Acts 20:24',title:'The KJV’s “finish my course with joy” contains words absent from many of the earliest manuscripts.',text:'“With joy” is well known from the KJV and later manuscript tradition, but many modern critical texts read simply that Paul wants to finish his course and ministry. The shorter wording may even sharpen the point: finishing faithfully matters whether the end feels joyful or painful.'},
   {ref:'Acts 20:24',title:'Paul does not despise life; he refuses to make self-preservation the highest good.',text:'His life is God’s gift and has been used fruitfully, but it is not so precious that he will abandon Christ’s assignment to protect it. The contrast is between life kept at the price of disobedience and a life spent faithfully.'},
   {ref:'Acts 20:26-27',title:'Paul’s claim to be “pure from the blood of all men” echoes the watchman in Ezekiel.',text:'He is not claiming sinless perfection. He means he has faithfully delivered the warning and has not withheld God’s counsel; therefore he is not responsible for another person’s refusal to hear.',cross:[{ref:'Ezekiel 33:7-9',label:'Watchman responsibility',reason:'The watchman must give the warning; after faithful warning, responsibility rests with the hearer’s response.'}]},
   {ref:'Acts 20:27',title:'“The whole counsel of God” means Paul refused selective teaching.',text:'No single speech contains every biblical doctrine, so Paul is describing the full scope of what God entrusted him to teach these believers. Faithfulness does not mean mentioning everything in every sermon; it means not deliberately hiding parts of God’s truth because they are unpopular or difficult.'},
   {ref:'Acts 20:17, 28',title:'The same leaders are called elders and then overseers and are told to shepherd the church.',text:'Paul summons the presbyteroi—elders—and tells them the Holy Spirit made them episkopoi—overseers—to shepherd or pastor the flock. Christian traditions later developed different structures and titles, but this passage shows substantial overlap among elder, overseer, and shepherd language in the first-century church.'},
   {ref:'Acts 20:28',title:'“The church of God, which he hath purchased with his own blood” has an important textual and translation discussion.',text:'The strongest manuscript evidence supports “church of God,” though some manuscripts read “church of the Lord.” The final phrase can be rendered “with his own blood” or understood as “with the blood of his own [Son].” Either way, the church’s value rests on the costly saving work of Christ, not on the status of its leaders.'},
   {ref:'Acts 20:28',title:'The flock belongs to God before it belongs to any pastor or congregation.',text:'Leaders are overseers entrusted with people God has made His own at immense cost. That makes spiritual leadership stewardship rather than possession. Paul’s first command is therefore to watch themselves and then the flock.'},
   {ref:'Acts 20:29-31',title:'Danger will come both from outside the church and from inside its leadership.',text:'Paul warns of “grievous wolves” entering from outside and of men arising “of your own selves” who distort truth to draw disciples after themselves. Longevity, office, or insider status never makes a teacher immune from examination.'},
   {ref:'Acts 20:31',title:'Paul’s three-year summary shows that his warning ministry included tears.',text:'Acts has described roughly three months in the synagogue, two years in Tyrannus, and additional time in the region. Paul summarizes the whole period as three years of persistent admonition “night and day with tears.” Warning can be tender rather than harsh.'},
   {ref:'Acts 20:32',title:'Paul ultimately entrusts the elders to God and to the word of His grace, not to his permanent presence.',text:'The apostle is leaving. The church cannot depend on endless access to Paul, so he commends them to God and the gracious word that is able to build them up and give the promised inheritance.'},
   {ref:'Acts 20:33-35',title:'Paul’s manual labor protects the weak and guards against greed.',text:'He reminds them that he coveted no one’s silver, gold, or clothing and that his own hands supplied needs. This does not cancel the biblical right of ministers to receive support; here Paul is modeling freedom from greed and a willingness to work so that vulnerable people can be helped.'},
   {ref:'Acts 20:35',title:'“It is more blessed to give than to receive” is a saying of Jesus not recorded in the four Gospels.',text:'Paul explicitly attributes the words to the Lord Jesus. They are an example of an authentic Jesus saying preserved in early Christian memory outside the written Gospel accounts. The Gospels themselves never claim to record every word Jesus spoke.',cross:[{ref:'John 21:25',label:'Not every act was written',reason:'John closes by saying Jesus did many other things beyond what his Gospel records.'}]},
   {ref:'Acts 20:36-38',title:'The farewell ends on its knees and in tears.',text:'Paul kneels with the elders and prays. They weep, embrace him, and grieve especially because he said they would not see his face again. Acts does not treat deep Christian attachment as weakness; love makes separation painful.'}
  ],
  reflections:['Is there any truth I am tempted to avoid because it feels difficult, unpopular, or personally costly?','If I knew I had limited time with people I loved, what would I most want my life and words to have taught them?','Do I think of Christian leadership as influence I possess, or as people belonging to God whom I am temporarily entrusted to serve?'],
  commentary:{voice:'Charles Simeon',identity:'Anglican evangelical preacher and pastor, 1759–1836',quote:'the trials with which a faithful discharge of our duty is attended are proportionably great',plain:'Simeon notices that Paul’s courage is not courage in an easy assignment. Paul knows bonds and suffering are ahead and still measures success by finishing the ministry Jesus gave him. Faithfulness is not proved by having no cost; sometimes the cost is exactly what reveals what we value most.',source:'Horae Homileticae — Acts 20:24, “Duty of Ministers”',url:'https://www.truthaccordingtoscripture.com/commentaries/shh/acts-20.php'},
  question:{q:'What does Paul mean when he says he declared “all the counsel of God” in Acts 20:27?',short:'He means he did not knowingly withhold the truth God entrusted him to teach. It does not mean every sermon contained every doctrine, but that over his ministry he refused to edit God’s message down to only the comfortable parts.',more:'The surrounding verses explain the phrase. Paul says he kept back nothing that was profitable, taught publicly and from house to house, testified about repentance toward God and faith in Jesus, and warned people with tears. “The whole counsel of God” therefore describes the integrity and breadth of his teaching rather than the impossible idea that every biblical subject appeared in every message. It also gives Christian teachers a guardrail: relevance does not mean avoiding hard truths, and doctrinal thoroughness does not mean dumping every truth into every conversation. Paul knew these believers over years. Faithful teaching gives people what they need across time without deliberately hiding what God has said.'}
 }
});
render();
