// John 7–9 — Living Bookmark cards.
Object.assign(studies,{
 'John 7':{body:''},
 'John 8':{body:''},
 'John 9':{body:''}
});

Object.assign(studyMeta,{
 'John 7':{
  oneLine:'At the Feast of Tabernacles Jesus moves on the Father’s timing, teaches that His doctrine comes from the One who sent Him, exposes shallow judgments about Sabbath and Messiah, and on the great day of the feast cries for the thirsty to come to Him and receive the Spirit.',
  write:[
   {ref:'John 7:6',title:'Jesus does not let pressure set His hour.',text:'His movements are governed by the Father’s timing, not by the demands of His brothers or the crowd.'},
   {ref:'John 7:17',title:'Willingness to do God’s will matters for spiritual understanding.',text:'Jesus joins honest obedience with knowing whether His teaching is from God.'},
   {ref:'John 7:24',title:'“Judge righteous judgment” is the opposite of judging by appearance.',text:'Jesus does not forbid discernment; He forbids shallow, crooked judgment.'},
   {ref:'John 7:37',title:'Jesus stands in the feast and makes Himself the place thirsty people must come.',text:'“If any man thirst, let him come unto me, and drink.”'},
   {ref:'John 7:38',title:'The life Christ gives is meant to overflow.',text:'Living water is not pictured as a private puddle but as rivers flowing outward.'},
   {ref:'John 7:46',title:'Even the officers sent to arrest Jesus come back struck by His words.',text:'“Never man spake like this man.”'}
  ],
  underline:{ref:'John 7:37-38',reason:'At the feast Jesus places Himself at the center of the thirst-and-water imagery and invites anyone thirsty to come to Him.'},
  notice:[
   {ref:'John 7:1-9',title:'Jesus’ brothers do not yet believe in Him, and their advice assumes public display is the obvious path.',text:'They tell Him to go to Judea and show His works openly. Jesus answers that His time is not theirs. John will later tell us His brothers do come to faith, but here they are part of the pressure Jesus refuses to let control His mission.'},
   {ref:'John 7:10-13',title:'Jesus goes to the feast, but not on the terms His brothers proposed.',text:'He goes privately rather than as a public self-promotional spectacle. The crowd is divided: some call Him good, others a deceiver, and many speak quietly because of fear. John keeps showing that the same Jesus produces radically different responses.'},
   {ref:'John 7:14-18',title:'Jesus roots His teaching in the Father who sent Him.',text:'He has not been trained in the recognized rabbinic schools, yet teaches with authority. His answer is not “I invented this myself” but “My doctrine is not mine, but his that sent me.” The test in verse 17 is not that good behavior earns truth; it is that a will bent against God can resist the truth it claims to be evaluating.'},
   {ref:'John 7:21-24',title:'The Sabbath argument exposes inconsistent judgment.',text:'Jesus points out that circumcision may be performed on the Sabbath so the law of Moses is not broken, yet His opponents are angry because He made a whole man well on the Sabbath. “Judge not according to the appearance” calls them to judge the act by God’s purpose rather than by a surface rule applied selectively.'},
   {ref:'John 7:25-31',title:'Knowing Jesus’ hometown is not the same as knowing where He truly comes from.',text:'Some Jerusalem residents think messianic expectation rules Jesus out because they know His earthly origin. Jesus answers that He has been sent by the One they do not know. John repeatedly lets earthly facts and heavenly origin sit together rather than compete.'},
   {ref:'John 7:37-39',title:'The feast setting makes the living-water cry especially vivid.',text:'The Feast of Tabernacles remembered Israel’s wilderness life, and water ceremonies had become part of the celebration. Against that background Jesus cries, “If any man thirst, let him come unto me, and drink.” John then interprets the image for us: He spoke of the Spirit, who would be given in the new stage opened by Jesus’ glorification.',cross:[{ref:'Isaiah 55:1',label:'Invitation echo',reason:'Isaiah calls the thirsty to come freely to the waters; Jesus places that invitation around Himself.'},{ref:'John 4:14',label:'Earlier living-water theme',reason:'Jesus had already promised the Samaritan woman an inward spring rising into everlasting life.'}]},
   {ref:'John 7:40-44',title:'The crowd’s Bethlehem objection is ironic because the reader already knows more than the speakers do.',text:'Some object that the Christ should come from Bethlehem and David’s line, assuming Jesus is simply from Galilee. The Synoptic Gospels explicitly give Bethlehem and Davidic ancestry. John does not stop to correct every speaker because he often lets misunderstanding expose how confidently people can judge with incomplete information.'},
   {ref:'John 7:45-52',title:'The failed arrest turns into another argument about whether anyone important believes.',text:'The officers return without Jesus because they are struck by His speech. The Pharisees answer by appealing to elite consensus: have any rulers believed? Nicodemus quietly reminds them that their own law does not judge a man before hearing him. John lets the irony stand: the people most confident that they are judging lawfully are being corrected on due process by one of their own.'},
   {ref:'John 7:53',title:'The sentence that begins “every man went unto his own house” belongs to the larger John 7:53–8:11 textual question.',text:'The earliest Greek manuscripts of John do not contain John 7:53–8:11, and later manuscripts sometimes place the story elsewhere. The account has a long history in the church and is consistent with much we know of Jesus, but its manuscript history should be stated honestly rather than hidden. The fuller note belongs with the story in John 8.'}
  ],
  reflections:['Do I ever pressure God to act on the timetable that would make the most sense to me?','Where might I be judging by appearance because I have only part of the story?'],
  commentary:{voice:'Alexander Maclaren',identity:'Scottish Baptist preacher and expositor, 1826–1910',quote:'He says of them all that they are the shadow, and the substance is in Him.',plain:'Maclaren is tracing the way John repeatedly shows Jesus fulfilling older biblical signs: Jacob’s ladder, the bronze serpent, manna, and now wilderness water. The feast and its water imagery do not become meaningless; they become clearer when Christ stands in their midst and says the thirsty must come to Him.',source:'Expositions of Holy Scripture — John 7',url:'https://biblehub.com/commentaries/maclaren/john/7.htm'},
  question:{q:'What are the “rivers of living water” in John 7?',short:'John tells us directly that Jesus is speaking about the Holy Spirit, who would be given to believers in the new stage opened by Jesus’ glorification.',more:'The image grows out of themes already present in John: living water at the Samaritan well, wilderness provision, prophetic promises of cleansing and Spirit, and the Feast of Tabernacles setting. Verse 39 removes the main uncertainty by explaining the symbol. The wording about rivers flowing “out of his belly” has some grammatical and interpretive questions—whether the pronoun refers most naturally to the believer or, in some readings, to Christ—but the central point is secure: Jesus is the source to whom the thirsty come, and the Spirit’s life does not remain sterile but overflows.'}
 },
 'John 8':{
  oneLine:'Jesus refuses a trap built around a woman accused of adultery, then declares Himself the Light of the world, exposes slavery to sin beneath claims of freedom, identifies truth and sonship around Himself, and ends the long temple dispute with the staggering words, “Before Abraham was, I am.”',
  write:[
   {ref:'John 8:11',title:'Jesus neither condemns the woman nor blesses the sin.',text:'Grace and the command “sin no more” stand together.'},
   {ref:'John 8:12',title:'Jesus does not merely point toward light.',text:'“I am the light of the world.”'},
   {ref:'John 8:31-32',title:'Freedom belongs to continuing in Jesus’ word.',text:'Truth is not a slogan detached from discipleship.'},
   {ref:'John 8:34',title:'Sin promises freedom while becoming a master.',text:'Jesus says the practice of sin is slavery.'},
   {ref:'John 8:36',title:'The Son gives real freedom.',text:'“If the Son therefore shall make you free, ye shall be free indeed.”'},
   {ref:'John 8:58',title:'Jesus does not say “Before Abraham was, I was.”',text:'He says, “Before Abraham was, I am.”'}
  ],
  underline:{ref:'John 8:12',reason:'Jesus identifies Himself as the Light of the world and promises His followers the light of life.'},
  notice:[
   {ref:'John 7:53-8:11',title:'The woman caught in adultery is one of the New Testament’s most important textual-history passages.',text:'The earliest and strongest Greek manuscripts of John do not contain this story, and some later manuscripts place it at other locations. That makes it very unlikely that the paragraph stood here in the earliest recoverable form of John’s Gospel. At the same time, the account is ancient and had a long life in the church. Bookmark should neither hide the manuscript evidence nor talk as though the story appeared yesterday. No central Christian doctrine depends uniquely on this passage.'},
   {ref:'John 8:3-6',title:'The accusers bring a woman, but the law they invoke did not make adultery a one-person crime.',text:'If she was truly “taken in adultery, in the very act,” the missing man is conspicuous. Deuteronomy speaks of both parties. John also tells us their purpose is to tempt Jesus so they can accuse Him. The woman’s sin is not made unreal, but neither should religious manipulation of her be ignored.',cross:[{ref:'Deuteronomy 22:22',label:'Law background',reason:'The law’s adultery penalty addresses both the man and the woman, not the woman alone.'}]},
   {ref:'John 8:7-11',title:'“He that is without sin” does not mean courts can never punish wrongdoing unless judges are morally perfect.',text:'Jesus is answering a hostile trap in a setting full of hypocrisy and irregularity. One by one the accusers leave. Jesus does not call adultery good; His final words are “go, and sin no more.” The scene brings mercy and moral seriousness together rather than using one to erase the other.'},
   {ref:'John 8:12-20',title:'“I am the light of the world” continues the feast imagery and the Gospel’s opening theme.',text:'John began by calling the Word the true Light. Now Jesus takes the claim on His own lips. The following witness discussion also returns to the legal theme: Jesus’ testimony is joined by the Father’s testimony. His opponents know His earthly categories but do not know the Father because they reject the Son.'},
   {ref:'John 8:21-30',title:'“Ye shall die in your sins” makes the identity of Jesus a life-and-death issue in John.',text:'Jesus does not present Himself as one helpful religious option among many equivalent roads. He says, “if ye believe not that I am he, ye shall die in your sins.” The supplied “he” in English helps the sentence read naturally, but the Greek has the stark egō eimi—“I am”—language that keeps recurring in the chapter.'},
   {ref:'John 8:31-36',title:'Jesus speaks of slavery to people who insist they have never been slaves.',text:'Their answer is striking given Israel’s own history under Egypt, Assyria, Babylon, and now Rome; they may mean they have never accepted the inner status of slaves. Jesus moves beneath the political claim anyway: whoever practices sin is sin’s servant. Freedom is not mere national independence or self-definition; the Son must make the slave truly free.'},
   {ref:'John 8:37-47',title:'The fierce argument about Abraham and “your father the devil” must never be turned into anti-Jewish contempt.',text:'Jesus, His disciples, and the people arguing with Him are all within the Jewish world. The issue is not ethnicity. Jesus explicitly grants, “I know that ye are Abraham’s seed,” then argues that spiritual kinship is shown by whose works a person does and whose word a person receives. Christians commit a serious distortion if they take an intra-Jewish confrontation and use it to demonize Jewish people as a race.'},
   {ref:'John 8:48-55',title:'Being insulted as a Samaritan and demon-possessed does not pull Jesus off mission.',text:'He answers the demon accusation directly and says He honors His Father and does not seek His own glory. John shows escalating hostility, but Jesus keeps the argument centered on His relationship to the Father and on His word giving life.'},
   {ref:'John 8:56-59',title:'“Before Abraham was, I am” deliberately contrasts Abraham’s beginning with Jesus’ continuing existence.',text:'Abraham “was” or came into being; Jesus says “I am.” The wording reaches naturally back toward the divine-name language of Exodus 3:14 and fits John 1’s claim that the Word already was in the beginning. The crowd’s attempt to stone Him shows they do not hear this as a harmless claim to be older in God’s plan.',cross:[{ref:'Exodus 3:14',label:'Divine-name echo',reason:'God’s “I AM” self-identification forms an important Old Testament background to Jesus’ emphatic “I am” language.'},{ref:'John 1:1',label:'Gospel prologue',reason:'John has already placed the Word in eternal existence before creation.'}]}
  ],
  reflections:['Do I tend to separate grace from repentance—either condemning people without mercy or calling mercy permission to keep sinning?','What kind of freedom am I seeking, and does it actually deal with the slavery Jesus says sin creates?'],
  commentary:{voice:'John Calvin',identity:'Reformation pastor and commentator, 1509–1564',quote:'he does not say, I was, but I am',plain:'Calvin notices the verb contrast in John 8:58. Abraham has a beginning; Jesus speaks in the present tense across the centuries. Whatever else is gathered into the saying, Calvin is right that John is not presenting Jesus as merely one more figure inside the ordinary human timeline.',source:'Commentary on John — John 8',url:'https://biblehub.com/commentaries/calvin/john/8.htm'},
  question:{q:'Should John 7:53–8:11 be in the Bible?',short:'The story has ancient church history, but the earliest and strongest manuscripts of John do not contain it in this location, so it should be read with a clear textual note rather than with false certainty about its original placement.',more:'Textual criticism asks what wording best explains the surviving manuscripts. Here the evidence is unusually visible: early Greek manuscripts omit the passage, later copies sometimes move it, and the vocabulary/style have features that stand apart from the immediate Johannine context. That is why many modern Bibles bracket or footnote it. None of that requires treating the story with contempt. It was known early in Christian tradition and strongly resembles Jesus’ characteristic combination of exposing hypocrisy, showing mercy, and calling sinners away from sin. The responsible posture is transparent: read it as an ancient Jesus tradition long received by the church, while acknowledging that its original place in John is doubtful.'}
 },
 'John 9':{
  oneLine:'Jesus rejects the idea that a man’s congenital blindness proves unusual personal guilt, gives him sight on the Sabbath, and then watches religious interrogators become more certain while the healed man grows step by step from knowing “a man called Jesus” to worshipping the Son of God.',
  write:[
   {ref:'John 9:3',title:'Suffering is not a scoreboard of hidden guilt.',text:'Jesus refuses the disciples’ attempt to blame the man or his parents for his blindness.'},
   {ref:'John 9:5',title:'Jesus calls Himself the Light of the world and then gives sight.',text:'The sign acts out the claim.'},
   {ref:'John 9:25',title:'The healed man keeps hold of what he knows.',text:'“One thing I know, that, whereas I was blind, now I see.”'},
   {ref:'John 9:31-33',title:'The man becomes bolder while his interrogators become angrier.',text:'He reasons that opening eyes from birth is evidence Jesus is from God.'},
   {ref:'John 9:35',title:'When people cast the man out, Jesus goes and finds him.',text:'Rejection by the religious court does not mean abandonment by Christ.'},
   {ref:'John 9:38',title:'Physical sight leads toward spiritual sight.',text:'The man says, “Lord, I believe,” and worships Jesus.'}
  ],
  underline:{ref:'John 9:25',reason:'The man cannot answer every argument, but he refuses to deny the grace he has actually received: “whereas I was blind, now I see.”'},
  notice:[
   {ref:'John 9:1-3',title:'Jesus directly rejects the disciples’ either-or blame question.',text:'They assume congenital blindness must trace to a particular sin of the man or his parents. Jesus answers, “Neither hath this man sinned, nor his parents” in the sense proposed by their question. He is not claiming they were sinless people; He is refusing to let disability become evidence for diagnosing someone’s secret moral guilt.'},
   {ref:'John 9:3',title:'“That the works of God should be made manifest” should not be used to say God enjoys suffering or that every disability exists only as a stage prop for a miracle.',text:'Jesus redirects the disciples from blame toward the work God is about to do. The chapter’s focus is what Christ does in the man’s present situation. It does not give us permission to explain every person’s lifelong suffering by claiming we know the hidden reason God allowed it.'},
   {ref:'John 9:4-7',title:'The Light-of-the-world claim becomes a sign you can see.',text:'Jesus has just said He is the Light of the world and then gives sight to a man blind from birth. The clay and washing do not function like a medical recipe; the power lies in Jesus. The pool’s name, Siloam, means “Sent,” fitting a Gospel that repeatedly calls Jesus the One sent by the Father.'},
   {ref:'John 9:13-16',title:'The Sabbath controversy shows how a true rule can be used to avoid a true sign.',text:'Some reason that Jesus cannot be from God because He made clay and healed on the Sabbath. Others ask how a sinner could do such signs. The chapter does not portray careful Sabbath obedience as evil; it portrays a framework so rigid that restored sight becomes evidence against the Healer.'},
   {ref:'John 9:17-34',title:'Watch the healed man’s confession grow while the investigation intensifies.',text:'At first he says “a man that is called Jesus.” Then: “He is a prophet.” Later he insists Jesus must be from God. The authorities keep demanding the same answers while becoming more hostile, but the man’s understanding becomes clearer under pressure rather than collapsing.'},
   {ref:'John 9:22-23',title:'The parents’ fear shows the social cost of confessing Jesus.',text:'They confirm that this is their son and that he was born blind, but refuse to say how he now sees because they fear being put out of the synagogue. John is not merely recording a theological disagreement; allegiance to Jesus can carry real community consequences.'},
   {ref:'John 9:31',title:'“God heareth not sinners” is spoken by the healed man inside his argument, not presented as an absolute rule that God never hears any prayer from a sinner.',text:'Scripture contains prayers of repentance precisely because sinners can cry to God for mercy. The man’s point is narrower: God would not authenticate a fraudulent, God-opposing claimant by granting such a messianic sign. We should not turn his debating sentence into a formula that makes frightened people think God cannot hear them until they become morally clean.'},
   {ref:'John 9:35-38',title:'Jesus finds the man after the authorities cast him out.',text:'The man had defended Jesus without yet fully knowing who He was. Jesus seeks him, identifies Himself as the Son of God, and brings the man to explicit faith and worship. The chapter’s deepest healing is not merely functioning eyes but recognition of Christ.'},
   {ref:'John 9:39-41',title:'The chapter ends by reversing the categories of seeing and blindness.',text:'The man who began physically blind ends worshipping Jesus. The people most certain that they see are warned that their claimed sight leaves their guilt exposed. Spiritual blindness in John is not lack of education; it is the refusal to receive the Light standing in front of you.'}
  ],
  reflections:['Have I ever been tempted to explain someone else’s suffering more confidently than Jesus allows me to?','If I could not answer every objection to my faith, what “one thing I know” about Christ’s work would I still refuse to deny?'],
  commentary:{voice:'John Gill',identity:'English Baptist pastor and commentator, 1697–1771',quote:'This life is but short, it is but as the length of a day',plain:'Gill is commenting on Jesus’ urgency to do the Father’s works while it is day. In this chapter that urgency is compassionate rather than frantic: Jesus does not spend His limited earthly ministry assigning blame to the blind man; He works the work of God and gives sight.',source:'Exposition of the Entire Bible — John 9',url:'https://biblehub.com/commentaries/gill/john/9.htm'},
  question:{q:'Did this man’s blindness happen because somebody sinned?',short:'Jesus says no to the blame framework the disciples propose. The man’s blindness is not evidence that he or his parents committed some particular sin deserving it.',more:'The Bible does teach that suffering and death exist in a world damaged by sin, and sometimes Scripture records particular judgments connected to particular sins. But those truths do not authorize us to reverse-engineer somebody’s illness, disability, accident, infertility, or grief into a secret moral diagnosis. John 9 is one of the clearest guardrails against that habit. The disciples ask whose fault it is; Jesus redirects them toward the work of God in the person in front of them.'}
 }
});
render();