// Acts 7 — Living Bookmark card.
Object.assign(studies,{
 'Acts 7':{body:''}
});

Object.assign(studyMeta,{
 'Acts 7':{
  oneLine:'Stephen answers the charge that he opposes Moses, the law, and the temple by retelling Israel’s story: God has always acted beyond one sacred place, His chosen deliverers were repeatedly rejected, the tabernacle and temple were real gifts but could never contain the Most High, and the council now repeats the old pattern by resisting the Holy Spirit and rejecting the Righteous One; they stone Stephen as he sees Jesus standing at God’s right hand and prays for his killers.',
  write:[
   {ref:'Acts 7:9',title:'Joseph was rejected by his brothers, but God was with him.',text:'Human rejection did not cancel God’s presence or His purpose.'},
   {ref:'Acts 7:35',title:'The Moses they refused became the ruler and deliverer God sent.',text:'Stephen keeps returning to the pattern of God’s chosen rescuer being rejected first.'},
   {ref:'Acts 7:48',title:'No building can contain the Most High.',text:'The temple mattered, but the God who made heaven and earth is greater than His house.'},
   {ref:'Acts 7:51',title:'Religious nearness can coexist with a heart that resists God.',text:'Stephen’s final charge is not lack of religious privilege but resistance to the Holy Spirit.'},
   {ref:'Acts 7:55-56',title:'While the court condemns Stephen, heaven gives a different verdict.',text:'He sees God’s glory and Jesus standing at the right hand of God.'},
   {ref:'Acts 7:60',title:'Stephen’s last recorded words are mercy for the people killing him.',text:'His prayer echoes the crucified Lord he has followed.'}
  ],
  underline:{ref:'Acts 7:55-56',reason:'At the moment Stephen is rejected on earth, he is given a vision of the risen Son of Man standing in the place of divine honor.'},
  notice:[
   {ref:'Acts 7:2-8',title:'Stephen begins by showing that God’s presence and promises were never confined to the Jerusalem temple.',text:'The “God of glory” appeared to Abraham in Mesopotamia, before Abraham lived in Haran and centuries before Israel possessed the land or had a temple. Stephen is not despising the holy place; he is widening the frame. Israel’s own story begins with God meeting a pilgrim outside the land.'},
   {ref:'Acts 7:2-4',title:'Stephen places God’s call to Abraham before Haran, while Genesis 12 narrates the command after Terah’s death.',text:'Genesis also says the LORD brought Abraham from Ur of the Chaldees, and later Jewish readings could understand a call beginning there and being renewed at Haran. The chronology around Terah’s age is compressed in Genesis 11, where naming Abram first does not necessarily prove he was the firstborn. Acts is summarizing the patriarchal story rather than supplying a new detailed timeline.',cross:[{ref:'Genesis 15:7',label:'God brought Abraham from Ur',reason:'God later identifies Himself as the One who brought Abraham out of Ur of the Chaldees.'},{ref:'Nehemiah 9:7',label:'Israel remembered the call from Ur',reason:'Nehemiah’s prayer also joins God’s choosing of Abram with bringing him out of Ur.'}]},
   {ref:'Acts 7:5',title:'Abraham receives promise before possession.',text:'Stephen stresses that Abraham had no inheritable foothold in the land at first, yet God promised it to him and his descendants. The story therefore rests on God’s promise before it rests on visible ownership.'},
   {ref:'Acts 7:9-16',title:'Joseph becomes Stephen’s first major example of a rejected deliverer.',text:'The patriarchs act from envy and sell Joseph, but God is with the rejected brother and later uses him to preserve the very family that rejected him. Stephen is preparing a pattern that will intensify with Moses and finally with Jesus.'},
   {ref:'Acts 7:14',title:'Stephen’s “seventy-five” follows the Greek Old Testament’s counting tradition.',text:'The Hebrew text behind many English Old Testaments gives seventy people connected with Jacob’s descent into Egypt, while the ancient Greek Septuagint form of Genesis 46 gives seventy-five by including additional descendants of Joseph. Stephen, a Greek-speaking Jewish believer, speaks in the scriptural form familiar in that world. The difference is a counting/textual tradition, not a different gospel message.',cross:[{ref:'Genesis 46:26-27',label:'The family count',reason:'Genesis preserves the family-number tradition that appears as seventy in the Hebrew form and seventy-five in the ancient Greek form.'}]},
   {ref:'Acts 7:16',title:'The burial summary is one of the hardest historical details in Stephen’s speech and deserves an honest note.',text:'Genesis records Abraham buying Machpelah near Hebron from Ephron, while Jacob buys land at Shechem from Hamor’s sons; Joshua records Joseph’s bones being buried at Shechem. Acts 7 compresses the patriarchal burial story in wording that appears to combine those traditions. Interpreters have proposed telescoping two purchases, reliance on an additional Jewish tradition, or a textual/transmission difficulty. The verse should not be “fixed” by pretending Genesis says exactly the same thing it does not.',cross:[{ref:'Genesis 23:16-20',label:'Abraham’s recorded purchase',reason:'Abraham buys the field and cave of Machpelah from Ephron the Hittite.'},{ref:'Genesis 33:18-20',label:'Jacob’s Shechem purchase',reason:'Jacob buys a parcel of land at Shechem from the sons of Hamor.'},{ref:'Joshua 24:32',label:'Joseph buried at Shechem',reason:'Joseph’s bones are buried in the Shechem parcel Jacob had bought.'}]},
   {ref:'Acts 7:17-29',title:'Moses’ first appearance as a deliverer is followed by rejection and exile.',text:'Stephen says Moses supposed his brothers would understand that God was giving deliverance through him, but they did not. The question “Who made thee a ruler and a judge?” becomes crucial because God later does exactly that—He sends the rejected Moses back as ruler and deliverer.'},
   {ref:'Acts 7:30-34',title:'The holy ground is in Midian, not Jerusalem.',text:'God appears to Moses in the wilderness at Sinai, identifies Himself as the God of the patriarchs, hears Israel’s suffering, and calls Moses. Stephen again locates a decisive holy encounter outside the land and outside a temple. Holiness follows God’s presence; God is not trapped by geography.'},
   {ref:'Acts 7:35-38',title:'Stephen deliberately repeats “this Moses” to honor the man he is accused of attacking.',text:'The rejected Moses is the one God sends as ruler and deliverer, the one who leads Israel out, the one who speaks of the coming Prophet, and the one who receives “living oracles.” Stephen’s case is not anti-Moses. His accusation is that Israel’s history repeatedly shows people refusing the very servant God sent.',cross:[{ref:'Deuteronomy 18:15',label:'Prophet like Moses',reason:'Stephen repeats the promise already applied to Jesus in Acts 3: God would raise up a Prophet like Moses.'}]},
   {ref:'Acts 7:38',title:'“The church in the wilderness” in the KJV does not mean the New Testament church already existed under that later name.',text:'The Greek ekklēsia means an assembly or gathered congregation. Here it refers to Israel assembled in the wilderness with Moses. The word itself does not erase the historical distinctions between Israel at Sinai and the church after Christ.'},
   {ref:'Acts 7:39-43',title:'The deeper rejection of Moses happened in the heart before it appeared in the idol.',text:'Israel “in their hearts turned back again into Egypt” and then made the calf. Stephen quotes Amos to show that outward sacrificial activity could coexist with idolatrous allegiance. God’s judgment is described as giving them over to the heavenly powers they chose to worship.'},
   {ref:'Acts 7:42-43',title:'“Moloch” and “Remphan/Rephan” come through Stephen’s Greek quotation of Amos.',text:'Acts follows the Greek Septuagint form of Amos 5, which uses Rephan/Remphan where the Hebrew tradition has Chiun and says “beyond Babylon” where the Hebrew says “beyond Damascus.” Stephen is quoting Scripture in the Greek form used by his audience and community. The point of the quotation is stable across the forms: Israel carried idolatry alongside outward worship and was therefore sent into exile.',cross:[{ref:'Amos 5:25-27',label:'Stephen’s prophetic quotation',reason:'Stephen draws his accusation from Amos’s warning that religious offerings did not cancel Israel’s idolatry.'}]},
   {ref:'Acts 7:44-47',title:'Stephen does not say the tabernacle or temple was a mistake.',text:'The wilderness tabernacle was made according to the pattern God gave Moses. David desired a dwelling place, and Solomon built the house. Stephen’s argument is not that sacred space is evil; it is that even a God-given sanctuary must never be confused with containing or controlling the God who gave it.'},
   {ref:'Acts 7:48-50',title:'“The Most High dwelleth not in temples made with hands” is Isaiah’s theology, not contempt for worship.',text:'Stephen quotes Isaiah 66: heaven is God’s throne, earth His footstool, and His own hand made everything. Solomon himself had already confessed that heaven and the heaven of heavens cannot contain God. The temple can be a true place of worship without becoming God’s address in the sense of limiting His presence.',cross:[{ref:'1 Kings 8:27',label:'Solomon’s own temple prayer',reason:'At the temple dedication Solomon says even the highest heaven cannot contain God, much less the house he built.'},{ref:'Isaiah 66:1-2',label:'Stephen’s quotation',reason:'The prophet denies that any human-built house can contain the Creator of heaven and earth.'}]},
   {ref:'Acts 7:51-53',title:'Stephen turns the accusation around: the council reveres the law but has not obeyed the God to whom the law points.',text:'“Stiffnecked” and “uncircumcised in heart and ears” are Israel’s own covenant vocabulary. Stephen is not attacking Jewish ethnicity; he is a Jew speaking as an Israelite prophet within Israel’s Scriptures. The charge is covenant unfaithfulness—resisting the Holy Spirit and repeating the pattern of persecuting God’s messengers.',cross:[{ref:'Deuteronomy 10:16',label:'Circumcision of heart',reason:'Moses himself commands Israel to circumcise the heart and be stiff-necked no longer.'},{ref:'Jeremiah 6:10',label:'Uncircumcised ears',reason:'Jeremiah describes ears unable to hear the word of the LORD.'}]},
   {ref:'Acts 7:53',title:'The law “by the disposition of angels” reflects an early Jewish and Christian way of describing Sinai.',text:'Exodus emphasizes God’s presence at Sinai, while later biblical texts also speak of angelic hosts attending the giving of the law. Paul and Hebrews use similar language. The point here is not to diminish the law but to heighten the council’s responsibility: they received a divinely attended law and did not keep it.',cross:[{ref:'Galatians 3:19',label:'Similar New Testament language',reason:'Paul also describes the law as ordained through angels by a mediator.'},{ref:'Hebrews 2:2',label:'Similar tradition',reason:'Hebrews speaks of the word declared through angels as binding.'}]},
   {ref:'Acts 7:54-56',title:'The “standing” Son of Man has invited several faithful interpretations, and Acts does not explain the posture for us.',text:'Jesus is usually pictured seated at God’s right hand. Here Stephen sees Him standing. Christians have understood this as Christ rising to welcome His martyr, standing as Stephen’s heavenly advocate or witness, or standing in readiness for judgment. All fit parts of the scene; Luke tells us what Stephen saw without explicitly choosing among those explanations.'},
   {ref:'Acts 7:56',title:'Stephen calls Jesus “the Son of man” in the very council where Jesus had used that title about His own exaltation.',text:'The title is overwhelmingly spoken by Jesus in the Gospels. Stephen’s vision echoes Jesus’ words before the high priest about the Son of Man at the right hand of Power. The court that rejected Jesus’ claim now hears Stephen say he sees its heavenly reality.',cross:[{ref:'Luke 22:69',label:'Jesus before the council',reason:'Jesus had told the council that the Son of Man would sit at the right hand of the power of God.'}]},
   {ref:'Acts 7:57-58',title:'Whether Stephen’s death is best described as a formal execution or a mob killing is debated.',text:'He is taken outside the city and stoned, and Luke mentions witnesses laying aside garments, details that resemble legal stoning procedure. Yet the scene erupts in a rush of rage, and Judea under Roman rule did not ordinarily possess unrestricted authority to carry out capital sentences. Many readers therefore see a lynching clothed in some judicial forms; others think the council carried out a sentence in an exceptional moment. Luke’s emphasis is on violent rejection, not on resolving the jurisdiction question.'},
   {ref:'Acts 7:58',title:'Saul enters Acts silently, standing beside Stephen’s killers.',text:'The witnesses place their garments at the feet of a young man named Saul. Luke will soon tell us Saul approved Stephen’s death and then ravaged the church. The future apostle first appears on the wrong side of the story.'},
   {ref:'Acts 7:59',title:'The Greek text shows Stephen directly addressing Jesus.',text:'The KJV supplies “God” in the phrase “calling upon God,” but the Greek simply describes Stephen calling out and saying, “Lord Jesus, receive my spirit.” His dying prayer entrusts his life to the risen Jesus he has just seen.'},
   {ref:'Acts 7:59-60',title:'Stephen’s death deliberately echoes Jesus without making Stephen equal to Jesus.',text:'Jesus entrusted His spirit to the Father and prayed forgiveness for His executioners. Stephen entrusts his spirit to Jesus and asks that the killers’ sin not be held against them. The disciple is being conformed to his Lord in suffering and mercy.',cross:[{ref:'Luke 23:34',label:'Prayer for enemies',reason:'Jesus prays for forgiveness for those crucifying Him.'},{ref:'Luke 23:46',label:'Entrusting the spirit',reason:'Jesus commits His spirit to the Father; Stephen entrusts his spirit to Jesus.'}]}
  ],
  reflections:['When I feel misunderstood or accused, can I answer from the larger story of God instead of only defending myself?','Am I ever tempted to confuse a God-given practice, place, tradition, or routine with God Himself?','What would it mean for Christ’s mercy to shape my response even toward someone who is treating me unjustly?'],
  commentary:{voice:'Matthew Poole',identity:'English Nonconformist biblical commentator, 1624–1679',quote:'standing ready to assist and comfort all that should suffer for his sake',plain:'Poole reads Jesus’ unusual standing posture as personal nearness to a suffering witness. Luke does not explain exactly why Jesus stands, so this remains an interpretation rather than a certainty; but it beautifully captures what the whole scene shows—Stephen is not abandoned when the earthly court turns against him.',source:'Annotations upon the Holy Bible — Acts 7:55',url:'https://biblehub.com/commentaries/acts/7-55.htm'},
  question:{q:'Why does Stephen say seventy-five people went to Egypt when Genesis in many Bibles says seventy?',short:'Stephen is using the ancient Greek Old Testament’s form of the family count, which gives seventy-five; the Hebrew textual tradition gives seventy. Both are ancient ways of counting Jacob’s extended family around the move to Egypt.',more:'Acts 7:14 is not the only evidence for the seventy-five figure. The Septuagint—the Greek Old Testament widely used in the first-century Greek-speaking Jewish world—has an expanded form of Genesis 46:27 that counts additional descendants of Joseph and totals seventy-five. The Hebrew Masoretic tradition totals seventy, a number repeated in Exodus 1:5 and Deuteronomy 10:22. Stephen is a Hellenistic Jewish Christian speaking in a Greek-language setting, so his use of the Greek scriptural form is unsurprising. The two figures count the family list according to different textual/counting traditions; Stephen’s argument does not depend on whether the total is seventy or seventy-five.'}
 }
});
render();
