// Acts 3 — Living Bookmark card.
Object.assign(studies,{
 'Acts 3':{body:''}
});

Object.assign(studyMeta,{
 'Acts 3':{
  oneLine:'Peter and John meet a man lame from birth at the temple gate, heal him in Jesus’ name, refuse credit for the miracle, and use the sign to proclaim the rejected but risen Servant of God, calling Israel to repent and turn toward the promised times of refreshing, the restoration spoken by the prophets, and the Prophet like Moses.',
  write:[
   {ref:'Acts 3:4',title:'Peter and John make the man more than a problem to walk past.',text:'“Look on us” gives him attention before it gives him anything else.'},
   {ref:'Acts 3:6',title:'Peter does not pretend to have what he does not have.',text:'He has no silver or gold, but he gives what Christ has actually entrusted to him.'},
   {ref:'Acts 3:12',title:'The apostles refuse to turn a miracle into their own platform.',text:'Peter immediately denies that personal power or holiness made the man walk.'},
   {ref:'Acts 3:15',title:'Human beings killed the Prince of life, but God raised Him from the dead.',text:'Peter puts the contradiction at the center of his sermon.'},
   {ref:'Acts 3:19',title:'Repentance is pictured as turning back toward God.',text:'Peter connects that turning with sins being blotted out and refreshment from the Lord’s presence.'},
   {ref:'Acts 3:26',title:'The blessing promised through Abraham includes being turned away from sin.',text:'Biblical blessing is deeper than comfort or material increase.'}
  ],
  underline:{ref:'Acts 3:19',reason:'Peter’s call is both urgent and hopeful: repent and turn, so sins may be blotted out and refreshing may come from the Lord.'},
  notice:[
   {ref:'Acts 3:1',title:'Peter and John are still going to the temple at the Jewish hour of prayer.',text:'The ninth hour is about three in the afternoon, a regular prayer time. Acts does not begin with Jewish believers instantly abandoning Israel’s worship life. The first Christian community is deeply Jewish, centered on Jesus as Israel’s Messiah, and only gradually forced to work out what His fulfillment means for old boundaries.'},
   {ref:'Acts 3:2-5',title:'The man has a history before he has a miracle.',text:'Luke says he has been lame from his mother’s womb and is carried daily to the gate to ask alms. The crowd later recognizes him precisely because his disability and begging place were publicly known. That makes the healing difficult to dismiss as mistaken identity or a temporary condition.'},
   {ref:'Acts 3:4',title:'“Look on us” restores ordinary human attention before the spectacular healing happens.',text:'The man is accustomed to being placed where worshippers pass and asking them for money. Peter and John stop and look at him, then ask him to look back. The narrative does not reduce him to a prop whose only value is proving apostolic power.'},
   {ref:'Acts 3:6-8',title:'“Silver and gold have I none” is not a command for the church to romanticize poverty or refuse practical help.',text:'Acts has just described believers sharing material resources with people in need. Peter is simply honest about what he does not have at this moment and then gives what he has been empowered to give: healing in Jesus’ name. The miracle is not permission to tell needy people that spiritual words should always replace material care.'},
   {ref:'Acts 3:8-10',title:'Luke piles up movement words because the man’s condition has genuinely changed.',text:'He leaps up, stands, walks, enters the temple, and keeps walking and leaping while praising God. The man who used to be carried to the gate now goes through it on his own feet. The sign restores participation as well as mobility.'},
   {ref:'Acts 3:11-12',title:'Peter refuses the exact two explanations religious celebrity can tempt people to believe.',text:'He asks why they stare “as though by our own power or holiness we had made this man to walk.” Apostolic authority is not personal spiritual magic, and a miracle is not evidence that the human instrument is exceptionally holy. Peter redirects the crowd toward the God of Abraham, Isaac, and Jacob and toward Jesus.'},
   {ref:'Acts 3:13',title:'The KJV’s “his Son Jesus” translates a word that can also mean “servant.”',text:'The Greek pais can mean child, son, or servant depending on context. Here many translations use “Servant Jesus,” and the wording strongly echoes Isaiah’s Servant language. Peter is presenting Jesus as the One glorified by the God of Israel in fulfillment of Scripture, not introducing an unrelated religious figure.',cross:[{ref:'Isaiah 52:13',label:'Servant background',reason:'Isaiah introduces the LORD’s Servant as the one who will be exalted and glorified, language that fits Peter’s description of Jesus.'}]},
   {ref:'Acts 3:13-15',title:'Peter names the Jerusalem crowd’s role sharply, but this must not become collective blame against Jewish people.',text:'He says they delivered Jesus up, denied Him before Pilate, chose a murderer, and killed the Prince of life. Peter himself is Jewish, John is Jewish, the healed man is Jewish, and the people being invited to repent are Jewish. Roman authority carried out the crucifixion. The sermon confronts a specific audience’s participation in rejecting Jesus; it does not authorize racial guilt across generations.'},
   {ref:'Acts 3:15-16',title:'The miracle is evidence for the risen Jesus whom the apostles claim to have seen.',text:'Peter says God raised Jesus “whereof we are witnesses,” then explains that Jesus’ name has strengthened the man. In biblical thought a name represents the person and authority, not a verbal formula with magical force. The power belongs to the living Christ.'},
   {ref:'Acts 3:16',title:'The wording about “faith in his name” leaves a small question about whose faith is being emphasized.',text:'The verse can be read as emphasizing faith in Jesus exercised by the apostles, the healed man, or the whole faith-event centered on Christ. Luke has not told us that the man expressed faith before Peter took him by the hand. The safest center is Peter’s own conclusion: the completeness of the healing comes through faith associated with Jesus, not through apostolic power or merit.'},
   {ref:'Acts 3:17-18',title:'Ignorance can lessen the kind of guilt involved without making the action innocent.',text:'Peter says the people and their rulers acted “through ignorance,” then immediately calls them to repent. He also says God fulfilled what the prophets foretold about Christ’s suffering through these events. Acts again refuses to choose between divine purpose and human responsibility.'},
   {ref:'Acts 3:19',title:'“Be converted” in older English means turn back, not wait passively for something to happen to you.',text:'Peter says “Repent ye therefore, and be converted,” using conversion language in the sense of turning or returning. The image of sins being “blotted out” is like a written charge being erased. Repentance does not purchase forgiveness; it turns toward the God who gives it.'},
   {ref:'Acts 3:19-21',title:'“Times of refreshing” and “restitution of all things” point toward God’s promised future renewal, but the exact end-times sequence is debated.',text:'Peter looks ahead to refreshment from the Lord’s presence, the sending of Christ, and the “restitution” or restoration of all things spoken by the prophets. Christians differ over how this relates to Israel, the millennium, and the timing of Christ’s return. The passage clearly promises real divine renewal; it does not give enough detail here to force one full prophetic chart.'},
   {ref:'Acts 3:21',title:'“Restitution of all things” should not be made to prove universal salvation by itself.',text:'The phrase describes the comprehensive restoration God promised through the prophets, but the same sermon warns that the person who refuses God’s Prophet will be cut off. Whatever “all things” includes, Peter does not teach that every person will finally be saved regardless of response to Christ.'},
   {ref:'Acts 3:22-23',title:'Peter identifies Jesus with Moses’ promised Prophet and keeps the warning attached.',text:'Deuteronomy promised that God would raise up a prophet like Moses whom Israel must hear. Peter says that promise reaches Jesus. The comparison is not merely that both men taught well; both stand at decisive moments of covenant revelation, and refusing the promised Prophet carries judgment.',cross:[{ref:'Deuteronomy 18:15-19',label:'Direct quotation and fulfillment',reason:'Peter applies Moses’ promise of a coming prophet like him directly to Jesus.'}]},
   {ref:'Acts 3:24-26',title:'Peter joins Moses, the prophets, and Abraham into one story that moves toward Jesus.',text:'The prophets from Samuel onward spoke of these days, and the audience are “children of the prophets” and of the covenant with Abraham. The promise that all families of the earth will be blessed through Abraham’s seed is not detached from repentance: Peter says God sent His Servant first to Israel “in turning away every one of you from his iniquities.”',cross:[{ref:'Genesis 22:18',label:'Covenant promise',reason:'Peter reaches back to the promise that all nations of the earth would be blessed through Abraham’s seed.'}]}
  ],
  reflections:['When God does something good through me, how quickly do I redirect attention away from my power or holiness and toward Christ?','Do I think of God’s blessing mainly as receiving good things, or also as being turned away from what is destroying me?'],
  commentary:{voice:'Alexander Maclaren',identity:'Scottish Baptist preacher and expositor, 1826–1910',quote:'Some quick touch of pity shot through the two friends’ hearts',plain:'Maclaren notices compassion before power. Peter and John do not begin Acts 3 by planning a public miracle; they stop for a man whose need has become part of the scenery for everybody else. The sign grows out of attention, pity, and the authority of Jesus—not a desire to build the apostles’ reputation.',source:'Expositions of Holy Scripture — Acts 3',url:'https://biblehub.com/commentaries/maclaren/acts/3.htm'},
  question:{q:'What are the “times of refreshing” and the “restitution of all things” in Acts 3?',short:'Peter is looking toward the future fullness of God’s promised renewal associated with Christ’s return; Christians agree on the reality of that restoration but differ over its detailed prophetic sequence.',more:'The language reaches beyond a private moment of emotional refreshment. Peter speaks of refreshing from the Lord’s presence, God sending the appointed Christ, and heaven receiving Him until the “times of restitution of all things” spoken by the prophets. That points toward the broad biblical hope that God will set right what sin has damaged. Interpreters differ over how Israel’s restoration, the millennium, the final judgment, and the new creation fit within the sequence. Acts 3 itself does not settle every later eschatological debate. It does make the practical response clear: repent and turn to God now, because the promised future belongs to the Christ Peter is proclaiming.'}
 }
});
render();