// John 14 — Living Bookmark card.
Object.assign(studies,{
 'John 14':{body:''}
});

Object.assign(studyMeta,{
 'John 14':{
  oneLine:'Jesus comforts troubled disciples by promising the Father’s house and His return, identifies Himself as the Way, the Truth, and the Life, reveals the Father through Himself, promises answered prayer and the abiding Holy Spirit, gives His own peace, and explains His departure as a return to the Father rather than abandonment.',
  write:[
   {ref:'John 14:1',title:'Jesus speaks peace before circumstances become peaceful.',text:'The arrest is coming, yet He tells troubled hearts to trust God and trust Him.'},
   {ref:'John 14:2',title:'The Father’s house has room.',text:'Jesus is not teasing anxious disciples with uncertainty; He goes ahead to prepare their place.'},
   {ref:'John 14:6',title:'Jesus does not merely teach a way.',text:'He says, “I am the way, the truth, and the life.”'},
   {ref:'John 14:9',title:'To know Jesus is to be brought face to face with the Father’s self-revelation.',text:'“He that hath seen me hath seen the Father.”'},
   {ref:'John 14:18',title:'Jesus will not leave His disciples as orphans.',text:'His departure will not mean abandonment.'},
   {ref:'John 14:27',title:'Christ’s peace is not the world’s fragile version.',text:'He gives peace while danger still remains outside the room.'}
  ],
  underline:{ref:'John 14:6',reason:'Jesus gathers the whole question of access to the Father into Himself: Way, Truth, and Life.'},
  notice:[
   {ref:'John 14:1',title:'“Believe in God, believe also in me” has a small grammatical ambiguity but a very large claim.',text:'The Greek verbs can be read as statements or commands, which is why translations vary slightly. The practical force is clear in context: the disciples’ trust in God is joined directly to trust in Jesus as He prepares them for His departure.'},
   {ref:'John 14:2-3',title:'“Many mansions” means many abiding places or rooms, not a promise that each believer receives a luxury estate.',text:'The older English word “mansion” meant a dwelling place. Jesus’ comfort is that the Father’s house has abundant room and that He personally prepares the way for His people to be with Him. The emphasis is belonging and presence, not heavenly square footage.'},
   {ref:'John 14:4-7',title:'Thomas’s honest confusion opens one of Jesus’ clearest self-revelations.',text:'Thomas says he does not know where Jesus is going, so how can he know the way? Jesus does not hand him a route map. He identifies Himself as the route: Way because He reveals the Father in truth and communicates life. “No man cometh unto the Father, but by me” makes access to God inseparable from the Son.'},
   {ref:'John 14:8-11',title:'Philip asks to see the Father, and Jesus points him back to the Son he has already been watching.',text:'Jesus does not say He is the Father as though Father and Son were the same person. He speaks of mutual indwelling—He is in the Father and the Father in Him—and says His words and works reveal the Father. John’s Gospel maintains distinction and unity together.'},
   {ref:'John 14:12',title:'“Greater works” does not have to mean every later Christian will perform more spectacular miracles than Jesus.',text:'Jesus connects the promise with His going to the Father. After His death, resurrection, ascension, and gift of the Spirit, the apostolic witness will spread far beyond the geographical reach of His earthly ministry. Christians differ over how miracle gifts apply today, but the verse should not become a measuring stick that makes ordinary faithful disciples feel defective because they have not surpassed Jesus’ signs.'},
   {ref:'John 14:13-14',title:'Praying “in Jesus’ name” is not a magic phrase attached to the end of any request.',text:'A name in Scripture represents the person, character, and authority. Prayer in His name asks as someone belonging to Him and seeking the Father’s glory through the Son. The promise sits inside a chapter about love, obedience, mission, and the Father’s will, not human control of divine power.'},
   {ref:'John 14:15-17',title:'The “another Comforter” is explicitly the Holy Spirit.',text:'The Greek paraklētos can carry ideas such as Helper, Advocate, or Comforter. Jesus has been the disciples’ present helper; He promises another who will abide with them. Father, Son, and Spirit are all active in the same promise without being collapsed into one person.'},
   {ref:'John 14:18-24',title:'Jesus’ departure will not make the disciples orphans.',text:'He promises His coming presence and speaks of Father and Son making their abode with the one who loves Him. The chapter moves from a prepared dwelling in the Father’s house to God making His dwelling with His people now. Future hope and present presence belong together.'},
   {ref:'John 14:25-26',title:'The Spirit’s teaching and reminder promise has a special first reference to the apostles who heard Jesus directly.',text:'The Comforter will teach them and bring Jesus’ words to remembrance. That promise helps explain the trustworthy apostolic witness from which the church learns. Believers also depend on the Spirit’s illumination, but this verse should not be used to make every private impression equal to apostolic revelation.'},
   {ref:'John 14:27',title:'Jesus gives peace without promising an immediately peaceful environment.',text:'Within hours there will be betrayal, arrest, scattering, and death. His peace is therefore not the absence of trouble. It is the settled gift of the One who knows the Father, knows where He is going, and will not abandon His own.'},
   {ref:'John 14:28',title:'“My Father is greater than I” belongs to the context of Jesus’ mission and return to the Father.',text:'Christians have long debated how best to state the verse in relation to Father and Son. John has already called the Word God and repeatedly shown divine works and honor belonging to the Son. Here Jesus is comforting disciples who grieve His departure: they should rejoice that the Son who humbled Himself and came into their world is returning to the Father. The verse should neither be erased nor isolated from the whole Gospel.'}
  ],
  reflections:['What trouble am I treating as evidence that Christ has left me alone, even though His promise is “I will not leave you comfortless”?','When I pray in Jesus’ name, am I merely using the words—or actually asking as someone who wants His character and the Father’s glory?'],
  commentary:{voice:'Alexander Maclaren',identity:'Scottish Baptist preacher and expositor, 1826–1910',quote:'We show a way, Christ is it. We speak truth, Christ is it.',plain:'Maclaren notices how unusual Jesus’ claim is. Other teachers can point, explain, or testify; Jesus places His own person at the center. The way to the Father is not finally a technique or information set but the Son who reveals God and gives life.',source:'Expositions of Holy Scripture — John 14',url:'https://biblehub.com/commentaries/maclaren/john/14.htm'},
  question:{q:'What does Jesus mean by “My Father is greater than I”?',short:'In this chapter Jesus is speaking as the Son who has come into the world and is returning to the Father; the verse describes the relationship within His saving mission and should be read beside John’s equally strong statements about the Son’s deity and unity with the Father.',more:'Some ancient interpreters emphasized Jesus’ true humanity; others stressed His role as the sent Son who willingly takes the servant’s place. Calvin, for example, reads the verse mainly in terms of Christ’s mediating mission—He descended to bring us to God and now returns to the Father. Whatever formulation is preferred, John 14:28 cannot responsibly be used as though John 1:1, 5:18–23, 10:30, 14:9–11, and 20:28 were absent. Nor should those verses be used to pretend Jesus never speaks of the Father as greater in this mission. Historic Christian theology learned to hold both sets of statements together rather than deleting either one.'}
 }
});
render();