// Acts 25 — Living Bookmark card.
Object.assign(studies,{
 'Acts 25':{body:''}
});

Object.assign(studyMeta,{
 'Acts 25':{
  oneLine:'Festus takes office and almost immediately faces renewed pressure to send Paul back to Jerusalem, where his enemies are planning an ambush; instead he holds a hearing in Caesarea, admits the accusations cannot be established, but suggests Jerusalem in an attempt to please the leaders, prompting Paul to exercise his Roman right of appeal to Caesar; when Herod Agrippa II and Bernice visit, Festus explains that the dispute centers unexpectedly on “one Jesus, which was dead, whom Paul affirmed to be alive,” and Paul is brought before a grand audience because Festus needs something coherent to write about a prisoner he has already agreed to send to the emperor.',
  write:[
   {ref:'Acts 25:4',title:'Festus does not grant the requested transfer.',text:'A dangerous plan can be stopped through an ordinary administrative decision.'},
   {ref:'Acts 25:8',title:'Paul answers the actual charges.',text:'He denies wrongdoing against Jewish law, the temple, and Caesar.'},
   {ref:'Acts 25:10',title:'Paul knows when to use the legal protection available to him.',text:'Trust in God and lawful self-defense are not opposites.'},
   {ref:'Acts 25:11',title:'Paul does not ask to escape justice.',text:'If he deserves death, he says he will accept the judgment; what he rejects is being handed over without proof.'},
   {ref:'Acts 25:19',title:'Festus accidentally states the heart of the Christian claim.',text:'The dispute is about Jesus, who died, and whom Paul insists is alive.'},
   {ref:'Acts 25:27',title:'Even Festus recognizes the absurdity of punishment without a clear charge.',text:'Sending a prisoner while being unable to state his offense exposes how weak the case has become.'}
  ],
  underline:{ref:'Acts 25:19',reason:'A Roman governor who does not share Paul’s faith still summarizes the controversy around the decisive claim: Jesus was dead, and Paul says He is alive.'},
  notice:[
   {ref:'Acts 25:1-3',title:'Festus inherits Paul’s case immediately—and the old assassination plan is still alive.',text:'Only three days after entering the province, Festus goes from Caesarea to Jerusalem. The leading priests ask that Paul be transferred there, but Luke tells the reader what they do not tell Festus: men are waiting to kill Paul on the road. Two years of delay have not dissolved the hostility.'},
   {ref:'Acts 25:4-5',title:'Festus refuses the requested transfer and tells the accusers to come to Caesarea.',text:'He says Paul will remain at Caesarea and invites qualified leaders to travel back with him and present any real charge. This ordinary jurisdictional decision quietly defeats the ambush before Festus appears to know it exists.'},
   {ref:'Acts 25:6-8',title:'The prosecution brings many serious accusations but still cannot prove them.',text:'Luke does not repeat every allegation because the pattern is now familiar. Paul answers the three spheres that matter: he has not sinned against Jewish law, the temple, or Caesar. Religious, sacred-space, and political accusations are all on the table, and none has been established.'},
   {ref:'Acts 25:9-11',title:'Festus’ desire to please the Jerusalem leaders puts Paul back in danger.',text:'Festus asks whether Paul is willing to be tried in Jerusalem. Paul recognizes that he is already before Caesar’s tribunal and that Festus knows he has not wronged the Jewish people. His appeal is not avoidance of judgment; it is an insistence on a lawful forum when transfer could expose him to both political pressure and assassination.'},
   {ref:'Acts 25:10',title:'“I stand at Caesar’s judgment seat” means Roman authority is already present in the provincial court.',text:'Paul is not claiming to be physically in Rome. Festus governs as Caesar’s representative, so the Caesarean tribunal is part of imperial justice. That makes a politically motivated surrender to another venue especially objectionable.'},
   {ref:'Acts 25:11',title:'“I appeal unto Caesar” invokes Paul’s status as a Roman citizen, but the precise first-century legal procedure is more complex than a modern appeal court.',text:'Roman citizens possessed important protections and avenues of appeal to imperial authority, especially in capital matters. Scholars debate the exact legal form operating in Acts 25 under provincial procedure. Luke’s narrative point is clear: Paul invokes a recognized right that removes the case from Festus’ discretion and sends it toward the emperor.'},
   {ref:'Acts 25:11',title:'The “Caesar” to whom Paul appeals is Nero.',text:'At this point Nero is the reigning emperor. The title “Caesar” functions as the imperial designation, so Paul’s appeal is to the emperor’s jurisdiction. Acts does not require us to assume Paul expected a personal face-to-face trial with Nero himself; imperial cases could be handled through delegated procedures.'},
   {ref:'Acts 25:12',title:'Festus consults his council before accepting the appeal.',text:'After conferring with his advisers, he answers, “Hast thou appealed unto Caesar? unto Caesar shalt thou go.” The decision moves Paul another step toward the promise Jesus gave in Acts 23:11 that he would testify in Rome.'},
   {ref:'Acts 25:13-14',title:'Agrippa II and Bernice arrive as royal visitors, and Festus uses their visit to discuss Paul’s unusual case.',text:'Agrippa II is the son of Herod Agrippa I and knows Jewish customs and disputes better than the newly arrived Festus. Bernice is his sister and a prominent member of the Herodian dynasty. Their presence gives Festus informed listeners as he tries to understand what report should accompany Paul to Rome.'},
   {ref:'Acts 25:14-18',title:'Festus’ retelling makes the weakness of the case visible.',text:'He says the Jerusalem leaders wanted judgment against Paul, but Roman custom requires an accused person to face accusers and answer the charge. When the hearing actually occurs, the prosecutors do not establish the crimes Festus expected.'},
   {ref:'Acts 25:16',title:'Festus states a sound principle of due process even though his own handling of Paul is imperfect.',text:'He tells Agrippa that it is not Roman custom to hand a person over before the accused has faced the accusers and had an opportunity to answer. Acts can acknowledge a just legal principle without pretending every Roman official consistently lives up to it.'},
   {ref:'Acts 25:19',title:'To Festus, the dispute sounds like religious questions centered on a dead man Paul says is alive.',text:'Festus’ wording is dismissive—“one Jesus”—but unintentionally concise. He has recognized that resurrection, not ordinary criminal conduct, lies near the center of the case. The Roman governor does not share Paul’s conviction, yet his summary preserves the gospel’s historical claim: Jesus died, and Paul declares Him living.'},
   {ref:'Acts 25:20-21',title:'Festus admits he is perplexed by the dispute.',text:'He says he was at a loss about how to investigate such questions and therefore asked whether Paul would go to Jerusalem. Paul instead appealed to the emperor. Festus’ uncertainty helps explain why Agrippa’s expertise is useful before the paperwork goes to Rome.'},
   {ref:'Acts 25:22',title:'Agrippa asks to hear Paul for himself.',text:'This is not a new criminal trial capable of overturning Paul’s appeal. It is an examination that may help Festus understand the case and gives Paul another audience for witness. Acts keeps turning legal complications into opportunities for proclamation.'},
   {ref:'Acts 25:23',title:'Luke deliberately contrasts public pomp with the chained prisoner who carries the important message.',text:'Agrippa and Bernice enter with great display alongside commanders and prominent citizens. Paul appears as the powerless prisoner, yet the next chapter will make him the central speaker. Acts repeatedly reverses ordinary ideas about who truly possesses significance and freedom.'},
   {ref:'Acts 25:24-25',title:'Festus publicly says he has found nothing worthy of death in Paul.',text:'The governor acknowledges that the loud demand for Paul’s death is not matched by evidence of a capital crime. This continues Luke’s repeated legal theme: Paul’s imprisonment advances the mission, but the narrative does not portray him as a convicted criminal.'},
   {ref:'Acts 25:26-27',title:'Festus has a paperwork problem: he is sending a prisoner to the emperor without a clear charge.',text:'Roman administration requires him to describe the case, but he admits he has nothing certain to write. He hopes Agrippa’s examination will give him something sensible to report. The irony is sharp: Paul has spent years confined while officials repeatedly struggle to identify an offense.'},
   {ref:'Acts 25:27',title:'“It seemeth to me unreasonable” is more than common sense; it exposes the injustice of vague accusation.',text:'Festus recognizes that sending a prisoner while failing to specify the charges makes no legal sense. Acts keeps returning to the need for evidence, identifiable accusations, and opportunity for defense rather than guilt by rumor or crowd pressure.'}
  ],
  reflections:['When I am accused unfairly, can I answer what is actually being claimed instead of fighting every imagined accusation at once?','Do I confuse trust in God with refusing ordinary lawful means of protection that may be available to me?','If someone unfamiliar with Christianity listened to me for a while, would they understand that the risen Jesus—not merely religious culture—is at the center of what I believe?'],
  commentary:{voice:'John Chrysostom',identity:'Archbishop of Constantinople and early Christian preacher, c. 347–407',quote:'he does his part, all that in him lies, committing the whole to God',plain:'Chrysostom notices that Paul’s appeal to Caesar is not unbelief in Jesus’ promise that he will reach Rome. Paul trusts the promise and still uses the lawful means available to him. Confidence in God does not require recklessness or passivity.',source:'Homily LI on the Acts of the Apostles — Acts 25:4–12',url:'https://www.newadvent.org/fathers/210151.htm'},
  question:{q:'If Jesus had already promised Paul would testify in Rome, why did Paul need to appeal to Caesar?',short:'Because trusting God’s promise did not make Paul passive. The appeal was one of the ordinary means through which the promised journey to Rome actually happened.',more:'Acts 23:11 gives Paul a divine promise: he will bear witness in Rome. Acts 25 then shows Festus considering a return to Jerusalem, while Paul knows his accusers have already plotted against his life. Paul does not say, “God promised Rome, so I can ignore danger and legal procedure.” He invokes his Roman right and appeals to Caesar. John Chrysostom made this point centuries ago: Paul acts responsibly and commits the outcome to God rather than deliberately placing himself in avoidable danger just to test whether God will rescue him. Providence often works that way in Acts. God gives the destination, while human decisions, laws, escorts, hearings, and even imprisonment become the road by which He brings Paul there.'}
 }
});
render();
