// John 20 — Living Bookmark card.
Object.assign(studies,{
 'John 20':{body:''}
});

Object.assign(studyMeta,{
 'John 20':{
  oneLine:'The empty tomb moves Mary, Peter, and the beloved disciple from confusion toward resurrection faith; the risen Jesus calls Mary by name, brings peace and the Spirit to frightened disciples, meets Thomas inside his demand for evidence, receives the confession “My Lord and my God,” and John states that these signs were written so readers may believe and have life in Jesus’ name.',
  write:[
   {ref:'John 20:8',title:'The beloved disciple sees the empty-tomb evidence and believes.',text:'Understanding grows as the disciples stand inside what they did not expect.'},
   {ref:'John 20:16',title:'Mary recognizes Jesus when He calls her by name.',text:'The Shepherd’s voice reaches her before her eyes understand.'},
   {ref:'John 20:19',title:'Jesus enters a locked room with “Peace be unto you.”',text:'Fear does not get the first word from the risen Lord.'},
   {ref:'John 20:21',title:'Resurrection peace turns into mission.',text:'“As my Father hath sent me, even so send I you.”'},
   {ref:'John 20:28',title:'Thomas answers Jesus with one of the Gospel’s highest confessions.',text:'“My Lord and my God.”'},
   {ref:'John 20:31',title:'John tells us why he selected these signs.',text:'They are written so we may believe Jesus is the Christ, the Son of God, and have life in His name.'}
  ],
  underline:{ref:'John 20:28',reason:'The Gospel that opened with “the Word was God” reaches its resurrection climax in Thomas’s confession to Jesus: “My Lord and my God.”'},
  notice:[
   {ref:'John 20:1-10',title:'The empty tomb is discovered, not staged as something the disciples were expecting.',text:'Mary initially assumes the body has been moved. Peter and the beloved disciple run to the tomb and find linen wrappings but no Jesus. John says the beloved disciple “saw, and believed,” while also admitting that they did not yet understand the Scripture about resurrection. Their faith is growing in contact with evidence they are still learning to interpret.'},
   {ref:'John 20:11-16',title:'Mary can see Jesus and still fail to recognize Him until He says her name.',text:'Grief, surprise, and the changed condition of resurrection all belong to the scene. Jesus asks why she weeps; she assumes He is the gardener. One word—“Mary”—changes everything. The moment echoes the Good Shepherd who calls His own sheep by name.'},
   {ref:'John 20:17',title:'“Touch me not” is better understood as “Do not keep clinging to me” than as a rule that Jesus’ risen body could not be touched.',text:'The Greek uses a present imperative that can carry the sense of stopping or not continuing an action. Elsewhere the risen Jesus invites physical contact, including Thomas in this chapter. Mary is being redirected from trying to hold onto the old form of Jesus’ earthly presence; He is ascending to the Father and sends her as a messenger instead.'},
   {ref:'John 20:17-18',title:'Jesus calls the disciples “my brethren” after their failure.',text:'The message is not merely “I am alive.” He says, “I ascend unto my Father, and your Father; and to my God, and your God.” The wording preserves His unique Sonship while bringing His followers into a newly declared family relationship.'},
   {ref:'John 20:19-23',title:'The locked-room appearance joins peace, mission, the Spirit, and forgiveness.',text:'Jesus shows the wounds, repeats “Peace,” commissions the disciples as the Father sent Him, breathes on them, and says, “Receive ye the Holy Ghost.” Christians differ over exactly how this moment relates chronologically and theologically to Pentecost in Acts 2—whether as an actual anticipatory gift, an enacted promise, or a Johannine presentation of the Spirit’s commissioning presence. The text clearly ties resurrection mission to divine breath and the Spirit.'},
   {ref:'John 20:23',title:'Christians have also differed over how the church exercises the authority to forgive and retain sins.',text:'Catholic and Orthodox traditions have connected this text strongly with sacramental absolution through ordained ministry. Many Protestants understand it primarily as apostolic and church authority to proclaim the gospel’s forgiveness and to declare its consequences faithfully. The verse should not be flattened into personal power to decide arbitrarily whose sins God must forgive. The commission comes from the risen Christ, in the Spirit, inside the mission He has just given.'},
   {ref:'John 20:24-25',title:'Thomas is not the only disciple in the chapter who needed evidence.',text:'Mary first thinks the body is missing, and the others rejoice after Jesus shows His hands and side. Thomas’s demand is stronger and more explicit, but John does not need us to turn him into a cartoon villain called “Doubting Thomas.” He is a grieving disciple who says what evidence he thinks he needs.'},
   {ref:'John 20:26-29',title:'Jesus meets Thomas’s stated demand and then calls future believers blessed.',text:'Eight days later Jesus comes again and repeats Thomas’s own language about the wounds. Thomas answers, “My Lord and my God.” Jesus then looks beyond the eyewitness generation to people who will believe without seeing Him physically. That blessing prepares the reader for the purpose statement in the next verses.'},
   {ref:'John 20:28',title:'Thomas’s “My Lord and my God” is addressed to Jesus, not merely exclaimed into the air.',text:'The Greek says Thomas answered “to him.” John began by saying the Word was God, filled the Gospel with signs and “I am” sayings, and now places this direct confession at the resurrection climax. Jesus does not correct Thomas for blasphemy; He speaks about the faith the confession expresses.'},
   {ref:'John 20:30-31',title:'John openly tells us that this Gospel is a selected witness, not a claim to record everything Jesus ever did.',text:'Many other signs are not written here. These are chosen so readers may believe that Jesus is the Christ, the Son of God, and by believing have life in His name. The selectivity is part of the author’s method, not a defect in the record.'}
  ],
  reflections:['When grief or fear makes Christ hard for me to recognize, can I still listen for the Shepherd who knows me by name?','What difference does it make that resurrection faith in John is not an escape from mission, but immediately becomes “so send I you”?'],
  commentary:{voice:'John Calvin',identity:'Reformation pastor and commentator, 1509–1564',quote:'by a single word, he corrects her mistake',plain:'Calvin is speaking about Jesus saying Mary’s name. Mary has the empty tomb, angels, and Jesus standing in front of her, but recognition comes when the Shepherd addresses her personally. The risen Christ does not shame her confusion; He calls her, then gives her a message to carry.',source:'Commentary on John — John 20',url:'https://biblehub.com/commentaries/calvin/john/20.htm'},
  question:{q:'What does John 20:23 mean when Jesus says the disciples can forgive or retain sins?',short:'Christian traditions differ on the precise church practice, but the authority is never independent or arbitrary: the risen Christ commissions His Spirit-empowered witnesses to carry His message and its real verdict about forgiveness.',more:'Catholic and Orthodox readers have historically seen here a strong foundation for sacramental confession and absolution through ordained ministry. Many Protestant readers understand the words as authority to announce what the gospel itself declares—those who receive Christ are forgiven; persistent rejection leaves sin retained—and also connect the verse with church discipline. Some scholars note that the grammar of the second clause is less simple than English “retain sins” can suggest. Bookmark can state the common center without pretending the traditions agree on every mechanism: Jesus entrusts His community with a serious ministry concerning sin and forgiveness, but the church does not become a rival source of grace free to contradict the Lord who sent it.'}
 }
});
render();