// Acts 26 — Living Bookmark card.
Object.assign(studies,{
 'Acts 26':{body:''}
});

Object.assign(studyMeta,{
 'Acts 26':{
  oneLine:'Given permission to speak before Agrippa, Paul stretches out his hand and turns his defense into testimony: he explains his Pharisaic hope in God’s promise to Israel, asks why resurrection should be thought incredible, confesses his violent campaign against Jesus’ followers, retells the heavenly encounter in which the risen Jesus appointed him a witness to Jews and Gentiles, and insists that his preaching of repentance, forgiveness, light, and resurrection says nothing beyond what Moses and the prophets anticipated; Festus calls him mad, Agrippa responds with the famous and debated “almost persuaded” line, and the rulers conclude that Paul has done nothing deserving death or imprisonment.',
  write:[
   {ref:'Acts 26:8',title:'Paul asks the room to examine its assumptions about God.',text:'If God is God, why should raising the dead automatically be judged incredible?'},
   {ref:'Acts 26:11',title:'Religious zeal can become cruelty when it is severed from truth.',text:'Paul remembers trying to force believers to blaspheme and pursuing them beyond Jerusalem.'},
   {ref:'Acts 26:16',title:'Jesus turns a persecutor into a witness.',text:'Paul is not commissioned because his past was clean but because Christ met and appointed him.'},
   {ref:'Acts 26:18',title:'The gospel moves people from darkness to light and from Satan’s power to God.',text:'Forgiveness and inheritance come through faith in Jesus.'},
   {ref:'Acts 26:20',title:'Repentance is meant to become visible.',text:'Paul preached that people should turn to God and live in ways consistent with that turning.'},
   {ref:'Acts 26:29',title:'Paul wants his hearers to share his faith, not his chains.',text:'Even as a prisoner, he desires their good rather than their humiliation.'}
  ],
  underline:{ref:'Acts 26:18',reason:'Jesus’ commission gathers the mission into one sentence: opened eyes, darkness turned to light, Satan’s authority exchanged for God’s, forgiveness of sins, and an inheritance received through faith in Christ.'},
  notice:[
   {ref:'Acts 26:1-3',title:'Paul begins respectfully without surrendering the truth.',text:'Agrippa gives him permission to speak, and Paul expresses gratitude that the king knows Jewish customs and controversies. This is not the exaggerated flattery Tertullus used with Felix; Paul identifies a real reason Agrippa is an unusually informed listener.'},
   {ref:'Acts 26:4-8',title:'Paul frames Christianity as the fulfillment of Israel’s hope, not a rejection of it.',text:'He points to his known Pharisaic past and says he is being judged for the hope of the promise God made to the fathers. His reference to “our twelve tribes” treats Israel as a whole people still hoping in God’s promise, even though the tribes had long experienced dispersion and political fragmentation.'},
   {ref:'Acts 26:8',title:'“Why should it be thought a thing incredible with you, that God should raise the dead?” challenges a theological assumption.',text:'Paul is not arguing that resurrection is ordinary. He is asking whether resurrection is impossible for the God Israel already confesses as Creator and covenant Lord. The scandal is not lack of divine power but the claim that God has actually raised Jesus.'},
   {ref:'Acts 26:9-11',title:'Paul gives the ugliest version of his former opposition without making himself the hero of the story.',text:'He imprisoned saints, voted or consented against them when they were put to death, punished them in synagogues, tried to force blasphemy, and pursued believers into foreign cities. His conversion testimony depends on grace precisely because his former zeal was destructive.'},
   {ref:'Acts 26:10',title:'“I gave my voice against them” most naturally means Paul cast his vote or gave his approval.',text:'The Greek phrase literally involves casting a voting pebble. Whether Paul held a formal Sanhedrin vote in every case is debated, but the statement clearly makes him an active participant in condemnation, not a passive observer.'},
   {ref:'Acts 26:12-14',title:'Paul’s third narrated Damascus-road account adds details suited to this audience.',text:'Luke has already told the event in Acts 9, and Paul retold it in Acts 22. Here he emphasizes the heavenly light brighter than the sun, everyone falling to the ground, and Jesus speaking in the Hebrew or Aramaic language. Repetition with selective detail is normal testimony, not evidence that Luke forgot his earlier versions.'},
   {ref:'Acts 26:14',title:'“It is hard for thee to kick against the pricks” is an image from an animal resisting a goad.',text:'A goad was a pointed implement used to direct working animals. Kicking against it only brought more pain. Jesus’ proverb pictures Saul’s resistance as futile self-injury against God’s direction. The saying is firmly present here in Acts 26; the longer KJV wording that also places it in Acts 9 comes from later manuscript tradition.'},
   {ref:'Acts 26:15-18',title:'Jesus’ commission makes Paul a witness, not the source of the message.',text:'The risen Lord appoints him to testify to what he has seen and what Jesus will yet show him. His authority is delegated. The mission belongs to Christ, and Paul’s task is to bear witness.'},
   {ref:'Acts 26:17-18',title:'The mission to the Gentiles echoes the servant language of Isaiah.',text:'Opening eyes, turning from darkness to light, and bringing people into God’s saving inheritance closely resemble Isaiah’s descriptions of God’s servant bringing light to the nations. Paul understands the Gentile mission as part of the scriptural story, not a late improvisation after Israel rejected him.',cross:[{ref:'Isaiah 42:6-7',label:'Light and opened eyes',reason:'God’s servant is appointed as a light and sent to open blind eyes and bring prisoners from darkness.'},{ref:'Isaiah 49:6',label:'Light to the Gentiles',reason:'The servant’s mission extends God’s salvation to the ends of the earth.'}]},
   {ref:'Acts 26:18',title:'“Sanctified by faith that is in me” places forgiveness and belonging in relation to Christ.',text:'The verse joins opened eyes, turning to God, forgiveness, an inheritance among the sanctified, and faith in Jesus. Sanctified here includes being set apart as God’s people; it does not mean Paul’s hearers become morally flawless the instant they believe.'},
   {ref:'Acts 26:19-20',title:'Paul says he was “not disobedient unto the heavenly vision.”',text:'He summarizes years of ministry as obedience: Damascus, Jerusalem, Judea, and the Gentiles. The message is repentance and turning to God, followed by deeds fitting repentance. Those deeds are the fruit of turning, not a price paid to purchase forgiveness.'},
   {ref:'Acts 26:21-23',title:'Paul says the real reason he was seized is his obedient witness—and that his message remains within Moses and the prophets.',text:'He credits God’s help for keeping him alive and says he witnesses to “small and great.” His claim is deliberately conservative: the Messiah would suffer, rise from the dead, and announce light to Israel and the Gentiles. Christianity is presented as fulfillment, not abandonment, of Scripture.'},
   {ref:'Acts 26:23',title:'Christ as “the first” to rise does not ignore earlier restorations to life.',text:'Scripture already records people restored from death, including Lazarus and Eutychus. Jesus is first in the decisive resurrection sense: raised into indestructible resurrection life and the beginning of the resurrection harvest promised to His people.',cross:[{ref:'1 Corinthians 15:20',label:'Christ the firstfruits',reason:'Paul calls the risen Christ the firstfruits of those who have fallen asleep, tying His resurrection to the future resurrection of His people.'}]},
   {ref:'Acts 26:24-25',title:'Festus calls Paul mad; Paul answers firmly and courteously.',text:'Festus thinks Paul’s great learning has driven him insane. Paul does not retaliate: “I am not mad, most noble Festus,” but says he speaks words of truth and soberness. Intellectual dismissal does not force him into either timidity or contempt.'},
   {ref:'Acts 26:26-27',title:'Paul turns directly to Agrippa because the events surrounding Jesus were public, not an esoteric secret.',text:'“This thing was not done in a corner” means Paul’s case rests on events and claims already known in the region. He then asks Agrippa whether he believes the prophets, pressing the king to connect his Jewish knowledge with Paul’s argument about the Messiah.'},
   {ref:'Acts 26:28',title:'“Almost thou persuadest me to be a Christian” is famous—but the Greek can carry more than one shade of meaning.',text:'The phrase en oligō may express “in a short time,” “with little effort,” or a somewhat ironic question such as “Do you think you can so quickly persuade me to become a Christian?” The KJV’s “almost” has shaped centuries of preaching, but the verse does not let us confidently measure Agrippa as nearly converted. His exact tone remains debated.'},
   {ref:'Acts 26:29',title:'Paul’s answer works whichever nuance Agrippa intended.',text:'Whether Agrippa is serious, evasive, or ironic, Paul says he prays that not only Agrippa but everyone listening might become as he is—except for the chains. Paul is the prisoner in the room, yet he sees the faith he possesses as something worth wishing for kings.'},
   {ref:'Acts 26:30-32',title:'The chapter ends with another official conclusion that Paul deserves neither death nor imprisonment.',text:'Agrippa, Festus, Bernice, and the others withdraw and agree that Paul has done nothing worthy of death or chains. Agrippa says Paul could have been released if he had not appealed to Caesar. That does not mean the appeal was a mistake: it protected Paul from a dangerous transfer and has become the legal road by which Jesus’ promise of witness in Rome will be fulfilled.'}
  ],
  reflections:['When I tell what Christ has done in my life, do I make myself impressive—or make His grace unmistakable?','Are there places where I am resisting God like an animal kicking against a goad, making obedience harder by fighting what I already know?','Could I sincerely want good even for people who have power over me, the way Paul wants his hearers to share his faith but not his chains?'],
  commentary:{voice:'John Chrysostom',identity:'Archbishop of Constantinople and early Christian preacher, c. 347–407',quote:'With gentleness, “I am not mad,” says he.',plain:'Chrysostom notices Paul’s tone when Festus publicly dismisses him as insane. Paul does not become timid, but neither does he answer contempt with contempt. He keeps speaking “truth and soberness,” preserving both courage and gentleness before a hostile or skeptical audience.',source:'Homily LII on the Acts of the Apostles — Acts 26',url:'https://www.newadvent.org/fathers/210152.htm'},
  question:{q:'Was Agrippa really “almost persuaded” to become a Christian?',short:'Possibly—but the Greek does not let us be certain. The familiar KJV wording can sound like Agrippa is on the brink of conversion, while the phrase can also mean something like, “In such a short time do you think you can persuade me to become a Christian?”',more:'Agrippa’s Greek phrase, en oligō, is compact and its tone is hard to recover from text alone. Older English tradition gave us the memorable “Almost thou persuadest me to be a Christian,” which has produced many powerful sermons about being nearly converted. Modern translations often render the line as a question about Paul persuading him “in such a short time.” Agrippa may be intrigued, evasive, ironic, or some mixture of those. Luke does not tell us that he later became a believer. The safest interpretation is to leave his inner state unmeasured and focus on Paul’s response: whether the persuasion takes little or much, Paul genuinely desires Agrippa and everyone present to share his faith—only without his chains.'}
 }
});
render();
