// Acts 16 — Living Bookmark card.
Object.assign(studies,{
 'Acts 16':{body:''}
});

Object.assign(studyMeta,{
 'Acts 16':{
  oneLine:'Paul adds Timothy to the mission and circumcises him for Jewish access rather than salvation, the Spirit redirects the team toward Macedonia, Lydia’s heart is opened in Philippi, a slave girl exploited through divination is freed in Jesus’ name, Paul and Silas are beaten and imprisoned after her owners lose their profit, and a midnight earthquake leads the jailer and his household to hear the gospel, believe, receive baptism, and care for the wounded missionaries before the magistrates must publicly acknowledge that they beat Roman citizens without trial.',
  write:[
   {ref:'Acts 16:5',title:'Faithful doctrine and healthy growth belong together.',text:'The churches are strengthened in the faith and increase in number daily.'},
   {ref:'Acts 16:14',title:'Lydia listens, and the Lord opens her heart.',text:'The gospel is spoken by human servants, but God is active in the hearing.'},
   {ref:'Acts 16:18',title:'Jesus’ name is authority, not a magic formula.',text:'Paul commands the spirit to leave in the name of Jesus Christ, and the deliverance belongs to Christ.'},
   {ref:'Acts 16:25',title:'Pain does not silence prayer and praise.',text:'At midnight Paul and Silas are praying and singing while the other prisoners listen.'},
   {ref:'Acts 16:28',title:'Paul protects the man who had been guarding him.',text:'Before the jailer can harm himself, Paul cries out, “Do thyself no harm.”'},
   {ref:'Acts 16:31',title:'The answer to “What must I do to be saved?” is a Person to trust.',text:'Paul and Silas point the jailer to the Lord Jesus Christ.'}
  ],
  underline:{ref:'Acts 16:31',reason:'The jailer asks the great question directly, and Paul gives the center of the gospel directly: believe on the Lord Jesus Christ.'},
  notice:[
   {ref:'Acts 16:1-3',title:'Timothy is circumcised immediately after the council refused to require circumcision for Gentile salvation.',text:'That is not a contradiction. Timothy has a Jewish mother and a Greek father, and the local Jewish communities know his family background. Paul circumcises him so his uncircumcised status will not become an avoidable barrier in synagogue ministry. Titus, a Gentile, was specifically not compelled to be circumcised when circumcision was being demanded as a condition of gospel acceptance. The same act can mean something very different depending on what is being claimed by it.',cross:[{ref:'Galatians 2:3-5',label:'Titus was not compelled',reason:'Paul resisted circumcising the Gentile Titus when false teachers tried to make circumcision a requirement tied to gospel freedom.'},{ref:'1 Corinthians 9:20',label:'Missionary accommodation',reason:'Paul later describes willingly adapting to Jewish settings in matters that did not surrender the gospel.'}]},
   {ref:'Acts 16:4-5',title:'The Jerusalem decision is carried outward as the churches are strengthened.',text:'Paul and his companions deliver the decrees agreed upon by the apostles and elders in Jerusalem. Luke places church growth beside doctrinal stability: the churches are strengthened “in the faith” and increase daily.'},
   {ref:'Acts 16:6-8',title:'The Spirit sometimes guides by closing routes before revealing the next open one.',text:'The team is forbidden to preach in the province of Asia at that time and is not permitted to enter Bithynia. Acts does not tell us exactly how these prohibitions were communicated. A closed plan in this story is divine guidance, but Christians should be cautious about treating every ordinary frustration as a private revelation from God.'},
   {ref:'Acts 16:7',title:'Many modern translations read “the Spirit of Jesus” where the KJV simply says “the Spirit.”',text:'The earliest Greek textual tradition includes the fuller expression “Spirit of Jesus.” The phrase fits Luke’s theology naturally: the risen Jesus is actively directing His mission through the Holy Spirit. The translation difference does not create two different Spirits.'},
   {ref:'Acts 16:9-10',title:'The Macedonian vision gives positive direction after the earlier “no.”',text:'Paul sees a man of Macedonia pleading, “Come over … and help us.” The team concludes that God has called them to preach the gospel there. This is an apostolic narrative of revealed guidance, not permission to treat every dream as automatically divine without discernment.'},
   {ref:'Acts 16:10',title:'The narration suddenly changes from “they” to “we.”',text:'This is the first of the famous “we” sections in Acts. The natural reading is that the narrator has now joined the traveling party, traditionally understood as Luke joining Paul’s team. Scholars have proposed other literary explanations, but the first-person shift is real and continues through this portion of the journey.'},
   {ref:'Acts 16:11-12',title:'Philippi is a Roman colony, and that identity matters throughout the chapter.',text:'Roman colonies enjoyed a strong civic connection to Rome and cultivated Roman law, status, and custom. That helps explain why the accusation “being Jews” and “being Romans” carries social force, and why the magistrates later become alarmed when they learn that Paul and Silas themselves are Roman citizens.'},
   {ref:'Acts 16:13',title:'The riverside prayer gathering may suggest there was no established synagogue, but Luke does not say that explicitly.',text:'The missionaries go outside the city gate by the river to a place where they expect prayer to occur. A common explanation is that Philippi lacked the number or resources for a synagogue. That is plausible, but it remains an inference rather than a fact Luke states.'},
   {ref:'Acts 16:14-15',title:'Lydia is both spiritually receptive and economically independent enough to host the mission.',text:'She is from Thyatira and deals in purple goods, a trade associated with costly dyed textiles. Luke calls her a worshiper of God and says the Lord opens her heart to attend to Paul’s message. After her household is baptized, she presses the missionaries to stay in her home, which becomes an early gathering place for the Philippian believers.'},
   {ref:'Acts 16:14',title:'“Whose heart the Lord opened” holds divine action and human hearing together.',text:'Lydia is already listening, Paul is genuinely preaching, and the Lord opens her heart to respond. Christian traditions explain the relation between grace and human response in different theological ways, but Luke is comfortable saying both that the word is proclaimed and that God acts within the hearer.'},
   {ref:'Acts 16:15',title:'Lydia’s household baptism is important, but the verse does not tell us the ages of everyone in the household.',text:'Christians who baptize infants see household baptisms like this one as fitting covenant inclusion of families. Christians who baptize professing believers note that Acts does not explicitly mention infants here and therefore do not regard the passage as proof of infant baptism. The text clearly tells us the household was baptized; it does not give an age list that settles the later debate by itself.'},
   {ref:'Acts 16:16',title:'The Greek description is literally connected with a “Python spirit.”',text:'The wording reflects the Greco-Roman world of oracles associated with Python and Apollo at Delphi. The KJV’s “spirit of divination” communicates the sense well. Luke presents the girl as genuinely under an oppressive spiritual power while also showing that other people are making money from her condition.'},
   {ref:'Acts 16:16-18',title:'What the spirit says about Paul is substantially true, but truth from a corrupt source is still not welcomed as gospel partnership.',text:'The girl identifies the missionaries as servants of the Most High God who proclaim a way of salvation. Paul does not accept demonic testimony simply because the words sound useful. After many days he commands the spirit to leave in Jesus Christ’s name. The gospel does not need spiritual darkness to authenticate it.'},
   {ref:'Acts 16:16-19',title:'The girl is doubly enslaved: spiritually oppressed and economically exploited.',text:'Luke calls her a slave girl and says her divination brings her masters much profit. Once she is freed from the spirit, her owners see that “the hope of their gains” is gone. Their outrage reveals that her usefulness to them mattered more than her freedom.'},
   {ref:'Acts 16:19-21',title:'The owners translate an economic loss into a public accusation about ethnicity, disorder, and Roman custom.',text:'They do not tell the magistrates, “These men ruined our income by freeing our slave.” Instead they accuse Paul and Silas as Jews who are troubling the city and promoting customs Romans should not receive. The rhetoric turns private financial injury into civic fear and uses their Jewish identity against them.'},
   {ref:'Acts 16:22-24',title:'Paul and Silas are stripped, beaten with rods, and imprisoned without the legal hearing Roman citizenship should have protected.',text:'The magistrates yield to the crowd, order them beaten, and give the jailer strict orders. They are put into the inner prison with their feet fastened in stocks. Luke later reveals that this treatment of uncondemned Roman citizens is precisely what frightens the officials.'},
   {ref:'Acts 16:25',title:'Their songs are not proof that faithful Christians should feel cheerful about suffering.',text:'They have been publicly humiliated, beaten, and placed in painful restraint. Their prayer and singing show trust in God inside suffering, not denial that suffering hurts. Luke even notes that the other prisoners are listening—the praise becomes witness in a place where no sermon platform exists.'},
   {ref:'Acts 16:26',title:'The earthquake opens doors and loosens bonds, but the greater wonder is that the prisoners do not run.',text:'A violent shaking affects the prison so that the doors open and everyone’s restraints come loose. Luke presents the event as extraordinary divine intervention. Yet Paul’s next words reveal that the prisoners are still there, turning what could have been a prison break into the setting for the jailer’s rescue.'},
   {ref:'Acts 16:27-28',title:'Paul’s first use of the miracle is to save the jailer’s life.',text:'Seeing the doors open, the jailer assumes the prisoners have escaped and prepares to kill himself. Roman custodians could face severe consequences for lost prisoners, which helps explain his panic. Paul stops him with a loud cry: “Do thyself no harm: for we are all here.” The gospel’s witness includes protecting the life of the man who had confined them.'},
   {ref:'Acts 16:29-32',title:'“Believe on the Lord Jesus Christ” is the beginning of the jailer’s instruction, not the only sentence he ever hears.',text:'Paul gives the saving center immediately, then verse 32 says they speak “the word of the Lord” to him and to everyone in his house. The short answer is not anti-teaching; it names the Person on whom salvation rests, and then that message is explained.'},
   {ref:'Acts 16:31-34',title:'“Thou shalt be saved, and thy house” does not mean one man’s faith automatically saves unbelieving relatives.',text:'The gospel promise reaches the household, and Paul and Silas speak the word to all who are there. The family is baptized, and the final description connects the household’s joy with believing in God. Christian traditions debate household baptism and the presence of children, but Acts does not teach salvation by somebody else’s faith.'},
   {ref:'Acts 16:33-34',title:'The jailer’s first visible fruit reverses the violence around him.',text:'He washes the apostles’ wounds, receives baptism with his household, brings them into his house, and feeds them. Within hours, the man responsible for confinement is caring for the bodies of the men who brought him the gospel.'},
   {ref:'Acts 16:35-39',title:'Paul refuses a quiet release after a public illegal beating.',text:'When the magistrates send word that the men may leave, Paul insists that officials come themselves because they publicly beat uncondemned Roman citizens and imprisoned them. Luke does not tell us exactly why Paul waited until now to invoke citizenship. Possible reasons include public vindication of the mission, protection of the new church from being branded criminal, and protection of the jailer; these are reasonable inferences, not stated motives.'},
   {ref:'Acts 16:37-39',title:'Roman citizenship changes the officials’ posture immediately.',text:'The magistrates become afraid when they hear that Paul and Silas are Romans. Roman citizens possessed important procedural protections against degrading punishment without due process. Paul is not embarrassed to use a lawful civil right when it can expose injustice and protect the church’s public standing.'},
   {ref:'Acts 16:40',title:'The chapter ends in Lydia’s house, not in the prison.',text:'Paul and Silas visit the believers, encourage them, and then depart. The woman whose heart the Lord opened near the river is now hosting a recognizable community of brothers and sisters. Philippi already has a church before the missionaries move on.'}
  ],
  reflections:['When God closes a plan I thought was right, can I remain attentive without assuming the whole mission has failed?','Do I care about people themselves, or can usefulness, productivity, or profit quietly matter more to me than their freedom and well-being?','If I were wounded and treated unjustly, what would it take for me still to notice the person beside me who was in danger?'],
  commentary:{voice:'Alexander Maclaren',identity:'Scottish Baptist preacher and expositor, 1826–1910',quote:'These birds could sing in a darkened cage.',plain:'Maclaren catches the startling contrast at midnight. Paul and Silas do not sing because the beating was trivial or the stocks comfortable. They sing because the prison has not taken away the God to whom they pray. Their praise becomes a form of witness—the other prisoners are listening before the earthquake ever comes.',source:'Expositions of Holy Scripture — Acts 16:19–34',url:'https://biblehub.com/commentaries/maclaren/acts/16.htm'},
  question:{q:'Why did Paul circumcise Timothy right after Acts 15 decided Gentile Christians did not need circumcision?',short:'Because Timothy’s circumcision was not being required for salvation. Paul did it as a missionary accommodation to Jewish hearers who knew Timothy had a Jewish mother, while he refused circumcision when it was demanded as a condition of gospel acceptance.',more:'Acts 15 rejects the claim that Gentiles must be circumcised and keep the law of Moses in order to be saved. Timothy is a different case: his mother is Jewish, his father is Greek, and the Jews in the region know his family background. Paul wants Timothy to enter Jewish settings with him without an avoidable controversy over Timothy’s status distracting from the message. Galatians gives the opposite example in Titus, a Gentile whom Paul refused to circumcise because false brothers were trying to make that act necessary to Christian freedom and acceptance. So Paul is not inconsistent. He can voluntarily surrender a liberty for mission, but he will not surrender the truth of the gospel by allowing the same practice to become a requirement for salvation.'}
 }
});
render();
