// Acts 11 — Living Bookmark card.
Object.assign(studies,{
 'Acts 11':{body:''}
});

Object.assign(studyMeta,{
 'Acts 11':{
  oneLine:'Peter returns to Jerusalem and answers criticism for entering a Gentile home by recounting exactly what God did: the Spirit fell on Cornelius’ household just as at Pentecost, and the church glorifies God for granting Gentiles repentance unto life; meanwhile believers scattered by persecution carry the gospel to Antioch, where Gentiles believe in large numbers, Barnabas rejoices at the grace he sees and brings Saul to help teach, the disciples are first called Christians, and the new church sends famine relief to Judea.',
  write:[
   {ref:'Acts 11:17',title:'Peter refuses to stand in the way of what God has clearly done.',text:'“What was I, that I could withstand God?” turns the argument away from preference and toward obedience.'},
   {ref:'Acts 11:18',title:'The church changes its conclusion when God’s work becomes unmistakable.',text:'They glorify God for granting Gentiles repentance unto life.'},
   {ref:'Acts 11:21',title:'The hand of the Lord does what human strategy alone cannot do.',text:'A great number believe and turn to the Lord.'},
   {ref:'Acts 11:23',title:'Barnabas can recognize grace in a place that does not look like Jerusalem.',text:'He sees God’s grace, rejoices, and encourages the believers to remain faithful.'},
   {ref:'Acts 11:26',title:'Before “Christian” became a familiar word, it named people whose lives were visibly tied to Christ.',text:'Antioch is the first place where the disciples are called Christians.'},
   {ref:'Acts 11:29',title:'Their unity becomes material, not merely verbal.',text:'Each disciple gives according to ability to help believers facing need in Judea.'}
  ],
  underline:{ref:'Acts 11:18',reason:'The Jerusalem believers move from criticism to worship when they recognize that God Himself has granted Gentiles repentance unto life.'},
  notice:[
   {ref:'Acts 11:1-3',title:'News of Gentile inclusion reaches Jerusalem before Peter does, and the first criticism focuses on table fellowship.',text:'The apostles and believers hear that Gentiles have received the word of God. When Peter returns, members of the circumcision group contend with him because he entered the house of uncircumcised men and ate with them. Their objection shows how deeply the old social and purity boundaries shaped Jewish Christian life even after Jesus’ command to take the gospel outward.'},
   {ref:'Acts 11:4',title:'Peter answers the objection by recounting the events “by order.”',text:'He does not begin by saying, “I am an apostle, so do not question me.” He patiently walks the church through the vision, the messengers, the Spirit’s direction, Cornelius’ angelic message, and the Spirit’s gift. Discernment is helped by facts told carefully.'},
   {ref:'Acts 11:5-10',title:'The vision is repeated because Peter’s change of mind matters to the whole church, not only to Peter.',text:'Luke has already narrated the sheet and the clean/unclean animals in Acts 10. Repeating it here lets the Jerusalem church hear the same divine correction Peter received: “What God hath cleansed, that call not thou common.” The repetition underlines how significant this boundary change is.'},
   {ref:'Acts 11:12',title:'The Spirit tells Peter to go “nothing doubting,” and six Jewish Christian brothers go with him.',text:'Peter is not asking the Jerusalem church to accept a private experience that nobody else can verify. The six companions witnessed the Gentile household, heard the tongues and praise, and saw the Spirit’s gift. Their presence gives the church a communal witness to what happened.'},
   {ref:'Acts 11:13-14',title:'Cornelius’ earlier devotion did not make the gospel unnecessary.',text:'The angel told him to send for Peter, who would speak words by which he and his household would be saved. Whatever one concludes about the exact point at which Cornelius entered saving grace, Acts insists that God’s answer to his seeking includes hearing the message of Jesus.'},
   {ref:'Acts 11:15-16',title:'Peter deliberately compares the Gentile outpouring with Pentecost: “as on us at the beginning.”',text:'The Spirit falls while Peter is beginning to speak, and Peter remembers Jesus’ promise about baptism with the Holy Spirit. Gentile inclusion is therefore not Peter lowering the standard; God gives the same decisive gift that marked the church’s beginning.',cross:[{ref:'Acts 2:1-4',label:'The beginning Peter remembers',reason:'At Pentecost the Holy Spirit came on the Jewish believers with visible signs; Peter recognizes the Gentile event as the same divine gift.'},{ref:'Acts 1:5',label:'Jesus’ promise remembered',reason:'Jesus had contrasted John’s water baptism with the coming baptism in the Holy Spirit.'}]},
   {ref:'Acts 11:17',title:'“Who was I, that I could withstand God?” is Peter’s theological conclusion.',text:'The key question is no longer whether Peter personally feels comfortable eating with Gentiles. God has given them the same gift in response to faith in the same Lord. To keep insisting on the old exclusion after that would mean opposing God rather than defending Him.'},
   {ref:'Acts 11:18',title:'The church is capable of correction—and its corrected response becomes worship.',text:'They fall silent, then glorify God: “Then hath God also to the Gentiles granted repentance unto life.” Acts does not portray faithful believers as people who never need their categories enlarged. It portrays them as people who can surrender a mistaken boundary when God’s word and work make the truth clear.'},
   {ref:'Acts 11:18',title:'Repentance is described as something God “granted.”',text:'Human beings are genuinely called to repent throughout Acts, yet here repentance unto life is also God’s gift. Scripture is comfortable holding divine grace and real human response together rather than forcing one to cancel the other.'},
   {ref:'Acts 11:19',title:'Luke now returns to the scattering that began with Stephen’s death.',text:'The narrative reaches back to the persecution described in Acts 8. Scattered believers traveled as far as Phoenicia, Cyprus, and Antioch, carrying the word with them. What looked like disruption in Jerusalem has become a network of witness across the eastern Mediterranean.'},
   {ref:'Acts 11:19',title:'At first the scattered believers still speak “to none but unto the Jews only.”',text:'They obey the missionary impulse while still carrying an inherited boundary about whom to approach. Acts shows growth in understanding happening in stages. Jesus’ worldwide commission was clear, but His followers had to learn what full Gentile inclusion actually required.'},
   {ref:'Acts 11:20',title:'The best-attested reading says some believers began speaking to “Greeks”—Gentiles—in Antioch.',text:'The KJV reads “Grecians,” which can sound like Greek-speaking Jews. Many early manuscripts instead read “Greeks,” and that fits Luke’s contrast: verse 19 says some preached only to Jews, while verse 20 introduces the new step of announcing the Lord Jesus to Gentiles. This is Antioch’s breakthrough moment.'},
   {ref:'Acts 11:20-21',title:'The unnamed believers from Cyprus and Cyrene become major boundary-crossers before Luke even gives us their names.',text:'They preach the Lord Jesus, the hand of the Lord is with them, and a great number believe and turn to the Lord. Acts repeatedly lets ordinary or unnamed disciples carry decisive pieces of the mission. The expansion is bigger than a few famous leaders.'},
   {ref:'Acts 11:22-24',title:'Jerusalem sends Barnabas to investigate, and Barnabas knows how to recognize grace instead of merely inspecting difference.',text:'When he arrives and sees the grace of God, he is glad. He does not treat the Gentile character of the church as proof something must be wrong. He exhorts them to remain with the Lord with purpose of heart, and Luke explains his response by describing him as a good man, full of the Holy Spirit and faith.'},
   {ref:'Acts 11:25-26',title:'Barnabas goes looking for Saul because a growing church needs more teachers, not a larger Barnabas platform.',text:'He travels to Tarsus, finds Saul, and brings him to Antioch. Together they spend a whole year gathering with the church and teaching many people. Barnabas’ leadership creates room for another gifted servant rather than protecting his own importance.'},
   {ref:'Acts 11:26',title:'“Christian” first appears at Antioch, probably as a name used by outsiders for people identified with Christ.',text:'The New Testament uses the word only three times. Luke says the disciples “were called Christians,” which likely means the surrounding population coined the label. It may have carried mockery, simple description, or both; the evidence is not strong enough to insist it began purely as an insult. What is clear is that Christ had become the public identifier of this mixed community.'},
   {ref:'Acts 11:27-28',title:'Agabus predicts a severe famine “throughout all the world,” using a word that often means the inhabited Roman world.',text:'The Greek oikoumenē can refer broadly to the inhabited world and, in Luke’s political setting, often to the Roman imperial world. Ancient sources describe several food shortages during Claudius’ reign, including a severe famine in Judea commonly dated around the mid-40s. Luke is not necessarily claiming every province experienced one identical famine at the same moment.'},
   {ref:'Acts 11:28',title:'“In the days of Claudius Caesar” anchors the prophecy in ordinary public history.',text:'Claudius ruled Rome from A.D. 41 to 54. Josephus describes serious famine conditions in Judea during his reign and tells of Queen Helena of Adiabene purchasing grain for relief. Acts places prophetic warning beside a historically recognizable period of food crisis.'},
   {ref:'Acts 11:29-30',title:'The Gentile-growing church at Antioch responds to Judean need with voluntary, proportionate generosity.',text:'Each disciple determines to send relief “according to his ability.” The church that received spiritual blessing through a Jewish Messiah now sends material help back toward Jewish believers in Judea. Their unity crosses geography and ethnicity and becomes visible in money, food, and responsibility.'},
   {ref:'Acts 11:30',title:'“Elders” appear here for the first time in Acts without Luke pausing to explain a full church-government system.',text:'Barnabas and Saul deliver the relief to the elders. Later Acts will show elders serving in local churches, but this first mention should not be forced to settle every later denominational question about bishops, presbyters, pastors, or governance structures. Luke’s immediate point is that recognized local leaders receive and steward the aid.'}
  ],
  reflections:['When clear evidence from God’s word challenges one of my long-held assumptions, am I able to change my conclusion and worship instead of defending myself?','Do I recognize and rejoice in God’s grace when it appears in people or places that do not look familiar to me?','Does my belief in one body of Christ become concrete when another believer’s need costs me something?'],
  commentary:{voice:'Alexander Maclaren',identity:'Scottish Baptist preacher and expositor, 1826–1910',quote:'like a true man, he yielded to facts, and widened his theory to suit them',plain:'Maclaren admires Barnabas because he does not arrive in Antioch determined to force a surprising Gentile work into his old expectations. He looks carefully, recognizes the grace of God, rejoices, and then helps the new believers become steady. Healthy discernment can be cautious without being suspicious of every unfamiliar thing.',source:'The Exhortation of Barnabas — Acts 11:23',url:'https://biblehub.com/commentaries/maclaren/acts/11.htm'},
  question:{q:'Why did Jewish Christians criticize Peter for eating with Gentiles if Jesus had already commanded the gospel to go to all nations?',short:'They understood that Gentiles could come to Israel’s God, but they had not yet fully understood that Gentiles could be received through Christ without first taking on Jewish covenant markers such as circumcision and purity boundaries.',more:'Jesus had clearly commanded worldwide witness, and the Old Testament itself promised blessing to the nations. The difficult question was how Gentiles would enter the Messiah’s people. Many Jewish believers naturally assumed that coming to Israel’s Messiah would also mean adopting the covenant boundary markers that had distinguished Israel for generations. Peter’s table fellowship with uncircumcised Gentiles made the issue unavoidable. Acts 10–11 shows God answering not only with an argument but with His own action: He sends Peter, gives the Spirit to Gentiles while they are still uncircumcised, and supplies Jewish Christian witnesses. The Jerusalem believers then do something important—they revise their understanding and glorify God. Acts will show that the practical implications still need further discussion in chapter 15, but the basic truth is now established: Gentiles are welcomed as Gentiles through faith in Jesus.'}
 }
});
render();
