// John 18 — Living Bookmark card.
Object.assign(studies,{
 'John 18':{body:''}
});

Object.assign(studyMeta,{
 'John 18':{
  oneLine:'Jesus knowingly meets the arresting force in the garden, protects His disciples while Peter reaches for a sword, is questioned as Peter denies Him beside a charcoal fire, and then tells Pilate that His kingdom is real but not sourced from this world and that His kingship advances by witness to the truth rather than worldly force.',
  write:[
   {ref:'John 18:4',title:'Jesus steps forward knowing what is coming.',text:'The arrest begins with His knowledge and initiative, not surprise.'},
   {ref:'John 18:8',title:'Jesus protects His disciples even as He is being taken.',text:'“If therefore ye seek me, let these go their way.”'},
   {ref:'John 18:11',title:'Peter’s sword is not the road Jesus chooses.',text:'The cup the Father has given Him will not be avoided by force.'},
   {ref:'John 18:18',title:'Peter’s denial unfolds beside a charcoal fire.',text:'John will bring Peter to another charcoal fire after the resurrection.'},
   {ref:'John 18:36',title:'Christ’s kingdom is in this world without coming from this world.',text:'Its source and methods are not the world’s violence and power.'},
   {ref:'John 18:37',title:'Jesus connects His kingship with witness to truth.',text:'Everyone who is of the truth hears His voice.'}
  ],
  underline:{ref:'John 18:36',reason:'Jesus claims a real kingdom while making clear that it does not arise from the world’s source or advance by the world’s weapons.'},
  notice:[
   {ref:'John 18:1-4',title:'Judas knows the garden because it was a familiar place of fellowship.',text:'The betrayal reaches into a place Jesus often used with His disciples. Yet John’s first emphasis is not Judas’s cleverness but Jesus’ knowledge: “knowing all things that should come upon him,” He goes forward. The Passion in John is never narrated as events spinning beyond Jesus’ awareness.'},
   {ref:'John 18:5-6',title:'“I am he” uses the same egō eimi wording heard earlier in John, and the arresting party falls backward.',text:'The words can function as ordinary identification—“I am Jesus of Nazareth”—so the scene should not be forced into a simplistic proof text. But John has filled the Gospel with “I am” language, and the unexpected retreat and fall underline the authority of the supposedly helpless prisoner. The text records the reaction without explaining every physical detail.'},
   {ref:'John 18:7-9',title:'Jesus gives Himself up while making space for His disciples to go free.',text:'He repeats the question, identifies Himself, and says, “let these go their way.” John connects that protection with Jesus’ earlier words about losing none of those the Father gave Him. In the immediate scene, spiritual keeping includes very practical bodily protection.'},
   {ref:'John 18:10-11',title:'Peter’s sword shows sincere loyalty using the wrong kingdom method.',text:'He strikes the high priest’s servant Malchus and cuts off his ear. Jesus stops him and speaks of the cup the Father has given. John does not portray the cross as something faithful disciples should prevent by violence. The King will win by receiving the cup, not by starting an armed rescue.'},
   {ref:'John 18:12-24',title:'Jesus is questioned while Peter’s denial story is deliberately interwoven around the hearing.',text:'John moves back and forth between the High Priest’s circle and Peter outside. Jesus speaks openly about His teaching; Peter, frightened, says “I am not.” The contrast is painful: the One on trial tells the truth publicly while His disciple tries to disappear through denial.'},
   {ref:'John 18:18',title:'The charcoal fire is a small detail John will use again.',text:'Peter warms himself at an anthrakia, a charcoal fire, while denying Jesus. In John 21 the risen Jesus prepares another charcoal fire before restoring Peter. John does not tell us explicitly to make the connection, but the repeated rare detail makes the later breakfast feel like a deliberate return to the scene of failure.'},
   {ref:'John 18:25-27',title:'Peter’s three denials fulfill Jesus’ warning without making Peter’s failure his final identity.',text:'The rooster crows immediately after the third denial. At this moment the prediction is fulfilled in shame. John’s Gospel is not finished with Peter, however; chapter 21 will answer this night with three searching questions and a renewed commission.'},
   {ref:'John 18:28',title:'“That they might eat the passover” belongs to a real chronology question between John and the Synoptic Gospels.',text:'John’s wording can sound as though the Passover meal is still ahead, while Matthew, Mark, and Luke describe the Last Supper as a Passover meal. Various harmonizations have been proposed, including different uses of “Passover” for the wider festival or differences in calendar reckoning, but the surviving evidence does not make every detail certain. Bookmark should acknowledge the question rather than pretending there is none.'},
   {ref:'John 18:28-32',title:'The Gospel does not allow “the Jews” in the Passion story to become a racial accusation against Jewish people.',text:'In John this expression often narrows in context to particular Judean leaders or hostile authorities. Jesus, His disciples, His mother, the beloved disciple, and many who believe in Him are Jewish. The chief priests seek Roman execution, and a Roman governor will authorize crucifixion. The Passion indicts sinful human rejection, not an ethnicity.'},
   {ref:'John 18:33-37',title:'“My kingdom is not of this world” means its source is not from here; it does not mean Christ’s rule is irrelevant to life on earth.',text:'Jesus’ proof is that His servants are not fighting to prevent His arrest. His kingdom does not arise from worldly coercion, armies, or political force. Yet the King is standing in a real governor’s hall speaking truth about authority, and His followers will live under His rule in the world. “Not of” is not the same as “has nothing to do with.”'},
   {ref:'John 18:37-38',title:'Pilate asks “What is truth?” while Truth’s King stands in front of him, then walks away from the question.',text:'The tone may contain skepticism, impatience, or weary political pragmatism; John does not tell us enough to diagnose Pilate’s inner psychology with certainty. What is clear is that Pilate does not stay for an answer, even while repeatedly recognizing that Jesus is not guilty of a capital crime.'},
   {ref:'John 18:39-40',title:'The chapter ends with a violent prisoner preferred over the King who refuses worldly violence.',text:'Barabbas is called a robber; the Greek term can also be used for a brigand or insurgent. The narrative irony is sharp: the crowd receives the sort of prisoner associated with force while rejecting the King whose kingdom is not advanced by the sword.'}
  ],
  reflections:['When I am afraid, am I tempted like Peter to use the world’s tools—force, denial, self-protection—to accomplish what I think faithfulness requires?','Do I ask “What is truth?” as someone ready to hear an answer, or mainly when I want distance from the claim truth might make on me?'],
  commentary:{voice:'Alexander Maclaren',identity:'Scottish Baptist preacher and expositor, 1826–1910',quote:'It is “not of this world,” though it is in this world',plain:'Maclaren keeps the two halves together. Jesus’ kingdom is not generated or sustained by the world’s force, but it is genuinely present here. The King rules people who live inside ordinary societies while belonging to a kingdom whose source, weapons, and final authority come from God.',source:'Expositions of Holy Scripture — John 18',url:'https://biblehub.com/commentaries/maclaren/john/18.htm'},
  question:{q:'Does “My kingdom is not of this world” mean Christians should have nothing to do with earthly life or public affairs?',short:'No. Jesus says His kingdom is not from the world’s source and is not defended by the world’s weapons; He does not say His kingship has no claim on how disciples live in the world.',more:'The immediate issue is Pilate’s fear of a political rival to Caesar. Jesus points to the absence of armed resistance as evidence that His kingdom is not another earthly regime fighting for territory by force. The Greek phrase can carry the sense “not from here.” That matters. Christ’s reign changes loyalties, ethics, truthfulness, mercy, justice, money, relationships, and every other part of discipleship, so it cannot be sealed off from public life. But the church betrays this passage when it imagines the kingdom is established by coercion, violence, or simple possession of state power. Its King conquers through truth and the cross.'}
 }
});
render();