// Acts 6 — Living Bookmark card.
Object.assign(studies,{
 'Acts 6':{body:''}
});

Object.assign(studyMeta,{
 'Acts 6':{
  oneLine:'As the Jerusalem church grows, Greek-speaking Jewish believers raise a real complaint that their widows are being overlooked; the apostles lead the church to appoint seven Spirit-filled men for the distribution so prayer and the ministry of the word are not neglected, the word continues to spread, and Stephen’s Spirit-given wisdom and signs bring him into conflict with opponents who answer him with false witnesses.',
  write:[
   {ref:'Acts 6:1',title:'Growth does not make a church immune to neglected people.',text:'The problem appears while the number of disciples is multiplying.'},
   {ref:'Acts 6:3',title:'Practical service deserves spiritual character.',text:'The men chosen for a food-distribution problem must be reputable, Spirit-filled, and wise.'},
   {ref:'Acts 6:4',title:'Prayer is part of the ministry, not preparation squeezed around it.',text:'The apostles devote themselves to prayer and to the ministry of the word.'},
   {ref:'Acts 6:7',title:'Healthy correction does not distract from the mission; it can strengthen it.',text:'After the neglected widows are addressed, the word increases and disciples multiply.'},
   {ref:'Acts 6:10',title:'Stephen’s opponents cannot out-argue the wisdom the Spirit gives.',text:'When honest debate fails, the conflict moves toward accusation instead.'},
   {ref:'Acts 6:15',title:'False charges do not get the final word over Stephen’s face.',text:'The council sees him as one whose face is like the face of an angel.'}
  ],
  underline:{ref:'Acts 6:4',reason:'The apostles protect the two ministries Christ especially entrusted to them: persevering prayer and the ministry of the word.'},
  notice:[
   {ref:'Acts 6:1',title:'The “Grecians” and “Hebrews” are two cultural-language groups inside the Jewish Christian community.',text:'The Hellenists were Greek-speaking Jews, often connected with the diaspora, while the Hebrews were Jews whose ordinary religious and community life was more closely tied to Hebrew or Aramaic language and Judean custom. This is not yet a Jew-versus-Gentile dispute; it is an internal fracture among Jewish believers.'},
   {ref:'Acts 6:1',title:'The complaint concerns widows, one of the groups most easily left without economic protection.',text:'The church has been sharing resources so that needs are met, but growth has made the daily distribution harder to administer fairly. Luke does not say the neglect was deliberate. A system can fail vulnerable people even when nobody set out to mistreat them.'},
   {ref:'Acts 6:1-2',title:'The apostles do not dismiss the complaint as murmuring and tell the widows to be quieter.',text:'They gather the whole body and change the structure. The response assumes that spiritual unity is not preserved by pretending unequal treatment is imaginary; a practical problem deserves a practical remedy.'},
   {ref:'Acts 6:2-4',title:'“Serve tables” is not contempt for practical ministry.',text:'The same diakonia word-family lies behind the daily “ministration” in verse 1 and the apostles’ “ministry of the word” in verse 4. Both are service. The apostles are distinguishing assignments, not ranking compassionate care as beneath spiritual work.'},
   {ref:'Acts 6:3',title:'The qualifications are strikingly spiritual for a job involving food and money.',text:'The seven must have a good reputation and be full of the Holy Spirit and wisdom. Acts refuses the idea that practical administration can be safely separated from character. Handling resources for vulnerable people is spiritual responsibility too.'},
   {ref:'Acts 6:5',title:'All seven names are Greek, but that does not prove with certainty that every one of the Seven was a Hellenist.',text:'Greek names were common among Jews generally. Many interpreters think the list reflects a deliberate choice of men especially connected with the aggrieved group, which would be a beautiful act of trust, but Luke does not explicitly label all seven as Hellenists. Nicolas alone is specifically identified as a proselyte from Antioch.'},
   {ref:'Acts 6:5-6',title:'The congregation chooses; the apostles pray and lay hands on the men.',text:'Luke shows shared participation rather than a private apostolic appointment made without the church. Laying on hands marks public recognition and commissioning. The exact relationship between this scene and later church offices is debated, so it is safest to describe what Acts itself says before importing a later title.'},
   {ref:'Acts 6:5',title:'Stephen and Philip will immediately become much more than names on an administrative list.',text:'Stephen becomes a powerful witness and the first martyr narrated in Acts. Philip will preach in Samaria and to the Ethiopian official and is later called “the evangelist.” The assignment to practical service does not place a ceiling on the Spirit’s later use of either man.',cross:[{ref:'Acts 8:5-8',label:'Philip in Samaria',reason:'Philip later preaches Christ in Samaria with remarkable fruit.'},{ref:'Acts 21:8',label:'Philip’s later title',reason:'Luke later calls him Philip the evangelist, one of the Seven.'}]},
   {ref:'Acts 6:7',title:'Luke’s growth report includes a surprising group: many priests become obedient to the faith.',text:'The gospel is not merely attracting people far from Jerusalem’s worship life. Even members of the priestly world connected with the temple are responding. “Obedient to the faith” shows belief as allegiance, not mere agreement with an idea.'},
   {ref:'Acts 6:8',title:'Stephen is chosen in a dispute about food distribution, but Luke next shows him doing wonders among the people.',text:'The Spirit is not confined by the first task a person is assigned. Stephen’s public ministry grows out of a life already described as full of faith, grace, power, wisdom, and the Holy Spirit.'},
   {ref:'Acts 6:9',title:'Stephen’s opponents come from Greek-speaking diaspora synagogue circles much like the world from which the Hellenists came.',text:'Luke names the synagogue of the Libertines or Freedmen along with people connected with Cyrene, Alexandria, Cilicia, and Asia. Jerusalem contained diaspora Jewish communities with their own language and regional networks. The conflict is therefore taking place inside a deeply Jewish and internationally connected setting.'},
   {ref:'Acts 6:9',title:'Cilicia is worth noticing because Saul comes from Tarsus in Cilicia—but Acts does not say he is in this synagogue debate.',text:'Saul will appear at Stephen’s death in the next chapter. The geographic connection makes his possible proximity interesting, but it should remain a possibility, not be presented as a fact Luke has told us.'},
   {ref:'Acts 6:10-12',title:'When Stephen’s opponents cannot resist his wisdom, the next move is not stronger reasoning but manufactured accusation.',text:'Men are induced to say they heard blasphemous words against Moses and God, and the crowd and council are stirred up. Acts is showing a moral contrast between Spirit-given wisdom and a case built through distortion.'},
   {ref:'Acts 6:13-14',title:'The false witnesses may be twisting real Christian claims rather than inventing every word from nothing.',text:'Jesus did teach that the temple’s role was being fulfilled in Him, and the gospel will transform how God’s people relate to Mosaic boundary markers. The charge becomes false by presenting Stephen as a blasphemer who attacks Moses and the holy place. Acts 7 will let Stephen answer from Israel’s own Scriptures rather than deny God’s history with Israel.',cross:[{ref:'John 2:19-21',label:'Temple fulfilled in Jesus',reason:'Jesus spoke of raising the temple of His body, language that opponents could distort into a simple threat against the building.'}]},
   {ref:'Acts 6:15',title:'Stephen is accused of speaking against Moses, yet his face is described in a way that recalls a heavenly messenger—and possibly Moses himself.',text:'Everyone in the council looks intently at him and sees a face “as it had been the face of an angel.” The phrase at minimum marks extraordinary calm and divine favor under accusation. Some readers also hear an intentional irony beside Moses’ shining face after meeting with God, though Luke does not explicitly state that comparison.',cross:[{ref:'Exodus 34:29-35',label:'Possible narrative echo',reason:'Moses’ face shone after being in God’s presence; Stephen is about to defend the story of Moses while being falsely accused of opposing him.'}]}
  ],
  reflections:['When someone says a system I belong to is overlooking them, is my first instinct to defend the system or to find out whether the need is real?','Do I treat practical service as spiritually important enough to require wisdom, character, and prayer?','What assignment has God given me right now that I may be tempted to call too ordinary to matter?'],
  commentary:{voice:'Johann Albrecht Bengel',identity:'Lutheran scholar and New Testament commentator, 1687–1752',quote:'Prayer takes precedency of the ministry of the word.',plain:'Bengel notices the order in verse 4. The apostles do not protect preaching while allowing prayer to become the leftover activity. Their public ministry of the word is paired with sustained dependence on God. The point is not that serving widows matters less; Acts has just reorganized the church precisely because that service matters enough to be done well.',source:'Gnomon of the New Testament — Acts 6:4',url:'https://biblehub.com/commentaries/bengel/acts/6.htm'},
  question:{q:'Were the Seven in Acts 6 the first deacons?',short:'They are often understood as a prototype of the later diaconate, but Acts never actually calls the Seven “deacons.”',more:'The connection is understandable because their assignment is a form of diakonia—service or ministry—and later churches associated the Seven with the office of deacon. But Acts simply calls them seven men appointed over this particular need. The same diakonia word-family is also used for the apostles’ ministry of the word, so the vocabulary alone does not settle an office title. Christian traditions therefore differ: some speak confidently of the first deacons, while others call the Seven a special Jerusalem ministry that helped shape the later diaconate. The safest reading is to affirm the clear pattern—qualified believers publicly entrusted with practical care—without claiming Luke uses a title he does not use.'}
 }
});
render();
