// Acts 24 — Living Bookmark card.
Object.assign(studies,{
 'Acts 24':{body:''}
});

Object.assign(studyMeta,{
 'Acts 24':{
  oneLine:'Five days after Paul reaches Caesarea, the high priest Ananias arrives with elders and the advocate Tertullus to accuse him before Governor Felix of sedition, leadership of the “sect of the Nazarenes,” and attempted temple profanation; Paul answers that the charges cannot be proved, openly confesses his worship according to “the Way,” and centers his hope on the resurrection of both just and unjust; Felix postpones judgment, later listens with his Jewish wife Drusilla as Paul reasons about righteousness, self-control, and coming judgment, becomes afraid but delays again, and keeps the innocent apostle confined for two years while hoping for a bribe and seeking favor with Paul’s accusers.',
  write:[
   {ref:'Acts 24:10',title:'Paul answers serious accusations without panic or flattery.',text:'He gives a reasoned defense and points to facts that can be checked.'},
   {ref:'Acts 24:14',title:'Paul does not deny belonging to the Way.',text:'What his accusers call a sect, he describes as worship of the God of his fathers.'},
   {ref:'Acts 24:15',title:'Paul’s hope includes resurrection and judgment.',text:'The gospel looks beyond this life to God raising both the just and the unjust.'},
   {ref:'Acts 24:16',title:'Future resurrection shapes present conscience.',text:'Paul practices keeping a conscience clear toward both God and people.'},
   {ref:'Acts 24:25',title:'Felix trembles when the message reaches righteousness, self-control, and judgment.',text:'Conviction can be real while obedience is still postponed.'},
   {ref:'Acts 24:27',title:'Delay becomes injustice when Felix leaves an uncondemned man imprisoned for political favor.',text:'Knowing better does not automatically produce doing right.'}
  ],
  underline:{ref:'Acts 24:16',reason:'Paul connects resurrection hope with ordinary moral life: because God will raise and judge, he practices a clear conscience toward God and neighbor now.'},
  notice:[
   {ref:'Acts 24:1-4',title:'Tertullus opens like a professional advocate, using heavy praise before stating the charges.',text:'The high priest Ananias and elders bring Tertullus to present their case before Felix. His elaborate thanks for Felix’s peace and reforms are conventional courtroom rhetoric and strategic flattery. Luke will shortly show that Felix is willing to delay justice and hope for money, so the speech should not be mistaken for Luke’s own moral assessment of the governor.'},
   {ref:'Acts 24:5-6',title:'The accusations are carefully shaped for a Roman governor.',text:'Paul is called a troublemaker who stirs unrest among Jews throughout the empire, a leader of the Nazarene sect, and someone who tried to profane the temple. Sedition threatens Roman order; sectarian leadership makes Paul sound dangerous; temple profanation gives the local conflict a concrete charge. The rhetoric is designed to make a theological dispute look like a security case.'},
   {ref:'Acts 24:5',title:'“Sect of the Nazarenes” is an outsider label for the Jesus movement.',text:'Nazareth was associated with Jesus, so “Nazarene” became a way to identify His followers. Tertullus uses the Greek word hairesis, which can mean a party, school, or sect; it did not yet automatically carry every later meaning of the English word “heresy.”'},
   {ref:'Acts 24:6-8',title:'The KJV contains a longer passage about Lysias that many modern translations omit.',text:'Later manuscripts include wording that Paul’s accusers seized him, intended to judge him by their law, and that the commander Lysias violently took him away and ordered the accusers to come to Felix. Several early and important manuscripts lack much of this material in verses 6-8, so modern critical editions usually print the shorter text. The basic narrative remains the same: the case has been transferred to Felix.'},
   {ref:'Acts 24:10-13',title:'Paul answers with a short timeline that makes the conspiracy charge hard to sustain.',text:'He says it has been only twelve days since he went up to Jerusalem to worship, and his accusers did not find him disputing with crowds, stirring people up in synagogues, or causing riots in the city. He invites proof rather than merely countering accusation with accusation.'},
   {ref:'Acts 24:14',title:'Paul accepts “the Way” while rejecting the idea that following Jesus means abandoning Israel’s God and Scriptures.',text:'He says that according to the Way—which his accusers call a sect—he worships the God of his fathers and believes the things written in the Law and the Prophets. Luke again refuses the idea that the Christian gospel is contempt for Israel; Paul understands Jesus as the fulfillment of Israel’s hope.'},
   {ref:'Acts 24:15',title:'Paul expects a resurrection of both the just and the unjust.',text:'Resurrection is not merely comforting language about believers going to heaven. Paul expects God to raise humanity for final accountability. That is why resurrection hope carries both promise and moral seriousness.'},
   {ref:'Acts 24:16',title:'“A conscience void of offence” is a practice, not a claim of sinless perfection.',text:'Paul says he exercises or trains himself to maintain a clear conscience toward God and people. His own testimony has already admitted grave past sins. A clear conscience means living honestly before God and making present choices in light of coming resurrection and judgment.'},
   {ref:'Acts 24:17-21',title:'Paul finally explains why he was in Jerusalem: charity, worship, and purification—not revolt.',text:'After years away he came bringing alms to his nation and offerings, fitting the collection described in his letters. He was found purified in the temple without a crowd or disturbance. The Asian Jews who first accused him are notably absent from Felix’s courtroom, and Paul challenges the present accusers to identify an actual crime beyond his statement about resurrection.'},
   {ref:'Acts 24:17',title:'Paul’s mention of alms fits the wider New Testament story of the Jerusalem collection.',text:'His letters show that Gentile churches contributed for needy believers in Jerusalem. The gift expressed practical care and the unity of Jewish and Gentile Christians. Acts mentions the alms briefly because the trial, not the fundraising project, is Luke’s immediate focus.',cross:[{ref:'Romans 15:25-27',label:'The Jerusalem collection',reason:'Paul describes bringing aid from Gentile believers in Macedonia and Achaia to the saints in Jerusalem.'}]},
   {ref:'Acts 24:22-23',title:'Felix already knows enough about “the Way” to realize the case is not as simple as the prosecution claims.',text:'He postpones the decision until the commander Lysias comes, while allowing Paul a measure of liberty and permitting friends to care for him. That relatively light custody suggests Felix does not regard Paul as the dangerous revolutionary Tertullus described.'},
   {ref:'Acts 24:24',title:'Drusilla connects the governor’s household directly to Jewish history and the Herodian family.',text:'Luke identifies Felix’s wife as Jewish. She was a daughter of Herod Agrippa I and therefore part of the dynasty already woven through Acts. Her presence also means Paul’s discussion of faith in Christ is heard by someone familiar with Jewish beliefs and hopes.'},
   {ref:'Acts 24:24-25',title:'Paul speaks to Felix about the parts of the gospel that press directly on conduct.',text:'He reasons about righteousness, self-control, and the judgment to come. This is not a vague spiritual conversation tailored to make a powerful governor comfortable. Christian proclamation includes grace, but grace does not remove moral accountability.'},
   {ref:'Acts 24:25',title:'The KJV says Felix “trembled”; the Greek describes becoming afraid or alarmed.',text:'Felix is genuinely affected enough to stop the conversation, but fear is not the same as repentance. “When I have a convenient season” becomes one of the chapter’s saddest lines because Luke never records the convenient moment arriving.'},
   {ref:'Acts 24:26',title:'Felix’s repeated conversations with Paul have a corrupt motive mixed into his interest.',text:'He hopes Paul will give him money and therefore sends for him often. The governor can be intellectually interested in the faith, morally disturbed by it, and still try to profit from the prisoner. Spiritual curiosity alone is not transformation.'},
   {ref:'Acts 24:26',title:'Paul does not buy freedom even though Felix appears open to a bribe.',text:'Luke gives no hint that Paul pays. Earlier Paul defended his right to use lawful protections; here he refuses the corrupt shortcut. There is a difference between using a right and purchasing an unjust favor.'},
   {ref:'Acts 24:27',title:'Two years pass while Paul remains in custody without a conviction.',text:'Porcius Festus eventually succeeds Felix, but Felix leaves Paul bound because he wants to do the Jews a favor. The delay is politically useful to Felix and personally costly to Paul. God’s promise of Rome is still active even when providence includes a long period that looks like waiting.'},
   {ref:'Acts 24:22-27',title:'Felix’s problem is not lack of information but unwillingness to act on what he knows.',text:'He has a relatively accurate knowledge of the Way, hears Paul repeatedly, becomes afraid under moral conviction, knows enough to grant Paul lighter custody, and still postpones justice. Acts 24 is a warning that information, interest, and even conviction can coexist with deliberate delay.'}
  ],
  reflections:['Is there something I already know is right but keep postponing until a more “convenient” time?','When I defend myself, can I stay factual and clear rather than becoming as manipulative as the people accusing me?','Does my hope in resurrection actually shape how carefully I keep my conscience toward God and other people today?'],
  commentary:{voice:'Alexander Maclaren',identity:'Scottish Baptist preacher and expositor, 1826–1910',quote:'the guilty couple found a judge in their prisoner',plain:'Maclaren captures the reversal in Paul’s private hearing with Felix and Drusilla. Legally, Felix has power over Paul. Morally, Paul speaks about righteousness, self-control, and coming judgment so directly that the governor becomes afraid. The prisoner refuses to turn the gospel into flattering conversation for powerful people.',source:'Expositions of Holy Scripture — “Felix Before Paul,” Acts 24:25',url:'https://biblehub.com/library/maclaren/expositions_of_holy_scripture_the_acts/felix_before_paul.htm'},
  question:{q:'What is the warning in Felix saying, “When I have a convenient season, I will call for thee”?',short:'Felix is affected by the truth but delays responding to it. Acts warns that conviction is not the same as repentance, and waiting for obedience to become convenient can become a way of refusing it.',more:'Felix is not ignorant. Luke says he already has a more accurate knowledge of the Way, and he listens while Paul explains faith in Christ. When Paul reasons about righteousness, self-control, and coming judgment, Felix becomes afraid. But rather than respond to what has pierced his conscience, he dismisses Paul until a more convenient time. He later speaks with Paul repeatedly, yet Luke exposes another motive: Felix hopes for a bribe. The chapter therefore presents a person who has information, access, emotional conviction, and repeated opportunity while still refusing the decisive step. Its warning is not that every spiritual decision must be made impulsively; careful thought can be wise. The danger is using “later” to avoid obeying what one already knows is true.'}
 }
});
render();
