// Acts 22 — Living Bookmark card.
Object.assign(studies,{
 'Acts 22':{body:''}
});

Object.assign(studyMeta,{
 'Acts 22':{
  oneLine:'Standing on the fortress steps after the riot, Paul addresses the Jerusalem crowd in their own language and tells his story: he was trained under Gamaliel, violently persecuted the Way, encountered the risen Jesus on the Damascus road, was received by the devout Ananias, baptized, and later commanded in a temple vision to go far away to the Gentiles; that final word reignites the crowd’s fury, but when the Roman commander orders Paul examined by scourging, Paul reveals that he is a Roman citizen and forces the authorities to confront the illegality of torturing an uncondemned citizen.',
  write:[
   {ref:'Acts 22:3',title:'Paul does not hide the story he once belonged to.',text:'He names his training, zeal, and former confidence before explaining how Jesus changed him.'},
   {ref:'Acts 22:7',title:'Jesus takes persecution of His people personally.',text:'“Why persecutest thou me?” joins Christ to the believers Saul was attacking.'},
   {ref:'Acts 22:10',title:'Paul’s conversion turns immediately toward obedience.',text:'His question becomes, “What shall I do, Lord?”'},
   {ref:'Acts 22:14',title:'Ananias says Paul has been chosen to know God’s will and see the Righteous One.',text:'Calling comes before the long years of suffering Paul will endure.'},
   {ref:'Acts 22:16',title:'Paul is told not to delay his public response.',text:'He rises, is baptized, and calls on the Lord’s name.'},
   {ref:'Acts 22:29',title:'Paul uses lawful protection without apologizing for it.',text:'Faithful endurance does not require submitting silently to every illegal abuse.'}
  ],
  underline:{ref:'Acts 22:10',reason:'The persecutor’s life pivots in one question: once he recognizes Jesus as Lord, the next issue is obedience.'},
  notice:[
   {ref:'Acts 22:1-2',title:'Paul opens with respect and speaks in the language most likely to reach this crowd.',text:'He calls them “brethren and fathers,” echoing Stephen’s respectful opening, and addresses them in what the KJV calls the “Hebrew tongue.” In this first-century setting most scholars understand Luke to mean Aramaic, the common Semitic language of Judea, though the wording can be discussed. The crowd becomes quieter because Paul is speaking as an insider, not as a distant foreigner.'},
   {ref:'Acts 22:3',title:'Paul establishes that his Christian faith did not grow from ignorance of Judaism.',text:'He was born in Tarsus, raised in Jerusalem, educated at the feet of Gamaliel, and zealous for God. Gamaliel was a respected Pharisaic teacher also known from Acts 5. Paul’s point is not that education saved him, but that following Jesus was not the result of casually abandoning a tradition he never understood.'},
   {ref:'Acts 22:4-5',title:'Paul confesses his persecution without softening it.',text:'He says he persecuted “this Way” unto death, binding and imprisoning both men and women, and that the high priest and elders could verify his authorization. His testimony begins by admitting that sincere religious zeal can be terribly wrong.'},
   {ref:'Acts 22:6-8',title:'The risen Jesus identifies Himself with the people Saul was harming.',text:'Jesus asks, “Why persecutest thou me?” Saul had been attacking Christians, yet Christ speaks as the One being persecuted. The scene gives powerful language for Christ’s solidarity with His people without erasing the real suffering of the individual believers Saul harmed.'},
   {ref:'Acts 22:9',title:'Acts 9 and Acts 22 describe Paul’s companions hearing the encounter from different angles, not necessarily contradicting each other.',text:'Acts 9:7 says the men heard a voice or sound, while Acts 22:9 says they did not hear the voice of the One speaking to Paul. The Greek can distinguish hearing a sound from hearing with comprehension, and the two accounts agree that the companions experienced something real without receiving Paul’s revelation in the same way. The safest reading is that they perceived the phenomenon but did not understand the message addressed to Paul.',cross:[{ref:'Acts 9:7',label:'Luke’s earlier account',reason:'Paul’s companions hear the sound/voice while seeing no one.'}]},
   {ref:'Acts 22:10-11',title:'Paul’s first response to the risen Jesus is surrender, not self-explanation.',text:'He asks what he should do and is told to enter Damascus. The man who arrived with authority to seize others must now be led by the hand because the heavenly brightness has left him unable to see.'},
   {ref:'Acts 22:12-13',title:'Paul describes Ananias in terms this Jewish audience can respect.',text:'He calls Ananias devout according to the law and well reported by the local Jews. That detail fits Paul’s whole defense: the Christian message did not arrive through contempt for Israel, and the man who received Paul in Damascus was himself known for Jewish faithfulness.'},
   {ref:'Acts 22:14-15',title:'Ananias frames Paul’s calling around God’s prior action.',text:'“The God of our fathers” has chosen Paul to know His will, see the Righteous One, hear His voice, and become a witness. Paul’s later Gentile mission is presented as something assigned to him, not a career he invented because he preferred Gentiles to Jews.'},
   {ref:'Acts 22:16',title:'“Be baptized, and wash away thy sins, calling on the name of the Lord” joins baptism tightly to conversion without making the water magical.',text:'Christian traditions explain the verse differently. Sacramental traditions emphasize baptism as God’s appointed means of grace and incorporation into Christ; Baptist and many evangelical traditions emphasize that cleansing is received through faith expressed in baptism, pointing especially to “calling on the name of the Lord.” What the verse does not support is treating baptism as an empty optional symbol with no connection to discipleship, or as a mechanical ritual that saves apart from Christ.'},
   {ref:'Acts 22:17-18',title:'Paul says the warning to leave Jerusalem came while he was praying in the temple.',text:'That setting matters for his defense. His call to Gentile ministry was not born from hatred of the temple; he says he was worshiping there when the Lord told him Jerusalem would not receive his testimony.'},
   {ref:'Acts 22:19-20',title:'Paul once thought his former persecution would make his testimony more persuasive to Jerusalem.',text:'He reasons that people know he imprisoned believers and consented to Stephen’s death, so his transformation should carry weight. The Lord’s answer shows that a powerful testimony does not guarantee that every audience will receive it.'},
   {ref:'Acts 22:20',title:'Paul still remembers his participation in Stephen’s death years later.',text:'He stood by, approved, and guarded the garments of those who killed Stephen. Grace has changed Paul, but Acts does not require him to pretend his past no longer happened. Forgiveness and honest memory can coexist.'},
   {ref:'Acts 22:21-22',title:'The crowd listens until Paul says God sent him far away to the Gentiles.',text:'That word is the breaking point. The issue is not merely that Gentiles might hear about Israel’s God—Judaism already knew Gentile God-fearers and converts—but the apostolic message places Gentiles within God’s saving work through Christ without requiring them first to become Jews. Acts has been building toward this conflict for many chapters.'},
   {ref:'Acts 22:22-23',title:'The renewed uproar shows how quickly listening can end when identity feels threatened.',text:'The crowd shouts for Paul’s death, throws off garments, and tosses dust into the air. Luke does not ask the reader to treat the mob’s intensity as evidence that its conclusion is correct.'},
   {ref:'Acts 22:24-25',title:'Roman “examination by scourging” was interrogation through severe physical punishment.',text:'The commander still does not understand why the crowd is furious and orders Paul scourged to force an explanation from him. Paul waits until he is stretched out and then asks the centurion whether it is lawful to scourge an uncondemned Roman citizen. It was not.'},
   {ref:'Acts 22:25-29',title:'Roman citizenship carried procedural protections that Paul is willing to invoke.',text:'The commander says he purchased citizenship at great cost; Paul replies that he was born a citizen. The men preparing to interrogate him immediately withdraw, and the commander becomes afraid because he has already bound a Roman citizen. Paul’s willingness to suffer for Christ does not mean refusing every legitimate legal protection.'},
   {ref:'Acts 22:28',title:'“I was free born” means Paul inherited Roman citizenship, though Acts does not explain how his family obtained it.',text:'Tarsus itself did not automatically make every resident a Roman citizen. Paul’s family possessed a status whose earlier origin is unknown to us. That citizenship will repeatedly affect how Roman officials are permitted to handle him.'},
   {ref:'Acts 22:30',title:'The commander finally moves from crowd control toward an actual hearing.',text:'Still wanting to know the charge, he releases Paul from the immediate bonds and orders the chief priests and council to assemble. The next stage of Paul’s witness will unfold before the Sanhedrin rather than through mob accusation.'}
  ],
  reflections:['When I tell the story of what God has changed in me, can I be truthful about who I was without either glorifying the past or hiding it?','Do I ever assume that a strong testimony should make everyone agree with me, when even Paul’s testimony could be rejected?','Can I distinguish faithful willingness to suffer from unnecessarily surrendering a lawful protection God has placed within reach?'],
  commentary:{voice:'Alexander Maclaren',identity:'Scottish Baptist preacher and expositor, 1826–1910',quote:'I saw and heard Him, and that revolutionised my life, and made me what I am.',plain:'Maclaren captures why Paul tells this story as his defense. Paul’s argument is deeply personal but not merely emotional: he is explaining that an encounter with the risen Jesus overturned the direction of his entire life. His former persecution makes the change harder, not easier, to explain away as convenience.',source:'Expositions of Holy Scripture — “Paul on His Own Conversion,” Acts 22:6–16',url:'https://ccel.org/ccel/maclaren/acts/acts.iii.xxxviii.html'},
  question:{q:'Does Acts 22:16 teach that baptism itself washes away sin?',short:'The verse connects baptism, cleansing, and calling on the Lord very closely, so it should not be weakened. Christians differ over how baptism relates to the moment of forgiveness, but the cleansing comes from Christ rather than from water treated as a magical substance.',more:'Ananias tells Paul, “Arise, and be baptized, and wash away thy sins, calling on the name of the Lord.” Sacramental Christian traditions often read this as a strong baptismal-regeneration text: God truly gives the grace signified in baptism. Baptist and many evangelical traditions emphasize the grammar and the wider New Testament pattern of forgiveness through faith, understanding baptism as the God-commanded public expression of the appeal to Christ. Either way, the verse resists two opposite reductions. Baptism is not presented as a meaningless add-on to conversion, but neither is the water an independent spiritual mechanism. The center remains the Lord whose name Paul calls upon—the same Jesus who confronted him, sent Ananias, and commissioned him as a witness.'}
 }
});
render();
