// Acts 13 — Living Bookmark card.
Object.assign(studies,{
 'Acts 13':{body:''}
});

Object.assign(studyMeta,{
 'Acts 13':{
  oneLine:'While Antioch’s prophets and teachers worship and fast, the Holy Spirit sets apart Barnabas and Saul for mission; sent by the Spirit and the church they cross Cyprus, where Paul confronts Elymas and the Roman proconsul believes, then travel to Pisidian Antioch, where Paul proclaims Israel’s promised Savior Jesus, His death and resurrection, forgiveness and justification through faith, before opposition turns their attention openly toward the Gentiles and the new disciples are filled with joy and the Holy Spirit.',
  write:[
   {ref:'Acts 13:2',title:'Mission begins in worship before it becomes movement.',text:'While the church ministers to the Lord and fasts, the Spirit names the work.'},
   {ref:'Acts 13:3',title:'The church sends away people it values because God has called them elsewhere.',text:'Prayer and open hands matter more than keeping gifted people close.'},
   {ref:'Acts 13:12',title:'The proconsul is astonished by the teaching of the Lord, not merely by a display of power.',text:'The sign exposes resistance so the word can be heard.'},
   {ref:'Acts 13:23',title:'Jesus arrives inside the long promise God made to Israel.',text:'Paul presents Him as the Savior raised from David’s seed according to promise.'},
   {ref:'Acts 13:38-39',title:'What the law could not give the guilty, Jesus gives to the believer.',text:'Forgiveness and justification are proclaimed through Him.'},
   {ref:'Acts 13:52',title:'Opposition can expel the messengers without emptying the disciples.',text:'They remain filled with joy and with the Holy Spirit.'}
  ],
  underline:{ref:'Acts 13:38-39',reason:'Paul brings the sermon to its saving announcement: through Jesus forgiveness is preached, and everyone who believes is justified from what the law of Moses could not justify.'},
  notice:[
   {ref:'Acts 13:1',title:'Antioch’s leadership is strikingly varied before the missionary journey even begins.',text:'Barnabas comes from Cyprus, Lucius from Cyrene in North Africa, Manaen has an intimate connection with Herod Antipas’ court, and Saul comes from Tarsus. Simeon’s Latin nickname Niger means “black” or “dark,” but the word alone cannot establish his precise ancestry. Luke shows a church already shaped by people from different regions and social worlds.'},
   {ref:'Acts 13:1',title:'Manaen grew up close to the same Herodian world that opposed Jesus and killed John the Baptist.',text:'The word can mean foster-brother, childhood companion, or one brought up together with Herod the tetrarch. Two men formed near the same court can take radically different paths: Herod Antipas becomes entangled in John’s death and Jesus’ trial, while Manaen becomes a prophet or teacher in Christ’s church.'},
   {ref:'Acts 13:2-3',title:'The Spirit’s call comes while the church is “ministering to the Lord” and fasting.',text:'The verb has the sense of sacred service or worship. They are not shown brainstorming a missionary expansion plan and then asking God to bless it. Their outward sending grows from worship, listening, fasting, and prayer.'},
   {ref:'Acts 13:2-4',title:'Barnabas and Saul are called by the Spirit and also publicly sent by the church.',text:'The Spirit says He has already called them to the work; the leaders then fast, pray, lay hands on them, and send them away. The laying on of hands recognizes and commissions what God is doing rather than creating the call from nothing. Luke can therefore say both that the church sent them and that they were “sent forth by the Holy Ghost.”'},
   {ref:'Acts 13:4-5',title:'Cyprus is a natural first destination for Barnabas, but the mission is larger than personal familiarity.',text:'Barnabas is a native of Cyprus. They sail from Seleucia to Salamis and begin in Jewish synagogues, with John Mark assisting them. Paul’s later pattern is already visible: begin among people who know Israel’s Scriptures, then carry the message outward.'},
   {ref:'Acts 13:6-8',title:'Bar-Jesus/Elymas is a Jewish false prophet and magician who tries to keep another man from hearing truth.',text:'Bar-Jesus is a personal name meaning “son of Jesus/Joshua”; Elymas is connected with his claim to be a wise man or magician. The problem is not ethnic identity but spiritual manipulation: he uses influence around Sergius Paulus to divert the governor from the faith.'},
   {ref:'Acts 13:7',title:'Luke’s title for Sergius Paulus—proconsul—fits Cyprus’ Roman administrative status.',text:'Rome divided provinces between imperial and senatorial administration. Cyprus had been reassigned to the Senate and was governed by a proconsul in this period. Ancient coins and inscriptions confirm the use of the proconsular title on Cyprus, matching Luke’s precise wording.'},
   {ref:'Acts 13:9',title:'“Saul, who also is called Paul” is not narrated as a miraculous renaming.',text:'A diaspora Jew and Roman citizen could carry both a Jewish/Semitic name and a Roman name. Luke does not say Jesus changed Saul’s name, nor that he took “Paul” from Sergius Paulus. He simply tells us Saul also had the name Paul, then uses the Roman name as the story moves deeper into Gentile territory.'},
   {ref:'Acts 13:9-11',title:'Paul’s first narrated miracle in the missionary journey is an act of temporary judgment, not self-defense.',text:'Filled with the Holy Spirit, Paul exposes Elymas for twisting the Lord’s straight ways and announces temporary blindness. The punishment strangely mirrors Paul’s own temporary blindness after resisting Jesus, but Luke never says Elymas’ future is sealed; he will be blind “for a season.”'},
   {ref:'Acts 13:12',title:'The miracle gets the proconsul’s attention, but Luke says he is astonished at “the doctrine of the Lord.”',text:'Christian mission is not supposed to leave people fascinated with the messenger’s power. Sergius Paulus sees what happens and believes, yet the object of his astonishment is the Lord’s teaching.'},
   {ref:'Acts 13:13',title:'John Mark leaves the team at Perga, but Acts 13 does not tell us why.',text:'Later Paul will consider Mark’s departure serious enough to refuse taking him on the next journey, while Barnabas will argue for another chance. Fear, illness, homesickness, disagreement, and other explanations have all been suggested, but Luke gives no reason here. It is better to leave the blank blank.',cross:[{ref:'Acts 15:37-39',label:'The later disagreement',reason:'Paul and Barnabas later disagree sharply over whether Mark, who had withdrawn from the earlier work, should travel with them again.'}]},
   {ref:'Acts 13:14-16',title:'Pisidian Antioch is not the Syrian Antioch that sent them.',text:'After traveling inland from Perga, Paul and Barnabas enter the synagogue on the Sabbath. The public reading of the Law and Prophets is followed by an invitation for a “word of exhortation,” giving Paul a natural opening to explain Jesus from Israel’s own story.'},
   {ref:'Acts 13:16-25',title:'Paul’s sermon begins with God’s actions before it speaks about human response.',text:'God chose the fathers, exalted the people in Egypt, bore with them in the wilderness, gave the land, raised judges, gave Saul, raised David, and from David’s seed brought the promised Savior. Jesus is not dropped into the story from nowhere; He is announced as the fulfillment of a history God has been directing.'},
   {ref:'Acts 13:22',title:'David as “a man after mine own heart” does not mean David was morally flawless.',text:'Paul combines Old Testament language about God choosing David with David’s calling to carry out God’s purpose. Scripture itself records David’s grave sins. The phrase concerns his chosen role and fundamental orientation toward God’s will, not sinless character.',cross:[{ref:'1 Samuel 13:14',label:'The phrase’s background',reason:'Samuel says the LORD has sought a man after His own heart to lead His people after Saul’s rejection.'}]},
   {ref:'Acts 13:26-29',title:'Paul addresses both descendants of Abraham and God-fearing Gentiles without turning Jesus’ death into ethnic blame.',text:'He says Jerusalem’s inhabitants and rulers failed to recognize Jesus and fulfilled the prophets by condemning Him, while Pilate carried out the execution. Paul himself is Jewish and is preaching first to a Jewish synagogue. The sermon confronts particular historical rejection; it cannot honestly be used as collective guilt against Jewish people across generations.'},
   {ref:'Acts 13:30-31',title:'The hinge of Paul’s message is four words: “But God raised him.”',text:'Human rulers condemn Jesus and place Him in a tomb; God reverses their verdict by raising Him from the dead. Paul then appeals to witnesses who saw the risen Jesus over many days, keeping resurrection proclamation tied to testimony rather than abstract symbolism.'},
   {ref:'Acts 13:32-33',title:'Psalm 2’s “this day have I begotten thee” does not mean Jesus began to exist or first became divine on that day.',text:'Psalm 2 is royal enthronement language in which the king’s sonship is publicly declared in connection with his installation and victory. Interpreters differ over whether “raised up Jesus” in verse 33 means God raised Him up in history as Messiah or points directly to resurrection; verse 34 explicitly moves to raising Him from the dead. Either way, Paul uses the psalm to declare Jesus’ messianic Sonship and vindication, not His creation.',cross:[{ref:'Psalms 2:7',label:'Royal Son language',reason:'Paul applies the psalm’s declaration of God’s anointed King and Son to Jesus.'}]},
   {ref:'Acts 13:34-37',title:'Paul uses Isaiah and Psalm 16 to argue that resurrection fulfills promises David himself could not exhaust.',text:'David served his generation, died, was buried, and saw corruption. Jesus, whom God raised, did not see corruption. Therefore the promise of God’s “sure mercies of David” and the Holy One not seeing decay reaches beyond David to the risen Messiah.',cross:[{ref:'Psalms 16:10',label:'The Holy One will not see corruption',reason:'Paul argues that David’s own death means the psalm reaches its fullest fulfillment beyond David.'},{ref:'Isaiah 55:3',label:'The sure mercies of David',reason:'Paul connects the enduring Davidic covenant promises with the Messiah raised never to return to corruption.'}]},
   {ref:'Acts 13:38-39',title:'“Justified” is courtroom language: through Jesus the believer is released from guilt the law cannot remove.',text:'Paul is not saying the law was evil or that it partly saved and Jesus merely supplies the missing percentage. The law reveals God’s will, names sin, and belongs to the covenant story Paul has just honored; but acquittal and full forgiveness are proclaimed through Christ to everyone who believes. Paul’s letters will unfold this doctrine much more fully.'},
   {ref:'Acts 13:40-41',title:'Paul ends the invitation with a warning from Habakkuk against seeing God’s work and refusing to believe it.',text:'Habakkuk originally warned Judah that God was doing a shocking work through the Chaldeans. Paul applies the prophetic warning analogically to the astonishing work God has now done in Christ. The quotation is not a claim that the ancient prophecy originally named Jesus directly; it is a warning not to repeat the posture of unbelief.',cross:[{ref:'Habakkuk 1:5',label:'Paul’s warning text',reason:'The prophet warns hearers not to scoff at a work of God they would scarcely believe even if told.'}]},
   {ref:'Acts 13:42-44',title:'Gentile hearers ask to hear more, and the next Sabbath almost the whole city gathers.',text:'The synagogue encounter spills beyond the synagogue. Many Jews and devout converts already follow Paul and Barnabas after the first service, and within a week the word has generated citywide interest.'},
   {ref:'Acts 13:45-46',title:'Luke criticizes specific opponents driven by jealousy, not Jewish people as a race.',text:'Some Jewish leaders contradict Paul when they see the crowds. Paul and Barnabas answer that the word had to be spoken to them first, honoring Israel’s priority in salvation history, but those particular hearers are thrusting the word away. Other Jews in the same chapter believe and follow the missionaries. The conflict is about response to the gospel, not ethnicity.'},
   {ref:'Acts 13:46-47',title:'Turning to the Gentiles is not Plan B after Israel “ruined” God’s plan.',text:'Paul says the word was necessarily spoken to Israel first, then quotes Isaiah 49:6 as divine command for a light reaching the ends of the earth. The Servant’s worldwide mission was already inside Scripture. Paul and Barnabas understand their mission as participating in what God promised through His Servant.',cross:[{ref:'Isaiah 49:6',label:'Light to the nations',reason:'The Servant is appointed not only for Israel’s restoration but as light so God’s salvation reaches the ends of the earth.'}]},
   {ref:'Acts 13:48',title:'“As many as were ordained to eternal life believed” has become a major election debate, and the verse deserves more than a slogan.',text:'The Greek tetagmenoi is commonly read as a perfect passive—those appointed or assigned to eternal life—and Reformed interpreters often see God’s electing appointment here. Some Arminian and other interpreters argue for a middle or dispositional sense, emphasizing people aligned or disposed toward eternal life, especially beside verse 46 where rejecters judge themselves unworthy. English translations overwhelmingly use “appointed,” “ordained,” or “destined.” The chapter itself holds divine initiative and real human response together; Christians disagree over how this verse fits a full doctrine of election.'},
   {ref:'Acts 13:49-52',title:'Expulsion from the district does not mean mission failure.',text:'Opponents recruit influential people and drive Paul and Barnabas from the region. The missionaries shake dust from their feet as a testimony and move on to Iconium. Yet Luke closes not with defeat but with disciples who are filled with joy and the Holy Spirit. The messengers leave; the church remains.'}
  ],
  reflections:['Am I willing to release people, gifts, or plans I value when the Holy Spirit clearly calls them into work I cannot control?','When Scripture corrects or confronts me, do I receive the word like the eager hearers or defend myself until I have pushed it away?','Is my confidence resting in religious background and effort, or in the forgiveness and justification Paul proclaims through Jesus?'],
  commentary:{voice:'Joseph Benson',identity:'English Methodist minister and biblical commentator, 1749–1821',quote:'their authority was not derived from them, but from the Holy Spirit himself',plain:'Benson notices the beautiful double sending at Antioch. The church truly prays, lays hands on Barnabas and Saul, and releases them; yet Luke immediately says they were sent out by the Holy Spirit. Christian community recognizes, blesses, and supports the call, but it does not own the missionaries or manufacture God’s authority.',source:'Commentary on the Old and New Testaments — Acts 13:2–4',url:'https://www.biblehub.com/commentaries/benson/acts/13.htm'},
  question:{q:'What does Acts 13:48 mean when it says those “ordained to eternal life” believed?',short:'The most common translation understands the phrase as people who had been appointed to eternal life, but Christians disagree about how that appointment relates to God’s election, grace, and the human response of faith.',more:'The key Greek expression is tetagmenoi eis zōēn aiōnion. Most major translations and many Greek commentators take tetagmenoi as passive: “appointed,” “ordained,” or “destined” for eternal life. Reformed readers commonly see this as a clear statement of God’s prior electing grace producing faith. Some Arminian and other interpreters argue that the form can be read with a middle or dispositional force—people who had placed or disposed themselves toward eternal life—and point to the immediate contrast in verse 46, where rejecters are said to judge themselves unworthy of eternal life. Others retain the passive translation while understanding divine appointment through prevenient grace, foreknowledge, or a corporate covenant framework rather than irresistible individual election. The grammar should be taken seriously, but one verse should not be forced to settle every later debate by itself. Luke’s whole scene contains both truths Christians must account for: salvation is moving forward under God’s purpose, and hearers genuinely believe, rejoice, reject, resist, or receive the word.'}
 }
});
render();
