// Acts 21 — Living Bookmark card.
Object.assign(studies,{
 'Acts 21':{body:''}
});

Object.assign(studyMeta,{
 'Acts 21':{
  oneLine:'Paul continues toward Jerusalem despite repeated warnings that suffering awaits him, stays with Philip the evangelist in Caesarea, hears Agabus dramatize his coming arrest, and answers his friends’ tears with readiness even to die for Jesus’ name; in Jerusalem James and the elders ask him to demonstrate that he has not taught Jewish believers to despise Moses, but Asian Jews falsely accuse him of bringing a Gentile into the temple, a mob nearly kills him, and Roman soldiers rescue and bind him before he asks permission to address the crowd.',
  write:[
   {ref:'Acts 21:5',title:'Whole families walk with Paul to the shore and pray.',text:'Mission in Acts is not only public preaching; it is also tearful, ordinary Christian fellowship.'},
   {ref:'Acts 21:13',title:'Paul is ready not only to be bound but to die for Jesus’ name.',text:'His courage is not lack of love for life; it is greater loyalty to Christ.'},
   {ref:'Acts 21:14',title:'When they cannot persuade Paul, his friends entrust the outcome to God.',text:'“The will of the Lord be done” is surrender after earnest concern, not emotional indifference.'},
   {ref:'Acts 21:20',title:'Thousands of Jewish believers still remain deeply Jewish.',text:'Faith in Jesus has not turned the Jerusalem church into an anti-Jewish movement.'},
   {ref:'Acts 21:26',title:'Paul is willing to make a costly accommodation for peace.',text:'He joins the purification process without making it the basis of salvation.'},
   {ref:'Acts 21:39',title:'Paul answers a false identity with simple truth.',text:'He is not the Egyptian rebel; he is a Jew from Tarsus asking to speak.'}
  ],
  underline:{ref:'Acts 21:13',reason:'Paul’s words reveal the chapter’s tension clearly: love makes the warnings painful, but loyalty to Jesus makes him willing to face what lies ahead.'},
  notice:[
   {ref:'Acts 21:1-6',title:'The journey is full of Christian hospitality and painful goodbyes.',text:'At Tyre, Paul’s party finds disciples and stays seven days. When they leave, men, women, and children accompany them outside the city, kneel on the shore, and pray. Luke lets the tenderness of Christian community sit beside the growing certainty of suffering.'},
   {ref:'Acts 21:4',title:'“Through the Spirit” they tell Paul not to go to Jerusalem—yet Acts has already said he is bound toward Jerusalem.',text:'This is one of the chapter’s real interpretive tensions. Acts 20:22-23 says Paul goes constrained in spirit while the Holy Spirit repeatedly testifies that imprisonment awaits. Many interpreters understand Acts 21:4 to mean the Spirit revealed the danger and the disciples responded by urging Paul not to go. Others see an actual prophetic prohibition that Paul nevertheless chose to face. Luke does not explicitly rebuke Paul, and later the Lord encourages him in Jerusalem and confirms that he will testify in Rome, so the passage should be handled with humility rather than pretending the tension is not there.',cross:[{ref:'Acts 20:22-23',label:'Earlier Spirit warning',reason:'Paul already knows the Spirit is testifying that bonds and afflictions await him in Jerusalem.'},{ref:'Acts 23:11',label:'The Lord later encourages Paul',reason:'After Paul is in Jerusalem, the Lord tells him to take courage and says he will also testify in Rome.'}]},
   {ref:'Acts 21:8-9',title:'Philip the evangelist is the same Philip first introduced among the Seven.',text:'He has now settled in Caesarea and has four unmarried daughters who prophesy. Acts neither hides women’s prophetic ministry nor tells us enough here to settle every later debate about church office. It simply presents their prophetic gift as part of the life of this Christian household.'},
   {ref:'Acts 21:10-11',title:'Agabus uses an old prophetic style: he acts out the message with Paul’s belt.',text:'Like several Old Testament prophets, Agabus turns prophecy into a visible sign by binding his own hands and feet. The drama makes the warning memorable: the owner of the belt will be handed over in Jerusalem.'},
   {ref:'Acts 21:11',title:'Agabus’ prophecy is fulfilled in substance even though the Romans do the actual chaining.',text:'The Jews seize Paul and try to kill him; Roman soldiers then physically bind him with two chains. Agabus says the Jews will bind and deliver him to Gentiles, language that captures the responsibility and outcome rather than narrating every mechanical step. The pattern also echoes Jesus being handed over through Jewish and Gentile authorities.'},
   {ref:'Acts 21:12-14',title:'Paul’s friends are not faithless because they weep and beg him not to go.',text:'Their love makes the prophecy hurt. Paul says their tears are weakening his resolve, which shows that courage and tenderness coexist. When they finally say, “The will of the Lord be done,” it comes after pleading, not because they never cared what happened.'},
   {ref:'Acts 21:17-20',title:'James and the Jerusalem elders receive Paul gladly, and Paul reports what God has done among the Gentiles.',text:'The meeting begins with worship, not suspicion. Paul gives a detailed account, and the elders glorify God. The tension that follows is therefore a family problem inside one church, not a war between two different gospels.'},
   {ref:'Acts 21:20',title:'“Many thousands” of Jewish believers are zealous for the law.',text:'The Greek word is myriades, literally “tens of thousands” or very large numbers. Luke’s point is that a substantial body of Jewish believers in Jerusalem remains serious about Jewish practice while confessing Jesus as Messiah.'},
   {ref:'Acts 21:21',title:'The rumor about Paul goes beyond what he actually taught.',text:'Paul is accused of teaching Jews living among Gentiles to abandon Moses, circumcision, and Jewish customs. His letters clearly refuse to make circumcision or Torah observance necessary for Gentile salvation, but that is not the same as commanding Jewish believers to erase their Jewish identity. The Jerusalem leaders treat the rumor as something needing public correction.'},
   {ref:'Acts 21:23-26',title:'Paul joins a purification arrangement to answer the rumor without changing the gospel.',text:'Four men have a vow, and Paul is asked to purify himself with them and pay their expenses. The action shows that he is not hostile to Jewish practice. Nothing in the scene says the ritual earns salvation or reverses Acts 15. It is voluntary accommodation for peace among Jewish believers.'},
   {ref:'Acts 21:25',title:'The Jerusalem leaders deliberately repeat the earlier decision about Gentile believers.',text:'They distinguish Paul’s accommodation among Jews from what is required of Gentiles. Gentiles are not suddenly being placed under the Mosaic law. The church is trying to preserve fellowship across Jewish and Gentile differences without making those differences the basis of salvation.'},
   {ref:'Acts 21:27-29',title:'The accusation that Paul brought Trophimus into the inner temple rests on an assumption, not evidence.',text:'Jews from Asia had seen Paul elsewhere in the city with Trophimus the Ephesian and concluded that Paul had taken him into the restricted temple area. Luke explicitly says they “supposed” this. A true observation—Paul was with Trophimus—becomes a false accusation when joined to an unproved inference.'},
   {ref:'Acts 21:28-29',title:'The charge is deadly serious because Gentiles were forbidden to cross the temple’s inner barrier.',text:'Archaeologists have found Greek warning inscriptions from the Second Temple period telling foreigners not to pass the balustrade surrounding the sanctuary, under threat of death. That background explains why the crowd treats the accusation as desecration rather than a minor breach of etiquette. The inscriptions confirm the rule and the stakes; they do not prove Paul actually violated it.'},
   {ref:'Acts 21:30-32',title:'The Roman force that arrests Paul also saves his life.',text:'The crowd drags him out of the temple and begins beating him. News reaches the Roman commander, who rushes down with soldiers; when the mob sees them, it stops beating Paul. Acts can show Roman power as unjust in one scene and providentially protective in another without making Rome morally pure.'},
   {ref:'Acts 21:33',title:'The “two chains” vividly echo Agabus’ warning.',text:'The commander orders Paul bound with two chains and begins asking who he is and what he has done. The arrest meant to control a riot becomes part of the path by which Paul will eventually reach Rome.'},
   {ref:'Acts 21:34-36',title:'The crowd is loud enough that the commander cannot discover the facts.',text:'Different people shout different accusations, so Paul is carried toward the barracks while the crowd cries, “Away with him.” Luke shows the danger of collective certainty without coherent evidence.'},
   {ref:'Acts 21:37-39',title:'The commander mistakes Paul for a recent Egyptian rebel.',text:'Paul’s fluent Greek surprises him. He asks whether Paul is the Egyptian who had led thousands of Sicarii—dagger-men or assassins—into the wilderness. Josephus also describes an Egyptian prophetic rebel from this period, though his surviving accounts give different numbers from Luke’s 4,000. The safest conclusion is that both sources know the same general unrest while the exact figures or groups counted differ.'},
   {ref:'Acts 21:39-40',title:'Paul’s first instinct after being beaten and arrested is to ask for permission to speak.',text:'He identifies himself as a Jew from Tarsus, receives permission, stands on the steps, and motions for silence. Acts 21 ends with the crowd quieting as Paul begins to address them in the local Semitic language—usually understood as Aramaic, though “Hebrew” can also be used more broadly for the language of the Jewish people.'}
  ],
  reflections:['When people I love warn me because they are afraid for me, can I hear their love without automatically treating their fear as God’s final direction?','Am I willing to give up a legitimate freedom when doing so can preserve peace without compromising the gospel?','How often do I turn one true observation into a confident conclusion I have not actually proved?'],
  commentary:{voice:'Alexander Maclaren',identity:'Scottish Baptist preacher and expositor, 1826–1910',quote:'No more lovely blending of melting tenderness and iron determination has ever been put into words.',plain:'Maclaren is describing Paul’s answer to the believers who beg him not to go. Paul is not emotionally hard; their tears are affecting him deeply. His steadiness comes from devotion to Jesus, not from being untouched by love or danger.',source:'Expositions of Holy Scripture — Acts 21',url:'https://biblehub.com/commentaries/maclaren/acts/21.htm'},
  question:{q:'Did Paul disobey the Holy Spirit by going to Jerusalem?',short:'Acts does not give a simple rebuke of Paul, so we should not pretend the question is easier than the text makes it. The strongest reading is that the Spirit repeatedly revealed the suffering ahead, while loving believers turned that warning into pleas for Paul not to go; other faithful interpreters think Acts 21:4 records an actual prohibition Paul chose to press past.',more:'The tension comes from reading the passages together. In Acts 20:22 Paul says he is going to Jerusalem “bound” or constrained in spirit, while the Holy Spirit testifies in every city that imprisonment and affliction await him. In Acts 21:4 disciples say “through the Spirit” that he should not go, and Agabus later dramatizes his coming arrest. One common interpretation is that the Spirit revealed what would happen and the disciples, understandably, drew the conclusion that Paul should avoid it. Another interpretation takes their words as a genuine Spirit-given prohibition and sees Paul’s determination as sincere but mistaken. Luke never explicitly condemns Paul for the journey, and once Paul is in Jerusalem the Lord appears to him and says, “Be of good cheer,” promising that he will also testify in Rome. So the safest conclusion is not that warnings always mean “stop,” nor that strong determination always proves “go.” Acts 21 calls for discernment, humility, and willingness to obey God even when faithful people read the same warning differently.'}
 }
});
render();
