// Acts 17 — Living Bookmark card.
Object.assign(studies,{
 'Acts 17':{body:''}
});

Object.assign(studyMeta,{
 'Acts 17':{
  oneLine:'Paul reasons from Scripture in Thessalonica that the Messiah had to suffer and rise and that Jesus is that Messiah; opposition drives the team to Berea, where hearers examine the Scriptures daily; in Athens Paul is distressed by idolatry, reasons with Jews and philosophers, and at the Areopagus proclaims the one Creator who made all nations, is near to every person, now commands repentance, and has appointed the risen Jesus as Judge.',
  write:[
   {ref:'Acts 17:3',title:'Paul’s gospel joins suffering, resurrection, and Messiahship.',text:'Jesus is not merely a teacher added to Israel’s story; He is the Christ who suffered and rose.'},
   {ref:'Acts 17:11',title:'Eagerness and examination belong together.',text:'The Bereans receive the word readily and search the Scriptures daily to test what they hear.'},
   {ref:'Acts 17:16',title:'Paul’s distress begins with what idolatry does to the glory owed to God.',text:'Athens impresses the eye, but Paul sees a city crowded with objects of worship.'},
   {ref:'Acts 17:24',title:'The Creator cannot be reduced to something humans contain or supply.',text:'The Lord of heaven and earth does not depend on temples or human hands.'},
   {ref:'Acts 17:27',title:'God is not far from any one of us.',text:'Paul calls people to seek the God who already gives them life and breath.'},
   {ref:'Acts 17:31',title:'The resurrection is God’s public assurance that judgment belongs to Jesus.',text:'Paul’s sermon ends not in vague spirituality but in repentance, judgment, and the risen Man God appointed.'}
  ],
  underline:{ref:'Acts 17:11',reason:'The Bereans model a mature response to teaching: receive it with readiness, then examine Scripture carefully rather than accepting or rejecting it on impulse.'},
  notice:[
   {ref:'Acts 17:1-3',title:'Paul’s synagogue method is reasoned and scriptural, not merely emotional appeal.',text:'For three Sabbaths he reasons from the Scriptures, “opening” and “alleging” that the Christ had to suffer and rise. The argument is not simply “believe me because I had an experience.” He shows how Jesus fits Israel’s scriptural hope.'},
   {ref:'Acts 17:3',title:'“This Jesus … is Christ” is the conclusion Paul is trying to establish.',text:'Christ is a title meaning Messiah or Anointed One, not Jesus’ surname. Paul’s claim is that the crucified and risen Jesus is the promised Messiah whom the Scriptures anticipated.'},
   {ref:'Acts 17:4-9',title:'The accusation about “another king, one Jesus” turns a theological claim into a political threat.',text:'Jesus truly is proclaimed as King, but the charge is framed to alarm Roman authorities by suggesting sedition against Caesar. Luke does not present the church as organizing a political revolt. The gospel’s claim over ultimate allegiance can still be misunderstood—or deliberately recast—as ordinary insurrection.'},
   {ref:'Acts 17:5-9',title:'Jason suffers because he gives hospitality to the missionaries.',text:'When Paul and Silas cannot be found, opponents drag Jason and other believers before the city authorities. Jason’s house has become associated with the mission, so ordinary hospitality becomes costly public identification with Christ.'},
   {ref:'Acts 17:10-12',title:'“More noble” describes the Bereans’ fair-minded response, not a superior social class.',text:'They are called more noble because they receive the word with readiness and examine the Scriptures daily to see whether Paul’s claims are so. Luke praises neither gullibility nor reflexive suspicion.'},
   {ref:'Acts 17:11',title:'The Bereans test an apostle by Scripture—and Paul is not offended by it.',text:'Acts treats careful examination as commendable. The passage is not permission to make private interpretation infallible, but it does show that Christian teaching should welcome serious scriptural testing.'},
   {ref:'Acts 17:13-15',title:'Opposition follows Paul from Thessalonica to Berea.',text:'The hostility is active enough that opponents travel to another city to stir crowds there. Paul leaves for Athens while Silas and Timothy remain for a time. Mission progress in Acts repeatedly includes both genuine reception and deliberate resistance.'},
   {ref:'Acts 17:16-18',title:'Athens brings Paul into conversation with Epicurean and Stoic philosophers.',text:'Epicureans generally sought a tranquil life and denied that the gods actively governed human affairs; Stoics emphasized divine reason or providence permeating the cosmos and valued self-mastery. Paul does not simply baptize either system. He begins from points they can understand and then challenges both with a Creator distinct from creation, human accountability, resurrection, and judgment.'},
   {ref:'Acts 17:18',title:'“Babbler” translates a word that literally pictured a seed-picker.',text:'Spermologos could describe a bird picking up scraps and came to be used contemptuously for someone who gathered bits of ideas without understanding them. The philosophers are not complimenting Paul’s breadth of learning; some are dismissing him as an intellectual scavenger.'},
   {ref:'Acts 17:18',title:'Some hear “Jesus and the resurrection” as though Paul were announcing foreign deities.',text:'The Greek word for resurrection, anastasis, is grammatically feminine, and some interpreters think the hearers may initially have mistaken “Jesus and Anastasis” for a pair of divinities. Luke’s wording at minimum shows how unfamiliar the Christian proclamation sounded in Athens.'},
   {ref:'Acts 17:19-21',title:'The Areopagus can mean both the hill and the council associated with it.',text:'Paul is brought before or to the Areopagus so his teaching can be heard and evaluated. Scholars differ over whether Luke intends primarily the physical place, the governing council, or both. The scene is public and intellectually serious either way.'},
   {ref:'Acts 17:22',title:'The KJV’s “too superstitious” can sound more insulting than Paul’s Greek wording requires.',text:'The term deisidaimonesterous can mean very religious or unusually devoted to religious matters. Paul is not flattering idolatry, but he opens by acknowledging the Athenians’ evident religious concern before exposing what their worship does not yet know.'},
   {ref:'Acts 17:23',title:'The altar “TO THE UNKNOWN GOD” becomes a bridge, not an endorsement of Athenian religion.',text:'Paul does not say every Athenian deity is really the biblical God under another name. He uses their confessed ignorance as an opening to proclaim the God they do not know: the Creator and Lord of all.'},
   {ref:'Acts 17:24-25',title:'Paul begins with creation because it overturns both idolatry and the idea that God needs human maintenance.',text:'The God who made the world cannot be housed as though a temple contained Him, nor served as though He lacked something. He is the giver of life, breath, and everything else. Worship is response to divine generosity, not supplying a needy deity.'},
   {ref:'Acts 17:26',title:'“One blood” in the KJV reflects a later Greek reading; the earliest manuscripts read that God made every nation “from one.”',text:'The sense is the shared human origin of all peoples under one Creator. Paul undercuts ethnic pride: nations differ in history and place, but no people exists outside the one human family God made.'},
   {ref:'Acts 17:26-27',title:'God’s sovereignty over peoples is ordered toward seeking Him, not toward racial superiority or fatalism.',text:'Paul says God determined appointed times and boundaries so people might seek Him. The verse does not make one nation spiritually superior by geography. The same God made all nations, governs history, and is near to every person.'},
   {ref:'Acts 17:28',title:'Paul quotes pagan poets without treating pagan religion as true.',text:'“In him we live, and move, and have our being” echoes Greek poetic language, and “we are also his offspring” appears in Aratus and similar Stoic poetry. Paul can affirm a true insight found in their culture, then redirect it: if humans are God’s offspring, God cannot sensibly be reduced to gold, silver, or stone images.'},
   {ref:'Acts 17:29-30',title:'Paul moves from shared language to repentance.',text:'The sermon does not end with “we all basically believe the same thing.” Having established the Creator’s nearness, Paul says idolatry misrepresents Him and that God now commands all people everywhere to repent.'},
   {ref:'Acts 17:30',title:'“Times of this ignorance God winked at” means He overlooked or passed over, not that idolatry was harmless.',text:'Paul is contrasting former ignorance with the clarity of the present summons. God’s patience did not mean approval; the universal command to repent shows that accountability remains.'},
   {ref:'Acts 17:31',title:'The resurrection is where the philosophical discussion becomes sharply Christian.',text:'Paul says God has appointed a day of judgment through a Man He has designated and has given assurance to all by raising Him from the dead. The resurrection is not an optional metaphor in the sermon; it is God’s public vindication of Jesus and the guarantee that history is moving toward judgment.'},
   {ref:'Acts 17:32-34',title:'The response is mixed: mockery, postponement, and belief.',text:'Some ridicule the resurrection, others want to hear more, and some believe, including Dionysius the Areopagite and Damaris. Acts does not measure faithfulness only by crowd size. Paul leaves Athens with a smaller visible response than in some cities, but not with no fruit.'}
  ],
  reflections:['Do I respond to teaching more like a Berean—open enough to listen and careful enough to examine?','When I speak about faith with someone from a different worldview, can I begin where there is real common ground without blurring what is distinctly Christian?','Is there any created thing—success, security, a place, a tradition, even a good religious habit—that I am tempted to treat as though it could contain or replace God?'],
  commentary:{voice:'John Chrysostom',identity:'Archbishop of Constantinople and early Christian preacher, c. 347–407',quote:'Do you mark the conciseness, and in conciseness, clearness?',plain:'Chrysostom admires how much Paul communicates in very little space. At Athens, Paul does not try to impress philosophers by sounding complicated. He moves quickly from Creator, to human dependence, to God’s nearness, to repentance, judgment, and resurrection. Depth does not require a wall of words.',source:'Homily XXXVIII on the Acts of the Apostles — Acts 17:16–31',url:'https://www.newadvent.org/fathers/210138.htm'},
  question:{q:'Was Paul compromising by quoting pagan poets in Acts 17?',short:'No. Paul uses true statements from their own cultural world as bridges, then corrects the worldview around them and leads the argument toward the Creator, repentance, judgment, and resurrection.',more:'Paul does not quote Aratus or other Greek poetry as though those writers had equal authority with Scripture, nor does he tell the Athenians that their gods are simply alternative names for the God of Israel. He notices statements they already know that can support part of his case: human life depends on God, and humanity has a real relation to its Creator. Then he turns those insights against idolatry itself. If humans derive their life from God, the divine nature cannot reasonably be reduced to an image fashioned from metal or stone. His method shows that Christians can recognize truth wherever it appears without surrendering the distinctive claims of the gospel. The sermon ends with a universal command to repent and with the resurrection of Jesus as God’s assurance of coming judgment.'}
 }
});
render();
