// Acts 1 — Living Bookmark card.
Object.assign(studies,{
 'Acts 1':{body:''}
});

Object.assign(studyMeta,{
 'Acts 1':{
  oneLine:'Luke opens his second volume by showing the risen Jesus teaching for forty days, promising the Holy Spirit, redirecting speculation about the kingdom toward Spirit-empowered witness, ascending bodily into heaven, and preparing the praying disciples to replace Judas with a qualified resurrection witness.',
  write:[
   {ref:'Acts 1:3',title:'The resurrection is not treated as one brief appearance.',text:'Jesus presents Himself alive over forty days with many proofs and keeps teaching about the kingdom of God.'},
   {ref:'Acts 1:7',title:'Some questions belong to the Father’s timetable, not ours.',text:'Jesus refuses to turn discipleship into date-setting.'},
   {ref:'Acts 1:8',title:'The Spirit gives power for witness, not spiritual celebrity.',text:'Jerusalem, Judea, Samaria, and the ends of the earth become the book’s widening map.'},
   {ref:'Acts 1:11',title:'The ascended Jesus will return as truly as He left.',text:'The angels turn the disciples from staring upward toward faithful waiting and mission.'},
   {ref:'Acts 1:14',title:'Before Acts becomes a book of public preaching, it is a room full of people praying together.',text:'The apostles, women, Mary, and Jesus’ brothers wait in one accord.'},
   {ref:'Acts 1:24',title:'The church asks the Lord to reveal the person He has chosen.',text:'The replacement for Judas is treated as God’s choice before it becomes theirs.'}
  ],
  underline:{ref:'Acts 1:8',reason:'This verse gives the program for the whole book: the Holy Spirit empowers witness that moves outward from Jerusalem to the nations.'},
  notice:[
   {ref:'Acts 1:1-3',title:'Acts is Luke’s second volume, not a disconnected sequel.',text:'The “former treatise” is the Gospel of Luke, addressed to the same Theophilus. Luke says the Gospel recorded what Jesus “began both to do and teach,” which quietly implies that Acts records what the risen and ascended Jesus continues to do through the Holy Spirit and His witnesses.'},
   {ref:'Acts 1:3',title:'Luke stresses the bodily resurrection with time, appearances, and evidence.',text:'Jesus shows Himself alive “by many infallible proofs” over forty days and speaks about the kingdom of God. Acts will repeatedly ground preaching in eyewitness resurrection testimony rather than in a vague spiritual idea that Jesus somehow lived on in the disciples’ memories.'},
   {ref:'Acts 1:4-5',title:'The disciples are told to wait before they are told to go.',text:'They already know Jesus’ teaching and have seen the risen Lord, but knowledge and eyewitness experience are not treated as sufficient for the mission by themselves. They must receive the promised Holy Spirit. Jesus connects this promise with John the Baptist’s distinction between water baptism and baptism with the Holy Ghost.',cross:[{ref:'Luke 24:49',label:'Luke’s first-volume promise',reason:'Luke’s Gospel also ends with Jesus telling the disciples to remain in Jerusalem until they are clothed with power from on high.'}]},
   {ref:'Acts 1:6-8',title:'Jesus does not satisfy their timetable question; He gives them their assignment.',text:'The disciples ask whether this is the time He will restore the kingdom to Israel. Christians disagree over how much future national restoration is implied in the question and in Jesus’ answer. What is clear is that Jesus does not give them a date. He redirects them from the Father’s hidden “times or seasons” to the revealed work in front of them: receive the Spirit and bear witness to Him.'},
   {ref:'Acts 1:7-8',title:'Two different Greek words sit behind the KJV’s “power.”',text:'In verse 7 the Father has exousia—authority or sovereign right—over the times and seasons. In verse 8 the disciples receive dynamis—power or enabling strength—when the Holy Spirit comes upon them. The contrast is useful: the Father keeps authority over the schedule; the church receives power for obedience.'},
   {ref:'Acts 1:8',title:'Jerusalem, Judea, Samaria, and the ends of the earth are more than a travel itinerary.',text:'They become a rough outline for Acts itself. The witness begins in Jerusalem, spreads through Judea and Samaria, then pushes outward through the Gentile mission until Paul is proclaiming Christ in Rome. The movement also crosses old social and religious boundaries, especially the Jewish-Samaritan divide and then the Jew-Gentile divide.'},
   {ref:'Acts 1:9-11',title:'The ascension is presented as a real departure, not Jesus simply becoming invisible.',text:'Jesus is lifted up while they watch, a cloud receives Him, and the angels say “this same Jesus” will come again in the same manner they saw Him go. In Scripture, clouds often accompany divine presence and glory. The point is not that heaven is physically just above the clouds; it is that the risen Lord enters the Father’s heavenly rule and will return personally.'},
   {ref:'Acts 1:11',title:'The angels’ question gently interrupts passive staring.',text:'“Why stand ye gazing up into heaven?” does not rebuke hope in Christ’s return; the very next sentence confirms it. It rebukes becoming immobilized by the departure. The disciples have already been given something to do while they wait.'},
   {ref:'Acts 1:12-14',title:'The waiting church is larger and more varied than the Eleven.',text:'Luke names the apostles, then mentions “the women,” Mary the mother of Jesus, and Jesus’ brothers. Earlier in the Gospels His brothers are described as not believing in Him; here they are praying with His followers. The resurrection has changed the family story as well as the public mission.',cross:[{ref:'John 7:5',label:'Earlier contrast',reason:'John explicitly says that during Jesus’ ministry His brothers did not yet believe in Him.'}]},
   {ref:'Acts 1:15-20',title:'Peter interprets Judas’s fall through Scripture without pretending Judas was an innocent puppet.',text:'He quotes Psalms that speak of a wicked enemy’s desolation and office being taken by another. Acts holds fulfillment and responsibility together: Judas’s betrayal fits the scriptural pattern, yet Judas is still described as the guide of those who arrested Jesus and as one who turned aside from apostolic ministry.'},
   {ref:'Acts 1:20',title:'Peter combines two different Psalms because each contributes part of the pattern.',text:'“Let his habitation be desolate” echoes Psalm 69, while “his bishoprick let another take” comes from Psalm 109. The KJV’s “bishoprick” means office or overseer-position here, not a later denominational job title.',cross:[{ref:'Psalm 69:25',label:'Scripture applied',reason:'Peter applies the psalm’s language of desolation to Judas’s end.'},{ref:'Psalm 109:8',label:'Scripture applied',reason:'Peter uses the psalm’s language of another person taking the office.'}]},
   {ref:'Acts 1:21-22',title:'The replacement apostle must be an eyewitness of the whole public ministry and especially the resurrection.',text:'The candidate must have accompanied the group from John’s baptism through the ascension and become “a witness with us of his resurrection.” This is a special qualification tied to the foundational apostolic role. It is not a general rule that every later Christian leader must meet the Twelve’s eyewitness requirement.'},
   {ref:'Acts 1:23-26',title:'The lot does not mean Acts teaches churches to make ordinary decisions by chance.',text:'The group narrows the candidates to two qualified men, prays to the Lord who knows hearts, and then casts lots. Lots had Old Testament precedent as a way of placing a decision before God. Acts never shows the church using this method again after the Spirit is poured out; later guidance comes through prayer, wisdom, Scripture, the Spirit, and communal discernment.'},
   {ref:'Acts 1:26',title:'There is no textual hint that choosing Matthias was a mistake because Paul would later become an apostle.',text:'That idea is sometimes suggested, but Acts simply says Matthias “was numbered with the eleven apostles.” Paul later receives a real apostolic calling, but of a different dramatic sort as the risen Christ appears to him. Luke never says the Eleven acted presumptuously here.'}
  ],
  reflections:['Am I spending energy trying to know a timetable God has not revealed instead of doing the work He has clearly put in front of me?','Where might I need to wait for God’s power rather than assuming good intentions and preparation are enough by themselves?'],
  commentary:{voice:'Alexander Maclaren',identity:'Scottish Baptist preacher and expositor, 1826–1910',quote:'the starting-point of the Christ’s heavenly activity',plain:'Maclaren sees the ascension not as Jesus becoming inactive but as the beginning of His heavenly work through the Spirit and the church. That fits Luke’s wording perfectly: his Gospel tells what Jesus “began” to do and teach, while Acts shows the risen Lord continuing His work from heaven.',source:'Expositions of Holy Scripture — Acts 1',url:'https://biblehub.com/commentaries/maclaren/acts/1.htm'},
  question:{q:'Was choosing Matthias a mistake because Paul was supposed to be the twelfth apostle?',short:'Acts gives no indication that Matthias was a mistake. Luke presents the choice as prayerful, scripturally reasoned, and accepted: Matthias “was numbered with the eleven apostles.”',more:'The theory that the disciples acted too soon usually assumes the vacant place had secretly been reserved for Paul. Acts never says that. Peter gives a specific qualification for Judas’s replacement: someone who accompanied Jesus’ public ministry from John’s baptism through the ascension and could serve as a resurrection witness from within that history. Matthias fits; Paul does not. Paul later becomes an apostle by an extraordinary personal call from the risen Christ and repeatedly defends that calling. Scripture can therefore affirm Matthias among the Twelve and Paul as a genuine apostle without making one cancel the other.'}
 }
});
render();