// Acts 2 — Living Bookmark card.
Object.assign(studies,{
 'Acts 2':{body:''}
});

Object.assign(studyMeta,{
 'Acts 2':{
  oneLine:'At Pentecost the promised Holy Spirit fills the disciples, the nations hear God’s mighty works in their own languages, Peter explains the event through Joel and the risen, exalted Jesus, about three thousand respond in repentance and baptism, and the new community devotes itself to apostolic teaching, fellowship, breaking bread, prayers, generosity, worship, and daily witness.',
  write:[
   {ref:'Acts 2:4',title:'The Spirit fills ordinary disciples and gives them speech they did not manufacture.',text:'Pentecost begins with God’s gift, not human technique.'},
   {ref:'Acts 2:11',title:'The miracle points attention toward “the wonderful works of God.”',text:'The languages serve proclamation, not spectacle.'},
   {ref:'Acts 2:17',title:'Peter says Joel’s “last days” have begun.',text:'The Spirit’s outpouring marks the arrival of the promised age, even though its final completion is still ahead.'},
   {ref:'Acts 2:23',title:'The cross belongs to God’s determined purpose without excusing human guilt.',text:'Divine sovereignty and human responsibility stand in the same sentence.'},
   {ref:'Acts 2:36',title:'The crucified Jesus is publicly declared both Lord and Christ.',text:'Resurrection and exaltation overturn the verdict placed on Him.'},
   {ref:'Acts 2:42',title:'The first church is described by steady devotion, not spiritual hype.',text:'Teaching, fellowship, breaking bread, and prayers become its ordinary rhythm.'}
  ],
  underline:{ref:'Acts 2:42',reason:'After the extraordinary signs of Pentecost, Luke shows the enduring life of the church in four ordinary devotions.'},
  notice:[
   {ref:'Acts 2:1',title:'Pentecost was already a Jewish feast before it became a Christian landmark.',text:'Pentecost is the Greek name connected with “fiftieth,” occurring fifty days after Passover. In the Old Testament it is associated with the Feast of Weeks and firstfruits. Luke’s setting matters because Jerusalem is filled with Jewish pilgrims from many regions, making the Spirit’s multilingual witness immediately international.'},
   {ref:'Acts 2:2-4',title:'Wind and fire echo older biblical signs of God’s presence, but Luke says “as of” wind and “like as” fire.',text:'He describes a sound from heaven like a rushing mighty wind and divided tongues like fire. The language is careful: the signs resemble familiar manifestations of God’s presence, while the central reality is that they are all filled with the Holy Ghost.'},
   {ref:'Acts 2:4-11',title:'The tongues in this scene are recognizable human languages.',text:'The visitors repeatedly say they hear the disciples speaking in their own native languages and dialects about God’s mighty works. Christians disagree about how Pentecost relates to later “tongues” passages, especially 1 Corinthians 12–14, but Acts 2 itself emphasizes intelligible languages crossing ethnic and geographic barriers.'},
   {ref:'Acts 2:5-11',title:'Luke’s long list of peoples is theological geography.',text:'Parthians, Medes, Elamites, residents of Mesopotamia, Judea, Cappadocia, Pontus, Asia, North Africa, Rome, Crete, and Arabia hear one gospel event in many languages. Pentecost does not erase human languages into one culture; the Spirit carries one message through their diversity.'},
   {ref:'Acts 2:12-16',title:'The same sign produces wonder in some people and mockery in others.',text:'Some ask what it means; others explain it away as drunkenness. Peter does not answer the mockery with outrage. He interprets the event through Scripture and points away from the disciples toward what God promised.'},
   {ref:'Acts 2:17-21',title:'Peter quotes Joel and explicitly says the promised “last days” have begun.',text:'Joel spoke of God pouring out His Spirit on sons and daughters, young and old, servants and handmaids, alongside cosmic judgment imagery and the promise that whoever calls on the Lord will be saved. Peter’s wording “in the last days” identifies Pentecost with the beginning of the promised end-time age. The New Testament can therefore call the present era “the last days” while still looking ahead to Christ’s final return.',cross:[{ref:'Joel 2:28-32',label:'Direct quotation',reason:'Peter identifies the Pentecost outpouring with Joel’s promise of the Spirit and salvation in the day of the LORD.'}]},
   {ref:'Acts 2:22-24',title:'Peter holds God’s plan and human responsibility together at the cross.',text:'Jesus was delivered according to God’s “determinate counsel and foreknowledge,” yet the people involved are still called responsible for crucifying Him through wicked hands. Luke does not solve the mystery by weakening either statement. God’s saving purpose is real; human evil is still evil.'},
   {ref:'Acts 2:25-32',title:'Peter reads Psalm 16 through the resurrection because David’s own grave remained with them.',text:'The psalm speaks of God’s Holy One not seeing corruption. Peter argues that David died and was buried, so the words ultimately reach beyond David to the promised descendant whose body would not remain in the grave. The apostles present themselves as witnesses that God raised Jesus up.',cross:[{ref:'Psalm 16:8-11',label:'Messianic fulfillment',reason:'Peter applies the psalm’s confidence that God’s Holy One will not see corruption to Jesus’ resurrection.'}]},
   {ref:'Acts 2:33-36',title:'Pentecost is explained as evidence that the risen Jesus has been exalted.',text:'Peter says Jesus, exalted at God’s right hand, received the promise of the Holy Ghost from the Father and poured out what the crowd now sees and hears. Then he quotes Psalm 110. The Spirit’s coming is therefore not a rival focus that replaces Jesus; it testifies that the crucified Jesus reigns as Lord and Christ.',cross:[{ref:'Psalm 110:1',label:'Direct quotation',reason:'Peter uses David’s “The LORD said unto my Lord” to explain Jesus’ exaltation at God’s right hand.'}]},
   {ref:'Acts 2:36',title:'“Whom ye have crucified” belongs to Peter’s concrete Jerusalem audience, not to a racial accusation against Jewish people.',text:'Peter is himself Jewish, the apostles are Jewish, and many of the people who respond in faith are Jewish pilgrims. The crucifixion also involved Roman authority. Christians distort Acts when they turn an apostolic call to repentance into collective blame against Jewish people across time.'},
   {ref:'Acts 2:37-38',title:'The people are “pricked in their heart,” and Peter answers with repentance and baptism in Jesus’ name.',text:'The response is not merely emotional regret. Peter calls for a changed mind and allegiance expressed openly in baptism. “In the name of Jesus Christ” marks public identification with the very Messiah they had rejected and with the forgiveness offered through Him.'},
   {ref:'Acts 2:38',title:'Christians disagree over exactly how baptism relates to “the remission of sins,” and the verse deserves more care than a slogan.',text:'Sacramental traditions read baptism here as God’s appointed means of receiving forgiveness within conversion. Many evangelical Protestants read baptism as the outward confession of repentance and faith by which forgiveness in Christ is publicly received and signified, not as water mechanically washing away sin. Acts itself keeps repentance, faith, baptism, forgiveness, and the Spirit closely joined; Bookmark should preserve that unity without pretending the historical debate does not exist.'},
   {ref:'Acts 2:39',title:'The promise reaches outward, but Peter still adds “as many as the Lord our God shall call.”',text:'The promise is “unto you, and to your children, and to all that are afar off.” Christians differ over how the reference to children relates to baptismal practice. What the sentence unquestionably emphasizes is widening grace: the promise is not trapped in the present Jerusalem crowd, yet its fulfillment rests in God’s call.'},
   {ref:'Acts 2:41-42',title:'Three thousand new believers do not disappear into a crowd statistic.',text:'Luke immediately describes what receiving the word looks like afterward: they are baptized and then continue steadfastly in the apostles’ doctrine, fellowship, breaking of bread, and prayers. Conversion produces a new pattern of belonging and learning.'},
   {ref:'Acts 2:42',title:'“Breaking of bread” may include both ordinary shared meals and the Lord’s Supper.',text:'Luke can use the phrase for ordinary meals, and the chapter later speaks of eating together in homes. Early Christian fellowship also centered on Jesus’ commanded meal. The wording here may intentionally carry both associations; the text does not force us to choose one every time the phrase appears.'},
   {ref:'Acts 2:44-45',title:'The believers’ generosity is radical, but Luke does not describe a state-enforced economic system.',text:'They hold possessions loosely, sell property, and distribute according to need. Later Acts shows believers still owning homes and property and portrays giving as voluntary. The passage confronts selfishness and indifference to need; it should not be flattened into either a proof text for compulsory communism or a promise that faithful Christians will become materially rich.'},
   {ref:'Acts 2:46-47',title:'Temple worship and house-to-house fellowship coexist in the first Jerusalem church.',text:'The believers continue daily in the temple and break bread in homes with gladness and singleness of heart. Acts begins with continuity as well as change: these Jewish believers do not instantly become detached from Israel’s worshiping life, even as a distinctly Christ-centered community forms.'}
  ],
  reflections:['Do I want the Holy Spirit mainly for extraordinary experiences, or for the power to make Christ known faithfully?','Which of Acts 2:42’s ordinary devotions—teaching, fellowship, breaking bread, prayer—most needs renewed steadiness in my own life?'],
  commentary:{voice:'Alexander Maclaren',identity:'Scottish Baptist preacher and expositor, 1826–1910',quote:'the whole fabric of Christianity is built',plain:'Maclaren is speaking about the resurrection fact at the center of Peter’s sermon. Pentecost is not spiritual excitement detached from history: Peter explains the Spirit’s outpouring by proclaiming the crucified, risen, exalted Jesus and grounding that proclamation in eyewitness testimony.',source:'Expositions of Holy Scripture — Acts 2',url:'https://www.biblehub.com/commentaries/maclaren/acts/2.htm'},
  question:{q:'Does Acts 2:38 teach that water baptism itself causes forgiveness of sins?',short:'Christians have answered that differently. The verse closely joins repentance, baptism, forgiveness, and the Holy Spirit, but it should not be reduced either to “the water mechanically saves” or to “baptism barely matters.”',more:'Sacramental Christians read Acts 2:38 within the New Testament pattern where baptism is God’s appointed initiation into Christ and the church, so they speak of forgiveness being received sacramentally. Many evangelical Protestants emphasize that forgiveness rests on Christ’s saving work and is received through repentant faith, with baptism as the commanded public expression of that conversion rather than its mechanical cause. Acts often places conversion realities close together without pausing to separate them into a later theological sequence. The safest Bookmark reading is to preserve Peter’s urgency: repent, openly identify with Jesus in baptism, receive the forgiveness He gives, and receive the Spirit—while acknowledging that faithful Christian traditions explain the precise sacramental relationship differently.'}
 }
});
render();