Object.assign(studies,{
'Genesis 3':{theme:'Selected places to pause: distorted words, hiding, promised conflict, mercy, and exile.',key:'Genesis 3:1, 9, 15, 21, 24',body:`
<h3>Bookmarks</h3>
<div class="note"><strong>🔖 Genesis 3:1 — “Has God indeed said...?”</strong><p>The serpent begins by handling God's words deceptively. Compare Genesis 2:16–17 with 3:1–5: God's generous permission is pushed to the background while the prohibition is made to dominate the conversation. Spurgeon, preaching from this verse, emphasized the serpent as deceiver and liar. The safest way to read the temptation is with God's actual words still open beside it.</p><p><strong>Follow it:</strong> John 8:44; 2 Corinthians 11:3.</p></div>
<div class="note"><strong>🔖 Genesis 3:9 — “Where are you?”</strong><p>Adam has hidden, yet God addresses him. The question draws the hiding man into the open and begins the reckoning. Watch for God's questions again in Genesis 4:6, 9–10; the pattern repeats with Cain.</p></div>
<div class="note"><strong>🔖 Genesis 3:15 — A promise spoken in the serpent's sentence.</strong><p>The verse announces enduring enmity and a coming blow against the serpent. Christians have long read this as the first glimmer of the gospel. Spurgeon called it the “first gospel sermon” and was struck that the promise appears before the sentences upon the woman and the man. Bookmark should let the later Bible help us see why Christians heard such hope here rather than forcing every later detail into this single verse.</p><p><strong>Follow it:</strong> Romans 16:20; Hebrews 2:14; Revelation 12:9; 20:2.</p></div>
<div class="note"><strong>🔖 Genesis 3:21 — God clothes them.</strong><p>Adam and Eve had already made coverings for themselves in verse 7. Here God makes garments and clothes them. Judgment has not disappeared, but neither has God's care. It is worth simply noticing who provides the covering.</p></div>
<div class="note"><strong>🔖 Genesis 3:24 — The guarded way to the tree of life.</strong><p>The chapter ends east of Eden, with the way back guarded. The tree itself has not vanished from Scripture. Revelation's closing chapters deliberately bring the tree of life back into view, now in the renewed dwelling of God with His people.</p><p><strong>Follow it:</strong> Revelation 2:7; 22:1–5, 14.</p></div>
<h3>Sources beside the open Bible</h3><p class="sources">Primary: Genesis 2–4 and the cross-references above. Historic companions checked: C. H. Spurgeon, “An Antidote to Satan's Devices” (Genesis 3:1), “Christ the Conqueror of Satan” (Genesis 3:15), and “The Serpent's Sentence” (Genesis 3:14–15). The finished bookmarks no longer rely on BibleProject. Pastor Brian material remains excluded pending a verifiable source and permission.</p>`}
});
render(document.querySelector('.tab.active')?.dataset.filter||'all');
