// John 17 — Living Bookmark card.
Object.assign(studies,{
 'John 17':{body:''}
});

Object.assign(studyMeta,{
 'John 17':{
  oneLine:'On the eve of the cross Jesus prays to the Father about the glory He shared before the world existed, defines eternal life as knowing the Father and the Son, prays that His disciples will be kept, joyful, sanctified in truth, and sent into the world, then includes future believers in His prayer for deep unity, witness, glory, and love.',
  write:[
   {ref:'John 17:3',title:'Eternal life is relational before it is merely endless.',text:'Jesus defines it as knowing the Father and Jesus Christ whom He sent.'},
   {ref:'John 17:5',title:'Jesus speaks of glory shared with the Father before the world existed.',text:'The cross approaches, but His story does not begin in Bethlehem.'},
   {ref:'John 17:11',title:'Jesus prays for unity while His disciples remain in a hostile world.',text:'Their oneness is meant to reflect Father and Son.'},
   {ref:'John 17:15',title:'Jesus does not pray for escape from the world.',text:'He prays for protection from evil while His people remain in it.'},
   {ref:'John 17:17',title:'Holiness and truth are not enemies.',text:'“Sanctify them through thy truth: thy word is truth.”'},
   {ref:'John 17:20',title:'Jesus’ prayer reaches beyond the room to people who will believe through the apostles’ word.',text:'Future believers are already inside His intercession.'}
  ],
  underline:{ref:'John 17:3',reason:'Jesus describes eternal life as knowing the only true God and Jesus Christ whom He sent—not merely existing forever.'},
  notice:[
   {ref:'John 17:1-5',title:'Jesus calls the cross His hour of glory and reaches back before creation.',text:'He asks the Father to glorify the Son so the Son may glorify the Father, then says He has finished the work given Him and asks for the glory He had “with thee before the world was.” John’s Gospel does not present Jesus as a merely human teacher who later receives divine status; the Son speaks from a pre-creation relationship with the Father.'},
   {ref:'John 17:3',title:'Knowing God in John is more than knowing facts about God.',text:'Jesus calls this eternal life: knowing the Father as the only true God and knowing Jesus Christ whom He sent. Biblical “knowing” is relational and covenantal without becoming anti-intellectual. Truth matters precisely because the relationship is with the real God, not a projection.'},
   {ref:'John 17:6-10',title:'The disciples belong to the Father and the Son together.',text:'Jesus says the Father gave them to Him, they received His words, and they came to know that He came from the Father. He then says, “all mine are thine, and thine are mine.” The prayer keeps distinguishing Father and Son while speaking of an extraordinary shared possession and glory.'},
   {ref:'John 17:11-12',title:'The prayer for oneness is rooted in God’s own name and keeping power.',text:'Jesus is leaving the world while the disciples remain. He asks the Holy Father to keep them so “they may be one, as we are.” Christian unity is therefore deeper than friendliness or organizational efficiency. It grows from a shared life kept in the Father’s name.'},
   {ref:'John 17:12',title:'Judas as “the son of perdition” does not make betrayal morally innocent.',text:'Jesus says Scripture is fulfilled, but throughout John Judas is also shown making real choices—stealing, rejecting warning, and going out to betray. Biblical fulfillment and human responsibility are allowed to stand together rather than one being used to erase the other.'},
   {ref:'John 17:13-16',title:'Jesus does not pray that disciples will be removed from a difficult world.',text:'He wants His joy fulfilled in them, acknowledges that the world hates them because they belong to Him, and then specifically says, “I pray not that thou shouldest take them out of the world.” The prayer is for preservation from evil in the middle of mission, not spirituality through disappearance.'},
   {ref:'John 17:17-19',title:'Sanctification here means being set apart to God in truth and mission.',text:'The Father sanctifies disciples through the truth of His word; Jesus sends them as the Father sent Him. When Jesus says “for their sakes I sanctify myself,” He does not mean He was previously sinful. He consecrates Himself to the saving work before Him so they may be truly set apart for God.'},
   {ref:'John 17:20',title:'Jesus explicitly prays for later believers through the apostles’ word.',text:'The church’s faith is not meant to float free of the first witnesses. Future believers come through their testimony. That makes apostolic truth part of the foundation for the unity Jesus prays for in the next verses.'},
   {ref:'John 17:21-23',title:'The unity Jesus prays for cannot be reduced either to visible organization or to invisible sentiment.',text:'He asks for a oneness patterned after Father and Son, rooted in mutual indwelling, given glory, and aimed at witness “that the world may believe.” Truth, love, holiness, mission, and recognizable communion belong together. Using the passage to demand unity by ignoring truth would contradict verse 17; using truth as an excuse for loveless fragmentation would contradict the prayer itself.'},
   {ref:'John 17:24-26',title:'The prayer ends with Jesus wanting His people to see His glory and share the Father’s love.',text:'He says the Father loved Him before the foundation of the world and asks that the love with which the Father loved Him may be in His people—and He in them. John’s farewell discourse ends not in bare duty but in divine love shared with the people Christ brings home.'}
  ],
  reflections:['Do I think of eternal life mainly as “going somewhere later,” or as knowing God through Christ beginning now?','What would Christian unity look like if I refused both false peace without truth and truth spoken without love?'],
  commentary:{voice:'John Calvin',identity:'Reformation pastor and commentator, 1509–1564',quote:'sanctification is not instantly completed in us on the first day',plain:'Calvin draws attention to the continuing work implied in Jesus’ prayer. Being set apart to God is real, but growth in holiness is not finished in a moment. Christ prays for disciples who already belong to Him to keep being sanctified through the truth.',source:'Commentary on John — John 17',url:'https://biblehub.com/commentaries/calvin/john/17.htm'},
  question:{q:'When Jesus prays “that they all may be one,” does that mean Christians should ignore doctrinal differences for the sake of unity?',short:'No. The unity Jesus prays for is inseparable from the truth He has just named, the apostolic word through which future believers come to faith, shared holiness, love, and mission.',more:'John 17 will not let us choose between unity and truth. Verse 17 says, “Sanctify them through thy truth: thy word is truth.” Verse 20 speaks of people believing through the apostles’ word. Then verses 21–23 pray for oneness patterned after Father and Son and visible enough to strengthen the church’s witness. Some divisions among Christians are needless products of pride, culture, or personality and should grieve us. Other disagreements concern genuinely weighty claims about God and the gospel and cannot be solved by pretending differences do not exist. Jesus’ prayer calls believers toward a deeper unity in received truth and self-giving love, not superficial agreement at any price.'}
 }
});
render();