// John 16 — Living Bookmark card.
Object.assign(studies,{
 'John 16':{body:''}
});

Object.assign(studyMeta,{
 'John 16':{
  oneLine:'Jesus prepares His disciples for religious persecution and His departure, promises that the Spirit will expose the world’s false verdict about sin, righteousness, and judgment and guide the apostles into truth, promises resurrection joy after their grief, and closes by joining peace in Him with tribulation in the world because He has overcome the world.',
  write:[
   {ref:'John 16:1',title:'Jesus warns them beforehand so suffering will not look like proof He failed.',text:'Preparation is part of His care.'},
   {ref:'John 16:7',title:'Jesus says His departure will become gain because the Comforter will come.',text:'Loss is not the last word in the Upper Room.'},
   {ref:'John 16:13',title:'The Spirit of truth keeps pointing away from Himself toward what belongs to Christ.',text:'He guides, speaks, and glorifies the Son.'},
   {ref:'John 16:20',title:'Resurrection does not merely replace sorrow; it transforms the meaning of it.',text:'“Your sorrow shall be turned into joy.”'},
   {ref:'John 16:27',title:'The Father Himself loves the disciples.',text:'Jesus does not describe the Father as reluctant while the Son tries to persuade Him to care.'},
   {ref:'John 16:33',title:'Christ promises peace and tribulation in the same sentence.',text:'“In the world ye shall have tribulation: but be of good cheer; I have overcome the world.”'}
  ],
  underline:{ref:'John 16:33',reason:'Jesus does not promise a trouble-free world; He promises peace in Himself because the world’s final verdict has already been overcome.'},
  notice:[
   {ref:'John 16:1-4',title:'Jesus warns that sincere religious conviction can still become violently wrong.',text:'Some will put the disciples out of synagogues and even kill them while thinking they are offering service to God. Zeal by itself is therefore not proof of truth. A person can feel morally certain and still oppose God because they do not know the Father or the Son.'},
   {ref:'John 16:5-7',title:'“It is expedient for you that I go away” sounds impossible until Jesus explains the Spirit’s coming.',text:'The disciples see only separation. Jesus sees death, resurrection, return to the Father, and the new stage of the Spirit’s presence and mission. The Comforter’s coming will not make Jesus less important; the rest of the chapter says the Spirit will glorify Christ.'},
   {ref:'John 16:8-11',title:'The Spirit’s “reproof” is conviction—exposing the world’s wrong judgment in three directions.',text:'Sin is brought to a crisis in unbelief toward Jesus; righteousness is vindicated as Jesus goes to the Father rather than remaining under the world’s condemnation; judgment is revealed because “the prince of this world is judged.” This is more than making people feel vaguely guilty. The Spirit exposes how the world has misjudged Jesus and therefore misjudged itself.'},
   {ref:'John 16:12-15',title:'The promise that the Spirit will “guide you into all truth” is spoken first to the apostles carrying Jesus’ witness forward.',text:'They cannot yet bear everything Jesus wants to teach. The Spirit will guide them, declare what is to come, and glorify Christ by taking what belongs to Him and making it known. Believers rightly depend on the Spirit for understanding, but the verse is not a blank check making every private impression new revelation equal to the apostolic witness.'},
   {ref:'John 16:16-22',title:'The “little while” becomes intelligible through death and resurrection.',text:'Jesus will be taken from their sight and they will grieve while the world rejoices; then they will see Him again. The woman-in-labor image explains the change: the pain is not simply erased from history, but the arrival of new joy changes how it is remembered.'},
   {ref:'John 16:23-28',title:'Prayer in Jesus’ name leads to the Father; it does not picture Jesus shielding believers from an unwilling Father.',text:'Jesus says plainly, “the Father himself loveth you.” His mediating work is essential, but Father and Son are not divided over whether the disciples should be loved. Their access rests in the saving relationship Jesus opens.'},
   {ref:'John 16:29-32',title:'The disciples finally say they understand—and Jesus immediately tells them they are about to scatter.',text:'Their confession is real, but their confidence outruns their strength. “Do ye now believe?” is followed by the prediction that each will flee to his own place. Jesus, however, says He is not truly alone because the Father is with Him.'},
   {ref:'John 16:33',title:'Peace and tribulation belong to two different centers of gravity.',text:'Jesus does not say, “I have overcome the world, therefore nothing painful will happen to you.” He has spent the chapter saying the opposite. Their peace is “in me”; their tribulation is “in the world.” Christian courage comes from Christ’s victory, not from pretending the conflict is imaginary.'}
  ],
  reflections:['When I feel strongly convinced that I am right, what keeps my zeal submitted to actually knowing the Father and the Son?','Can I receive Christ’s kind of peace—a peace that can exist in the middle of trouble rather than only after everything becomes easy?'],
  commentary:{voice:'Alexander Maclaren',identity:'Scottish Baptist preacher and expositor, 1826–1910',quote:'Peace is not lethargy.',plain:'Maclaren notices that Jesus places peace beside tribulation and victory language. Christ’s peace is not emotional numbness or retreat from the battle; it is inward steadiness rooted in Him while the disciple still faces a difficult world.',source:'Expositions of Holy Scripture — John 16',url:'https://biblehub.com/commentaries/maclaren/john/16.htm'},
  question:{q:'What does it mean that the Holy Spirit “reproves” or convicts the world of sin, righteousness, and judgment?',short:'The Spirit exposes the world’s wrong verdict about Jesus and therefore its own spiritual condition: unbelief is sin, Jesus is vindicated by returning to the Father, and the ruler of this world stands judged.',more:'The three explanations Jesus gives in verses 9–11 should control the answer. “Of sin, because they believe not on me” brings humanity’s rejection of the Son into focus. “Of righteousness, because I go to my Father” means the One condemned as unrighteous by human courts will be vindicated by the Father. “Of judgment, because the prince of this world is judged” announces that the evil power behind the world’s rebellion has already received its decisive sentence. The Spirit certainly awakens personal conscience, but this paragraph is larger than a private feeling of guilt: He overturns the world’s whole verdict on Christ.'}
 }
});
render();