// John 11 — Living Bookmark card.
Object.assign(studies,{
 'John 11':{body:''}
});

Object.assign(studyMeta,{
 'John 11':{
  oneLine:'Jesus deliberately waits after hearing Lazarus is sick, meets Martha and Mary inside real grief, declares Himself the Resurrection and the Life, weeps and groans at the tomb, calls Lazarus out after four days, and turns the sign into the immediate setting for the authorities’ decision to kill Him.',
  write:[
   {ref:'John 11:5-6',title:'Jesus’ delay happens inside His love, not outside it.',text:'John says He loved Martha, Mary, and Lazarus—and then tells us He stayed two more days.'},
   {ref:'John 11:25',title:'Resurrection is not only an event Jesus performs.',text:'He says, “I am the resurrection, and the life.”'},
   {ref:'John 11:27',title:'Martha answers grief with a confession of who Jesus is.',text:'She calls Him the Christ, the Son of God, the One coming into the world.'},
   {ref:'John 11:35',title:'Jesus knows the resurrection is minutes away and still weeps.',text:'Hope does not make grief unreal or tears faithless.'},
   {ref:'John 11:40',title:'Faith is invited to look for God’s glory before the stone moves.',text:'Jesus reminds Martha of what He had told her.'},
   {ref:'John 11:43-44',title:'Death hears the voice of Jesus.',text:'He calls Lazarus by name, and the dead man comes out.'}
  ],
  underline:{ref:'John 11:25-26',reason:'At the center of the chapter Jesus does not merely promise resurrection; He identifies resurrection life with Himself.'},
  notice:[
   {ref:'John 11:1-6',title:'John deliberately puts Jesus’ love and Jesus’ delay side by side.',text:'The sisters send the simplest possible message: “Lord, behold, he whom thou lovest is sick.” John then explicitly says Jesus loved this family, followed by “therefore” He remained two days where He was. The delay is purposeful, but this story should not be turned into a formula promising that every delayed answer will end in the miracle we want. John is telling us what Jesus is doing in this particular sign.'},
   {ref:'John 11:11-14',title:'Jesus calls Lazarus’ death “sleep,” then speaks plainly when the disciples misunderstand.',text:'The image does not deny real death. Lazarus is dead, and Jesus says so. “Sleep” points toward death as temporary before the power of resurrection, but the chapter gives no support to pretending death is trivial or grief is unnecessary.'},
   {ref:'John 11:17-24',title:'Four days in the tomb removes any suggestion of a brief faint or mistaken diagnosis.',text:'By the time Jesus arrives, Lazarus has been buried four days. Martha’s “if thou hadst been here” contains both sorrow and continued trust. Jesus does not scold her for speaking honestly. He draws her from a general belief in resurrection “at the last day” toward Himself.'},
   {ref:'John 11:25-27',title:'“I am the resurrection, and the life” moves the doctrine from an abstract future into the person of Jesus.',text:'Martha already believes in a final resurrection. Jesus does not correct that hope; He reveals its center. The life of the age to come stands in front of her. Her answer is one of John’s great confessions: Christ, Son of God, the One coming into the world.'},
   {ref:'John 11:32-35',title:'Jesus does not answer Mary’s tears with a lecture against grieving.',text:'Mary repeats Martha’s “if thou hadst been here.” Jesus sees her and the mourners weeping, is deeply moved and troubled, asks where Lazarus is laid, and then weeps. The shortest verse is not shallow. The One who knows He is about to raise Lazarus still enters the sorrow of the grave.'},
   {ref:'John 11:33-38',title:'The word translated “groaned” carries stronger emotion than quiet sadness alone.',text:'The Greek verb embrimaomai can carry the sense of indignation, stern emotion, or deep agitation. Interpreters differ over the exact object of Jesus’ anger—death itself, unbelief, the misery sin has brought, or the whole scene—but John gives us more than sentimental tears. Jesus confronts the tomb with grief and holy disturbance.'},
   {ref:'John 11:39-40',title:'Martha’s practical objection does not cancel her earlier faith.',text:'She has confessed Jesus magnificently, yet when He orders the stone moved she immediately thinks about a four-day-old body. John lets strong faith and frightened realism coexist in the same disciple. Jesus brings her back to His promise about seeing God’s glory.'},
   {ref:'John 11:41-44',title:'Jesus prays aloud for the crowd’s sake and then commands the dead man directly.',text:'He thanks the Father before Lazarus emerges and says His public prayer is meant to help the people believe the Father sent Him. Then no ritual or struggle follows: “Lazarus, come forth.” The sign dramatizes the earlier claim that the dead will hear the Son’s voice.',cross:[{ref:'John 5:25',label:'Earlier promise',reason:'Jesus had already said the dead would hear the voice of the Son of God, and those who hear would live.'}]},
   {ref:'John 11:45-53',title:'The greatest sign in the Gospel does not force everyone into faith.',text:'Many believe, but others report the event to the authorities. The council’s fear centers on losing place and nation under Rome. Caiaphas then says it is expedient for one man to die for the people. John treats the statement as an unwitting prophecy: a cynical political calculation speaks more truth than Caiaphas understands.'},
   {ref:'John 11:51-52',title:'John widens the meaning of Jesus’ death beyond one political nation.',text:'He says Jesus will die for the nation, “and not for that nation only,” but also to gather together the scattered children of God. The raising of one beloved friend therefore points toward a death that will gather a people.'}
  ],
  reflections:['Can I bring Christ the sentence “If You had been here…” without assuming honest grief is the opposite of faith?','What changes when resurrection is not merely something Jesus promises someday, but something rooted in who He is right now?'],
  commentary:{voice:'John Calvin',identity:'Reformation pastor and commentator, 1509–1564',quote:'we ought not to judge of the love of God from the condition which we see before our eyes',plain:'Calvin is commenting on the strange combination of love and delay at the beginning of the chapter. The sisters can see only worsening sickness and then death; John tells the reader that Christ’s love has not disappeared. That does not give us permission to predict how every painful delay will resolve, but it does warn us against measuring God’s love only by the circumstances visible today.',source:'Commentary on John — John 11',url:'https://biblehub.com/commentaries/calvin/john/11.htm'},
  question:{q:'Why did Jesus wait if He loved Lazarus, Martha, and Mary?',short:'John says the delay was deliberate and still part of Jesus’ loving purpose in this particular sign: Lazarus’ death would become the setting for a greater revelation of God’s glory and of Jesus as the Resurrection and the Life.',more:'The chapter intentionally makes the tension uncomfortable. Jesus loves them; He receives the message; He stays two more days; Lazarus dies. The point is not that love always looks like immediate rescue, nor that every tragedy will be reversed before our eyes. In this story Jesus allows the situation to reach a place no one can repair so that the sign reveals who He is. Just as important, John shows that purposeful delay does not make Jesus emotionally detached. He meets Martha, receives Mary’s tears, groans, and weeps before He raises Lazarus.'}
 }
});
render();