// Acts 15 — Living Bookmark card.
Object.assign(studies,{
 'Acts 15':{body:''}
});

Object.assign(studyMeta,{
 'Acts 15':{
  oneLine:'Teachers from Judea insist Gentile believers cannot be saved without circumcision, so Paul and Barnabas go to Jerusalem where apostles, elders, and the church weigh God’s work among Gentiles and the Scriptures; Peter declares that hearts are cleansed by faith and both Jews and Gentiles are saved through the grace of Jesus, James agrees that Gentile converts must not be burdened with becoming Jews, a letter communicates the decision and practical fellowship instructions, and the chapter ends with a sharp but later-healed division between Paul and Barnabas over John Mark.',
  write:[
   {ref:'Acts 15:1',title:'The issue is salvation, not merely tradition.',text:'“Except ye be circumcised … ye cannot be saved” adds a covenant marker as a condition God did not require.'},
   {ref:'Acts 15:9',title:'God made no distinction in the cleansing of hearts.',text:'Jew and Gentile alike are cleansed by faith.'},
   {ref:'Acts 15:11',title:'Peter puts everyone on the same ground.',text:'“Through the grace of the Lord Jesus Christ we shall be saved, even as they.”'},
   {ref:'Acts 15:19',title:'James refuses to make turning to God unnecessarily difficult.',text:'Gentiles who are coming to God are not to be troubled with a conversion into Jewish identity.'},
   {ref:'Acts 15:28',title:'The church discerns together under the Holy Spirit.',text:'“It seemed good to the Holy Ghost, and to us” joins divine guidance with careful communal judgment.'},
   {ref:'Acts 15:39',title:'Faithful servants can disagree sharply without God abandoning either person or His mission.',text:'Paul and Barnabas separate, yet both continue serving—and Mark will later be restored to Paul’s confidence.'}
  ],
  underline:{ref:'Acts 15:11',reason:'Peter states the council’s deepest theological answer in one sentence: Jews do not save Gentiles by making them Jewish; “we” are saved through the grace of the Lord Jesus in the same way “they” are.'},
  notice:[
   {ref:'Acts 15:1',title:'The teachers from Judea are not merely recommending circumcision; they make it necessary for salvation.',text:'Circumcision was the ancient covenant sign given to Abraham and deeply bound up with Jewish identity. The crisis comes when some believers say an uncircumcised Gentile “cannot be saved.” That changes a God-given sign into an additional entrance requirement beside the grace of Christ.'},
   {ref:'Acts 15:2',title:'Paul and Barnabas treat this as a gospel-level dispute worth open argument.',text:'Luke says there is “no small dissension and disputation.” Not every disagreement deserves this level of conflict, but a teaching that changes the basis of salvation does. The church sends delegates to Jerusalem so the issue can be examined with the apostles and elders rather than allowed to fracture churches by rumor.'},
   {ref:'Acts 15:2-4',title:'Many scholars identify this visit with Galatians 2:1–10, but the chronology is genuinely debated.',text:'A common view sees Paul’s meeting with Jerusalem’s leading apostles in Galatians 2 as the same occasion viewed from Paul’s private perspective and Luke’s public one. Other scholars identify Galatians 2 with the earlier famine-relief visit of Acts 11. The question affects Pauline chronology but not the central agreement both texts affirm: Gentile believers were not to be compelled to become Jews in order to belong to Christ.'},
   {ref:'Acts 15:3-4',title:'The journey to debate a controversy is filled with reports of Gentile conversion that bring the churches joy.',text:'Passing through Phoenicia and Samaria, Paul and Barnabas describe Gentiles turning to God, and the believers rejoice greatly. The dispute is real, but Luke keeps placing the actual fruit of grace in front of the reader before the council even begins.'},
   {ref:'Acts 15:5',title:'The Pharisees in this verse are believers in Jesus, not outside enemies.',text:'Some believers from the Pharisaic party argue that Gentiles must be circumcised and commanded to keep the law of Moses. Acts therefore shows a dispute inside the church between people who confess Jesus. Their previous theological framework has not instantly answered every implication of Gentile inclusion.'},
   {ref:'Acts 15:6-7',title:'The council includes real debate before Peter speaks.',text:'The apostles and elders gather to consider the question, and Luke says there is “much disputing.” “It seemed good to the Holy Ghost, and to us” later in the chapter does not describe a group that skipped discussion. Prayerful discernment can include serious argument, evidence, Scripture, and time.'},
   {ref:'Acts 15:7-9',title:'Peter’s decisive evidence comes from Cornelius: God gave uncircumcised Gentiles the Holy Spirit and cleansed their hearts by faith.',text:'God “which knoweth the hearts” bore witness to the Gentile believers before they had adopted circumcision. The Spirit’s gift was God’s own testimony that they were accepted. Peter therefore refuses to create a distinction God Himself did not make.',cross:[{ref:'Acts 10:44-48',label:'The event Peter appeals to',reason:'The Holy Spirit fell on Cornelius’ uncircumcised household before water baptism, astonishing the Jewish Christian witnesses.'}]},
   {ref:'Acts 15:10',title:'The “yoke” is not Peter calling God’s law bad.',text:'The law is holy within Israel’s covenant story, and Peter himself has lived within it. The unbearable yoke in this debate is the demand that full Torah observance function as the saving burden Gentile disciples must carry. Neither Israel’s ancestors nor the present generation achieved righteousness by flawless law-keeping. The law cannot be turned into the means by which sinners earn salvation.'},
   {ref:'Acts 15:11',title:'Peter’s wording is wonderfully reversed: “we” Jews are saved like “they” Gentiles.',text:'He could have said Gentiles are graciously allowed to be saved like Jews. Instead he puts Jewish believers on the same ground as Gentiles: all depend on the grace of the Lord Jesus. Heritage, circumcision, and law cannot create a superior class of saved people.'},
   {ref:'Acts 15:12',title:'Barnabas and Paul add the evidence of God’s work among uncircumcised Gentiles.',text:'The assembly listens as they recount signs and wonders God did among the Gentiles through them. Experience is not allowed to replace Scripture, but neither is clear fruit from God ignored. James will next show that what God has done agrees with what the prophets said.'},
   {ref:'Acts 15:13-18',title:'James grounds Gentile inclusion in Scripture by quoting Amos 9 about David’s restored tent and the nations called by God’s name.',text:'For James, Cornelius and the Gentile mission are not an embarrassing exception to Israel’s story. They fit the prophetic hope that the restored Davidic rule would reach the nations. The Messiah’s people can therefore include Gentiles as Gentiles because Scripture anticipated nations bearing God’s name.',cross:[{ref:'Amos 9:11-12',label:'James’ prophetic foundation',reason:'Amos connects restoration of David’s fallen house with God’s claim reaching beyond Israel to the nations.'}]},
   {ref:'Acts 15:16-17',title:'James’ quotation follows the ancient Greek form of Amos, which sounds different from many Old Testament translations based on Hebrew.',text:'The Hebrew Masoretic text speaks of possessing “the remnant of Edom,” while the Greek Septuagint has “the rest of mankind” seeking the Lord. The difference reflects very similar-looking Hebrew words behind the ancient textual traditions. Both forms move beyond Israel toward other nations; James uses the Greek form familiar to his Greek-speaking audience to make Gentile inclusion explicit.'},
   {ref:'Acts 15:19',title:'“Trouble not them” does not mean Gentile Christians have no moral obligations.',text:'James means they should not be harassed with circumcision and conversion to full Jewish covenant identity as a condition of salvation. The very next verse gives instructions intended to shape holy life and shared fellowship. Grace removes the false entrance requirement; it does not turn discipleship into moral indifference.'},
   {ref:'Acts 15:20',title:'The four instructions have been understood in several faithful ways.',text:'James tells Gentile believers to abstain from idol pollution, sexual immorality, things strangled, and blood. Many interpreters see echoes of Leviticus 17–18, laws that applied to resident aliens as well as Israelites, making them especially suitable for Jewish-Gentile table fellowship. Others connect them with ancient Noahide expectations for Gentiles, or see a mixture of permanent moral commands and temporary food concessions. Christians still differ over whether the blood/strangled-food instructions remain universally binding in the same way as the prohibition of sexual immorality.'},
   {ref:'Acts 15:20',title:'The four requirements are not four works added back in as conditions for salvation.',text:'The council has already rejected adding circumcision and Torah observance to grace. These instructions address life together after Gentiles have turned to God—especially separation from idolatrous practices, sexual immorality, and behaviors deeply offensive to Jewish believers. They protect holiness and fellowship without becoming a second route to justification.'},
   {ref:'Acts 15:21',title:'“Moses … is read in the synagogues every sabbath” is one of the chapter’s more debated sentences.',text:'A common reading is that Jewish communities everywhere continually hear these commands, so Gentile Christians should respect several especially sensitive practices if Jewish-Gentile fellowship is to remain possible. Others think James means Jewish believers do not need a separate letter explaining Moses, or that Gentile converts can continue learning moral wisdom where Moses is known. The verse gives a reason for the limited instructions; it does not reverse James’ decision and secretly require Gentiles to adopt the whole law later.'},
   {ref:'Acts 15:22-23',title:'The decision is not delivered by Paul alone; Jerusalem sends trusted representatives with the written letter.',text:'Judas Barsabbas and Silas are leading men from the Jerusalem church. Their presence authenticates the message and prevents opponents from claiming Paul invented the outcome. Luke also says the apostles, elders, and “whole church” agreed to send them, showing broad participation in communicating the decision.'},
   {ref:'Acts 15:24',title:'Jerusalem explicitly disowns the teachers who unsettled Gentile believers.',text:'The letter says certain men went out from Jerusalem and troubled the believers, “to whom we gave no such commandment.” In the KJV the verse adds “saying, Ye must be circumcised, and keep the law”; the oldest manuscripts omit that explanatory phrase, though it accurately summarizes the teaching already stated in verses 1 and 5. The textual difference does not change the council’s decision.'},
   {ref:'Acts 15:25-27',title:'The letter honors Barnabas and Paul as men who have risked their lives for Jesus, while also providing independent witnesses.',text:'The Jerusalem church does not treat the Antioch missionaries as suspicious innovators. It calls them beloved and says they have hazarded their lives for the Lord Jesus Christ. Judas and Silas accompany the letter so the written decision can also be confirmed in person.'},
   {ref:'Acts 15:28',title:'“It seemed good to the Holy Ghost, and to us” describes humble cooperation, not a claim that every church meeting is infallible.',text:'The council has listened to testimony, remembered Jesus’ work through Peter, heard missionary evidence, searched the prophets, debated, and reached agreement. They understand that conclusion as Spirit-guided. The verse gives a model of communal discernment under God; it does not provide a blank check for any later majority vote to be called the Holy Spirit’s voice.'},
   {ref:'Acts 15:28-29',title:'“No greater burden than these necessary things” protects Gentile freedom while asking for real restraint.',text:'The believers are not told to earn acceptance. They are asked to abstain from practices tied to idolatry, sexual immorality, and blood in order to live faithfully and preserve fellowship. Christian freedom is therefore not freedom from love of neighbor.'},
   {ref:'Acts 15:30-35',title:'The result in Antioch is encouragement, not the fear produced by the earlier teachers.',text:'The congregation rejoices over the letter’s consolation. Judas and Silas, themselves prophets, encourage and strengthen the believers, and Paul and Barnabas continue teaching. Luke contrasts two kinds of religious speech: one unsettles souls by adding requirements God did not command; the other strengthens believers in grace and truth.'},
   {ref:'Acts 15:36-39',title:'The Paul-Barnabas disagreement is about judgment concerning Mark, not the gospel itself.',text:'Barnabas wants to take John Mark again; Paul considers the earlier withdrawal from Pamphylia sufficient reason not to entrust him with this journey. The disagreement becomes a paroxysmos—a sharp clash. Luke does not tell us that one man received a revelation proving the other sinful. Faithful people can agree completely on the gospel and still make different prudential judgments.'},
   {ref:'Acts 15:39-41',title:'The separation is painful, but it is not the last word on Mark or on Paul’s regard for Barnabas.',text:'Barnabas takes Mark to Cyprus; Paul chooses Silas and travels through Syria and Cilicia. Later Paul can speak respectfully of Barnabas and explicitly call Mark useful for ministry. The New Testament therefore gives us both the reality of a sharp rupture and evidence that failure and conflict need not define relationships forever.',cross:[{ref:'2 Timothy 4:11',label:'Mark’s later restoration',reason:'Near the end of Paul’s life he asks for Mark because “he is profitable to me for the ministry.”'},{ref:'1 Corinthians 9:6',label:'Paul later names Barnabas respectfully',reason:'Paul still speaks of Barnabas as a fellow worker in apostolic ministry.'}]}
  ],
  reflections:['Am I ever tempted to add my preferred religious marker, practice, or background to what God requires for a person to be received in Christ?','When a serious disagreement arises, can I listen to evidence, Scripture, and other believers instead of protecting my first position at all costs?','Is there a John Mark in my life whom I have frozen forever at the point of an earlier failure—or a Barnabas or Paul I need to remember more charitably?'],
  commentary:{voice:'Charles Spurgeon',identity:'English Baptist preacher, 1834–1892',quote:'salvation is all of grace from first to last',plain:'Spurgeon catches the center of Peter’s speech. The Jerusalem question sounds like a debate about circumcision, but underneath it is a question about what saves. Peter does not say Gentiles need a smaller version of Jewish merit. He says Jewish believers themselves stand where Gentiles stand: dependent on the grace of the Lord Jesus.',source:'Grace—The One Way of Salvation — Acts 15:11',url:'https://www.spurgeon.org/sermons/grace-the-one-way-of-salvation'},
  question:{q:'Are the four requirements in Acts 15:20 still binding on Christians today?',short:'Sexual immorality and idolatry are consistently forbidden throughout the New Testament. Christians differ on whether the instructions about blood and strangled meat are permanent universal commands or first-century fellowship requirements for mixed Jewish-Gentile churches.',more:'The council clearly does not present the four items as conditions for getting saved; salvation has just been grounded in the grace of Jesus. The debate is about how already-received Gentile believers should live in holiness and fellowship. One major interpretation sees all four as drawn especially from Leviticus 17–18, where certain commands applied not only to Israelites but also to resident foreigners; on this view the decree gave Gentiles a minimal set of practices that made shared life with Torah-observant Jewish believers possible. Some Christians therefore see the food rules as enduring apostolic commands. Others note Paul’s later teaching about meat, conscience, and food offered to idols and conclude that the blood/strangled provisions addressed a particular Jewish-Gentile fellowship problem, while sexual immorality and idolatry remain universally moral prohibitions. Eastern Orthodox and some other Christian traditions have historically retained stronger concern about consuming blood; many Western Protestant and Catholic readers treat the food provisions as contextual. Acts 15 itself makes the essential point clear even where later application differs: Gentiles are not saved by becoming Jews, and Christian freedom is to be exercised in holiness and loving consideration for fellow believers.'}
 }
});
render();
