// John 4–6 — Living Bookmark cards.
Object.assign(studies,{
 'John 4':{body:''},
 'John 5':{body:''},
 'John 6':{body:''}
});

Object.assign(studyMeta,{
 'John 4':{
  oneLine:'Jesus crosses social and religious barriers to offer living water to a Samaritan woman, reveals Himself as Messiah, teaches worship in spirit and truth, gathers a Samaritan harvest, and then heals a royal official’s son by His word alone.',
  write:[
   {ref:'John 4:10',title:'Jesus is both the Giver and the gift.',text:'The thirsty Man at the well is the One who offers living water.'},
   {ref:'John 4:14',title:'Christ’s water becomes a spring within.',text:'What He gives is not another temporary drink but life rising toward everlasting life.'},
   {ref:'John 4:23',title:'The Father seeks worshippers.',text:'True worship is not trapped on one mountain or in one building; it is in spirit and in truth.'},
   {ref:'John 4:26',title:'Jesus tells this woman plainly that He is Messiah.',text:'“I that speak unto thee am he.”'},
   {ref:'John 4:35',title:'Jesus sees a harvest where the disciples see interruption.',text:'He tells them to lift up their eyes because the fields are already white.'},
   {ref:'John 4:50',title:'The father believes before he sees.',text:'He takes Jesus at His word and starts home.'}
  ],
  underline:{ref:'John 4:14',reason:'Jesus describes the life He gives as an inward, continuing spring that reaches into everlasting life.'},
  notice:[
   {ref:'John 4:4-9',title:'John places Jesus in the middle of a real Jewish-Samaritan hostility and then shows Him crossing it.',text:'Samaritans and Jews shared Israelite roots but had centuries of religious and political conflict, including rival claims about the proper place of worship. The woman is therefore surprised that a Jewish man asks her for a drink. Jesus does not pretend the history is unreal; He simply refuses to let inherited hostility stop mercy.'},
   {ref:'John 4:6',title:'The Gospel that calls Jesus the eternal Word also shows Him genuinely tired and thirsty.',text:'John will not let readers choose between Jesus’ deity and His humanity. The One through whom all things were made sits wearied at Jacob’s well and asks another person for water. The incarnation in John 1:14 is not a costume; the Word truly entered human weakness without ceasing to be who He is.'},
   {ref:'John 4:10-15',title:'“Living water” begins as a deliberate double meaning.',text:'In ordinary speech it could mean fresh, flowing water rather than stagnant water. Jesus uses the woman’s everyday question to lead toward a deeper gift: divine life that becomes an enduring spring within. Later in John, living-water language is explicitly connected with the Holy Spirit.',cross:[{ref:'John 7:37-39',label:'Later explanation',reason:'John later explains Jesus’ living-water language in connection with the Holy Spirit given to believers.'}]},
   {ref:'John 4:16-18',title:'Jesus exposes the truth of her life without turning her into a spectacle.',text:'He knows her relationship history exactly. The text does not tell us how much of that history involved her own choices, abandonment, widowhood, exploitation, or some mixture, so we should not invent a lurid biography. Jesus tells the truth she needs to face, yet He continues the conversation and reveals Himself to her.'},
   {ref:'John 4:19-24',title:'Jesus neither flatters Samaritan theology nor makes location the final answer.',text:'He says plainly that salvation is “of the Jews,” because God’s covenant promises and the Messiah come through Israel. Yet He also announces that the decisive hour is arriving when neither Gerizim nor Jerusalem will define true worship. The Father seeks worship in spirit and truth, centered in the revelation now arriving in Christ.'},
   {ref:'John 4:25-26',title:'One of Jesus’ clearest early self-disclosures comes to a Samaritan woman.',text:'She speaks of the coming Messiah who will explain all things. Jesus answers, “I that speak unto thee am he.” John deliberately gives this moment to someone outside the social and religious center.'},
   {ref:'John 4:28-30',title:'The waterpot is suddenly less important than the news.',text:'John does not explicitly tell us why she leaves it, so we should not turn the detail into a doctrine. But the narrative movement is striking: she came to draw water and leaves hurrying toward the city, saying, “Come, see a man.” Her witness begins before she has every theological answer sorted out.'},
   {ref:'John 4:31-38',title:'Doing the Father’s will is food to Jesus, and people are the harvest.',text:'The disciples return thinking about lunch; Jesus is thinking about mission. He does not despise bodily food—He had been hungry and tired—but obedience to the Father’s work gives Him a deeper urgency. The harvest is already appearing as Samaritans come out toward Him.'},
   {ref:'John 4:39-42',title:'The woman’s testimony gets people started, but they finally believe because they hear Jesus themselves.',text:'The Samaritans first come because she tells what Jesus knew about her. After hearing Him, they say their faith no longer rests only on her report: they know for themselves that He is “the Christ, the Saviour of the world.” Witness points beyond the witness to Christ.'},
   {ref:'John 4:46-54',title:'The royal official is led from sign-dependent urgency toward trust in Jesus’ spoken word.',text:'He comes desperate for his dying son. Jesus challenges the wider demand for signs, then simply says, “Go thy way; thy son liveth.” The man believes the word before receiving confirmation. When he later learns the fever broke at that exact hour, his faith deepens and spreads through his household.'}
  ],
  reflections:['Who do I find easiest to treat as “not my kind of person,” and what does Jesus’ conversation at the well challenge in me?','Can I trust what Christ has said before I have the confirming evidence I wish I could see?'],
  commentary:{voice:'Alexander Maclaren',identity:'Scottish Baptist preacher and expositor, 1826–1910',quote:'The way to increase faith is to exercise faith.',plain:'Maclaren is reflecting on the royal official at the end of the chapter. The man’s first faith is imperfect and urgent, but he acts on Jesus’ word; the experience that follows strengthens what had begun. John repeatedly shows faith growing as people entrust themselves to Christ.',source:'Expositions of Holy Scripture — John 4',url:'https://biblehub.com/commentaries/maclaren/john/4.htm'},
  question:{q:'Why does Jesus say “salvation is of the Jews” if He is breaking down the Jewish-Samaritan barrier?',short:'Because salvation comes through God’s real covenant history with Israel and through the Jewish Messiah; Jesus rejects ethnic hostility without pretending all religious claims are equally true.',more:'The woman asks about the dispute between Mount Gerizim and Jerusalem. Jesus answers in two directions at once. First, He says the Samaritan tradition is mistaken at important points and that God’s saving revelation has come through Israel: “salvation is of the Jews.” Second, He says the hour is arriving when the argument over sacred geography will no longer define true worship. The Messiah fulfills Israel’s story and opens worship of the Father in spirit and truth beyond the old location boundary.'}
 },
 'John 5':{
  oneLine:'Jesus heals a man disabled for thirty-eight years on the Sabbath, then answers the controversy by claiming divine authority to give life and execute judgment and by calling multiple witnesses—including Scripture and Moses—to testify about Him.',
  write:[
   {ref:'John 5:6',title:'Jesus sees the man before the man knows who Jesus is.',text:'Grace initiates the encounter at Bethesda.'},
   {ref:'John 5:8-9',title:'Jesus’ word accomplishes what thirty-eight years had not.',text:'“Rise, take up thy bed, and walk.”'},
   {ref:'John 5:17',title:'Jesus answers the Sabbath charge by speaking of His Father’s work and His own.',text:'His defense immediately raises the question of equality with God.'},
   {ref:'John 5:24',title:'Eternal life is spoken of as a present possession.',text:'The believer has passed from death unto life.'},
   {ref:'John 5:39-40',title:'Bible study can still miss the One the Bible points to.',text:'The Scriptures testify of Christ, yet people can refuse to come to Him for life.'},
   {ref:'John 5:44',title:'Craving human approval can make faith harder.',text:'Jesus exposes the trap of receiving honor from one another instead of seeking God’s honor.'}
  ],
  underline:{ref:'John 5:24',reason:'Jesus says the one who hears and believes has everlasting life now and has passed from death into life.'},
  notice:[
   {ref:'John 5:1-9',title:'The man’s thirty-eight years of disability make the healing unmistakably beyond ordinary recovery.',text:'Jesus does not use the pool, wait for movement in the water, or compete to get the man in first. He simply commands him to rise, carry his bed, and walk. The sign shifts attention away from the pool and onto the authority of Jesus’ word.'},
   {ref:'John 5:3-4',title:'The familiar sentence about an angel stirring the water is a real textual question.',text:'Many later manuscripts include the explanation that an angel periodically troubled the water and the first person entering was healed. The earliest and strongest Greek manuscripts omit all or most of that explanation, which is why many modern Bibles bracket or footnote it. The man’s belief about the water is still clear from verse 7; the disputed wording does not change the chapter’s central point that Jesus heals him without the pool.'},
   {ref:'John 5:14',title:'“Sin no more, lest a worse thing come unto thee” must not be turned into a rule that every illness is punishment for one specific sin.',text:'Jesus does give this particular man a serious warning, so sin and judgment cannot be made harmless. But elsewhere Jesus explicitly rejects the assumption that a person’s suffering proves unusual personal guilt. This verse addresses this man; it does not authorize us to diagnose the hidden cause of somebody else’s disability.',cross:[{ref:'John 9:1-3',label:'Misuse guardrail',reason:'Jesus later rejects the disciples’ attempt to assign a man’s blindness directly to his own sin or his parents’ sin.'}]},
   {ref:'John 5:16-18',title:'The controversy quickly becomes much bigger than carrying a bed on the Sabbath.',text:'Jesus says, “My Father worketh hitherto, and I work.” John then tells us how His opponents understand the claim: Jesus is calling God His Father in a way that makes Himself equal with God. The rest of the chapter does not walk that claim back; it expands it.'},
   {ref:'John 5:19-23',title:'The Son’s unity with the Father is not independence from the Father.',text:'Jesus says the Son does what He sees the Father doing, gives life as the Father gives life, receives judgment from the Father, and is to be honored “even as” the Father is honored. His obedience does not make Him a lesser rival deity; John presents an astonishing unity of action, life, judgment, and honor between Father and Son.'},
   {ref:'John 5:24-29',title:'John holds present spiritual life and future bodily resurrection together.',text:'Verse 24 says the believer has already passed from death to life. Verses 28–29 then look ahead to an hour when all who are in the graves will hear the Son’s voice and come forth. Eternal life begins now, but John does not reduce resurrection to an inward spiritual metaphor.'},
   {ref:'John 5:30-38',title:'Jesus answers the demand for testimony with a whole cluster of witnesses.',text:'He names John the Baptist, His works, and the Father’s testimony. This fits the legal-witness language that runs through John’s Gospel. Jesus is not asking for blind belief detached from testimony; He is exposing the refusal to receive the testimony already given.'},
   {ref:'John 5:39-40',title:'“Search the Scriptures” can be read as either a command or a description, but the rebuke is clear either way.',text:'The Greek form can mean “Search the Scriptures” or “You search the Scriptures.” In context, Jesus is addressing people who already prize Scripture and expect life in it, yet refuse the One to whom it testifies. The problem is not too much Bible study. The problem is reading without coming to Christ.'},
   {ref:'John 5:45-47',title:'Jesus does not set Himself against Moses; He says Moses wrote about Him.',text:'His opponents imagine loyalty to Moses as a reason to reject Jesus. Jesus reverses the accusation: if they truly believed Moses, they would believe Him. John’s Gospel presents Christ not as an enemy of the Old Testament but as the One toward whom its testimony moves.'}
  ],
  reflections:['Is there any way I use religious rules or knowledge to avoid seeing the person and work of Christ in front of me?','Whose approval has enough weight in my life that it could make obedience to God harder?'],
  commentary:{voice:'John Calvin',identity:'Reformation pastor and commentator, 1509–1564',quote:'The Sabbath or rest of God, therefore, is not idleness, but true perfection.',plain:'Calvin is responding to Jesus’ claim that the Father continues His sustaining and life-giving work. The Sabbath was never meant to forbid God’s works of mercy and life. In John 5 the deeper issue is that Jesus places His own healing work alongside the Father’s work and then unfolds His authority to give life and judge.',source:'Commentary on John — John 5',url:'https://biblehub.com/commentaries/calvin/john/5.htm'},
  question:{q:'Does John 5:39 command “Search the Scriptures,” or say “You search the Scriptures”?',short:'The Greek can be read either way. The larger point is the same: Scripture testifies about Jesus, and studying it while refusing to come to Him misses its goal.',more:'The verb form can function as an imperative (“Search”) or an indicative (“You search”). The KJV gives the command form, while many modern translations take it descriptively because Jesus is addressing people already devoted to Scripture study. Nothing important depends on choosing one as though the other were heresy. In both readings, Jesus honors Scripture as testimony and rebukes a way of handling it that stops short of the One it reveals.'}
 },
 'John 6':{
  oneLine:'Jesus feeds five thousand, walks across the sea, refuses to be reduced to a miracle-working bread king, identifies Himself as the Bread of life, gives hard teaching about eating His flesh and drinking His blood, and watches many disciples leave while Peter stays because Jesus has the words of eternal life.',
  write:[
   {ref:'John 6:6',title:'Jesus tests Philip while already knowing what He will do.',text:'The question reveals the disciple’s limits, not a shortage in Christ.'},
   {ref:'John 6:20',title:'Jesus answers fear with His presence.',text:'“It is I; be not afraid.”'},
   {ref:'John 6:27',title:'Do not spend your whole life on bread that perishes.',text:'Jesus redirects the crowd from a full stomach to enduring life.'},
   {ref:'John 6:35',title:'Jesus does not merely give bread; He is the Bread of life.',text:'The deepest hunger in the chapter is answered in Him.'},
   {ref:'John 6:68',title:'Peter stays because there is nowhere better to go.',text:'“Lord, to whom shall we go? thou hast the words of eternal life.”'},
   {ref:'John 6:69',title:'Faith can remain when understanding is stretched.',text:'Peter confesses who Jesus is even after admitting the teaching is hard.'}
  ],
  underline:{ref:'John 6:35',reason:'The sign of multiplied bread points beyond itself to Jesus: “I am the bread of life.”'},
  notice:[
   {ref:'John 6:1-15',title:'The feeding of the five thousand is the one miracle recorded in all four Gospels.',text:'John adds details especially suited to his purpose: Passover is near, Jesus tests Philip, Andrew mentions the boy with barley loaves and fish, and the crowd reacts by wanting to make Jesus king. The sign evokes wilderness provision and messianic expectation, but the crowd is ready to define the Messiah by the kind of bread they want.',cross:[{ref:'Exodus 16:4-15',label:'Wilderness background',reason:'The later Bread-of-life discussion explicitly reaches back to the manna God gave Israel in the wilderness.'}]},
   {ref:'John 6:12-13',title:'Abundance does not make wastefulness holy.',text:'After feeding thousands, Jesus tells the disciples to gather the fragments “that nothing be lost.” The miracle displays extravagant sufficiency, yet Jesus still treats what remains as worth gathering.'},
   {ref:'John 6:14-15',title:'The crowd recognizes a prophet but tries to force Jesus into their preferred kind of kingship.',text:'They connect the sign with “that prophet” and want to take Him by force to make Him king. Jesus withdraws. He is truly King, but He will not receive a crown that bypasses the Father’s hour, the cross, and the kind of kingdom He actually came to establish.',cross:[{ref:'Deuteronomy 18:15',label:'Prophetic expectation',reason:'The crowd’s “that prophet” language recalls Moses’ promise of a prophet like him.'}]},
   {ref:'John 6:16-21',title:'“It is I” can be heard as ordinary identification and as language with a deeper echo.',text:'Jesus comes walking on the sea and says, “It is I; be not afraid.” The Greek is egō eimi, literally “I am.” The phrase can simply mean “It’s me,” so we should not force every use into a direct divine-name claim. Yet in John, and in a scene where Jesus treads the chaotic waters, the wording contributes to the Gospel’s larger presentation of who He is.'},
   {ref:'John 6:26-35',title:'The crowd wants another meal; Jesus keeps moving from gift to Giver.',text:'He tells them they are seeking Him because they ate and were filled, not because they understood the sign. When they ask what work God requires, Jesus answers with faith in the One God sent. When they ask for bread like manna, He finally says, “I am the bread of life.”'},
   {ref:'John 6:37-40',title:'Jesus joins strong assurance with an open invitation.',text:'He says all the Father gives Him will come, He will never cast out the one who comes, and He will lose none of those entrusted to Him but raise them at the last day. The chapter does not present divine initiative and human coming as enemies; Jesus speaks both truths together.'},
   {ref:'John 6:44-45',title:'The Father’s drawing is tied to divine teaching, not human cleverness.',text:'Jesus says no one can come unless the Father draws him, then quotes the prophets: “They shall be all taught of God.” Coming to Christ is not finally produced by superior intelligence or salesmanship; God Himself must work in the learner.',cross:[{ref:'Isaiah 54:13',label:'Prophetic background',reason:'Jesus quotes the promise that God’s people will be taught by the LORD.'}]},
   {ref:'John 6:51-58',title:'Eating Christ’s flesh and drinking His blood has been understood differently across Christian traditions, and the language should not be flattened.',text:'Sacramental traditions hear a strong Eucharistic reference, while many Protestant interpreters emphasize believing participation in Christ and His sacrificial death, especially because the whole discourse repeatedly links coming/believing with receiving life. The passage certainly refuses a shallow, distant admiration of Jesus: life is found only in truly receiving and depending on the crucified Son. Bookmark should state the shared center without pretending the historic sacramental debate does not exist.'},
   {ref:'John 6:60-66',title:'Jesus does not chase departing disciples by making the teaching sound easier than He meant it.',text:'Many who had been called disciples say, “This is an hard saying,” and eventually walk no more with Him. Jesus explains that the Spirit gives life and the flesh profits nothing in itself, yet He does not retract His claim. John is showing a dividing moment: signs can attract a crowd that truth later exposes.'},
   {ref:'John 6:67-71',title:'Peter’s confession is not “I understand everything.”',text:'Jesus asks the Twelve whether they will leave too. Peter answers with relationship and identity: where else could they go, since Jesus has the words of eternal life and is the Holy One of God? John immediately adds the sobering note that Judas remains physically inside the Twelve while already moving toward betrayal.'}
  ],
  reflections:['Am I mainly asking Jesus to keep giving me things, or am I learning to want Him as the Bread of life?','When a teaching of Jesus is difficult for me, can I stay near Him long enough to say with Peter, “to whom shall we go?”'],
  commentary:{voice:'Matthew Henry',identity:'English Presbyterian pastor and commentator, 1662–1714',quote:'it is the only passage of the actions of Christ’s life that is recorded by all the four evangelists',plain:'Henry notices the unusual four-Gospel witness to the feeding of the five thousand. That makes the sign especially important: Jesus meets real hunger, but the event is also the doorway into a much harder lesson about the difference between wanting bread from Christ and receiving Christ Himself as the Bread of life.',source:'Commentary on the Whole Bible — John 6',url:'https://biblehub.com/commentaries/mhcw/john/6.htm'},
  question:{q:'Is John 6 teaching the Lord’s Supper when Jesus says to eat His flesh and drink His blood?',short:'Christians have answered that differently for centuries. The chapter certainly teaches that eternal life requires receiving Christ and His sacrificial life personally; sacramental traditions also see Eucharistic meaning here, while many Protestants read the language primarily as faith in the crucified Son.',more:'Several details matter. The discourse begins before the Lord’s Supper is instituted and repeatedly describes believing, coming, and being raised at the last day. That strongly supports the idea that Jesus is speaking fundamentally about receiving Him by faith. At the same time, His later institution of bread and wine and the church’s long Eucharistic practice explain why many ancient and sacramental readers hear more than a general metaphor. The safest reading for Bookmark is not to make John 6 settle every later sacramental question by itself. The non-negotiable center is that life is not found in admiring Jesus from a distance; it is found in receiving the Son who gives His flesh “for the life of the world.”'}
 }
});
render();