// John 1–3 — Living Bookmark cards.
Object.assign(studies,{
 'John 1':{body:''},
 'John 2':{body:''},
 'John 3':{body:''}
});

Object.assign(studyMeta,{
 'John 1':{
  oneLine:'John opens before creation itself: the eternal Word is with God and is God, becomes flesh and dwells among us, and is identified by John the Baptist and the first disciples as the Lamb, Messiah, Son of God, King of Israel, and Son of man.',
  write:[
   {ref:'John 1:1',title:'Jesus does not begin at Bethlehem.',text:'When creation begins, the Word already is: with God and Himself God.'},
   {ref:'John 1:5',title:'Darkness does not overcome the Light.',text:'John begins the Gospel with conflict already present, but the Light keeps shining.'},
   {ref:'John 1:12',title:'Receiving Christ and believing His name belong together.',text:'Those who receive Him are given the right to become the children of God.'},
   {ref:'John 1:14',title:'The eternal Word truly became flesh.',text:'God did not merely appear human from a distance; the Word entered our human life and dwelt among us.'},
   {ref:'John 1:29',title:'John points away from himself to the Lamb.',text:'Jesus comes as the One who takes away the sin of the world.'},
   {ref:'John 1:46',title:'Philip answers skepticism with an invitation.',text:'When Nathanael doubts Nazareth, Philip does not argue him into the kingdom; he says, “Come and see.”'}
  ],
  underline:{ref:'John 1:14',reason:'John moves from eternity to incarnation in one sentence: the Word who is God became flesh and lived among us.'},
  notice:[
   {ref:'John 1:1-3',title:'John deliberately sounds like Genesis, but he reaches behind Genesis.',text:'Genesis begins with God creating “in the beginning.” John says that when that beginning arrived, the Word already was. The Word is distinguished from God—He is “with God”—yet John also says plainly, “the Word was God.” Then he places all created things on the other side of the line: everything that came into being came through Him.',cross:[{ref:'Genesis 1:1',label:'Creation echo',reason:'John intentionally opens with the same “in the beginning” language while identifying the Word as already present when creation starts.'}]},
   {ref:'John 1:4-9',title:'John the Baptist is a witness to the Light, not the Light itself.',text:'The Gospel is careful to honor John without confusing him with Christ. John is sent by God, but his greatness is the greatness of a witness: he points beyond himself to the true Light. That distinction will matter again when some of John’s disciples begin following Jesus.'},
   {ref:'John 1:10-13',title:'Rejection is real, but it is not the whole story.',text:'The world made through the Word does not recognize Him, and “his own” do not receive Him. Yet John immediately turns to the people who do receive Him. Becoming God’s child is not secured by ancestry, family line, human desire, or another person’s decision; John says this new birth is “of God.”'},
   {ref:'John 1:14',title:'“Dwelt among us” carries tabernacle language.',text:'The verb can carry the sense of pitching a tent or tabernacling. John has just said that the invisible God comes among us in flesh; now he describes the disciples beholding His glory. The old tabernacle was the place of God’s dwelling glory among Israel, and John presents Jesus as the decisive personal dwelling of God among His people.',cross:[{ref:'Exodus 40:34-35',label:'Tabernacle background',reason:'God’s glory filled the tabernacle; John uses dwelling language as he speaks of the glory seen in the incarnate Word.'}]},
   {ref:'John 1:14-18',title:'“Only begotten” speaks of the Son’s unique relationship to the Father.',text:'The KJV’s “only begotten” renders the Greek monogenēs, a word emphasizing the Son as uniquely one-of-a-kind. John is not saying Jesus was created. The whole prologue has already placed the Word before creation and on God’s side of the Creator-creature distinction. The Son uniquely makes the unseen Father known.'},
   {ref:'John 1:19-34',title:'John the Baptist understands his whole ministry as preparation and witness.',text:'He denies being the Christ, Elijah in the simple sense his questioners expect, or “that prophet,” and identifies himself with Isaiah’s wilderness voice. Then the center shifts completely to Jesus: Lamb of God, the One who baptizes with the Holy Ghost, and the Son of God.',cross:[{ref:'Isaiah 40:3',label:'Direct prophetic background',reason:'John applies Isaiah’s wilderness voice to his work of preparing the Lord’s way.'},{ref:'Isaiah 53:7',label:'Lamb connection',reason:'The suffering servant is compared to a lamb led to slaughter, one important Old Testament background for John’s Lamb language.'}]},
   {ref:'John 1:29',title:'“The Lamb of God” gathers more than one Old Testament thread.',text:'Passover lambs, sacrificial worship, Isaiah’s suffering servant, and the larger biblical pattern of substitution all stand nearby. John does not stop here to define one single ritual background. What he makes unmistakable is the direction: Jesus bears away sin, and His saving work reaches beyond one small circle to “the world.”'},
   {ref:'John 1:35-42',title:'The first disciples move from testimony to personal encounter.',text:'John points; two disciples follow; Jesus asks, “What seek ye?” and invites them to “Come and see.” Andrew then brings Simon to Jesus. John’s Gospel repeatedly treats witness this way: one person can point faithfully, but the goal is that the other person encounter Christ Himself.'},
   {ref:'John 1:45-51',title:'Nathanael’s “Nazareth” objection ends with Jacob’s ladder imagery.',text:'Philip identifies Jesus with Moses and the prophets, Nathanael hesitates because of Nazareth, and Jesus reveals knowledge Nathanael cannot explain. The closing promise about angels ascending and descending over the Son of man echoes Jacob’s dream: Jesus Himself is the meeting place between heaven and earth.',cross:[{ref:'Genesis 28:12-17',label:'Jacob’s ladder echo',reason:'Jacob sees heaven and earth joined by the ladder; Jesus places that imagery over the Son of man.'}]}
  ],
  reflections:['When I think about Jesus, do I begin mainly with the manger—or do I remember that John begins with the eternal Word who made all things?','Where might God be asking me simply to point someone toward Jesus rather than trying to win every argument myself?'],
  commentary:{voice:'Alexander Maclaren',identity:'Scottish Baptist preacher and expositor, 1826–1910',quote:'The other Gospels begin with Bethlehem; John begins with ‘the bosom of the Father.’',plain:'Maclaren catches John’s starting point beautifully. Matthew and Luke tell the birth story; John reaches behind the birth, behind Abraham, and behind creation itself so that everything else in the Gospel is read in the light of who Jesus already is.',source:'Expositions of Holy Scripture — John 1',url:'https://biblehub.com/commentaries/maclaren/john/1.htm'},
  question:{q:'Why does John call Jesus “the Word”?',short:'John presents Jesus as God’s eternal self-expression: personally distinct from the Father, fully divine, Creator, source of life and light, and the One who makes the unseen God known.',more:'“Word” translates the Greek logos. John writes in Greek, but his opening is saturated with the Old Testament: God creates by speaking, His word accomplishes His purpose, and divine Wisdom is associated with creation and revelation. John gathers that world of meaning into a person. The Word is not merely something God says; He is “with God,” He “was God,” all things were made through Him, and then “the Word was made flesh.” John 1:18 gives the direction of the whole idea: the Son makes the unseen Father known.'}
 },
 'John 2':{
  oneLine:'At Cana Jesus turns purification water into abundant good wine as the first sign revealing His glory, then in Jerusalem He cleanses the temple and identifies His own body as the true temple that will be raised after death.',
  write:[
   {ref:'John 2:5',title:'Mary leaves the servants with the right instruction.',text:'“Whatsoever he saith unto you, do it.”'},
   {ref:'John 2:11',title:'John calls Cana a sign, not merely a spectacle.',text:'The miracle reveals Jesus’ glory and strengthens the disciples’ faith.'},
   {ref:'John 2:16',title:'Jesus calls the temple “my Father’s house.”',text:'His authority in the temple is tied to His unique relationship with the Father.'},
   {ref:'John 2:19',title:'Jesus points beyond the building to His own body.',text:'His death and resurrection become the sign by which His words are finally understood.'},
   {ref:'John 2:22',title:'Some words of Jesus become clearer after resurrection.',text:'The disciples remember, understand, and believe after He is raised.'},
   {ref:'John 2:24-25',title:'Jesus is never fooled by surface enthusiasm.',text:'He knows what is in man and does not confuse fascination with settled faith.'}
  ],
  underline:{ref:'John 2:11',reason:'John tells us how to read the miracle: it is a sign that manifests Jesus’ glory and calls forth faith.'},
  notice:[
   {ref:'John 2:1-11',title:'John calls Cana the “beginning of signs.”',text:'In this Gospel miracles are regularly called signs because they point beyond themselves to Jesus’ identity and mission. The wonder matters, but John does not want the reader to stop at the wonder. Cana reveals glory and moves the disciples toward faith.'},
   {ref:'John 2:3-5',title:'“Woman” sounds harsher in modern English than it did in this setting.',text:'Jesus is not insulting His mother. He will address her with the same word from the cross while providing for her care. But He does establish a boundary: His messianic “hour” is governed by the Father’s purpose, not even by the claims of His earthly family.',cross:[{ref:'John 19:26-27',label:'Same form of address',reason:'Jesus addresses Mary as “Woman” from the cross while tenderly arranging her care, showing the term itself is not contemptuous.'}]},
   {ref:'John 2:6-10',title:'The six stone jars are specifically connected with Jewish purification.',text:'John could simply have said there were containers of water, but he tells us what they were used for and emphasizes their large capacity. Jesus transforms what fills vessels associated with ceremonial washing into an abundance of excellent wine. The sign fits a Gospel that repeatedly shows old covenant institutions reaching their fulfillment in Christ.'},
   {ref:'John 2:10',title:'This passage celebrates Christ’s provision; it does not celebrate drunkenness.',text:'The master of the feast praises the quality of the wine, and John emphasizes the sign and the glory it reveals. Nothing in the chapter requires treating intoxication as harmless. Elsewhere Scripture explicitly condemns drunkenness; the point here is the abundance and goodness of Jesus’ provision.',cross:[{ref:'Ephesians 5:18',label:'Misuse guardrail',reason:'The New Testament plainly warns against drunkenness, so Cana should not be turned into permission for intoxication.'}]},
   {ref:'John 2:13-17',title:'The temple cleansing is about zeal for the Father’s house, not uncontrolled temper.',text:'Jesus acts deliberately, drives out the commercial traffic, pours out money, overturns tables, and commands the dove sellers to remove their merchandise. The disciples interpret the scene through Psalm 69: zeal for God’s house consumes Him.',cross:[{ref:'Psalm 69:9',label:'Scripture remembered',reason:'The disciples understand Jesus’ temple action through the psalmist’s consuming zeal for God’s house.'}]},
   {ref:'John 2:13-22',title:'John places a temple cleansing near the beginning; the Synoptic Gospels place one near the end.',text:'Faithful interpreters have handled the difference in more than one way. Some understand two cleansings, one early and one during the final week. Others think John has placed the event here for theological reasons while the Synoptics preserve its final-week setting. The texts do not give enough information to force absolute certainty, so Bookmark should not pretend the chronology question is simpler than it is.'},
   {ref:'John 2:18-22',title:'Jesus shifts the temple question from architecture to resurrection.',text:'His opponents ask for a sign proving His authority. Jesus gives a saying they misunderstand as a threat against the building, but John explains that He spoke of the temple of His body. After the resurrection, the disciples remember the saying and understand it. God’s dwelling with His people is now centered in Christ Himself.'},
   {ref:'John 2:23-25',title:'“Believed” can describe a beginning response that Jesus Himself knows is not yet trustworthy.',text:'Many believe in His name because they see signs, yet Jesus does not “commit” Himself to them; the Greek wording plays on the same root. John immediately moves into Nicodemus in chapter 3, a man impressed by signs who still needs to hear about new birth.'}
  ],
  reflections:['Do I sometimes want the gift, the sign, or the answer more than I want the glory of Christ the sign is meant to reveal?','Is there any place where familiarity with religious things has become a substitute for actually knowing and trusting Jesus?'],
  commentary:{voice:'John Calvin',identity:'Reformation pastor and commentator, 1509–1564',quote:'It is a high honor given to marriage, that Christ not only deigned to be present at a nuptial banquet.',plain:'Calvin notices something easy to miss while debating the miracle: Jesus begins His public signs in the middle of an ordinary human wedding celebration. He does not treat embodied life, family joy, or a shared table as beneath Him; His presence there becomes the setting for His glory to be revealed.',source:'Commentary on John — John 2',url:'https://biblehub.com/commentaries/calvin/john/2.htm'},
  question:{q:'Did Jesus cleanse the temple twice, or did John move the same event earlier?',short:'Both are serious Christian readings. John places a cleansing early in Jesus’ ministry, while Matthew, Mark, and Luke place a cleansing in the final week; Scripture does not explicitly tell us whether these are two events or one event arranged differently.',more:'The details overlap enough that many interpreters see the same historical event, with John arranging material thematically to introduce Jesus as the true temple very early. Other interpreters point to differences in wording and setting and understand two separate cleansings, which is historically possible. Because none of the Gospels pauses to explain the relationship, the safest approach is to acknowledge the options. What all four accounts make clear is Jesus’ authority over temple worship; John adds the crucial explanation that His own body is the temple that will be destroyed and raised.'}
 },
 'John 3':{
  oneLine:'Nicodemus learns that religious status cannot replace birth from above by the Spirit; Jesus points to His coming lifting up as God’s saving gift to the world, and John the Baptist gladly steps back because the Bridegroom must increase.',
  write:[
   {ref:'John 3:3',title:'The kingdom is not entered by pedigree.',text:'Jesus tells a respected teacher of Israel that he must be born again—from above.'},
   {ref:'John 3:8',title:'The Spirit is not under human control.',text:'Like the wind, His work is real and recognizable even when we cannot command or map it.'},
   {ref:'John 3:14-15',title:'Jesus says the Son of man must be lifted up.',text:'He connects His saving death to the bronze serpent raised in the wilderness.'},
   {ref:'John 3:16',title:'God’s love gives the Son.',text:'The gift is offered to the world, and whoever believes in Him is promised everlasting life.'},
   {ref:'John 3:21',title:'Coming to the Light exposes what we would rather hide.',text:'Truth does not merely inform us; it brings our works into God’s light.'},
   {ref:'John 3:30',title:'John knows the joy of becoming less visible.',text:'“He must increase, but I must decrease.”'}
  ],
  underline:{ref:'John 3:16',reason:'Jesus’ saving mission is rooted in God’s love and gift: the Son is given so believers will not perish but have everlasting life.'},
  notice:[
   {ref:'John 3:1-2',title:'Nicodemus is not an ignorant outsider.',text:'He is a Pharisee, a ruler of the Jews, and later Jesus calls him “a master of Israel.” He comes respectful and impressed by the signs, but John has just warned that Jesus knows what is in a person. Nicodemus has religion, learning, position, and evidence—and Jesus still tells him he needs new birth.'},
   {ref:'John 3:3-8',title:'“Born again” can also mean “born from above.”',text:'The Greek anōthen can carry both ideas, and John appears to make use of the double meaning. Nicodemus hears it as a second physical birth; Jesus explains a birth produced by the Spirit. The point is not self-improvement or starting over by willpower. Life from God must come from God.'},
   {ref:'John 3:5',title:'“Born of water and of the Spirit” has been understood in several serious Christian ways.',text:'Many interpreters hear Ezekiel 36 behind Jesus’ words: cleansing water and God’s Spirit belong together in the promise of inward renewal, a background Nicodemus as Israel’s teacher should know. Sacramental traditions have also long connected the verse with Christian baptism. Another modern reading takes “water” as natural birth, though that has less obvious Old Testament grounding. Whatever view is taken, Jesus does not teach that an outward ritual by itself can manufacture the new birth.',cross:[{ref:'Ezekiel 36:25-27',label:'New-covenant background',reason:'Ezekiel joins cleansing water, a new heart, and God’s Spirit in one promise of inward renewal.'}]},
   {ref:'John 3:8',title:'Jesus uses one word-picture for wind and Spirit.',text:'The Greek pneuma can mean spirit, wind, or breath depending on context. You hear the wind without controlling its origin or destination; in the same way, the Spirit’s regenerating work is sovereign rather than mechanically produced, yet its effects are real.'},
   {ref:'John 3:10-13',title:'Jesus expects Israel’s teacher to recognize that new-heart, new-Spirit language is already in Scripture.',text:'The new birth is not a strange New Testament idea dropped from nowhere. Israel’s prophets had promised cleansing, a new heart, and the Spirit. Jesus then grounds His authority differently from every earthly teacher: the Son of man speaks of heavenly things because He comes from heaven.'},
   {ref:'John 3:14-15',title:'The bronze serpent is a deliberate picture of looking in faith to the lifted-up Son.',text:'In Numbers, dying Israelites could not cure themselves; God provided a means of rescue and told them to look at the lifted serpent. Jesus says the Son of man “must” likewise be lifted up so that believers may have eternal life. In John, “lifted up” will carry both crucifixion and exaltation.',cross:[{ref:'Numbers 21:4-9',label:'Direct comparison',reason:'Jesus explicitly compares His coming lifting up with Moses raising the bronze serpent for dying Israelites.'}]},
   {ref:'John 3:16-18',title:'John 3:16 belongs inside a paragraph about rescue from perishing and judgment.',text:'God loves the world and gives His only begotten Son; the invitation is genuinely wide—“whosoever believeth.” Verse 17 stresses that the Son is sent to save rather than merely condemn. Verse 18 then makes the dividing line personal: the decisive question is what a person does with the Son God has given.'},
   {ref:'John 3:19-21',title:'Judgment is described as a response to Light.',text:'John does not picture unbelief as a merely intellectual puzzle. Light exposes deeds, and people may resist it because darkness allows them to remain hidden. By contrast, the person who “doeth truth” comes into the light. This is not sinless perfection; it is the opposite of hiding from God.'},
   {ref:'John 3:22-30',title:'John the Baptist refuses to turn ministry into competition.',text:'When his disciples worry that people are going to Jesus, John answers with joy. He is not the Christ; he is the friend of the Bridegroom. The Bridegroom’s voice is the reason for rejoicing, not a threat to John’s importance. “He must increase” is not self-hatred; it is clear-eyed joy that the whole work was always about Christ.'},
   {ref:'John 3:31-36',title:'The chapter ends where it began: earthly status cannot give what only the Son gives.',text:'The One from above speaks the words of God and gives the Spirit without measure. The Father loves the Son and has given all things into His hand. Eternal life is described not merely as a future prize but as a present possession of the one who believes in the Son.'}
  ],
  reflections:['Is there any religious knowledge, family background, or spiritual habit I quietly lean on instead of the new life only God can give?','Could I sincerely rejoice if Christ became more visible while I became less important in somebody else’s story?'],
  commentary:{voice:'John Gill',identity:'English Baptist pastor and commentator, 1697–1771',quote:'he must be “born again”; in distinction from, and opposition to his first birth by nature',plain:'Gill presses the part of Jesus’ answer that would have confronted Nicodemus most sharply: natural birth—even birth into Abraham’s family—cannot produce spiritual life. Whatever privileges Nicodemus already possessed, the life Jesus speaks of has to come from above by the Spirit.',source:'Exposition of the Entire Bible — John 3',url:'https://biblehub.com/commentaries/gill/john/3.htm'},
  question:{q:'Does “born of water and of the Spirit” mean that baptism causes the new birth?',short:'Christians have read the phrase differently. Ezekiel 36 gives a strong Old Testament background of cleansing water joined with God’s Spirit, while sacramental traditions have also connected the verse with baptism; the text does not support treating the outward act as a magic mechanism apart from the Spirit.',more:'Jesus expects Nicodemus, “a master of Israel,” to understand what He is saying, which makes Ezekiel 36:25–27 especially important: God promises clean water, a new heart, and His Spirit. That strongly supports reading “water and Spirit” as one promised work of cleansing and renewal. Early Christian and sacramental traditions also saw baptism in the words, especially because baptism became the church’s ordinary sign of entry into Christ. Those readings need not be made enemies if the central point is preserved: the new birth is God’s work by the Spirit, not something human ancestry, effort, or bare external ritual can produce.'}
 }
});
render();