// Mark 1–8 — Living Bookmark cards.
Object.assign(studies,{
 'Mark 1':{body:''},
 'Mark 2':{body:''},
 'Mark 3':{body:''},
 'Mark 4':{body:''},
 'Mark 5':{body:''},
 'Mark 6':{body:''},
 'Mark 7':{body:''},
 'Mark 8':{body:''}
});

Object.assign(studyMeta,{
 'Mark 1':{
  oneLine:'Mark begins at full speed: John prepares the way, Jesus is baptized and tempted, calls disciples, teaches with authority, confronts demons and disease, and refuses to let popularity control His mission.',
  write:[
   {ref:'Mark 1:1',title:'Mark calls the story “the gospel.”',text:'The good news is not merely an idea; it is bound to the person and work of Jesus Christ, the Son of God.'},
   {ref:'Mark 1:3',title:'John prepares the way for the LORD.',text:'Isaiah’s wilderness road becomes the opening path for Jesus’ arrival.'},
   {ref:'Mark 1:11',title:'The Father names Jesus beloved Son before public ministry begins.',text:'Identity comes before achievement.'},
   {ref:'Mark 1:15',title:'The kingdom is near, so repent and believe.',text:'Jesus’ announcement joins God’s reign with a demanded human response.'},
   {ref:'Mark 1:17',title:'“Follow me” comes before “I will make you.”',text:'Jesus forms disciples after calling them to Himself.'},
   {ref:'Mark 1:35',title:'Jesus seeks solitude to pray even when crowds want Him.',text:'Urgency does not eliminate communion with the Father.'}
  ],
  underline:{ref:'Mark 1:15',reason:'Mark summarizes Jesus’ public message in one line: God’s kingdom has drawn near, so turn and trust the good news.'},
  notice:[
   {ref:'Mark 1:1',title:'Mark opens without a birth story because his Gospel is built around action and proclamation.',text:'Matthew and Luke begin with ancestry and infancy; John reaches back into eternity. Mark plunges directly into the public arrival of the good news. That does not make Jesus less divine—Mark’s opening title already calls Him “the Son of God,” and the rest of the Gospel keeps revealing what that title means.'},
   {ref:'Mark 1:2-3',title:'The quotation blends Malachi and Isaiah even though many manuscripts read “Isaiah the prophet.”',text:'Verse 2 echoes Malachi 3:1 and verse 3 quotes Isaiah 40:3. Ancient writers could name the major or climactic prophet in a composite citation. Later manuscripts sometimes changed the wording to “the prophets,” likely because scribes noticed the mixture. The textual difference is real and does not need to be hidden.',cross:[{ref:'Malachi 3:1',label:'Messenger promise',reason:'The LORD promises a messenger who prepares the way before His coming.'},{ref:'Isaiah 40:3',label:'Wilderness voice',reason:'Isaiah announces a voice preparing the way of the LORD.'}]},
   {ref:'Mark 1:9-11',title:'Jesus’ baptism joins humility, Spirit-anointing, and divine sonship.',text:'Jesus enters the same baptismal waters as repentant Israel without confessing personal sin. The heavens are torn open, the Spirit descends, and the Father speaks. Mark introduces Jesus as the obedient Son who stands with the people He came to save while being uniquely identified by heaven.'},
   {ref:'Mark 1:12-13',title:'Mark’s temptation account is brief but forceful.',text:'The Spirit “driveth” Jesus into the wilderness—a strong verb that fits Mark’s urgency. He is with wild beasts and angels minister to Him. Mark gives less detail than Matthew and Luke, but he still presents Jesus entering the wilderness conflict and emerging ready to announce the kingdom.'},
   {ref:'Mark 1:21-28',title:'Jesus’ authority is recognized by both hearers and unclean spirits.',text:'The crowd notices He does not teach like the scribes, and the demon identifies Him as “the Holy One of God.” Yet Jesus silences the spirit. Mark repeatedly shows that correct supernatural recognition is not the same as faithful discipleship.'},
   {ref:'Mark 1:32-39',title:'Jesus refuses to let demand dictate His mission.',text:'Everyone seeks Him after a night of healings, but Jesus has gone to pray. When the disciples find Him, He moves to other towns because preaching there is part of why He came. Compassion and mission are both present; crowds do not become His master.'},
   {ref:'Mark 1:40-45',title:'Jesus touches the leper and the direction of uncleanness reverses.',text:'Under Levitical purity law, contact with serious skin disease could communicate uncleanness. Here Jesus touches the man and cleansing flows outward from Him instead. The man is then sent to the priest as Moses required, showing that the healing restores both body and communal standing.'}
  ],
  reflections:['Where do I let other people’s urgency crowd out the quiet place where I hear God clearly?','Do I treat following Jesus as mainly changing myself, or as coming to Him and letting Him make me?'],
  commentary:{voice:'Alexander Maclaren',identity:'Scottish Baptist preacher and expositor, 1826–1910',quote:'The gospel is the narrative of the facts of Christ’s life and death.',plain:'Maclaren catches Mark’s opening instinct. Christianity begins with news about what God has done in Jesus, not merely a collection of religious advice.',source:'Expositions of Holy Scripture — Mark 1',url:'https://biblehub.com/commentaries/maclaren/mark/1.htm'},
  question:{q:'Why does Mark 1:2 say Isaiah when part of the quotation comes from Malachi?',short:'Mark combines Malachi 3:1 with Isaiah 40:3 and names Isaiah, the major prophet whose line carries the main emphasis; some later manuscripts changed the phrase to “the prophets.”',more:'Composite quotations were not unusual in ancient writing. Mark’s point is theological: John is the promised messenger and wilderness voice preparing the LORD’s way, and Jesus is the One whose arrival fulfills that expectation. The manuscript variation likely shows later scribes trying to make the attribution feel less difficult.'}
 },
 'Mark 2':{
  oneLine:'Jesus forgives and heals a paralytic, calls Levi, eats with sinners, identifies Himself as bridegroom, and claims authority over Sabbath—turning controversy after controversy into revelation of who He is.',
  write:[
   {ref:'Mark 2:5',title:'Jesus sees the faith expressed in determined action.',text:'The paralytic reaches Him because friends refuse to let the crowd be the final answer.'},
   {ref:'Mark 2:7',title:'The scribes understand the size of Jesus’ claim.',text:'Forgiving sins belongs to God, so the issue is larger than one healing.'},
   {ref:'Mark 2:10',title:'The Son of man has authority on earth to forgive sins.',text:'The visible healing confirms the invisible claim.'},
   {ref:'Mark 2:14',title:'Levi rises from the tax booth and follows.',text:'Jesus’ call reaches people whose old vocation carries public shame.'},
   {ref:'Mark 2:17',title:'Jesus comes as physician for the sick.',text:'Mercy moves toward sinners in order to heal, not to flatter sickness.'},
   {ref:'Mark 2:27',title:'The Sabbath was made for man.',text:'God’s gift is not meant to become a burden that crushes the people it was designed to bless.'},
   {ref:'Mark 2:28',title:'The Son of man is Lord of the Sabbath.',text:'Jesus does not merely offer one legal opinion among many; He claims authority over the institution itself.'}
  ],
  underline:{ref:'Mark 2:10',reason:'The paralytic’s healing is deliberately used as evidence for the deeper claim: Jesus has authority to forgive sins.'},
  notice:[
   {ref:'Mark 2:1-12',title:'The roof scene makes faith visible without turning ingenuity into magic.',text:'First-century Galilean roofs could be accessed from outside and made of beams with packed material that could be opened. The friends’ persistence matters because it gets the man before Jesus; the power remains entirely Christ’s.'},
   {ref:'Mark 2:5-12',title:'The controversy is theological before it is medical.',text:'The scribes do not dispute that the man needs healing. They object because Jesus pronounces forgiveness. Jesus then performs the harder-to-verify physical sign so that they may know He possesses the harder-to-see authority over sin.'},
   {ref:'Mark 2:13-17',title:'Levi’s dinner is not Jesus pretending sin does not matter.',text:'Tax collectors could be associated with Rome’s revenue system and exploitative practices. Jesus calls Levi away from his booth and describes sinners as sick people needing a physician. Table fellowship becomes a place where mercy pursues repentance rather than where wrongdoing is renamed healthy.'},
   {ref:'Mark 2:18-22',title:'Bridegroom language quietly puts Jesus inside Old Testament God-and-bride imagery.',text:'Israel’s prophets often picture the LORD as husband to His people. Jesus identifies Himself as bridegroom whose presence changes the meaning of fasting. The new cloth and wine images say His arrival cannot simply be treated as one more patch within unchanged religious expectations.'},
   {ref:'Mark 2:23-26',title:'The Abiathar phrase is a known interpretive difficulty.',text:'1 Samuel 21 names Ahimelech in the bread episode, while Mark says it occurred “in the days of Abiathar the high priest.” Possible explanations include broader-era reference, family association, or textual/idiomatic nuance. The main argument is clear even if the historical phrasing remains debated: Scripture itself records necessity overriding a narrow use of sacred bread.'},
   {ref:'Mark 2:27-28',title:'Sabbath is both gift and authority claim.',text:'“The sabbath was made for man” protects the day from interpretations that injure people, while “the Son of man is Lord also of the sabbath” places Jesus above the debate. Mercy is not lawlessness; it is obedience under the Lord who gave the Sabbath its purpose.'}
  ],
  reflections:['Whose faith has helped carry me when I could not get myself to Jesus alone?','Where have I treated a gift from God as though its rules mattered more than the person the gift was meant to bless?'],
  commentary:{voice:'Matthew Henry',identity:'English Nonconformist commentator, 1662–1714',quote:'True faith and strong faith may work in various ways.',plain:'Henry notices that the friends’ faith is not abstract. It becomes creative persistence that carries another person to Christ.',source:'Concise Commentary — Mark 2',url:'https://biblehub.com/commentaries/mhc/mark/2.htm'},
  question:{q:'Why does Mark say Abiathar was high priest when 1 Samuel names Ahimelech?',short:'It is a genuine historical-textual difficulty with several plausible explanations, but the wording does not change Jesus’ point about David, necessity, and Sabbath mercy.',more:'Some understand Mark’s phrase as locating the event in the broader Abiathar era, since Abiathar became the better-known priest in David’s story. Others propose scribal, familial, or idiomatic explanations. Bookmark should acknowledge the difficulty rather than pretend there is no question. Jesus’ argument remains: Scripture itself refuses a wooden holiness that ignores human need.'}
 },
 'Mark 3':{
  oneLine:'Jesus heals on Sabbath while grieving hard hearts, appoints the Twelve, is accused of working by Satan, warns against hardened blasphemy, and defines His true family around doing God’s will.',
  write:[
   {ref:'Mark 3:5',title:'Jesus is both angry and grieved.',text:'His anger at hard hearts is joined with sorrow, not detached contempt.'},
   {ref:'Mark 3:14',title:'The Twelve are appointed first “that they should be with him.”',text:'Presence with Jesus comes before being sent out by Jesus.'},
   {ref:'Mark 3:15',title:'Mission includes delegated authority.',text:'The Twelve preach and confront evil because Jesus gives them authority.'},
   {ref:'Mark 3:22',title:'The scribes explain goodness as demonic.',text:'Their accusation is not mere confusion; it morally reverses what Jesus is doing.'},
   {ref:'Mark 3:27',title:'Jesus is binding the strong man.',text:'His exorcisms are signs that a stronger kingdom is invading the enemy’s house.'},
   {ref:'Mark 3:35',title:'Doing God’s will marks Jesus’ family resemblance.',text:'Kingdom kinship reaches beyond biology without despising natural family.'}
  ],
  underline:{ref:'Mark 3:14',reason:'Before the Twelve preach or exercise authority, Mark says Jesus appointed them “that they should be with him.”'},
  notice:[
   {ref:'Mark 3:1-6',title:'The Sabbath conflict is framed around doing good versus doing harm.',text:'Jesus asks whether the holy day permits saving life or killing. His opponents stay silent, then leave to plan His destruction. Mark creates deliberate irony: Jesus restores a hand on Sabbath while His critics use the same day to begin plotting death.'},
   {ref:'Mark 3:5',title:'Jesus’ anger is not emotional sinlessness by numbness.',text:'Mark openly says Jesus looks around “with anger” and is grieved by hardness of heart. The two emotions belong together. Holy anger sees evil clearly; grief keeps the person from becoming merely an object of hatred.'},
   {ref:'Mark 3:13-19',title:'The Twelve symbolically signal the renewal of Israel.',text:'Twelve is not an arbitrary leadership-team size. Against the background of Israel’s twelve tribes, Jesus forms a representative people around Himself, appointing them to be with Him and then to continue His proclamation.'},
   {ref:'Mark 3:20-21',title:'Jesus’ own relatives think He is “beside himself.”',text:'The language is startling and Mark does not protect Jesus from family misunderstanding. Later in the Gospel, natural familiarity repeatedly proves insufficient. Relationship to Jesus must be reshaped around hearing and doing God’s will.'},
   {ref:'Mark 3:22-30',title:'The blasphemy warning belongs to deliberate moral reversal.',text:'The scribes come from Jerusalem, observe liberation from demonic bondage, and attribute the work to Beelzebub. Jesus’ warning is not aimed at an anxious believer frightened by one bad thought; it confronts settled resistance that calls the Spirit’s saving work satanic.'},
   {ref:'Mark 3:27',title:'The strong-man image interprets Jesus’ exorcisms as kingdom warfare.',text:'A robber cannot plunder a strong man’s house without first binding him. Jesus says His works show exactly that kind of superior authority: Satan’s domain is being invaded and captives are being released.'},
   {ref:'Mark 3:31-35',title:'Jesus expands family without mocking family.',text:'His mother and brothers stand outside while disciples sit around Him. Jesus points to the gathered hearers and defines kinship by doing God’s will. The scene is not permission for neglecting relatives; it announces that allegiance to God creates a deeper covenant family around Christ.'}
  ],
  reflections:['Can my anger at what is wrong remain joined to grief for the people involved?','Am I more interested in being sent by Jesus than in first being with Jesus?'],
  commentary:{voice:'Alexander Maclaren',identity:'Scottish Baptist preacher and expositor, 1826–1910',quote:'Obedience to Him is the first and main thing.',plain:'Maclaren sees why Jesus can redefine family around doing God’s will. The deepest bond is shared obedience to the Father revealed in Christ.',source:'Expositions of Holy Scripture — Mark 3',url:'https://biblehub.com/commentaries/maclaren/mark/3.htm'},
  question:{q:'How do I know if I committed blasphemy against the Holy Spirit?',short:'Mark’s warning is directed at people persistently witnessing the Spirit’s liberating work in Jesus and deliberately calling it satanic; fearful concern that you may have accidentally done it is a different posture.',more:'The danger is hardened moral reversal, not one intrusive thought or impulsive sentence. The scribes are not begging for mercy or worried they have gone too far; they are entrenched opponents explaining light as darkness. Anyone wanting to come to Christ for forgiveness should come rather than using the warning to argue themselves away from Him.'}
 },
 'Mark 4':{
  oneLine:'Jesus teaches the kingdom through seed, soils, lamps, hidden growth, and mustard seed, then stills a storm so His disciples must ask who this is whom even wind and sea obey.',
  write:[
   {ref:'Mark 4:9',title:'The parable demands hearing.',text:'Jesus’ repeated call is not “admire the story” but “hear.”'},
   {ref:'Mark 4:14',title:'The sower sows the word.',text:'Different outcomes do not mean the seed itself changes.'},
   {ref:'Mark 4:20',title:'Good soil hears, receives, and bears fruit.',text:'Kingdom hearing moves toward lasting productivity.'},
   {ref:'Mark 4:24',title:'“Take heed what ye hear.”',text:'Attention is morally significant because reception shapes what grows.'},
   {ref:'Mark 4:27',title:'The seed grows while the farmer sleeps and rises.',text:'God’s kingdom has life and power beyond human ability to micromanage.'},
   {ref:'Mark 4:31',title:'The kingdom can begin in something that looks tiny.',text:'Small beginnings are not evidence of small final significance.'},
   {ref:'Mark 4:41',title:'The storm leaves the disciples asking a Christological question.',text:'Their great fear shifts from the sea to the One the sea obeys.'}
  ],
  underline:{ref:'Mark 4:41',reason:'The miracle is meant to create more than relief: “What manner of man is this?” is the question every Mark reader must answer.'},
  notice:[
   {ref:'Mark 4:1-20',title:'The sower parable is really about hearing under pressure.',text:'Path, rocky ground, thorns, and good soil show what happens after the word arrives. Satanic removal, shallow roots, affliction, persecution, worldly cares, riches, and other desires all test whether initial hearing becomes durable fruit.'},
   {ref:'Mark 4:10-12',title:'Parables reveal and judge at the same time.',text:'Jesus cites Isaiah’s hardened-hearing language. The stories are not merely simple illustrations for easy understanding; they disclose the kingdom to receptive hearers while exposing people who keep themselves at a distance from what Jesus is saying.'},
   {ref:'Mark 4:21-25',title:'Lamp and measure sayings link revelation with responsibility.',text:'A lamp is meant to be revealed, and the measure used becomes the measure received. Jesus warns disciples that hearing creates accountability: light is given to be received, practiced, and eventually made visible.'},
   {ref:'Mark 4:26-29',title:'The secretly growing seed is unique to Mark.',text:'The farmer cannot explain or control the inner process of growth; he sleeps and rises while the earth produces. This does not teach human passivity in every ministry decision. It teaches humility: kingdom life ultimately comes from power the worker does not manufacture.'},
   {ref:'Mark 4:30-32',title:'Mustard-seed imagery stresses disproportionate growth rather than botanical trivia.',text:'Jesus speaks proverbially about a tiny familiar seed becoming a remarkably large garden plant. Debates over whether some other seed is microscopically smaller miss the point of the ancient everyday comparison.'},
   {ref:'Mark 4:35-41',title:'The sea-stilling scene echoes Old Testament descriptions of the LORD ruling chaotic waters.',text:'The disciples ask Jesus whether He cares, and He answers by rebuking wind and sea. Israel’s Scriptures portray God as the One who stills storms. Mark places Jesus in that divine-action space while the disciples respond with awe.',cross:[{ref:'Psalm 107:28-29',label:'Storm-stilling background',reason:'The psalm describes the LORD making the storm calm after distressed sailors cry out.'}]},
   {ref:'Mark 4:38',title:'Jesus sleeping does not mean He is indifferent.',text:'The disciples’ accusation “carest thou not?” interprets His apparent inactivity as lack of concern. The rest of the story proves the opposite. Mark allows faithful readers to recognize how easily fear turns silence or delay into a false conclusion about Jesus’ heart.'}
  ],
  reflections:['Which pressure most threatens to choke the word in me: trouble, shallow roots, anxiety, or desire for more?','When Jesus seems quiet in a storm, do I interpret silence as absence of care?'],
  commentary:{voice:'Matthew Henry',identity:'English Nonconformist commentator, 1662–1714',quote:'Of the many that hear the word of the gospel, but few receive it.',plain:'Henry keeps the soils parable focused on reception. Exposure to the word is not the same thing as rooted, fruitful hearing.',source:'Concise Commentary — Mark 4',url:'https://biblehub.com/commentaries/mhc/mark/4.htm'},
  question:{q:'Why did Jesus ask why the disciples were afraid when the storm was genuinely dangerous?',short:'He is not pretending the storm was harmless; He is teaching them to interpret danger in light of who is with them.',more:'The boat really is filling. Their fear is understandable, but it becomes accusatory: “Carest thou not?” Jesus’ authority over the sea reveals that the decisive fact was not the size of the waves but the identity of the One in the boat. Faith does not deny danger; it refuses to let danger define God’s character.'}
 },
 'Mark 5':{
  oneLine:'Jesus liberates a man no one else can restrain, restores a bleeding woman who touches Him in faith, and raises Jairus’s daughter—displaying authority over demons, chronic illness, ritual uncleanness, and death.',
  write:[
   {ref:'Mark 5:4',title:'Human restraints have failed completely.',text:'Chains can restrain a body for a time, but they cannot heal the bondage this man lives under.'},
   {ref:'Mark 5:8',title:'Jesus commands the unclean spirit directly.',text:'The battle is not between equals; the demons plead while Jesus commands.'},
   {ref:'Mark 5:15',title:'The delivered man is sitting, clothed, and in his right mind.',text:'Jesus restores personhood, dignity, and community—not merely symptom relief.'},
   {ref:'Mark 5:19',title:'Jesus sends him home to tell what the Lord has done.',text:'The first commissioned witness in this Gentile region is the man who was once feared.'},
   {ref:'Mark 5:28',title:'The woman reaches for Jesus in desperate faith.',text:'Her faith is not power in itself; it reaches toward the One who can heal.'},
   {ref:'Mark 5:34',title:'Jesus calls her “Daughter.”',text:'The hidden sufferer receives public peace and relational recognition.'},
   {ref:'Mark 5:36',title:'“Be not afraid, only believe.”',text:'Jesus speaks faith into the moment when news of death seems to end every possibility.'}
  ],
  underline:{ref:'Mark 5:15',reason:'Mark’s picture of restoration is wonderfully whole: the man once violent and isolated is sitting, clothed, sane, and near Jesus.'},
  notice:[
   {ref:'Mark 5:1-20',title:'The demoniac story takes place in a largely Gentile environment.',text:'The herd of pigs is one strong clue. Jesus crosses the sea into territory many Jewish readers would associate with uncleanness and danger—tombs, unclean spirits, pigs—and shows authority over all of it.'},
   {ref:'Mark 5:3-5',title:'The man’s self-harm is described as part of his terrible bondage, not moralized as proof of personal worthlessness.',text:'He lives among tombs, cries out, and cuts himself with stones. Mark’s emphasis is misery and enslavement. Jesus moves toward him as a person to be restored, not as an object of disgust.'},
   {ref:'Mark 5:9',title:'“Legion” communicates overwhelming multiplicity and may also carry Roman-military resonance.',text:'A Roman legion numbered thousands, though exact strength varied. The term makes the man’s bondage sound immense. Mark does not require the reader to calculate a literal demon count from military tables; the point is that even overwhelming evil is not beyond Jesus’ command.'},
   {ref:'Mark 5:18-20',title:'Jesus gives this healed man a mission different from many people He tells to be silent.',text:'In Gentile territory the man is told to go home and announce what the Lord has done. The secrecy pattern varies by setting and purpose. Jesus is not inconsistent; He controls how His identity is announced in different contexts.'},
   {ref:'Mark 5:21-43',title:'Mark deliberately interweaves Jairus’s daughter and the bleeding woman.',text:'Both stories involve women, the number twelve, uncleanness, and impossible need. Jairus is publicly prominent while the woman is hidden and socially burdened, yet Jesus gives full attention to both.'},
   {ref:'Mark 5:25-34',title:'The woman’s bleeding likely carried ritual and social consequences beyond physical weakness.',text:'Leviticus treats ongoing discharge as uncleanness, which could complicate ordinary contact and worship. Instead of uncleanness contaminating Jesus, healing flows from Him. He then insists on bringing her out of anonymity and calls her “Daughter.”'},
   {ref:'Mark 5:30-34',title:'Jesus’ question “Who touched my clothes?” is not because He lacks all awareness of what happened.',text:'The disciples point out the obvious crowd pressure, but Jesus draws the woman into personal encounter. The healing is not allowed to remain a secret extraction of power; it becomes a spoken relationship of faith, peace, and restoration.'},
   {ref:'Mark 5:35-43',title:'“Talitha cumi” preserves Jesus’ Aramaic words.',text:'Mark often keeps vivid eyewitness-like details. “Little girl, arise” is tender language in a room full of grief. The same authority that rebuked demons and storm now speaks to death as though waking a child.'}
  ],
  reflections:['Where have I assumed a person or situation is too far gone because every human restraint has failed?','What does Jesus’ insistence on speaking with the healed woman teach me about the difference between receiving help and being personally known?'],
  commentary:{voice:'Matthew Henry',identity:'English Nonconformist commentator, 1662–1714',quote:'The man joyfully proclaimed what great things Jesus had done for him.',plain:'Henry notices that restored life immediately becomes testimony. The man’s past does not disqualify him; it becomes the backdrop for telling others what mercy has done.',source:'Concise Commentary — Mark 5',url:'https://biblehub.com/commentaries/mhc/mark/5.htm'},
  question:{q:'Why did Jesus allow the demons to enter the pigs?',short:'Mark does not explain every reason, but the scene visibly demonstrates the reality and destructiveness of the expelled evil while showing Jesus’ absolute authority over it.',more:'Several interpretations are possible: public proof that the demons truly left, exposure of their destructive nature, judgment symbolism in a Gentile setting, or some combination. We should not invent certainty beyond the text. What Mark makes unmistakable is that the man is worth more than the herd and that the demons act only after receiving permission.'}
 },
 'Mark 6':{
  oneLine:'Jesus is rejected in Nazareth, sends the Twelve in dependence, John the Baptist is murdered by Herod, Jesus feeds five thousand, walks on the sea, and keeps meeting unbelief with patient authority and compassion.',
  write:[
   {ref:'Mark 6:3',title:'Familiarity becomes an excuse for unbelief.',text:'Nazareth knows Jesus’ family and trade but refuses to receive what His works and wisdom mean.'},
   {ref:'Mark 6:7',title:'The Twelve are sent two by two.',text:'Mission is shared, witnessed, and dependent rather than solitary self-display.'},
   {ref:'Mark 6:12',title:'Their message is repentance.',text:'Miracles accompany the mission, but the central human response remains turning to God.'},
   {ref:'Mark 6:20',title:'Herod fears John and still listens to him.',text:'Interest in truth can coexist with unwillingness to obey it.'},
   {ref:'Mark 6:34',title:'Jesus sees sheep without a shepherd.',text:'His response to exhaustion and need is compassion and teaching.'},
   {ref:'Mark 6:41',title:'Jesus gives the bread through the disciples.',text:'His sufficiency does not make their participation unnecessary.'},
   {ref:'Mark 6:50',title:'“It is I; be not afraid.”',text:'Jesus answers fear with His presence before He answers it with explanation.'}
  ],
  underline:{ref:'Mark 6:34',reason:'Mark shows the heart beneath the miracles: Jesus looks at a needy crowd and is moved because they are like sheep without a shepherd.'},
  notice:[
   {ref:'Mark 6:1-6',title:'Nazareth’s unbelief does not mean Jesus loses divine ability like a powerless magician.',text:'Mark says He “could there do no mighty work” except some healings and marvels at their unbelief. The language describes the moral-relational setting of His ministry: He does not perform signs as entertainment for hardened familiarity, though His power remains evident.'},
   {ref:'Mark 6:3',title:'Jesus is called “the carpenter,” a detail unique and striking in Mark’s phrasing.',text:'The Greek term tekton can refer to a craftsman or builder working with wood and possibly stone. The townspeople reduce Him to a familiar trade and family network; the scandal is that ordinary known origins seem incompatible with extraordinary authority.'},
   {ref:'Mark 6:7-13',title:'Travel simplicity trains dependence and keeps mission from looking commercial.',text:'The Twelve carry little, receive hospitality, and move on when rejected. These instructions are specific to this mission and should not be turned into a universal ban on preparation; later Jesus can give different travel directions.'},
   {ref:'Mark 6:14-29',title:'Herod’s relationship to John is morally divided.',text:'He fears John, knows him to be just and holy, listens with perplexity, yet protects his own pride and public oath. The story warns that being fascinated by a preacher can remain spiritually useless if truth never becomes obedience.'},
   {ref:'Mark 6:26',title:'Herod’s oath does not morally bind him to commit murder.',text:'A sinful promise should be broken rather than fulfilled into greater sin. Herod values face-saving before guests more than justice toward John. Scripture never makes “keeping my word” an excuse for carrying out an evil pledge.'},
   {ref:'Mark 6:30-44',title:'Jesus’ desire for rest is real, and so is His compassion when rest is interrupted.',text:'He tells the apostles to come apart and rest because ministry has left no leisure even to eat. When the crowd arrives first, Jesus teaches and feeds them. Mark does not pit self-care against compassion; both needs are honestly present.'},
   {ref:'Mark 6:34',title:'Sheep-without-shepherd language has Old Testament leadership resonance.',text:'Moses asked God to appoint a leader so Israel would not be like sheep without a shepherd, and prophets rebuked failed shepherds. Jesus steps into that leadership vacuum by teaching, feeding, and guiding.',cross:[{ref:'Numbers 27:16-17',label:'Shepherd-leader background',reason:'Moses asks for a leader so the congregation will not be as sheep without a shepherd.'}]},
   {ref:'Mark 6:45-52',title:'The sea-walking scene contains an Exodus-like “passing by” phrase.',text:'Mark says Jesus “would have passed by them.” In Scripture, divine “passing by” can be a self-revelation rather than an attempt to ignore someone, as in God passing before Moses and Elijah. Jesus comes on the sea and speaks “It is I,” revealing His identity amid fear.'},
   {ref:'Mark 6:52',title:'The disciples’ failure to understand the loaves is linked to hard hearts.',text:'Mark is unusually candid about the disciples. They have just participated in miraculous provision, yet the sea miracle astonishes them because they have not grasped what the bread sign revealed about Jesus.'}
  ],
  reflections:['Where has familiarity with Jesus made me less attentive rather than more receptive?','Am I content to listen to truth like Herod while protecting the part of my life truth is asking me to surrender?'],
  commentary:{voice:'Alexander Maclaren',identity:'Scottish Baptist preacher and expositor, 1826–1910',quote:'His heart yearns for ‘His own country,’ and ‘His own kin,’ and ‘His own house.’',plain:'Maclaren notices the patience behind Jesus’ return to Nazareth. Rejection does not make Him emotionally indifferent to the people who know Him best.',source:'Expositions of Holy Scripture — Mark 6',url:'https://biblehub.com/commentaries/maclaren/mark/6.htm'},
  question:{q:'Does Mark 6:5 mean unbelief can make Jesus literally powerless?',short:'No. Mark still says Jesus heals people there; the verse describes a setting in which hardened unbelief limits the kind of mighty public ministry He chooses to perform.',more:'Jesus’ power is not a battery charged by human confidence. Throughout Mark He acts sovereignly even when others misunderstand Him. But signs are relational revelations, not circus performances. Nazareth’s settled offense creates a context where Jesus does not perform the broader mighty works seen elsewhere.'}
 },
 'Mark 7':{
  oneLine:'Jesus confronts traditions that nullify God’s command, teaches that defilement comes from within, grants a Syrophoenician mother’s request, and privately opens a deaf man’s ears and tongue.',
  write:[
   {ref:'Mark 7:6',title:'Lips can honor God while the heart is far away.',text:'Religious correctness cannot repair inward distance.'},
   {ref:'Mark 7:8',title:'Human tradition can displace God’s command.',text:'Tradition is judged by whether it serves Scripture or replaces it.'},
   {ref:'Mark 7:15',title:'Defilement comes from what proceeds out of a person.',text:'Jesus moves the purity problem from external contact to the moral heart.'},
   {ref:'Mark 7:21',title:'Jesus names evil as coming “from within.”',text:'The list refuses the easier story that corruption is only something outside us.'},
   {ref:'Mark 7:28',title:'The Syrophoenician woman answers with humble persistence.',text:'She does not deny Israel’s priority; she appeals to the abundance of mercy.'},
   {ref:'Mark 7:34',title:'“Ephphatha”—be opened.',text:'Jesus meets the deaf man personally and speaks directly into his closed world.'},
   {ref:'Mark 7:37',title:'“He hath done all things well.”',text:'The crowd’s words echo creation-like wonder at restoration.'}
  ],
  underline:{ref:'Mark 7:15',reason:'Jesus relocates the deepest purity problem: what enters the stomach is not what makes a person morally unclean; the heart is the source.'},
  notice:[
   {ref:'Mark 7:1-13',title:'The handwashing dispute is ritual, not modern hygiene.',text:'The Pharisees are not complaining that the disciples skipped soap before lunch. Mark explains a tradition of ceremonial washing associated with purity. Jesus’ objection is not to clean hands but to a religious system that can elevate inherited rules over God’s actual commands.'},
   {ref:'Mark 7:9-13',title:'Corban shows how spiritual language can protect selfishness.',text:'A person could declare resources dedicated to God in a way that blocked their use for needy parents. Jesus says this makes God’s word ineffective through tradition. A religious vow cannot morally cancel the command to honor father and mother.'},
   {ref:'Mark 7:14-23',title:'Mark explicitly points toward the cleansing of foods.',text:'The Greek syntax in verse 19 is commonly understood as an editorial explanation: “thus he declared all foods clean.” The KJV’s wording “purging all meats” is more ambiguous in English, but the wider movement is clear: Jesus shifts purity from food categories to the heart’s moral output.'},
   {ref:'Mark 7:21-23',title:'Jesus’ list includes respectable inward sins beside obvious outward ones.',text:'Covetousness, deceit, envy (“evil eye”), pride, and foolishness stand alongside murder, adultery, and theft. The heart diagnosis does not let socially respectable people imagine they are clean simply because their sins are less publicly shocking.'},
   {ref:'Mark 7:24-30',title:'The Syrophoenician woman is a Gentile outsider who understands Jesus better than many insiders.',text:'Jesus says the children must be fed first, reflecting Israel-first mission order. She accepts the metaphor and asks for a crumb from the abundance. Jesus honors the response by granting the request from a distance.'},
   {ref:'Mark 7:27',title:'The “dogs” image is still a hard saying and should not be softened into something cute.',text:'The diminutive can mean household dogs rather than wild scavengers, but the metaphor still places her outside the children’s first place at the table. The story’s movement matters: she is not finally rejected; her faith receives mercy that anticipates wider Gentile inclusion.'},
   {ref:'Mark 7:31-37',title:'Jesus adapts His manner to a deaf man’s sensory world.',text:'He takes the man aside, touches ears and tongue, looks to heaven, sighs, and says “Ephphatha.” The gestures are not magic. They are embodied communication to someone who cannot hear ordinary speech, making the healing personally intelligible.'},
   {ref:'Mark 7:32-37',title:'The healing echoes Isaiah’s vision of God’s saving future.',text:'Isaiah promised that deaf ears would be unstopped and the mute tongue sing. Mark’s unusual vocabulary for the speech impediment strengthens the connection. Jesus’ healing ministry looks like Isaiah’s promised restoration breaking in.',cross:[{ref:'Isaiah 35:5-6',label:'Restoration background',reason:'Isaiah promises opened ears and a tongue released into praise when God comes to save.'}]}
  ],
  reflections:['What tradition or habit do I assume is “biblical” without checking whether it actually serves God’s command?','Which inward sin am I most tempted to overlook because it does not look scandalous from the outside?'],
  commentary:{voice:'Matthew Henry',identity:'English Nonconformist commentator, 1662–1714',quote:'Our wicked thoughts and affections, words and actions, defile us, and these only.',plain:'Henry follows Jesus’ diagnosis: external rituals cannot solve the pollution that rises from a corrupt heart.',source:'Concise Commentary — Mark 7',url:'https://biblehub.com/commentaries/mhc/mark/7.htm'},
  question:{q:'Did Jesus declare all foods clean in Mark 7?',short:'Mark’s explanation in verse 19 is widely understood to say yes: Jesus’ teaching points beyond food-based purity toward the heart as the true source of moral defilement.',more:'The KJV wording is less explicit because of older translation choices, but the Greek construction is commonly read as Mark’s editorial comment that Jesus was cleansing or declaring clean all foods. The later church still had to work through the implications, as Acts 10 and Acts 15 show. The shift was real even if its communal application unfolded gradually.'}
 },
 'Mark 8':{
  oneLine:'Jesus feeds four thousand, refuses a sign-on-demand, warns about corrupting leaven, heals a blind man in stages, receives Peter’s confession, predicts the cross, rebukes Peter’s resistance, and calls every disciple into cross-shaped following.',
  write:[
   {ref:'Mark 8:2',title:'Jesus says plainly, “I have compassion on the multitude.”',text:'Provision begins in His heart before it appears in bread.'},
   {ref:'Mark 8:12',title:'Jesus sighs deeply over sign-seeking unbelief.',text:'Persistent refusal grieves Him; miracles are not tricks performed on demand.'},
   {ref:'Mark 8:18',title:'The disciples have eyes and ears but still struggle to perceive.',text:'Mark makes their slowness part of the story rather than hiding it.'},
   {ref:'Mark 8:24',title:'The blind man sees partially before he sees clearly.',text:'This unusual two-stage healing becomes a fitting picture beside the disciples’ partial understanding.'},
   {ref:'Mark 8:29',title:'Peter confesses, “Thou art the Christ.”',text:'The title is right, but the next verses show Peter does not yet understand what kind of Christ Jesus is.'},
   {ref:'Mark 8:31',title:'The Son of man “must” suffer, die, and rise.',text:'The cross is not an accident interrupting Messiah’s mission; it belongs to it.'},
   {ref:'Mark 8:34',title:'Discipleship is cross-shaped too.',text:'Self-denial means Jesus—not self-preservation—becomes the organizing center of life.'}
  ],
  underline:{ref:'Mark 8:34',reason:'Mark’s turning point is not complete with “You are the Christ.” The Messiah goes to a cross, and followers must accept the same shape of surrender.'},
  notice:[
   {ref:'Mark 8:1-10',title:'Mark intends the four-thousand feeding as a second event, not a duplicate accidentally retold.',text:'Jesus later mentions both feedings separately and asks the disciples to remember the different basket totals. The second scene unfolds after Gentile-region ministry, supporting the widening provision theme.'},
   {ref:'Mark 8:11-13',title:'Jesus refuses a sign because the demand comes after abundant revelation.',text:'The Pharisees are not honest investigators who have seen nothing. Mark has narrated healings, exorcisms, feedings, and restoration. A demand for one more sign can become a way to postpone response indefinitely.'},
   {ref:'Mark 8:14-21',title:'The disciples’ bread anxiety reveals how little they have absorbed from two feedings.',text:'Jesus asks a barrage of questions—Do you not perceive? Is your heart hardened? Do you not remember? The issue is not intelligence but spiritual perception. They have witnessed abundance and still interpret one loaf as crisis.'},
   {ref:'Mark 8:22-26',title:'The two-stage healing is unique in the Gospels.',text:'Jesus could heal instantly elsewhere, so the gradual process should not be used to imply lack of power. Its placement is striking: the disciples are also moving from blindness toward partial sight, about to confess Jesus rightly while misunderstanding His cross.'},
   {ref:'Mark 8:27-30',title:'Caesarea Philippi provides a charged backdrop for the confession.',text:'The area was associated with pagan sanctuaries and imperial honor. In that setting Peter identifies Jesus as the Christ. Mark’s shorter confession compared with Matthew fits Mark’s narrative economy, not a denial of Jesus’ sonship, which Mark affirms elsewhere.'},
   {ref:'Mark 8:31-33',title:'Peter moves from confession to satanic resistance in a few verses.',text:'He accepts “Messiah” but rejects a suffering Messiah. Jesus calls the mindset satanic because it repeats the temptation to seek kingdom without the cross. Correct titles do not guarantee correct discipleship.'},
   {ref:'Mark 8:34',title:'Taking up the cross was execution language before it became devotional metaphor.',text:'Roman subjects knew the cross as shameful state violence. Jesus is not saying every inconvenience is “my cross.” He calls followers to a loyalty willing to surrender status, security, and life itself rather than deny Him.'},
   {ref:'Mark 8:35-38',title:'Jesus’ value-scale exposes the bad bargain of gaining the world.',text:'Saving life at the cost of Jesus loses what matters most; losing life for Jesus and the gospel saves it. Mark frames discipleship not as heroic self-hatred but as seeing eternal value clearly.'},
   {ref:'Mark 8:38',title:'The rejected suffering Son of man will also come in the Father’s glory.',text:'Cross and glory belong to one identity. Jesus refuses both triumphalism without suffering and suffering without final vindication.'}
  ],
  reflections:['Where have I seen enough of God’s faithfulness to know better than my current panic suggests?','Can I confess Jesus as Christ while still resisting the part of His way that requires self-denial?'],
  commentary:{voice:'Alexander Maclaren',identity:'Scottish Baptist preacher and expositor, 1826–1910',quote:'The law for every disciple is self-denial and taking up his cross.',plain:'Maclaren keeps Peter’s confession and Jesus’ correction together. Recognizing the Messiah means accepting the road the Messiah Himself defines.',source:'Expositions of Holy Scripture — Mark 8',url:'https://biblehub.com/commentaries/maclaren/mark/8.htm'},
  question:{q:'Why did Jesus heal the blind man in two stages?',short:'Mark does not state the reason directly; the placement strongly suggests a living picture of partial sight becoming clear beside the disciples’ slowly developing understanding.',more:'Jesus’ other healings prove He does not need two attempts. Here the man first sees “men as trees, walking,” then clearly. Immediately afterward Peter sees enough to call Jesus the Christ but not enough to accept the cross. The narrative parallel is compelling, though it should be described as literary-theological insight rather than the only possible explanation.'}
 }
});
render();
