// Acts 28 — Living Bookmark card.
Object.assign(studies,{
 'Acts 28':{body:''}
});

Object.assign(studyMeta,{
 'Acts 28':{
  oneLine:'The shipwrecked company discovers that the island is Malta, where the islanders show unusual kindness and Paul survives a viper bite that causes the crowd to swing from expecting his death to calling him a god; Paul heals Publius’ father and many others, then finally reaches Rome, where believers come out to meet him and strengthen his courage; under house arrest Paul explains the hope of Israel to Rome’s Jewish leaders, reasons from Moses and the Prophets concerning Jesus, faces the familiar mixed response, and spends two years receiving everyone who comes to him—preaching God’s kingdom and teaching about Jesus Christ “with all confidence, no man forbidding him.”',
  write:[
   {ref:'Acts 28:2',title:'Kindness appears before anyone on Malta knows Paul’s story.',text:'The islanders meet cold, soaked strangers with fire and hospitality.'},
   {ref:'Acts 28:5',title:'Paul shakes the snake into the fire and keeps serving.',text:'The danger is real, but it does not become the center of his identity or mission.'},
   {ref:'Acts 28:15',title:'Even Paul needs encouragement from other believers.',text:'When he sees the Christians who came to meet him, he thanks God and takes courage.'},
   {ref:'Acts 28:20',title:'Paul calls his chain a chain “for the hope of Israel.”',text:'He still understands Jesus and resurrection as fulfillment of Israel’s hope.'},
   {ref:'Acts 28:23',title:'Paul keeps reasoning from Scripture about Jesus.',text:'Even in custody, he spends the day explaining the kingdom of God from Moses and the Prophets.'},
   {ref:'Acts 28:31',title:'Acts ends with Paul chained and the gospel unhindered.',text:'The messenger is confined, but the message is not.'}
  ],
  underline:{ref:'Acts 28:31',reason:'The final word of Acts is effectively “unhindered”: the story closes not with Paul’s fate but with the continuing freedom of the gospel.'},
  notice:[
   {ref:'Acts 28:1-2',title:'The island is Malta, and Luke remembers the hospitality of people he calls “barbarians” in older English.',text:'The Greek barbaroi simply means non-Greek-speaking people, not uncivilized savages. Luke immediately praises their “no little kindness”: they build a fire for the soaked survivors because of the rain and cold.'},
   {ref:'Acts 28:3-6',title:'The viper episode exposes how quickly people can build theology from circumstances.',text:'When the snake fastens on Paul, the islanders assume Justice has caught a murderer who escaped the sea. When he does not die, they swing to the opposite conclusion and call him a god. Luke presents both judgments as mistaken. Suffering does not prove hidden guilt, and survival does not make a human being divine.'},
   {ref:'Acts 28:3-6',title:'The snake story is not permission to handle venomous snakes as a test of faith.',text:'Paul does not seek out danger, stage a demonstration, or promise immunity to others. He is bitten accidentally while gathering wood and survives. The point is God’s protection in this particular mission, not a ritual Christians are commanded to repeat.'},
   {ref:'Acts 28:7-10',title:'Publius’ title fits what archaeology and inscriptions tell us about Roman Malta.',text:'Luke calls him the “chief man” of the island. Inscriptions from Malta use comparable official language for the island’s leading Roman administrator, which fits Luke’s local terminology. Publius welcomes the travelers for three days before Paul ministers to his sick father.'},
   {ref:'Acts 28:8-9',title:'Paul prays and lays hands on Publius’ father before healing him.',text:'The man suffers from fever and dysentery. After he is healed, other sick people on the island come and are cured. The signs again serve people rather than becoming a performance detached from compassion.'},
   {ref:'Acts 28:10',title:'The islanders respond to the travelers with honor and practical provision.',text:'Luke says they honor the group in many ways and supply what is needed when they sail. The chapter begins with strangers giving warmth and ends the Malta section with those strangers becoming generous friends.'},
   {ref:'Acts 28:11',title:'The ship’s figurehead is “Castor and Pollux,” the twin gods associated with sailors.',text:'The Alexandrian vessel had wintered at Malta and bore the Dioscuri as its sign. Luke mentions the pagan symbol without treating it as the reason the voyage succeeds. The God who promised Paul Rome remains the One directing the story.'},
   {ref:'Acts 28:12-14',title:'The final route runs through Syracuse, Rhegium, and Puteoli before the overland journey to Rome.',text:'At Puteoli the travelers find believers and remain with them seven days. Christianity is already present in Italy before Paul arrives in Rome, reminding us that Acts records only part of the gospel’s wider spread.'},
   {ref:'Acts 28:15',title:'Roman Christians travel a significant distance to meet Paul.',text:'Some reach him at the Forum of Appius and others at Three Taverns along the Appian Way. Their welcome matters enough that Luke records Paul’s emotional response: he thanks God and takes courage. Apostles need encouragement too.'},
   {ref:'Acts 28:16',title:'Paul reaches Rome as promised, but under guard.',text:'He is allowed to live by himself with a soldier guarding him. Jesus’ promise in Acts 23 has been fulfilled without removing chains, hearings, storms, or shipwreck. God’s faithfulness and a difficult route are not opposites.'},
   {ref:'Acts 28:17-20',title:'Paul quickly explains his case to Rome’s Jewish leaders and again rejects an anti-Jewish reading of his mission.',text:'He says he has done nothing against the people or ancestral customs and appealed to Caesar only because he was forced into that legal route, not because he wanted to accuse his nation. He describes his chain as being “for the hope of Israel.”'},
   {ref:'Acts 28:21-22',title:'The Roman Jewish leaders say they have received no official report about Paul, though they know the Christian movement is widely opposed.',text:'Their response creates a fresh hearing rather than importing the Jerusalem mob’s verdict. They want to hear what Paul thinks because this “sect” is spoken against everywhere. Curiosity and opposition coexist at the beginning of the conversation.'},
   {ref:'Acts 28:23',title:'Paul’s final major teaching scene sounds like his ministry throughout Acts.',text:'From morning until evening he explains and testifies about the kingdom of God and tries to persuade them concerning Jesus from the Law of Moses and the Prophets. Luke closes Paul’s public ministry exactly where it began: Scripture, kingdom, Messiah, persuasion.'},
   {ref:'Acts 28:24-28',title:'The response is mixed, and Paul applies Isaiah 6 to persistent unbelief.',text:'Some are persuaded and others do not believe. Paul quotes Isaiah’s language about hearing without understanding and seeing without perceiving. The warning concerns hardened response to God’s message; it should not be weaponized as contempt for Jewish people, especially since Paul himself is Jewish and some of these Jewish hearers believe.',cross:[{ref:'Isaiah 6:9-10',label:'Isaiah’s commission',reason:'The prophetic passage describes a people hearing God’s message while becoming hardened in their refusal to respond.'}]},
   {ref:'Acts 28:28',title:'“The salvation of God is sent unto the Gentiles” continues Acts’ widening mission rather than erasing Israel from God’s story.',text:'Gentile inclusion has been central since Acts 10 and was anticipated in the prophets. Paul’s grief and repeated synagogue-first ministry show that Gentile mission is not rooted in contempt for Jews. The immediate contrast is between rejected proclamation and those who will hear.'},
   {ref:'Acts 28:29',title:'The KJV includes a verse about the Jewish listeners departing and debating; many early manuscripts omit it.',text:'The sentence fits the scene naturally, but several early and important witnesses move directly from verse 28 to verse 30. Modern critical editions therefore often omit verse 29 or place it in a footnote. No central teaching depends on the variant.'},
   {ref:'Acts 28:30',title:'Paul spends two full years in rented quarters receiving everyone who comes.',text:'House arrest limits his movement but not his hospitality. Luke does not tell us in Acts how Paul’s appeal is finally resolved. Instead of satisfying our curiosity about Paul’s later biography, the narrative keeps attention on the continuing mission.'},
   {ref:'Acts 28:31',title:'The last word of the Greek text is akōlytōs—“unhindered.”',text:'Paul is still a prisoner, but he preaches the kingdom of God and teaches about the Lord Jesus Christ with bold openness and without hindrance. Acts ends deliberately open-ended: the gospel has moved from Jerusalem toward the ends of the earth and now sounds freely in the imperial capital.'}
  ],
  reflections:['When circumstances tempt me to make instant judgments about another person, can I resist deciding that suffering proves guilt or success proves divine approval?','Who has come alongside me at the right moment and helped me “take courage,” and am I willing to be that person for someone else?','What would it look like for the gospel to remain “unhindered” in my own life even when my circumstances are limited?'],
  commentary:{voice:'Alexander Maclaren',identity:'Scottish Baptist preacher and expositor, 1826–1910',quote:'“None forbidding him” marks a great step forward.',plain:'Maclaren sees the final phrase as more important than the fact that Paul is still a prisoner. Rome has not silenced the message. Acts closes with a chained apostle and an unchained gospel—the mission has reached the heart of the empire and the word keeps moving.',source:'Expositions of Holy Scripture — Acts 28',url:'https://biblehub.com/commentaries/maclaren/acts/28.htm'},
  question:{q:'Why does Acts end without telling us what happened at Paul’s trial or how Paul died?',short:'Because Luke’s ending is focused less on finishing Paul’s biography than on showing the gospel reaching Rome and continuing “unhindered.” Paul’s personal story remains unfinished on the page, while the mission Jesus announced in Acts 1 has reached the imperial capital.',more:'Acts begins with Jesus telling the apostles that they will be His witnesses in Jerusalem, Judea, Samaria, and to the ends of the earth. By chapter 28 the witness has crossed those boundaries and reached Rome. Luke could have had additional reasons for ending where he does, and scholars debate questions of date and what Luke may have known about Paul’s later life. The text itself, however, gives a powerful literary ending: Paul spends two years receiving everyone who comes, preaching God’s kingdom and teaching about Jesus with boldness “unhindered.” The final emphasis is therefore not “What happened to Paul next?” but “The word has not been stopped.” Acts ends with the mission still open, inviting the reader to understand that the story of witness continues beyond the final page.'}
 }
});
render();
