// Acts 5 — Living Bookmark card.
Object.assign(studies,{
 'Acts 5':{body:''}
});

Object.assign(studyMeta,{
 'Acts 5':{
  oneLine:'Ananias and Sapphira lie about a voluntary gift and die under sudden divine judgment; signs continue through the apostles, the Sadducean leadership imprisons them, an angel sends them back to preach, Peter again insists that God must be obeyed above men, and after Gamaliel’s intervention the beaten apostles leave rejoicing and continue teaching Jesus every day.',
  write:[
   {ref:'Acts 5:4',title:'God did not require Ananias to pretend greater generosity than he had.',text:'The land and the money were his to give; the sin was the lie.'},
   {ref:'Acts 5:20',title:'Freedom from prison sends them back to the assignment.',text:'“Go, stand and speak” is not escape for comfort but release for witness.'},
   {ref:'Acts 5:29',title:'Human authority has a limit when it directly commands disobedience to God.',text:'Peter answers, “We ought to obey God rather than men.”'},
   {ref:'Acts 5:31',title:'The risen Jesus gives what sinners cannot manufacture.',text:'God exalted Him as Prince and Saviour to give repentance and forgiveness.'},
   {ref:'Acts 5:41',title:'They do not rejoice because pain is good.',text:'They rejoice because suffering for the Name cannot make them ashamed of Christ.'},
   {ref:'Acts 5:42',title:'Threats and bruises do not become the final word.',text:'Every day, publicly and from house to house, they keep teaching and preaching Jesus.'}
  ],
  underline:{ref:'Acts 5:29',reason:'The apostles state the governing principle behind their refusal to stop preaching: when human command and God’s command directly collide, God must be obeyed.'},
  notice:[
   {ref:'Acts 5:1-4',title:'Ananias and Sapphira are not condemned for refusing to give all their money.',text:'Peter explicitly says the property was theirs before the sale and the proceeds remained under their control afterward. They could have kept the land, kept the money, or honestly given only part. Their sin is presenting part as though it were the whole in order to gain the appearance of sacrificial generosity.',cross:[{ref:'Acts 4:36-37',label:'The immediate contrast',reason:'Barnabas has just given openly and honestly; Ananias and Sapphira imitate the appearance while hiding the truth.'}]},
   {ref:'Acts 5:3-4',title:'Luke places lying to the Holy Spirit alongside lying to God.',text:'Peter first says Ananias has lied to the Holy Ghost and then says he has not lied merely to men but to God. Christians have historically seen this as significant evidence for the Spirit’s full deity. The passage is not a complete explanation of the Trinity by itself, but its language about the Spirit is unmistakably divine.'},
   {ref:'Acts 5:5-10',title:'The deaths are presented as divine judgment, not as an execution ordered by Peter.',text:'Peter exposes the deception; Ananias falls down and dies. Later Sapphira is questioned separately, confirms the false story, and likewise falls dead. The apostles do not stone them, sentence them to death, or establish a church penalty of killing liars. This is an extraordinary act of judgment by God, not a model for religious violence.'},
   {ref:'Acts 5:7-9',title:'Sapphira is treated as morally responsible for her own answer.',text:'About three hours later she comes in without knowing what happened to her husband. Peter gives her a direct opportunity to tell the truth about the price. She repeats the agreed deception, so the narrative does not portray her as punished merely for being married to Ananias.'},
   {ref:'Acts 5:11',title:'The result is “great fear,” not casual fascination with apostolic power.',text:'The church and everyone hearing about the deaths understand that the holiness of God is not a stage prop. Acts has shown extraordinary generosity and grace; it now shows that deliberate hypocrisy inside the community is also serious.'},
   {ref:'Acts 5:12-14',title:'A strange pair of statements belongs together: outsiders hesitate to attach themselves casually, yet believers keep being added.',text:'Luke says others “durst” not simply join the apostles, while also saying multitudes of men and women were added to the Lord. The best sense is not that evangelism stopped, but that public awe made superficial association costly while genuine faith continued to grow.'},
   {ref:'Acts 5:15-16',title:'Peter’s shadow should not be turned into a magic object.',text:'Luke reports that people laid the sick where they hoped Peter’s passing shadow might fall on them, and then says the sick and tormented were healed. He does not describe Peter teaching that his shadow carried independent power. As throughout Acts, healing belongs to God and serves the witness to Jesus, not a relic technique that believers can reproduce on command.'},
   {ref:'Acts 5:17-18',title:'The same Sadducean leadership that opposed resurrection preaching in Acts 4 arrests the apostles again.',text:'Luke says the high priest and his associates are filled with indignation or jealousy. The conflict is escalating: a warning has failed to silence the movement, the public signs continue, and the apostles are now placed in the common prison.'},
   {ref:'Acts 5:19-20',title:'The angel does not merely say, “You are free”; he gives them somewhere to stand and something to say.',text:'They are told to return to the temple and speak “all the words of this life.” Deliverance therefore serves mission. God opens a door that puts them back in the very public place from which the authorities want their message removed.'},
   {ref:'Acts 5:21-25',title:'Luke lets the irony sit in plain view: the council is fully assembled while its prisoners are already teaching.',text:'The officers report the prison securely shut and the guards standing outside, yet no one is inside. Then news arrives that the men they imprisoned are in the temple teaching the people. Human custody looks impressive until God opens what humans locked.'},
   {ref:'Acts 5:26-28',title:'The apostles do not resist the officers physically, but they still refuse the command to stop witnessing.',text:'The captain brings them without violence because the officers fear the crowd. The apostles go with them to the council; their disobedience is not indiscriminate rebellion. The point of conflict remains specific: the rulers insist on silence about Jesus, while Jesus has commanded witness.'},
   {ref:'Acts 5:28',title:'“Ye have filled Jerusalem with your doctrine” is an unintended progress report on Acts 1:8.',text:'The council complains that the apostles’ teaching has spread through Jerusalem. Luke’s readers can hear the echo of Jesus’ program: witnesses in Jerusalem first, then outward. Opposition itself admits that the first stage is happening.',cross:[{ref:'Acts 1:8',label:'The book-wide commission',reason:'Jesus told the disciples that their Spirit-empowered witness would begin in Jerusalem before moving outward.'}]},
   {ref:'Acts 5:29',title:'“We ought to obey God rather than men” repeats the limit stated in Acts 4, but it is not a slogan for rejecting every authority.',text:'The apostles have been directly commanded by God to bear witness, and an angel has just told them again to speak in the temple. Their answer applies where obedience to a human order would require direct disobedience to God. It should not be stretched into permission for lawlessness whenever a believer dislikes a rule.',cross:[{ref:'Acts 4:19-20',label:'The same conflict already stated',reason:'Peter and John had already told the council that God’s command to witness could not be surrendered to the council’s gag order.'}]},
   {ref:'Acts 5:30',title:'“Whom ye slew and hanged on a tree” confronts this council, not every Jewish person in every generation.',text:'Peter is Jewish, the apostles are Jewish, and the first church is overwhelmingly Jewish. The Roman state carried out crucifixion, while particular leaders and crowds participated in handing Jesus over. This verse must never be used as a warrant for anti-Jewish collective blame. “Tree” also echoes biblical curse language that the New Testament later connects with Christ bearing the curse.',cross:[{ref:'Deuteronomy 21:22-23',label:'Tree and curse background',reason:'A person exposed on a tree was described under the law’s curse, language Paul later applies to Christ in Galatians 3:13.'}]},
   {ref:'Acts 5:31',title:'Repentance and forgiveness are gifts connected with the exalted Jesus.',text:'Peter does not preach a Christ who only exposes guilt. God has exalted Jesus as Prince and Saviour “to give repentance to Israel, and forgiveness of sins.” Even after rejection and repeated opposition, the message being offered to Israel still contains mercy.'},
   {ref:'Acts 5:32',title:'The Spirit being given “to them that obey him” should not be made into a wage earned by good behavior.',text:'In this setting, obedience is the response of yielding to God’s testimony about Jesus rather than resisting it. Acts consistently treats the Holy Spirit as God’s gift. The verse joins faith, allegiance, and obedience; it does not say a person earns the Spirit by accumulating moral merit.'},
   {ref:'Acts 5:33-39',title:'Gamaliel gives cautious political advice, not an inspired formula for proving whether every movement is from God.',text:'Gamaliel is a respected Pharisee and teacher of the law who urges the council not to kill the apostles. He cites failed movements under Theudas and Judas the Galilean and argues that a merely human movement will collapse, while a work truly from God cannot be overthrown. His counsel is wise restraint, but Scripture does not teach that temporary success by itself proves divine approval.'},
   {ref:'Acts 5:36-37',title:'The reference to Theudas has a real historical discussion around it.',text:'Josephus describes a rebel named Theudas under the procurator Fadus in the A.D. 40s, later than this speech, while Gamaliel’s Theudas appears before Judas of Galilee. Interpreters have proposed more than one rebel named Theudas, a chronological problem in one source, or other historical explanations. The names and sequence should be handled honestly rather than pretending the question does not exist.'},
   {ref:'Acts 5:40-41',title:'Rejoicing after a beating does not mean Christians should seek abuse or call pain good.',text:'The apostles are flogged, ordered again not to speak in Jesus’ name, and released. Their joy is that shame imposed for faithfulness to Christ cannot actually separate them from His honor. The suffering is evil treatment; the joy comes from belonging to Jesus within it, not from treating cruelty as desirable.',cross:[{ref:'Matthew 5:11-12',label:'Jesus prepared them for this',reason:'Jesus taught His disciples to rejoice when they were falsely reviled and persecuted for His sake.'}]},
   {ref:'Acts 5:42',title:'Their final answer to the council is not a speech but a daily pattern.',text:'In the temple and from house to house they continue teaching and preaching that Jesus is the Christ. Acts 5 ends with steady repetition: after fear, judgment, prison, interrogation, and beating, the witness continues.'}
  ],
  reflections:['Where am I most tempted to manage how faithful or generous I look instead of simply being truthful before God?','When obedience becomes costly, do I ask only how to escape the cost, or also how to remain faithful through it?','What would quiet, daily faithfulness look like for me if no dramatic deliverance came?'],
  commentary:{voice:'John Calvin',identity:'French Reformer and biblical commentator, 1509–1564',quote:'God doth set men over us in such sort with power, that he keepeth still his own authority safe and sound.',plain:'Calvin reads Peter’s words as a limit, not a rejection, of human authority. Earthly rulers can possess real authority, but never in a way that cancels God’s higher claim. The apostles therefore obey the council wherever they can, but not when the council requires silence where Christ has commanded witness.',source:'Commentary on Acts 5:29',url:'https://biblehub.com/commentaries/calvin/acts/5.htm'},
  question:{q:'Why did Ananias and Sapphira die for lying when other sinners in the church do not die immediately?',short:'Acts presents their deaths as an extraordinary act of divine judgment at a critical early moment in the church, not as the ordinary earthly penalty for lying.',more:'The chapter emphasizes that their gift was voluntary. They were not struck down because they kept part of the money, but because they deliberately staged a false appearance of total generosity and lied in the presence of the Holy Spirit. The sudden deaths teach the young church that God’s holiness cannot be manipulated for religious reputation. Scripture contains other moments where judgment is unusually immediate at a significant beginning, but Acts does not say every lie will receive instant physical death. It also gives no permission for church leaders to threaten, harm, or execute people who lie. Peter exposes the deception; God is the One who judges.'}
 }
});
render();
