Object.assign(studies,{
'Genesis 3':{theme:'Selected places to pause: distorted words, hiding, promised conflict, mercy, and exile.',key:'Genesis 3:1, 9, 15, 21, 24',body:`
<h3>Bookmarks</h3>
<div class="note"><strong>🔖 Genesis 3:1 — “Has God indeed said...?”</strong><p>The serpent begins by handling God's words deceptively. Compare Genesis 2:16–17 with 3:1–5: God's generous permission is pushed to the background while the prohibition is made to dominate the conversation. Spurgeon, preaching from this verse, emphasized the serpent as deceiver and liar. The safest way to read the temptation is with God's actual words still open beside it.</p><p><strong>Follow it:</strong> John 8:44; 2 Corinthians 11:3.</p></div>
<div class="note"><strong>🔖 Genesis 3:9 — “Where are you?”</strong><p>Adam has hidden, yet God addresses him. The question draws the hiding man into the open and begins the reckoning. Watch for God's questions again in Genesis 4:6, 9–10; the pattern repeats with Cain.</p></div>
<div class="note"><strong>🔖 Genesis 3:15 — A promise spoken in the serpent's sentence.</strong><p>The verse announces enduring enmity and a coming blow against the serpent. Christians have long read this as the first glimmer of the gospel. Spurgeon called it the “first gospel sermon” and was struck that the promise appears before the sentences upon the woman and the man. Bookmark should let the later Bible help us see why Christians heard such hope here rather than forcing every later detail into this single verse.</p><p><strong>Follow it:</strong> Romans 16:20; Hebrews 2:14; Revelation 12:9; 20:2.</p></div>
<div class="note"><strong>🔖 Genesis 3:21 — God clothes them.</strong><p>Adam and Eve had already made coverings for themselves in verse 7. Here God makes garments and clothes them. Judgment has not disappeared, but neither has God's care. It is worth simply noticing who provides the covering.</p></div>
<div class="note"><strong>🔖 Genesis 3:24 — The guarded way to the tree of life.</strong><p>The chapter ends east of Eden, with the way back guarded. The tree itself has not vanished from Scripture. Revelation's closing chapters deliberately bring the tree of life back into view, now in the renewed dwelling of God with His people.</p><p><strong>Follow it:</strong> Revelation 2:7; 22:1–5, 14.</p></div>
<h3>Sources beside the open Bible</h3><p class="sources">Primary: Genesis 2–4 and the cross-references above. Historic companions checked: C. H. Spurgeon, “An Antidote to Satan's Devices” (Genesis 3:1), “Christ the Conqueror of Satan” (Genesis 3:15), and “The Serpent's Sentence” (Genesis 3:14–15). The finished bookmarks no longer rely on BibleProject. Pastor Brian material remains excluded pending a verifiable source and permission.</p>`},
'Genesis 4':{theme:'Selected places to pause: worship, anger at the door, brotherhood, blood that speaks, and mercy within judgment.',key:'Genesis 4:3–7, 9–10, 15–16',body:`
<h3>Bookmarks</h3>
<div class="note"><strong>🔖 Genesis 4:3–5 — Two offerings, and the heart behind them.</strong><p>Genesis tells us that both brothers bring offerings, but it does not explicitly say that Cain is rejected merely because his gift is produce. The later Bible gives the clearest interpretive help: Abel offers “by faith,” and John contrasts Cain's evil works with Abel's righteous ones. Notice the order in Genesis itself too: the LORD regards <em>Abel and his offering</em>, but does not regard <em>Cain and his offering</em>. The worshipper and the worship are not separated.</p><p><strong>Follow it:</strong> Hebrews 11:4; 1 John 3:11–12; Jude 11.</p></div>
<div class="note"><strong>🔖 Genesis 4:6–7 — God speaks before Cain strikes.</strong><p>Cain's fallen face is not hidden from God. Before the murder, God questions him and warns him. Sin is pictured as crouching at the door, desiring mastery; Cain is told he must rule over it. This is worth stopping over because the chapter does not present the murder as an unexplained explosion. There is anger, there is warning, and then there is a choice to continue toward violence.</p><p><strong>Follow it:</strong> James 1:14–15. <strong>Remember:</strong> compare God's questions here with Genesis 3:9–13.</p></div>
<div class="note"><strong>🔖 Genesis 4:9 — “Am I my brother's keeper?”</strong><p>God's question names the relationship Cain has violated: “Where is Abel your brother?” Cain answers first with a lie and then with contempt. Spurgeon later preached an entire sermon from this question, pressing the responsibility we bear toward others. Before making the application, however, let the narrative sting on its own: the man who should have loved his brother has killed him and now speaks as though his brother were none of his concern.</p></div>
<div class="note"><strong>🔖 Genesis 4:10 — Blood has a voice.</strong><p>Cain can hide Abel's body from human sight, but not Abel's blood from God. Innocent blood cries from the ground for justice. Hebrews deliberately returns to this scene and says that Jesus' sprinkled blood “speaks better things than that of Abel.” Spurgeon made that contrast central in his 1866 sermon <em>The Blood of Abel and the Blood of Jesus</em>: Abel's blood witnesses to wrong and calls for justice; Christ's blood announces the better word of the new covenant.</p><p><strong>Follow it:</strong> Hebrews 11:4; 12:22–24.</p></div>
<div class="note"><strong>🔖 Genesis 4:15–16 — Judgment, restraint, and another move east.</strong><p>Cain is sentenced to restless wandering, yet God also places him under protection from private vengeance. Mercy does not erase the judgment, and judgment does not mean God has surrendered Cain to immediate human retaliation. Then Cain goes out from the presence of the LORD and settles east of Eden. Genesis 3 ended with humanity driven eastward from the garden; now the movement away continues.</p><p><strong>Look ahead:</strong> Genesis 4:23–24 shows how violence grows when Lamech boasts of vengeance far beyond the limit God set around Cain.</p></div>
<h3>Sources beside the open Bible</h3><p class="sources">Primary: Genesis 4; Hebrews 11:4; Hebrews 12:22–24; 1 John 3:11–12; Jude 11; James 1:14–15. Historic companions checked: Matthew Henry, <em>Commentary on Genesis 4</em>; John Gill, <em>Exposition of Genesis 4</em>; C. H. Spurgeon, “Am I Clear of His Blood?” (Genesis 4:10, 20 July 1862), “The Blood of Abel and the Blood of Jesus” (Genesis 4:10; Hebrews 12:24, 2 September 1866), and “Am I My Brother's Keeper?” (Genesis 4:9, 1878). Interpretive caution preserved: Genesis 4 itself does not state that Cain's produce was intrinsically an unacceptable class of offering, so the bookmark does not make that disputed inference its explanation. Pastor Brian material remains excluded pending a verifiable source, proper citation, and permission.</p>`},
'Genesis 5':{theme:'Selected places to pause: the image carried forward, the repeated sentence of death, Enoch walking with God, and hope for relief from the cursed ground.',key:'Genesis 5:1–3, 5–31',body:`
<h3>Bookmarks</h3>
<div class="note"><strong>🔖 Genesis 5:1–3 — Image, likeness, and a family line.</strong><p>The genealogy deliberately reaches back to creation: God made humanity in His likeness, male and female, and blessed them. Then Adam fathers Seth “in his own likeness, after his image.” The wording links creation and generation without saying that God's image has vanished after the fall. Genesis 9:6 and James 3:9 will still speak of human beings in relation to God's image and likeness.</p><p><strong>Follow it:</strong> Genesis 1:26–28; 9:6; James 3:9.</p></div>
<div class="note"><strong>🔖 Genesis 5:5, 8, 11, 14, 17, 20, 27, 31 — “And he died.”</strong><p>The long lifespans can draw the eye, but the chapter's repeated ending is more important: “and he died.” Adam's sentence in Genesis 3:19 is now heard generation after generation. Even lives measured in centuries do not outrun death. The genealogy is therefore not merely a list of names and ages; its rhythm makes the consequence of the fall audible.</p><p><strong>Remember:</strong> Genesis 2:17; 3:19. <strong>Follow it:</strong> Romans 5:12–14.</p></div>
<div class="note"><strong>🔖 Genesis 5:22–24 — Enoch walked with God.</strong><p>Twice the genealogy breaks its usual wording to tell us that Enoch “walked with God.” Then, instead of the expected “and he died,” we read that he was not, because God took him. Hebrews interprets this explicitly through faith: Enoch was taken so that he did not see death, and before that he had the testimony that he pleased God. Spurgeon devoted his 1876 sermon <em>Enoch</em> to these verses and emphasized that walking with God was not a momentary spiritual experience but the steady tenor of a life.</p><p><strong>Follow it:</strong> Hebrews 11:5–6; Jude 14–15. <strong>Look ahead:</strong> Genesis 6:9 will use the same striking description of Noah.</p></div>
<div class="note"><strong>🔖 Genesis 5:28–29 — A child named in hope.</strong><p>Lamech names his son Noah while longing for comfort from the painful toil of ground the LORD had cursed. The wording intentionally reaches back to Genesis 3:17–19. The verse records Lamech's hope; it is safest not to make it promise more than the text does. Noah will indeed become central to the next great act of judgment and preservation, but Genesis itself will show how the curse, the ground, and human sin continue beyond the flood.</p><p><strong>Follow the thread:</strong> Genesis 6:5–9; 8:20–22; 9:20–21.</p></div>
<h3>Sources beside the open Bible</h3><p class="sources">Primary: Genesis 1:26–28; 3:17–19; Genesis 5; 6:9; 8:20–22; 9:6; Romans 5:12–14; Hebrews 11:5–6; James 3:9; Jude 14–15. Historic companion verified: C. H. Spurgeon, “Enoch” (Genesis 5:21–24; Hebrews 11:5–6; Jude 14–15), Metropolitan Tabernacle Pulpit, Vol. 22, preached 30 July 1876. Spurgeon's treatment was used only to illuminate the biblical description of Enoch's walk; the later New Testament texts remain the controlling cross-references. Interpretive caution preserved around Genesis 5:29: Lamech's naming speech is recorded as hope for comfort, not expanded into an unsupported claim that Noah would finally remove the curse. Pastor Brian material remains excluded pending a verifiable source, proper citation, and permission.</p>`}
});
render(document.querySelector('.tab.active')?.dataset.filter||'all');
