// Acts 12 — Living Bookmark card.
Object.assign(studies,{
 'Acts 12':{body:''}
});

Object.assign(studyMeta,{
 'Acts 12':{
  oneLine:'Herod Agrippa I kills James the brother of John and imprisons Peter, but while the church prays earnestly an angel leads Peter past chains, guards, and an iron gate; the praying believers are astonished when their answer is literally knocking at the door, Peter reports his rescue and withdraws, Herod later accepts divine praise at Caesarea and dies under judgment, and Luke closes the contrast by saying that the word of God keeps growing.',
  write:[
   {ref:'Acts 12:2',title:'Faithfulness does not guarantee the same earthly outcome for every believer.',text:'James is killed; Peter is rescued. Both belong to Christ.'},
   {ref:'Acts 12:5',title:'The church cannot open Peter’s prison, but it can pray.',text:'Luke places earnest prayer directly beside humanly overwhelming security.'},
   {ref:'Acts 12:7',title:'Chains that look final to people are not final to God.',text:'Peter’s chains fall off before he has even fully understood what is happening.'},
   {ref:'Acts 12:11',title:'Peter finally recognizes that the Lord truly delivered him.',text:'The rescue becomes clear only after he is standing free in the street.'},
   {ref:'Acts 12:16',title:'Sometimes the answer to prayer keeps knocking while believers are still arguing about whether it can be real.',text:'Peter remains at the gate until someone finally opens it.'},
   {ref:'Acts 12:24',title:'Herod dies, but the word keeps growing.',text:'Human power has a lifespan; God’s word is not chained to it.'}
  ],
  underline:{ref:'Acts 12:5',reason:'Peter is locked behind soldiers and chains, “but prayer was made without ceasing of the church unto God for him.” Luke makes the contrast impossible to miss.'},
  notice:[
   {ref:'Acts 12:1-2',title:'This Herod is Agrippa I, grandson of Herod the Great.',text:'He ruled Judea under Roman favor and cultivated popularity among his Jewish subjects. Luke’s brief identification as “Herod the king” fits the unusual few-year period when a Herodian again ruled Judea with the title king. He is not Herod Antipas, who killed John the Baptist, nor the later Agrippa before whom Paul will speak.'},
   {ref:'Acts 12:2',title:'James the brother of John becomes the first of the Twelve whose death Acts records.',text:'Herod kills him “with the sword,” probably meaning execution by beheading. James had once told Jesus he could drink His cup, and Jesus said he would. Acts gives no rescue scene for James and no explanation of why Peter will be delivered while James is not.',cross:[{ref:'Mark 10:38-39',label:'Jesus’ earlier words to James and John',reason:'Jesus told the brothers that they would indeed drink the cup associated with His suffering.'}]},
   {ref:'Acts 12:2-5',title:'James’ death and Peter’s rescue must be kept together so prayer is not turned into a formula.',text:'The same faithful God allows one apostle to die and miraculously frees another. Acts does not teach that enough faith guarantees escape from persecution. The church is called to pray earnestly without assuming it can dictate whether God’s faithfulness will take the form of deliverance, endurance, or final homecoming.'},
   {ref:'Acts 12:3-4',title:'Herod’s next arrest is politically calculated.',text:'Luke says Herod sees that James’ death pleases part of the public and therefore arrests Peter too. The days of unleavened bread delay the public action until after the festival, when Jerusalem is crowded and Peter’s fate can become a spectacle.'},
   {ref:'Acts 12:4',title:'The KJV’s “after Easter” translates pascha, the ordinary Greek word for Passover.',text:'The setting is explicitly the Jewish days of unleavened bread, and the intended time is after the Passover festival. “Easter” reflects older English Christian usage for the Paschal season; it should not be read as though Luke were describing a separate later Christian holiday celebrated by Herod.'},
   {ref:'Acts 12:4, 6',title:'Four quaternions means Peter is guarded by four squads of four soldiers.',text:'Roman night duty was divided into watches, with a four-man squad taking each watch. On the night of his intended appearance Peter sleeps between two soldiers, chained to them, while other guards secure the door. Luke piles up the security details so the escape cannot reasonably be credited to lax guarding.'},
   {ref:'Acts 12:5-6',title:'The church is praying intensely while Peter is sleeping.',text:'The word translated “without ceasing” carries the sense of earnest, stretched-out prayer. Peter, meanwhile, sleeps on the night before Herod intends to bring him out. Acts does not tell us whether he expected death or rescue; it simply gives the striking picture of a praying church and a resting prisoner.'},
   {ref:'Acts 12:7-10',title:'Peter’s rescue is so completely God’s initiative that Peter initially thinks he is seeing a vision.',text:'The angel wakes him, chains fall away, doors and guards are passed, and the iron gate opens “of his own accord.” Peter follows instructions but does not engineer the escape. Only after the angel leaves does he come fully to himself and understand that the Lord has delivered him.'},
   {ref:'Acts 12:10',title:'The iron gate opening “of its own accord” uses the Greek word automatos.',text:'It is the source behind the English word “automatic.” Luke is not describing machinery; he means the gate opens without Peter or the angel physically opening it. The small word makes the effortless nature of the divine rescue vivid.'},
   {ref:'Acts 12:11',title:'Peter names the rescue as the Lord’s work, not his own cleverness.',text:'Once he realizes what has happened, he says the Lord sent His angel and delivered him from Herod and from the expected public outcome. Acts consistently directs attention away from apostolic heroics and toward God.'},
   {ref:'Acts 12:12',title:'Mary’s house is already a known gathering place, and John Mark is introduced through this family connection.',text:'Peter knows where believers are gathered for prayer and goes directly there. Mary is identified as the mother of John whose surname is Mark, the man who will soon travel with Barnabas and Saul and later become a significant, sometimes complicated, ministry companion.'},
   {ref:'Acts 12:13-16',title:'Rhoda recognizes Peter correctly while the praying adults dismiss her report.',text:'Overjoyed, she forgets the practical first step of opening the gate and runs to announce that Peter is outside. The others call her mad and then offer another explanation. Luke lets the scene retain its humor: earnest believers can pray sincerely and still be startled when the answer arrives in a form they hardly dare believe.'},
   {ref:'Acts 12:15',title:'“It is his angel” reports what the believers said; it does not by itself establish a doctrine of personal guardian angels.',text:'Some ancient Jews and Christians believed an individual could have an angelic guardian who might appear in that person’s likeness. Others have understood the phrase differently. Luke records the group’s startled explanation without pausing to endorse or correct its angelology. Doctrine should not be built on a panicked guess made before they open the door.'},
   {ref:'Acts 12:17',title:'The James Peter asks them to notify is almost certainly James the brother of Jesus.',text:'James the son of Zebedee has just been killed. By this point Jesus’ brother James has become a leading figure in the Jerusalem church and will appear prominently again in Acts 15 and 21. Peter’s instruction quietly shows the Jerusalem leadership broadening beyond Peter alone.',cross:[{ref:'Galatians 1:18-19',label:'James in Jerusalem',reason:'Paul identifies James the Lord’s brother among the leading figures he met in Jerusalem.'}]},
   {ref:'Acts 12:17',title:'Peter leaves “and went into another place,” but Luke does not tell us where.',text:'Later traditions and guesses have proposed several destinations, but the text stays deliberately unspecific. Peter is not disappearing from Christian ministry—he will appear again in Acts 15—but he prudently removes himself from the immediate reach of Herod’s search.'},
   {ref:'Acts 12:18-19',title:'The guards pay a terrible price for a prisoner God removed from their custody.',text:'Herod examines the guards and orders them executed. Roman military discipline could hold guards personally liable for an escaped prisoner. Luke reports Herod’s action without praising it; the detail exposes the brutality of a ruler whose failed control is answered by killing subordinates.'},
   {ref:'Acts 12:20',title:'Tyre and Sidon need peace with Herod because their food supply depends on his territory.',text:'The Phoenician coastal cities depended heavily on inland grain. Their representatives gain the favor of Blastus, the king’s chamberlain, and seek reconciliation. The scene sets Herod in a position of economic and political leverage just before he accepts praise that belongs to God.'},
   {ref:'Acts 12:21-23',title:'Josephus independently describes Agrippa I’s spectacular public appearance at Caesarea and sudden fatal illness.',text:'Josephus says Agrippa appeared at a festival in shining silver garments, was acclaimed with divine language, failed to reject the flattery, and was struck with severe illness, dying five days later. Luke is briefer and the medical imagery differs, but both sources place his death at Caesarea after he accepts divine honor. Luke interprets the event theologically: he did not give God the glory.'},
   {ref:'Acts 12:23',title:'“Eaten of worms” describes humiliating bodily judgment, not necessarily the exact modern diagnosis.',text:'Ancient descriptions of fatal intestinal or parasitic disease could use worm language, and commentators have proposed medical possibilities. Luke’s point is not to provide a pathology report. The king hailed as a god is shown to be a mortal creature whose body can decay.'},
   {ref:'Acts 12:24',title:'Luke’s final contrast is deliberately simple: the king falls, the word grows.',text:'Herod can kill James, imprison Peter, execute guards, and receive public acclaim, but he cannot halt the gospel. “The word of God grew and multiplied” turns the chapter from royal self-exaltation back to the quiet, unstoppable mission of God.'},
   {ref:'Acts 12:25',title:'Barnabas and Saul return from the relief mission with John Mark, linking Jerusalem, Antioch, and the next missionary stage.',text:'The verse forms a bridge into Acts 13. The church has survived Herod’s attack, famine relief has connected Antioch with Judea, and Mark now joins Barnabas and Saul just before the Spirit sets apart the missionary team.'}
  ],
  reflections:['Can I trust God’s faithfulness even when two faithful people receive painfully different earthly outcomes, as James and Peter did?','When I pray, do I leave room for God to answer in ways I have almost stopped expecting?','Where am I tempted to admire human power, visibility, or applause more than the quiet growth of God’s word?'],
  commentary:{voice:'John Wesley',identity:'English Anglican minister and theologian, 1703–1791',quote:'Peter was sleeping — Easy and void of fear.',plain:'Wesley notices the quietness of Peter on the night before Herod intends to bring him out. Acts does not tell us Peter knew an angel was coming. His rest therefore does not depend on knowing the outcome. James has already died, so Peter has every reason to understand the danger; yet he sleeps in God’s hands.',source:'Explanatory Notes upon the New Testament — Acts 12:6',url:'https://biblehub.com/commentaries/wes/acts/12.htm'},
  question:{q:'Why did God rescue Peter but allow James to be killed?',short:'Acts does not give us a hidden reason. It gives us something harder and more important: both outcomes occur within the life of faithful disciples, so God’s love and a believer’s faithfulness cannot be measured by whether suffering is miraculously removed.',more:'James and Peter are both apostles chosen by Jesus. Nothing in Acts suggests James died because he prayed less, believed less, or mattered less. In the same chapter, Peter is rescued in a spectacular way. Scripture often asks believers to hold together two truths: God can deliver from suffering, and God can remain fully faithful when He does not remove it. Jesus Himself told James and John they would share His cup of suffering. The church is therefore right to pray urgently for Peter without turning Peter’s escape into a guarantee that every faithful prayer ends in earthly rescue. Christian hope is larger than survival. Sometimes God’s faithfulness is seen in deliverance from death; sometimes in grace to remain faithful through death and in the promise of resurrection beyond it.'}
 }
});
render();
