// Acts 27 — Living Bookmark card.
Object.assign(studies,{
 'Acts 27':{body:''}
});

Object.assign(studyMeta,{
 'Acts 27':{
  oneLine:'Paul is sent by sea toward Rome under the centurion Julius, and after a difficult voyage his warning against leaving Fair Havens is ignored; a violent northeaster drives the ship for two weeks until nearly all hope is lost, but an angel assures Paul that he must stand before Caesar and that God has granted the lives of everyone sailing with him; Paul then becomes the calmest voice aboard, urging courage, insisting the sailors remain with the ship, encouraging everyone to eat, and trusting God’s promise until the vessel breaks apart on the shore and all 276 people reach land alive.',
  write:[
   {ref:'Acts 27:11',title:'Expert opinion can still be wrong.',text:'The centurion trusts the pilot and shipowner over Paul, and the safer-looking plan becomes the dangerous one.'},
   {ref:'Acts 27:20',title:'There are storms long enough to erase every visible reason for hope.',text:'For many days they cannot see sun or stars, and Luke says all hope of survival disappears.'},
   {ref:'Acts 27:23',title:'Paul knows both whose he is and whom he serves.',text:'His courage begins with belonging to God before it becomes leadership in the storm.'},
   {ref:'Acts 27:25',title:'Faith rests on God’s trustworthiness.',text:'“I believe God” does not deny the storm; it trusts what God has said inside it.'},
   {ref:'Acts 27:31',title:'God’s promise does not make wise action unnecessary.',text:'The promised rescue still includes the sailors remaining aboard and doing their part.'},
   {ref:'Acts 27:44',title:'The ship is lost, but every life is preserved.',text:'God fulfills the promise even though the form of rescue is broken planks and pieces of wreckage.'}
  ],
  underline:{ref:'Acts 27:25',reason:'Paul’s confidence is beautifully simple: circumstances are terrifying, but God has spoken, and Paul believes He will prove trustworthy.'},
  notice:[
   {ref:'Acts 27:1-3',title:'Paul travels as a prisoner, but Julius treats him with unusual kindness.',text:'The centurion permits Paul to visit friends at Sidon and receive care. Aristarchus of Thessalonica also travels with the group, and Luke’s “we” language shows the narrator is aboard. Paul is confined, but he is not abandoned.'},
   {ref:'Acts 27:4-8',title:'The detailed route reflects difficult Mediterranean sailing, not random place-name clutter.',text:'Contrary winds force the ship to use the lee of Cyprus and Crete before reaching Fair Havens. At Myra they transfer to an Alexandrian ship bound for Italy—likely part of the important grain traffic carrying Egyptian wheat toward Rome.'},
   {ref:'Acts 27:9',title:'“The fast was now already past” most naturally refers to the Jewish Day of Atonement.',text:'That annual fast fell in early autumn. Luke uses it as a seasonal marker: the voyage has reached the part of the year when Mediterranean navigation becomes increasingly dangerous. It helps explain Paul’s concern without requiring a precise modern calendar date for the journey.'},
   {ref:'Acts 27:9-12',title:'Paul’s first warning sounds like experienced judgment rather than the later angelic promise.',text:'He predicts serious loss including lives, while the later message from God specifically promises that no life will be lost. Paul had already endured multiple shipwrecks and knew sea travel. The difference suggests his first counsel was a wise human assessment; the later assurance is explicit revelation that changes what he can promise.'},
   {ref:'Acts 27:11-12',title:'The majority chooses the more desirable harbor over the more cautious plan.',text:'Fair Havens is inconvenient for wintering, so the pilot, owner, centurion, and majority favor trying to reach Phoenix. The decision is understandable rather than cartoonishly foolish—and that makes the lesson sharper: a plan can be reasonable by ordinary calculation and still prove disastrous.'},
   {ref:'Acts 27:14-17',title:'The KJV’s “Euroclydon” is the violent northeaster that takes control of the voyage.',text:'Ancient manuscripts preserve slightly different forms of the storm name, commonly represented today as Euraquilo or “Northeaster.” The crew can no longer hold the ship into the wind. They secure the small boat, use cables or ropes to undergird the hull, and fear being driven onto the Syrtis shallows off North Africa.'},
   {ref:'Acts 27:18-20',title:'The crew progressively throws away what once seemed necessary.',text:'Cargo goes overboard, then ship’s tackle or equipment. With neither sun nor stars visible for many days, ancient navigation becomes extremely difficult. Luke’s line that “all hope that we should be saved was then taken away” lets the despair remain real before the promise arrives.'},
   {ref:'Acts 27:21-26',title:'Paul’s “you should have listened” is followed by encouragement, not gloating.',text:'He acknowledges that staying in Crete would have avoided the loss, but he does not spend the crisis proving he was right. He immediately urges courage and reports the angelic message: he must stand before Caesar, and God has graciously given him all those sailing with him.'},
   {ref:'Acts 27:23-25',title:'Paul’s steadiness comes from belonging to God before it comes from understanding the weather.',text:'“Whose I am, and whom I serve” gives the foundation of his confidence. He cannot control the storm or even name the island ahead, but he can say, “I believe God, that it shall be even as it was told me.” Faith here is trust in God’s word amid unresolved danger.'},
   {ref:'Acts 27:24',title:'“God hath given thee all them that sail with thee” suggests Paul has been praying for more than himself.',text:'The wording presents the lives of the whole company as a gracious gift connected with Paul. The text does not explain every detail of that granting, but Paul’s concern throughout the chapter is plainly communal: he wants the crew, soldiers, prisoners, and passengers to survive together.'},
   {ref:'Acts 27:27-29',title:'The “Adria” of Acts is broader than the modern Adriatic Sea.',text:'Ancient writers could use the name for a much larger area of the central Mediterranean between Greece, Italy, Sicily, and North Africa. The sailors sense land approaching, take soundings that grow shallower, and drop four anchors from the stern while praying for daylight.'},
   {ref:'Acts 27:30-32',title:'The sailors’ attempted escape shows how God’s promise works together with human means.',text:'Some sailors lower the boat under the pretense of setting anchors. Paul tells the centurion that unless they remain in the ship, “ye cannot be saved,” and the soldiers cut the boat loose. There is no contradiction between divine assurance and necessary action: the promised outcome includes the means by which God preserves them.'},
   {ref:'Acts 27:33-38',title:'Paul turns from prophet to practical caregiver and gets 276 exhausted people to eat.',text:'He urges them to take food because their survival will require strength, assures them that not a hair will perish, gives thanks to God before everyone, and begins eating. The others take courage and eat too. Spiritual leadership in the storm includes ordinary bodily needs.'},
   {ref:'Acts 27:35',title:'Paul’s breaking bread and giving thanks resembles Christian meal language, but the scene is not clearly a church communion service.',text:'The verbs naturally echo Jesus’ table actions and early Christian meals, yet the participants include sailors, soldiers, and prisoners in an emergency voyage. The safest reading is that Paul publicly gives thanks to God over an ordinary meal without requiring the passage to be a formal Eucharist.'},
   {ref:'Acts 27:37',title:'Luke records 276 people aboard.',text:'That large number fits an Alexandrian grain ship capable of carrying substantial cargo and passengers. Ancient manuscripts contain a numerical variant here, but 276 has strong support and is the reading familiar in most modern editions.'},
   {ref:'Acts 27:39-41',title:'The final approach succeeds and fails at the same time.',text:'The sailors spot a bay with a beach and aim for it, but the ship strikes a shoal or sandbar and becomes stuck while the stern is broken by the surf. God’s promise never included saving the vessel; the ship can be destroyed while every promised life is preserved.'},
   {ref:'Acts 27:42-43',title:'The soldiers plan to kill the prisoners, and Julius stops them because he wants to save Paul.',text:'Roman guards could face severe consequences if prisoners escaped, so killing them prevents escape during the wreck. The centurion’s intervention preserves Paul and, with him, the other prisoners. Once again God’s promised destination is advanced through a human official’s decision.'},
   {ref:'Acts 27:44',title:'Everyone reaches land, but not everyone reaches it the same way.',text:'Some swim; others cling to boards or broken pieces of the ship. Luke’s final sentence deliberately closes the storm narrative with complete fulfillment: “so it came to pass, that they escaped all safe to land.” The rescue is certain, but its means are wonderfully ordinary and messy.'}
  ],
  reflections:['When circumstances erase every visible reason for hope, what does it mean for me to say, with Paul, “I believe God”?','Am I tempted to use God’s promises as an excuse for passivity, or can I trust Him while still taking the wise actions placed in front of me?','When I discover that my earlier advice was right, do I use that moment to gloat—or to help the people who did not listen?'],
  commentary:{voice:'Matthew Henry',identity:'English Presbyterian minister and Bible commentator, 1662–1714',quote:'Paul knows not where he is himself, yet God’s angel knows where to find him out.',plain:'Henry catches one of the loveliest truths in the storm. Paul cannot navigate by sun or stars and does not yet know where the ship will land, but he is not lost to God. Divine care is not limited by Paul’s ability to locate himself or control the route.',source:'Matthew Henry’s Commentary on Acts 27',url:'https://biblehub.com/commentaries/mhcw/acts/27.htm'},
  question:{q:'If God promised everyone aboard would survive, why did Paul later say the sailors had to stay in the ship to be saved?',short:'Because God’s promise includes the means of fulfillment. The guaranteed outcome does not make human action pointless; the sailors’ skill and presence are part of how God brings the promised rescue about.',more:'The angel tells Paul that he must stand before Caesar and that God has granted him everyone sailing with him. Later, when sailors try to escape in the small boat, Paul warns the centurion, “Except these abide in the ship, ye cannot be saved.” Acts places both statements in the same story without embarrassment. That makes the chapter a vivid picture of providence: God’s certainty and responsible action are not rivals. Paul believes the promise strongly enough to encourage everyone, and he also acts strongly enough to stop a dangerous escape attempt, urge people to eat, and direct attention to what survival requires. Different Christian traditions explain the relation between divine sovereignty and human means in different ways, but Acts 27 itself refuses to choose between trust and action.'}
 }
});
render();
