// John 7 — Living Bookmark card.
Object.assign(studies,{
 'John 7':{body:''}
});

Object.assign(studyMeta,{
 'John 7':{
  oneLine:'At the Feast of Tabernacles Jesus refuses pressure from His unbelieving brothers, teaches publicly in the temple, exposes shallow judgment, and on the feast’s climactic day cries out that the thirsty should come to Him and receive the Spirit as living water.',
  write:[
   {ref:'John 7:5',title:'Even Jesus’ brothers did not yet believe in Him.',text:'Familiarity with Jesus did not automatically become faith.'},
   {ref:'John 7:17',title:'Willingness to obey matters to spiritual understanding.',text:'Jesus says the person willing to do God’s will can recognize whether His teaching is from God.'},
   {ref:'John 7:24',title:'Do not judge by appearance alone.',text:'Jesus calls for righteous judgment rather than quick conclusions from the surface.'},
   {ref:'John 7:37',title:'Jesus makes Himself the place thirsty people must come.',text:'“If any man thirst, let him come unto me, and drink.”'},
   {ref:'John 7:38',title:'Life received from Christ does not stay stagnant.',text:'Jesus pictures living water flowing outward from the believer.'},
   {ref:'John 7:39',title:'John tells us what the living water points to.',text:'He is speaking of the Holy Spirit who would be given to believers after Jesus was glorified.'}
  ],
  underline:{ref:'John 7:37-38',reason:'At the feast Jesus stands and cries out publicly that spiritual thirst is answered by coming to Him and believing in Him.'},
  notice:[
   {ref:'John 7:1-9',title:'Jesus will not let even family pressure set His timetable.',text:'His brothers urge Him to make a public display in Judea, and John plainly says they do not yet believe in Him. Jesus refuses to let their expectations determine His “time.” Later in the chapter He does go to the feast, but quietly at first and on His own terms. His mission moves according to the Father’s purpose, not pressure to prove Himself.'},
   {ref:'John 7:10-13',title:'The crowd is already divided over Jesus, but fear shapes what people are willing to say aloud.',text:'Some call Him good; others accuse Him of deceiving the people. John notes that people speak cautiously because of fear of the Jewish authorities. In this Gospel, “the Jews” often refers to particular Judean leaders or opponents in context rather than every Jewish person; Jesus, His disciples, His family, and the crowd here are themselves Jewish.'},
   {ref:'John 7:14-18',title:'Jesus answers the question of where His teaching came from by pointing beyond Himself to the One who sent Him.',text:'He has not received the recognized rabbinic training His hearers expect, yet He teaches with authority. Jesus says His doctrine belongs to the Father who sent Him. Verse 17 adds a moral dimension to understanding: a heart willing to do God’s will is better positioned to recognize whether the teaching is truly from God.'},
   {ref:'John 7:19-24',title:'The Sabbath controversy exposes the danger of judging by one visible act without understanding the whole law.',text:'Jesus points out that circumcision can be performed on the Sabbath so that Moses’ law is not broken, yet His opponents are angry because He made an entire man well on the Sabbath. His conclusion is not “never judge”; it is “judge righteous judgment”—judge with truth, proportion, and the whole matter in view.'},
   {ref:'John 7:25-31',title:'The crowd’s confidence that Messiah’s origin should be mysterious collides with their incomplete knowledge of Jesus.',text:'They think they know where Jesus is from and therefore assume He cannot be the Christ. Jesus answers that they know His visible earthly origin but do not truly know the One who sent Him. John keeps pressing the same question from chapter 1 onward: knowing facts about Jesus is not the same as knowing who He is.'},
   {ref:'John 7:32-36',title:'“Where I am, thither ye cannot come” is misunderstood because Jesus is speaking about His return to the Father.',text:'The officers are sent to arrest Him, but Jesus speaks of the short time remaining before He goes to the One who sent Him. His hearers wonder whether He plans to go among the Greek-speaking Jewish diaspora. John lets the misunderstanding stand for the moment; the Gospel will clarify Jesus’ “going” through His death, resurrection, and return to the Father.'},
   {ref:'John 7:37-39',title:'Jesus’ living-water invitation is especially striking at the Feast of Tabernacles.',text:'The feast remembered God’s wilderness provision, and later Jewish celebration included a water-pouring ceremony connected with prayer for rain and salvation. Against that setting Jesus stands and cries out that the thirsty should come to Him and drink. John then removes any doubt about the deeper meaning: He is speaking of the Holy Spirit who would be given to believers after Jesus was glorified.',cross:[{ref:'Isaiah 44:3',label:'Prophetic background',reason:'Isaiah joins water poured on the thirsty with God pouring His Spirit on His people.'},{ref:'John 4:14',label:'Earlier Johannine echo',reason:'Jesus has already spoken of His gift as living water springing up into everlasting life.'}]},
   {ref:'John 7:38',title:'The exact Old Testament source of “out of his belly shall flow rivers of living water” is not a single verbatim verse.',text:'Jesus says “as the scripture hath said,” but no one Old Testament sentence matches the wording exactly. The image fits a cluster of prophetic texts about life-giving water, blessing, and the Spirit. The point is stronger than finding one hidden quotation: Scripture repeatedly associates God’s saving presence with water flowing into dry places.'},
   {ref:'John 7:40-44',title:'The Bethlehem objection depends on incomplete information.',text:'Some people reject Jesus because they know Him as a Galilean and remember that Scripture places the Davidic ruler in Bethlehem. John does not stop to retell the birth narratives as Matthew and Luke do. The irony is that the readers already know the crowd is repeatedly judging Jesus from partial knowledge.',cross:[{ref:'Micah 5:2',label:'Messianic background',reason:'The crowd correctly remembers that the promised ruler is associated with Bethlehem, the city of David.'}]},
   {ref:'John 7:45-52',title:'The officers are impressed by Jesus, Nicodemus asks for due process, and the leaders answer with contempt rather than investigation.',text:'The officers return without arresting Jesus because “Never man spake like this man.” When Nicodemus reminds the council that the law should hear a person before judging him, he is mocked as though he too were from Galilee. Their confidence that no prophet arises from Galilee is at least careless: Jonah is associated with Gath-hepher in the Galilean region. The scene demonstrates the very appearance-based judgment Jesus warned against earlier in the chapter.',cross:[{ref:'2 Kings 14:25',label:'Historical correction',reason:'Jonah son of Amittai came from Gath-hepher, a town in the region later known as Galilee.'}]},
   {ref:'John 7:53',title:'The story that continues into John 8:1–11 has an important manuscript note.',text:'The account of the woman caught in adultery is beloved and ancient in Christian tradition, but the earliest and strongest Greek manuscripts of John do not contain John 7:53–8:11, and some later manuscripts place it in other locations. That does not require hiding or mocking the passage; it does require honesty that its original location in John is textually uncertain. Bookmark will treat the story respectfully while clearly labeling the manuscript evidence.'}
  ],
  reflections:['Where am I tempted to judge a person, situation, or teaching from appearances before I have actually understood the whole matter?','What thirst am I trying to satisfy somewhere else that Jesus is inviting me to bring directly to Him?'],
  commentary:{voice:'John Gill',identity:'English Baptist pastor and commentator, 1697–1771',quote:'there is a fulness of grace in Christ',plain:'Gill is commenting on Jesus’ invitation to the thirsty at the Feast of Tabernacles. The point is not that Christ gives a reluctant trickle of life; those who come to Him find an abundant source, and John immediately identifies that promised living water with the Holy Spirit.',source:'Exposition of the Entire Bible — John 7',url:'https://biblehub.com/commentaries/gill/john/7.htm'},
  question:{q:'What did Jesus mean by “rivers of living water” in John 7:38?',short:'John answers the question in the next verse: Jesus is speaking about the Holy Spirit given to those who believe in Him.',more:'The feast setting makes the image especially rich. Tabernacles remembered God’s wilderness care, and later Jewish celebration included ceremonial water-pouring. Israel’s prophets also pictured God’s salvation and Spirit as water poured on dry ground. Jesus places Himself at the center of those hopes: the thirsty come to Him and drink. The image then turns outward—living water flows from within the believer. There is some grammatical debate about whether the “his” in verse 38 points most directly to the believer or to Christ, but John’s explanation is clear enough for the main point: the Spirit is the living water Christ gives, and His life does not remain barren or stagnant.'}
 }
});
render();