// Luke 1–3 — Living Bookmark cards.
Object.assign(studies,{
 'Luke 1':{body:''},
 'Luke 2':{body:''},
 'Luke 3':{body:''}
});

Object.assign(studyMeta,{
 'Luke 1':{
  oneLine:'Luke begins with careful historical purpose, then tells how God answers long waiting through John’s promised birth and Jesus’ miraculous conception, while Mary, Elizabeth, and Zechariah answer God’s mercy with faith and song.',
  write:[
   {ref:'Luke 1:4',title:'Luke wants faith to rest on things carefully known.',text:'He writes so Theophilus may know the certainty of what he has been taught.'},
   {ref:'Luke 1:13',title:'A long-unanswered prayer was not a forgotten prayer.',text:'Gabriel tells Zacharias, “thy prayer is heard,” when the answer now looks humanly impossible.'},
   {ref:'Luke 1:37',title:'God’s promise is not limited by human impossibility.',text:'The virgin conception and Elizabeth’s late pregnancy both stand under the same truth: nothing is too hard for God.'},
   {ref:'Luke 1:38',title:'Mary answers mystery with surrendered faith.',text:'She does not pretend to understand everything; she entrusts herself to the word of the Lord.'},
   {ref:'Luke 1:45',title:'Elizabeth calls Mary blessed because she believed.',text:'The emphasis falls on trusting that the Lord will perform what He has spoken.'},
   {ref:'Luke 1:78-79',title:'The Messiah comes like sunrise into darkness.',text:'Zacharias ends with mercy, light, and feet guided into the way of peace.'}
  ],
  underline:{ref:'Luke 1:38',reason:'Mary’s answer gives a beautiful pattern of faith: honest about the mystery, yet willing to receive what God has said.'},
  notice:[
   {ref:'Luke 1:1-4',title:'Luke opens like a careful historian, not like a storyteller inventing a legend.',text:'He refers to earlier accounts, eyewitnesses, transmitted testimony, investigation, and an orderly written account. “From the very first” can also carry the sense of tracing matters accurately from their source. Luke’s stated goal is certainty about events already taught in the church.'},
   {ref:'Luke 1:5-25',title:'John’s birth announcement is deliberately shaped like Old Testament miracle-birth stories.',text:'Zacharias and Elisabeth are righteous, elderly, and childless. Their story recalls couples such as Abraham and Sarah, while John’s promised role reaches especially toward Elijah: he will turn hearts and prepare a people for the Lord.',cross:[{ref:'Malachi 4:5-6',label:'Prophetic background',reason:'Gabriel’s description of John echoes Malachi’s promise of an Elijah-like forerunner.'}]},
   {ref:'Luke 1:18-20',title:'Zacharias is not silenced merely because he asked a question.',text:'Gabriel interprets his response as unbelief: “thou believest not my words.” Mary will also ask “How?” in verse 34, but her question seeks understanding and is followed by submission. The difference is not that questions are forbidden; it is the posture toward God’s promise.'},
   {ref:'Luke 1:26-38',title:'The announcement to Mary makes claims about Jesus before He is born.',text:'He will be called Jesus, Son of the Highest, receive David’s throne, reign without end, and be called the Son of God. Luke does not introduce Jesus merely as a later teacher who becomes important; His identity belongs to the birth announcement itself.',cross:[{ref:'2 Samuel 7:12-16',label:'Davidic promise',reason:'Gabriel’s language about David’s throne and an enduring kingdom reaches back to God’s covenant promise to David.'}]},
   {ref:'Luke 1:28',title:'“Highly favoured” describes grace received, not a claim that Mary is the source of grace.',text:'The Greek verb is related to grace and speaks of God’s favor toward her. Luke absolutely presents Mary as uniquely blessed, but Mary’s own song immediately rejoices in “God my Saviour” and credits the Mighty One for what He has done.'},
   {ref:'Luke 1:39-45',title:'Elizabeth calls the unborn Jesus “my Lord.”',text:'Before Jesus is born, Elizabeth—filled with the Holy Ghost—recognizes the child Mary carries in language of astonishing honor. John’s leap also fits his forerunner role: even the birth narratives keep directing attention toward the coming Christ.'},
   {ref:'Luke 1:46-55',title:'The Magnificat sounds new because God is acting, but it sounds old because Mary knows Israel’s Scriptures.',text:'Her song is full of Old Testament wording and strongly resembles Hannah’s song. It praises God for mercy, reversals of human pride, care for the lowly and hungry, and faithfulness to Abraham. Luke’s poor/rich reversal theme is already present before Jesus’ birth.',cross:[{ref:'1 Samuel 2:1-10',label:'Song parallel',reason:'Hannah’s praise supplies especially close themes of God humbling the proud and lifting the lowly.'}]},
   {ref:'Luke 1:67-79',title:'The Benedictus joins David, Abraham, forgiveness, and light into one covenant story.',text:'Zacharias blesses God because He has “visited and redeemed his people,” speaks of the house of David, remembers the covenant with Abraham, and then describes John preparing the Lord’s ways. Salvation includes deliverance, forgiveness of sins, tender mercy, and light for people in darkness.'}
  ],
  reflections:['Where have I mistaken a long wait for evidence that God has forgotten?','What would it look like for me to bring God an honest question while still saying, with Mary, “be it unto me according to thy word”?'],
  commentary:{voice:'Alexander Maclaren',identity:'Scottish Baptist preacher and expositor, 1826–1910',quote:'These old psalms provided the mould into which her glowing emotions almost instinctively would run.',plain:'Maclaren notices why Mary’s song sounds so thoroughly Scriptural. Her praise does not float free of the Bible she already knows; when God acts, the language stored in her heart becomes the language of worship.',source:'Expositions of Holy Scripture — Luke 1',url:'https://biblehub.com/commentaries/maclaren/luke/1.htm'},
  question:{q:'Why was Zacharias corrected for asking “Whereby shall I know this?” when Mary also asked “How shall this be?”',short:'Gabriel says Zacharias did not believe his words, while Mary’s question seeks to understand the manner of fulfillment and is followed by willing trust.',more:'The two questions look similar on the surface, but Luke lets the angel explain the difference. Zacharias asks for a confirming sign even though he is speaking to Gabriel in the temple; the angel says plainly that he did not believe. Mary asks how a promised virgin conception will occur and, after the explanation, answers, “Behold the handmaid of the Lord.” Scripture therefore leaves room for honest questions without treating unbelief and inquiry as the same thing.'}
 },
 'Luke 2':{
  oneLine:'Jesus is born in David’s city under the shadow of empire, announced as Saviour and Lord to shepherds, recognized in the temple by Simeon and Anna, and later shown at twelve years old to belong uniquely to His Father while still living in obedient family life.',
  write:[
   {ref:'Luke 2:7',title:'The King enters the world in startling humility.',text:'Mary lays Jesus in a manger because their lodging has no place available for them.'},
   {ref:'Luke 2:11',title:'The angel gives Jesus three enormous titles.',text:'The child born in David’s city is “a Saviour, which is Christ the Lord.”'},
   {ref:'Luke 2:19',title:'Mary treasures before she fully understands.',text:'She keeps these things and ponders them instead of rushing past what God is doing.'},
   {ref:'Luke 2:32',title:'Jesus is for the Gentiles and for Israel.',text:'Simeon sees one salvation large enough to be light to the nations and glory to God’s people Israel.'},
   {ref:'Luke 2:49',title:'Jesus already knows His first allegiance is to His Father.',text:'At twelve, His identity and mission are not reducible to ordinary family expectations.'},
   {ref:'Luke 2:51-52',title:'Sonship does not make Jesus contemptuous of ordinary obedience.',text:'He returns home, submits to His parents, and grows through real human childhood.'}
  ],
  underline:{ref:'Luke 2:11',reason:'Luke’s birth announcement says who this child is: Saviour, Messiah, and Lord.'},
  notice:[
   {ref:'Luke 2:1-5',title:'Luke deliberately sets Jesus’ birth inside public history.',text:'Augustus, an imperial decree, registration, Syria, and Joseph’s Davidic ancestry place the story in the political world of Rome. The irony is quiet but strong: Caesar issues a decree, yet the movement it causes brings Joseph and Mary to David’s town as God’s older promises move toward fulfillment.'},
   {ref:'Luke 2:2',title:'The Quirinius census is a real chronology question and should not be hidden.',text:'Quirinius is securely connected with a later census around AD 6, the one Luke himself knows in Acts 5:37. Christians and historians have proposed several explanations for Luke 2:2—including an earlier role for Quirinius or different ways of understanding the wording—but the surviving evidence does not settle every detail. The responsible approach is to acknowledge the difficulty rather than pretending it does not exist.'},
   {ref:'Luke 2:4-7',title:'Bethlehem matters because Jesus is born in David’s town.',text:'Joseph belongs to David’s house and lineage. Luke stresses that ancestry while Micah had already associated Bethlehem with the ruler who would come for Israel. Luke is interested in both humble circumstances and royal promise.',cross:[{ref:'Micah 5:2',label:'Messianic background',reason:'Micah names Bethlehem as the little town from which Israel’s ruler will come.'}]},
   {ref:'Luke 2:7',title:'The text never mentions a cruel innkeeper.',text:'The Greek word translated “inn” here can mean a lodging or guest room and is used by Luke for the guest room at the Last Supper. Whatever the exact house arrangement, Luke’s point is simple: the available lodging space was full, so the newborn Jesus was laid where animals were fed.'},
   {ref:'Luke 2:8-20',title:'The first announced audience is ordinary shepherds, and the message moves from fear to joy to witness.',text:'Luke does not need the popular claim that shepherds were universally despised in order to make the scene striking. They are working people in the fields. Heaven tells them that David’s promised city now holds a Saviour, Christ the Lord, and they become immediate witnesses after seeing Him.'},
   {ref:'Luke 2:22-24',title:'Mary and Joseph obey the law, and their offering points to modest means.',text:'Leviticus allowed a pair of birds when a family could not afford a lamb for the purification offering. Luke therefore presents the family of Jesus not as wealthy elites but as faithful people making the provision the law gave to those of limited means.',cross:[{ref:'Leviticus 12:6-8',label:'Law background',reason:'The law permits two birds as the offering when a lamb is beyond the family’s means.'}]},
   {ref:'Luke 2:25-35',title:'Simeon’s song reaches beyond Israel while refusing to bypass Israel.',text:'Jesus is “a light to lighten the Gentiles” and “the glory of thy people Israel.” Luke’s universal reach is already explicit. Simeon also warns Mary that this child will expose hearts and be opposed; Christmas joy in Luke already points toward conflict and the cross.',cross:[{ref:'Isaiah 49:6',label:'Servant-song background',reason:'Isaiah speaks of God’s servant as a light to the Gentiles so salvation may reach the ends of the earth.'}]},
   {ref:'Luke 2:36-38',title:'Anna is not decorative background; Luke names her as a prophetess and witness.',text:'An elderly widow devoted to worship recognizes the moment and speaks about Jesus to those waiting for redemption in Jerusalem. Luke repeatedly gives women active, speaking roles in the story of God’s saving work.'},
   {ref:'Luke 2:41-52',title:'The twelve-year-old Jesus is both extraordinary and genuinely human.',text:'He amazes teachers with understanding, speaks of His Father’s affairs in a unique way, yet goes home and is subject to Mary and Joseph. Verse 52 then describes real growth in wisdom and stature. Luke will not let readers protect Jesus’ divinity by denying His true human development.'}
  ],
  reflections:['What do I learn about God from the fact that the Saviour enters ordinary, crowded, materially modest circumstances?','Can I treasure what God is doing even when, like Mary, I do not yet understand all of it?'],
  commentary:{voice:'Alexander Maclaren',identity:'Scottish Baptist preacher and expositor, 1826–1910',quote:'Simeon’s whole life appears, in its later years, to have been under the immediate direction of the Spirit of God.',plain:'Maclaren notices how repeatedly Luke mentions the Spirit around Simeon. His waiting is not passive drift; he is a faithful old man whose long expectation has been shaped and finally fulfilled by the Spirit.',source:'Expositions of Holy Scripture — Luke 2',url:'https://biblehub.com/commentaries/maclaren/luke/2.htm'},
  question:{q:'Was Jesus born in a commercial inn because an innkeeper turned Mary and Joseph away?',short:'Luke says there was no place for them in the “katalyma,” but he never mentions an innkeeper, and the word can mean a lodging or guest room rather than a commercial inn.',more:'The traditional picture of a heartless innkeeper goes beyond the text. Luke’s word is also used for the guest room in Luke 22:11. Some scholars therefore picture a crowded family home with its guest space already occupied and the couple using the lower area where animals were kept; others allow a more general lodging-place sense. The exact floor plan is uncertain. What Luke clearly says is that the normal lodging space was unavailable and Jesus was laid in a manger.'}
 },
 'Luke 3':{
  oneLine:'Luke anchors John’s ministry in public history, John demands repentance with practical fruit, Jesus is baptized and publicly affirmed by the Father and Spirit, and His genealogy is traced past Abraham all the way to Adam and God.',
  write:[
   {ref:'Luke 3:6',title:'Luke keeps the words “all flesh shall see the salvation of God.”',text:'From the beginning, this Gospel keeps widening our eyes beyond one nation.'},
   {ref:'Luke 3:8',title:'Repentance has fruit.',text:'John refuses ancestry, religious identity, or words without a changed direction of life.'},
   {ref:'Luke 3:11',title:'Repentance reaches closets and kitchens.',text:'John’s first example is sharing clothing and food with someone who lacks them.'},
   {ref:'Luke 3:14',title:'Power must not become a tool for exploitation.',text:'Soldiers are told to stop violence and false accusation and be content with their wages.'},
   {ref:'Luke 3:16',title:'John knows exactly who is greater.',text:'His baptism points forward to One who baptizes with the Holy Ghost and fire.'},
   {ref:'Luke 3:22',title:'Father, Son, and Holy Ghost appear together at Jesus’ baptism.',text:'The Son prays, the Spirit descends, and the Father speaks His delight.'}
  ],
  underline:{ref:'Luke 3:22',reason:'Before Jesus begins public ministry, the Father identifies Him as His beloved Son and declares His pleasure in Him.'},
  notice:[
   {ref:'Luke 3:1-2',title:'The long list of rulers is Luke’s way of putting the gospel on the calendar and map.',text:'Tiberius, Pilate, Herod, Philip, Lysanias, Annas, and Caiaphas locate John’s appearance within identifiable imperial, regional, and priestly leadership. Exact ancient dating still requires care, but Luke clearly intends readers to understand these events as history in the public world.'},
   {ref:'Luke 3:3-6',title:'John fulfills Isaiah’s wilderness-voice role, and Luke quotes far enough to reach “all flesh.”',text:'Matthew and Mark also identify John with Isaiah 40, but Luke carries the quotation through the promise that all flesh will see God’s salvation. That ending fits a Gospel that will keep highlighting Gentiles, outsiders, and a salvation meant to reach the nations.',cross:[{ref:'Isaiah 40:3-5',label:'Direct quotation',reason:'Luke directly quotes Isaiah’s promised voice preparing the Lord’s way, including the line about all flesh seeing God’s salvation.'}]},
   {ref:'Luke 3:7-14',title:'John will not let repentance remain vague and emotional.',text:'He tells crowds to share, tax collectors to take no more than authorized, and soldiers to stop extortion and false accusation. He does not tell every person to abandon ordinary work; he tells them to stop using possessions, office, or force selfishly.'},
   {ref:'Luke 3:8',title:'“We have Abraham to our father” is a warning against inherited confidence.',text:'John does not deny Israel’s covenant history. He denies that ancestry can substitute for repentance. God is not trapped into accepting fruitlessness because someone has the right family line.'},
   {ref:'Luke 3:15-17',title:'In context, the “fire” beside Spirit includes judgment imagery.',text:'John immediately pictures a winnowing fan, gathered wheat, and chaff burned with unquenchable fire. Christians rightly connect Jesus with the promised gift of the Holy Spirit, but this paragraph also warns that His coming separates and judges; “fire” should not automatically be reduced to a pleasant spiritual sensation.'},
   {ref:'Luke 3:21-22',title:'Luke uniquely emphasizes that Jesus is praying when heaven opens.',text:'Jesus has no sins to confess, so His baptism is not repentance for personal wrongdoing. He identifies Himself with the people He came to save, and the scene becomes a divine commissioning: the Spirit descends and the Father names Him the beloved Son.',cross:[{ref:'Psalm 2:7',label:'Royal-Messiah echo',reason:'The Father’s words about the Son echo royal sonship language from Psalm 2.'},{ref:'Isaiah 42:1',label:'Servant echo',reason:'“In thee I am well pleased” recalls the LORD’s delight in His chosen servant.'}]},
   {ref:'Luke 3:23-38',title:'Luke’s genealogy runs backward to Adam, fitting the Gospel’s universal horizon.',text:'Matthew begins with Abraham and moves forward; Luke moves backward past Abraham to Adam and finally “God.” The line from David also differs: Matthew follows Solomon while Luke follows Nathan. Several explanations have been offered for the differences—legal versus biological descent, levirate relationships, or Luke preserving Mary’s family line through Joseph—but Luke does not spell out the mechanism, so certainty beyond the text is unwise.'},
   {ref:'Luke 3:38',title:'Calling Adam “the son of God” is about creation, not divine nature.',text:'Adam has no human father because God directly creates him. Luke has just recorded the Father calling Jesus His beloved Son, so the genealogy prepares an important contrast: Jesus enters the human family that begins with Adam, yet His Sonship is unique.'}
  ],
  reflections:['If John examined the ordinary use of my money, possessions, words, and power, what fruit of repentance would he look for?','What does it mean that Jesus begins His public ministry not by self-promotion but in prayer, receiving the Father’s word and the Spirit’s descent?'],
  commentary:{voice:'John Gill',identity:'English Baptist pastor and commentator, 1697–1771',quote:'Luke traces it upwards, in an ascending line, from Mary by Joseph, even up to Adam.',plain:'Gill represents one longstanding Protestant explanation of Luke’s genealogy: that Luke preserves Mary’s family line while naming Joseph in the formal genealogy. That view is possible, but it is not the only faithful explanation. The text itself is clearer about Luke’s theological direction than about the exact legal mechanism: Jesus is connected through David to the whole human family all the way back to Adam.',source:'Exposition of the Entire Bible — Luke 3',url:'https://biblehub.com/commentaries/gill/luke/3.htm'},
  question:{q:'Why is Luke’s genealogy different from Matthew’s?',short:'Both connect Jesus to David, but Matthew follows the line through Solomon while Luke follows the line through Nathan; Scripture does not explicitly tell us why the two lists use different lines.',more:'Christians have proposed several serious explanations. Some see Matthew as a royal/legal line and Luke as a biological line; some understand Luke as Mary’s ancestry expressed through Joseph; others appeal to ancient marriage and inheritance practices such as levirate relationships. Each proposal has strengths and questions. What is certain is the emphasis each Gospel gives: Matthew foregrounds Abraham and Davidic kingship, while Luke traces Jesus through David and Abraham all the way to Adam, fitting Luke’s repeated concern for salvation reaching all humanity.'}
 }
});
render();