// Luke 4–6 — Living Bookmark cards.
Object.assign(studies,{
 'Luke 4':{body:''},
 'Luke 5':{body:''},
 'Luke 6':{body:''}
});

Object.assign(studyMeta,{
 'Luke 4':{
  oneLine:'Jesus defeats the devil in the wilderness by trusting God’s word, announces Isaiah’s good news as fulfilled in Himself, is rejected at Nazareth when He exposes hometown entitlement, and then teaches and heals with unmistakable authority.',
  write:[
   {ref:'Luke 4:1',title:'The Spirit who descends at Jesus’ baptism also leads Him into testing.',text:'Being led by God does not mean every road avoids wilderness or conflict.'},
   {ref:'Luke 4:4',title:'Jesus answers appetite with dependence on God.',text:'Bread matters, but life itself rests on the God who gives and sustains it.'},
   {ref:'Luke 4:8',title:'Worship cannot be traded for a shortcut to power.',text:'Jesus refuses a kingdom gained by bowing to the wrong lord.'},
   {ref:'Luke 4:18',title:'Jesus describes His mission as good news for people in need.',text:'Poor, captive, blind, and bruised people stand at the center of the announcement.'},
   {ref:'Luke 4:21',title:'Jesus says the promised Scripture is fulfilled “this day.”',text:'Nazareth is not merely hearing a lesson about Messiah; Messiah is speaking to them.'},
   {ref:'Luke 4:43',title:'Jesus says He “must” preach the kingdom elsewhere also.',text:'Popularity in one town will not shrink the mission God sent Him to complete.'}
  ],
  underline:{ref:'Luke 4:21',reason:'The shock of the Nazareth sermon is Jesus’ claim that Isaiah’s promised good news is arriving in their hearing through Him.'},
  notice:[
   {ref:'Luke 4:1-13',title:'Jesus answers every temptation from Deuteronomy, Israel’s wilderness book.',text:'The quotations come from Israel’s wilderness instruction, where God’s people had been tested over hunger, worship, and trust. Jesus stands where Israel failed and remains faithful. The point is not a magic formula in which any isolated verse defeats evil; it is obedient trust in Scripture rightly understood.',cross:[{ref:'Deuteronomy 8:3',label:'Direct quotation',reason:'Jesus answers the bread temptation with Moses’ lesson that Israel’s life depended on God, not bread alone.'},{ref:'Deuteronomy 6:13',label:'Direct quotation',reason:'Jesus answers the worship temptation with Israel’s command to worship and serve the LORD alone.'}]},
   {ref:'Luke 4:9-12',title:'The devil can quote Scripture and still misuse it.',text:'Psalm 91 truly promises God’s care, but Satan tears that promise away from faithful obedience and turns it into a demand that Jesus manufacture danger so God must prove Himself. Jesus answers Scripture with Scripture and refuses to test God.',cross:[{ref:'Psalm 91:11-12',label:'Quoted and misused',reason:'Satan cites this promise of angelic protection while urging Jesus to create a needless crisis.'},{ref:'Deuteronomy 6:16',label:'Corrective quotation',reason:'Jesus refuses to turn trust into a test of whether God will perform on demand.'}]},
   {ref:'Luke 4:16-21',title:'Jesus’ Nazareth reading joins proclamation, release, healing, and the year of the Lord’s favor.',text:'The main wording comes from Isaiah 61, with language also echoing Isaiah’s liberation themes. Jesus announces that the promised age is not merely future. In His ministry, the good news is beginning to arrive for people crushed by sin, sickness, exclusion, and bondage.',cross:[{ref:'Isaiah 61:1-2',label:'Direct quotation',reason:'Jesus reads Isaiah’s Spirit-anointed good-news passage and says it is fulfilled in their hearing.'}]},
   {ref:'Luke 4:19',title:'Jesus stops before Isaiah’s phrase about “the day of vengeance.”',text:'That does not mean judgment disappears from Jesus’ message; Luke will record plenty of warning. The reading emphasizes the gracious arrival of the Lord’s favor at this point in the story. We should not turn the stopping point into a claim that the rest of Isaiah has been cancelled.'},
   {ref:'Luke 4:22-30',title:'Nazareth’s anger rises when grace refuses to become hometown property.',text:'The crowd first marvels, then stumbles over knowing Jesus as Joseph’s son. Jesus brings up Elijah’s help to a widow in Sidon and Elisha’s cleansing of Naaman the Syrian—Old Testament stories where God’s mercy reaches outsiders while many in Israel remain unbelieving. Their rage exposes more than familiarity; it exposes offended entitlement.',cross:[{ref:'1 Kings 17:8-16',label:'Story parallel',reason:'Elijah is sustained with a widow in Sidon during Israel’s famine.'},{ref:'2 Kings 5:1-14',label:'Story parallel',reason:'Naaman the Syrian receives cleansing while many lepers in Israel do not.'}]},
   {ref:'Luke 4:31-41',title:'Demons recognize Jesus, but Jesus will not receive testimony on their terms.',text:'They identify Him with frightening accuracy, yet He rebukes and silences them. Correct words from an unclean source are not the same thing as faithful witness. Jesus controls both the spirits and the disclosure of His identity.'},
   {ref:'Luke 4:42-44',title:'Jesus refuses to let success trap Him in one place.',text:'The crowds want to keep Him, but He says the kingdom must be preached to other cities because that is why He was sent. Luke’s Jesus is compassionate toward the people in front of Him without allowing their demands to redefine His mission.'}
  ],
  reflections:['Where am I tempted to use a good desire—food, safety, influence, recognition—as permission to distrust God’s way of providing it?','Do I rejoice when God’s mercy reaches people outside the group I instinctively think of as “ours”?'],
  commentary:{voice:'John Calvin',identity:'Reformation pastor and commentator, 1509–1564',quote:'men do not live by bread alone, but by the secret blessing of God.',plain:'Calvin sees Jesus’ first answer as more than heroic fasting. Bread is ordinarily one of God’s means of sustaining us, but bread is never the ultimate source of life. Jesus refuses to treat a legitimate hunger as proof that He must seize provision apart from the Father’s will.',source:'Commentary on a Harmony of the Evangelists — Luke 4',url:'https://biblehub.com/commentaries/calvin/luke/4.htm'},
  question:{q:'Why did the people of Nazareth move from admiration to trying to kill Jesus?',short:'Jesus exposed their unbelief and used Elijah and Elisha to show that God’s mercy is not controlled by hometown privilege or ethnic entitlement.',more:'At first they marvel at His gracious words, but they also reduce Him to “Joseph’s son” and expect the local miracle-worker to prove Himself in Nazareth. Jesus answers with two uncomfortable Old Testament examples: a Sidonian widow and a Syrian leper receive mercy in times when many Israelites do not. The issue is not that Jesus insults Israel; He confronts the assumption that familiarity or ancestry gives anyone a claim on God while faith and repentance can be ignored.'}
 },
 'Luke 5':{
  oneLine:'Jesus calls fishermen through an overwhelming catch, touches and cleanses a leper, forgives and heals a paralytic, calls Levi into a new life, eats with sinners, and explains that His arrival cannot be squeezed into unchanged religious patterns.',
  write:[
   {ref:'Luke 5:5',title:'Peter obeys after failure: “nevertheless at thy word.”',text:'The night has taught him what his skill can do; Jesus’ word sends him back out anyway.'},
   {ref:'Luke 5:8',title:'Peter sees abundance and becomes conscious of sin.',text:'The miracle does not make him feel impressive; the nearness of Jesus makes him feel unworthy.'},
   {ref:'Luke 5:10',title:'Jesus answers Peter’s fear with a calling.',text:'“Fear not” comes before “from henceforth thou shalt catch men.”'},
   {ref:'Luke 5:16',title:'Jesus repeatedly withdraws to pray.',text:'The busier and more sought-after His ministry becomes, the more Luke lets us see His hidden communion with the Father.'},
   {ref:'Luke 5:20',title:'Jesus sees the friends’ faith and addresses the man’s deepest need.',text:'Before He restores the body, He declares forgiveness of sins.'},
   {ref:'Luke 5:32',title:'Jesus comes for sinners who know they need a physician.',text:'His table fellowship is mercy calling people to repentance, not indifference to sin.'}
  ],
  underline:{ref:'Luke 5:5',reason:'Peter’s “nevertheless at thy word” is a compact picture of obedience when experience, fatigue, and visible results all argue the other way.'},
  notice:[
   {ref:'Luke 5:1-11',title:'The catch is not merely a reward for lending Jesus a boat; it becomes a call story.',text:'Peter knows the lake and has failed all night. When the catch overwhelms the nets, his response is confession rather than celebration. Jesus then turns the fishermen’s work into a mission image: from now on Peter will be catching people—not to destroy them, but to bring them into the life of the kingdom.'},
   {ref:'Luke 5:8-10',title:'Holy fear and gracious calling meet in the same moment.',text:'Peter says, “Depart from me,” because he suddenly sees himself as a sinful man before someone whose authority he cannot explain away. Jesus does not deny Peter’s sinfulness. He answers, “Fear not,” and calls the very man on his knees into service.'},
   {ref:'Luke 5:12-14',title:'Jesus touches the leper before the cleansing is announced.',text:'Under the law, leprosy-like skin conditions could make a person ceremonially unclean and socially isolated. Jesus is not contaminated by the man’s uncleanness; His holiness moves the other direction and cleanses. He still sends the man to the priest and the Mosaic offering, honoring the law’s public process for restoration.',cross:[{ref:'Leviticus 14:1-20',label:'Law background',reason:'Leviticus gives the priestly procedure and offerings connected with a cleansed leper’s restoration.'}]},
   {ref:'Luke 5:15-16',title:'Growing demand does not eliminate Jesus’ habit of withdrawal.',text:'Luke deliberately places crowds and healing beside solitary prayer. Prayer is not presented as what Jesus does only when ministry is quiet; it belongs inside the pressure of ministry itself.'},
   {ref:'Luke 5:17-26',title:'The paralytic story makes forgiveness the contested claim.',text:'The teachers are not offended because Jesus heals a man. They object because He says, “Thy sins are forgiven thee,” something they rightly connect with God’s authority. Jesus then heals the visible paralysis so they may know that the Son of man has authority on earth to forgive sins.'},
   {ref:'Luke 5:18-20',title:'The friends’ faith is active, communal, and inconvenient.',text:'They cannot get through the crowd, so they carry the man upward and lower him through the roof area into Jesus’ presence. Luke does not tell us that their faith mechanically earns the miracle. He shows determined trust that refuses to let obstacles keep a helpless person away from Christ.'},
   {ref:'Luke 5:27-32',title:'Levi’s feast shows the direction of Jesus’ mercy.',text:'Jesus calls a tax collector away from his booth, and Levi responds by leaving, following, and opening his table. “I came not to call the righteous, but sinners to repentance” keeps two truths together: Jesus gladly eats with sinners, and His mercy calls them into a changed life.'},
   {ref:'Luke 5:33-39',title:'Bridegroom, new cloth, and new wine all say that Jesus changes the situation.',text:'Fasting is not condemned; Jesus says His disciples will fast when the bridegroom is taken away. But His presence cannot simply be treated as a patch sewn onto an unchanged system. The kingdom He brings has a newness that old categories cannot safely contain.'}
  ],
  reflections:['Where has repeated failure made me reluctant to obey a fresh word from Christ?','Who has helped carry me toward Jesus when I did not have enough strength to get there alone?'],
  commentary:{voice:'Alexander Maclaren',identity:'Scottish Baptist preacher and expositor, 1826–1910',quote:'The obligation is universal.',plain:'Maclaren is commenting on Jesus turning fishermen into fishers of people. The particular apostolic calling is unique, but no Christian is meant to treat following Jesus as private possession with no concern for others. Grace received becomes grace carried outward.',source:'Expositions of Holy Scripture — Luke 5',url:'https://biblehub.com/commentaries/maclaren/luke/5.htm'},
  question:{q:'Why did Jesus tell the cleansed leper to tell no one but still send him to the priest?',short:'Jesus restrains uncontrolled publicity while still requiring the man to follow the law’s process for verified cleansing and restoration.',more:'Mark and Luke both show that publicity could make Jesus’ movement through towns harder. The command is therefore not embarrassment about the miracle. The priestly examination and offering were part of the law given in Leviticus, and Jesus tells the man to fulfill that requirement “for a testimony unto them.” The man is not told to pretend nothing happened; he is told to let Jesus govern how the sign is handled.'}
 },
 'Luke 6':{
  oneLine:'Jesus claims lordship over Sabbath, chooses twelve apostles after a night of prayer, announces kingdom blessings and warnings, commands enemy-love and mercy, and insists that real discipleship is known by fruit and by doing His words.',
  write:[
   {ref:'Luke 6:5',title:'Jesus does not merely enter a Sabbath debate; He claims authority over the Sabbath.',text:'“The Son of man is Lord also of the sabbath.”'},
   {ref:'Luke 6:12',title:'Jesus prays all night before choosing the Twelve.',text:'Major decisions in Luke repeatedly sit inside prayer, not frantic self-confidence.'},
   {ref:'Luke 6:20',title:'The kingdom overturns ordinary measures of who is fortunate.',text:'Jesus speaks blessing over poor disciples because the kingdom of God belongs to them.'},
   {ref:'Luke 6:27',title:'Enemy-love is not a feeling test; Jesus gives it verbs.',text:'Love, do good, bless, and pray turn the command into concrete action.'},
   {ref:'Luke 6:36',title:'Mercy reflects the Father’s character.',text:'The standard is not “be nicer than your enemy” but “be ye therefore merciful, as your Father also is merciful.”'},
   {ref:'Luke 6:46',title:'Calling Jesus “Lord” while ignoring His words is a contradiction.',text:'The rock foundation is hearing Christ and actually doing what He says.'}
  ],
  underline:{ref:'Luke 6:36',reason:'Jesus roots the difficult life of mercy in God’s own character: His children learn to treat people in a way that resembles their Father.'},
  notice:[
   {ref:'Luke 6:1-5',title:'Jesus answers the grain-field controversy with David and then with His own authority.',text:'David ate consecrated bread in a time of need, showing that sacred regulations must be read within God’s purposes rather than weaponized against human necessity. Jesus then goes further: the Son of man is Lord of the Sabbath. He is not merely proposing a softer rabbinic opinion.'},
   {ref:'Luke 6:6-11',title:'The Sabbath question becomes “Is it lawful to save life or destroy it?”',text:'Jesus heals a withered hand openly and asks what the holy day is for. The opponents respond to restoration by becoming filled with rage and discussing what to do to Jesus. Luke exposes the moral reversal: zeal for Sabbath can become hatred of the Lord of Sabbath.'},
   {ref:'Luke 6:12-16',title:'The Twelve are chosen after prayer and carry obvious Israel symbolism.',text:'Jesus spends the night in prayer, then names twelve from the larger group of disciples as apostles. The number recalls Israel’s twelve tribes and signals that Jesus is gathering a renewed covenant people around Himself.'},
   {ref:'Luke 6:17-26',title:'Luke’s blessings and woes are strikingly concrete.',text:'Luke says poor, hungry, weeping, and hated—and then rich, full, laughing, and well-spoken-of. This should not be flattened into “poverty automatically saves” or “possessions automatically condemn.” Jesus is announcing a kingdom reversal that exposes where people locate security, satisfaction, reputation, and hope. Luke will keep returning to the spiritual danger of wealth and the dignity of the poor.'},
   {ref:'Luke 6:27-36',title:'Enemy-love renounces revenge; it does not require a victim to remain available for abuse.',text:'Jesus commands active goodwill toward hostile people: do good, bless, pray, give, and refuse retaliation as the governing instinct. That is not the same as pretending evil is safe, refusing lawful protection, or remaining in a situation where someone can keep harming you. Elsewhere Scripture permits fleeing danger and requires confronting sin; mercy and wise boundaries are not enemies.',cross:[{ref:'Luke 17:3',label:'Further explanation',reason:'Jesus also tells disciples to rebuke a sinning brother and forgive the repentant one; love is not silence about wrongdoing.'},{ref:'Matthew 10:23',label:'Safety example',reason:'Jesus tells disciples that when they are persecuted in one city, they may flee to another.'}]},
   {ref:'Luke 6:37-42',title:'“Judge not” forbids hypocritical condemnation, not all moral discernment.',text:'Jesus immediately speaks about removing the beam from your own eye so that you can see clearly to address your brother’s speck. The goal is not moral blindness. It is self-examined, merciful clarity rather than a double standard that magnifies another person’s failure and excuses your own.'},
   {ref:'Luke 6:43-45',title:'Fruit reveals the kind of tree, and speech reveals what fills the heart.',text:'Jesus moves from outward behavior to inward abundance: the mouth speaks from what the heart stores. That makes spiritual fruit more than reputation management. Lasting change must reach the source.'},
   {ref:'Luke 6:46-49',title:'The rock is not merely hearing Jesus; it is hearing and doing.',text:'Both builders hear. The difference appears in obedience before the flood arrives. Jesus ends by placing His own words in the position of foundation: discipleship that admires Him but will not obey Him has no deep footing when pressure comes.'}
  ],
  reflections:['Is there someone I can refuse to repay with hatred while still keeping wise and truthful boundaries?','Which teaching of Jesus am I most tempted to admire without actually doing?'],
  commentary:{voice:'John Calvin',identity:'Reformation pastor and commentator, 1509–1564',quote:'the charity, which God requires in his law, looks not at what a man has deserved',plain:'Calvin gets at the nerve of enemy-love. If we make another person’s deservingness the measure of our mercy, we will always find reasons to withhold it. Jesus directs His disciples instead toward the Father, who is kind even to the unthankful and evil.',source:'Commentary on a Harmony of the Evangelists — Luke 6',url:'https://biblehub.com/commentaries/calvin/luke/6.htm'},
  question:{q:'Does “turn the other cheek” mean a Christian must stay where someone is abusing or attacking them?',short:'No. Jesus forbids revenge and commands enemy-love; He does not command people to make themselves continuously available for abuse or forbid them from seeking safety.',more:'In Luke 6 the emphasis is the disciple’s refusal to mirror an enemy’s hatred, grasping, cursing, or retaliatory spirit. That command is demanding, but it is not a command to call evil good. Jesus also teaches confrontation of sin, and He tells persecuted disciples to flee when necessary. A person can pray for an enemy, refuse revenge, tell the truth about harm, establish boundaries, involve lawful authorities, and move to safety without violating enemy-love.'}
 }
});
render();