// Acts 4 — Living Bookmark card.
Object.assign(studies,{
 'Acts 4':{body:''}
});

Object.assign(studyMeta,{
 'Acts 4':{
  oneLine:'Peter and John are arrested for preaching the resurrection, stand before Jerusalem’s rulers, boldly confess salvation in Jesus alone, refuse to stop speaking what they have seen and heard, and return to a praying church that asks God for courage, is freshly filled with the Spirit, and shares its resources so that no one among them is left in need.',
  write:[
   {ref:'Acts 4:12',title:'Jesus is not presented as one rescue among many.',text:'Peter says salvation is found in no other name given among humanity.'},
   {ref:'Acts 4:13',title:'Being with Jesus had become visible in ordinary men.',text:'The council could dismiss their formal training, but it could not dismiss their boldness.'},
   {ref:'Acts 4:20',title:'Witness begins with what God has made impossible to keep silent.',text:'Peter and John say they cannot stop speaking what they have seen and heard.'},
   {ref:'Acts 4:29',title:'Under threat, the church asks first for faithfulness.',text:'They pray for boldness to speak God’s word, not for an easier assignment.'},
   {ref:'Acts 4:31',title:'The answer to their prayer is fresh courage.',text:'The place is shaken, they are filled with the Holy Spirit, and they speak boldly.'},
   {ref:'Acts 4:32',title:'Unity loosens the grip of “mine.”',text:'One heart and one soul produces open-handed care for one another.'}
  ],
  underline:{ref:'Acts 4:12',reason:'Peter’s defense reaches its center here: salvation is in Jesus Christ, and no other name has been given by which we must be saved.'},
  notice:[
   {ref:'Acts 4:1-2',title:'The first organized opposition in Acts is especially provoked by the resurrection message.',text:'The priests, the temple captain, and the Sadducees interrupt Peter and John. The Sadducees denied resurrection, so preaching that resurrection had begun decisively in Jesus challenged more than public order; it challenged a major theological conviction of the priestly leadership.',cross:[{ref:'Acts 23:8',label:'Sadducean belief',reason:'Luke later states plainly that the Sadducees say there is no resurrection, angel, or spirit.'}]},
   {ref:'Acts 4:3-4',title:'The apostles are arrested, but the word is not.',text:'Because it is already evening, Peter and John are held until the next day. Luke immediately places the arrest beside the growth of the believing community. The wording about “about five thousand” is usually read as the number of male believers having reached roughly that total, though some interpreters have taken it as a new group added on this occasion.'},
   {ref:'Acts 4:5-6',title:'Peter and John now face the same high-priestly world that condemned Jesus.',text:'Luke names rulers, elders, scribes, Annas, Caiaphas, and members of the high-priestly family. Annas had formerly held the high priesthood and remained highly influential; Caiaphas held the office at this time. The family network reminds the reader how close this hearing is to the trial scenes at the end of the Gospels.',cross:[{ref:'John 18:12-14',label:'Earlier hearing',reason:'Jesus was taken first to Annas and then to Caiaphas, the same high-priestly circle now confronting His apostles.'}]},
   {ref:'Acts 4:7-10',title:'The council asks about power and name; Peter answers with a Person.',text:'The question is essentially, “By what authority did you do this?” Peter, filled with the Holy Spirit, refuses to make the healed man or the apostles the center. He names Jesus Christ of Nazareth—crucified by human action, raised by God—as the One by whom the man stands whole.'},
   {ref:'Acts 4:11',title:'Peter uses Psalm 118 to tell the builders that the stone they rejected is now central.',text:'Jesus had already applied the rejected-stone text to Himself. Peter now says the rejection has happened and God has reversed the verdict: the One the builders treated as useless has become the head of the corner.',cross:[{ref:'Psalms 118:22-23',label:'Rejected stone',reason:'Peter draws directly from the psalm’s picture of the rejected stone becoming the chief stone by the LORD’s doing.'},{ref:'Matthew 21:42',label:'Jesus used the same text',reason:'Before His death, Jesus applied Psalm 118:22 to the leaders who were rejecting Him.'}]},
   {ref:'Acts 4:12',title:'“Neither is there salvation in any other” is an exclusive claim about the source of salvation, not permission for contempt.',text:'Peter does not say Christians are better people than everyone else. He says God has given one saving name: Jesus. The verse rules out competing saviors while the rest of Acts sends believers toward every nation with that news, not away from people in superiority or hostility.'},
   {ref:'Acts 4:13',title:'“Unlearned and ignorant” does not mean Peter and John were stupid.',text:'The Greek describes men without the recognized scholarly training of the scribal schools and men regarded as ordinary laypeople. “Ignorant” in older English can sound harsher than Luke’s point. The council is astonished that men without elite credentials speak with such parrēsia—open, confident boldness—and they recognize that Peter and John had been companions of Jesus.'},
   {ref:'Acts 4:14-16',title:'The healed man is standing in the room as evidence the council cannot talk away.',text:'The leaders send the apostles out and confer privately because the public sign is undeniable. Their problem is not lack of evidence that something happened; it is what to do with a sign they do not want spreading further through Jerusalem.'},
   {ref:'Acts 4:17-20',title:'The apostles’ refusal is a narrow conflict of loyalties, not a blanket rejection of civil authority.',text:'The council commands them not to speak or teach at all in Jesus’ name. Peter and John answer that they must obey what is right in God’s sight and cannot stop bearing witness to what they have seen and heard. Scripture elsewhere commands ordinary submission to governing authorities, so Acts 4 should not be stretched into permission to ignore any law a Christian dislikes; the issue here is a direct command to stop obeying Christ’s commission.',cross:[{ref:'Acts 1:8',label:'Direct commission',reason:'Jesus had already appointed the apostles to be His witnesses.'},{ref:'Romans 13:1-7',label:'Ordinary posture toward authority',reason:'Paul normally calls Christians to submission to governing authorities, showing that Acts 4 is not general lawlessness.'}]},
   {ref:'Acts 4:20',title:'“We cannot but speak” is eyewitness language before it becomes a slogan.',text:'Peter and John are not excusing uncontrolled speech. They are explaining why the council’s gag order cannot govern their testimony: they have seen and heard the events they are commissioned to announce.'},
   {ref:'Acts 4:23-26',title:'The church answers threats by praying Scripture back to God.',text:'They begin with God as Creator, then quote Psalm 2 about nations and rulers gathering against the LORD and His Anointed. Their circumstances are not interpreted as proof that God has lost control; opposition itself is placed inside a Scripture-shaped understanding of God’s kingdom.',cross:[{ref:'Psalms 2:1-2',label:'Prayer shaped by Scripture',reason:'The believers quote the psalm about rulers gathering against the LORD and His Anointed.'}]},
   {ref:'Acts 4:27-28',title:'Herod, Pilate, Gentiles, and people of Israel are all named, while God’s purpose is still affirmed.',text:'The KJV’s “holy child Jesus” again uses the Greek pais; many translations render “holy Servant Jesus,” echoing the Servant language already heard in Acts 3. Luke then refuses to solve the mystery by erasing either human responsibility or divine sovereignty: real people opposed Jesus and are named for it, while the church confesses that God’s hand and counsel were not defeated by their actions.'},
   {ref:'Acts 4:29-30',title:'They do not pray for revenge—and they do not even make personal safety the center of the prayer.',text:'They ask God to notice the threats, give His servants boldness, and continue confirming Jesus’ name through healing and signs. Courage here is not personality or bravado; it is grace requested by people who know the danger is real.'},
   {ref:'Acts 4:31',title:'Being filled with the Holy Spirit happens again after Pentecost.',text:'These believers have already received the Spirit, yet Luke can describe a fresh filling connected with a particular moment of prayer and witness. The repeated filling does not undo Pentecost; it shows ongoing divine empowerment for the work Jesus gave them. The result is exactly what they requested: they speak the word of God with boldness.'},
   {ref:'Acts 4:32-35',title:'“All things common” describes voluntary generosity, not the abolition of private ownership by force.',text:'Believers stop treating possessions as untouchable private islands and make resources available so needs can be met. Acts 5:4 will make the voluntary nature explicit: property remained under the owner’s control before it was sold, and the proceeds remained under the owner’s authority afterward. The passage challenges possessiveness and neglect of the poor; it does not authorize coercion or a promise that generous Christians will become rich.',cross:[{ref:'Acts 5:4',label:'Voluntary ownership',reason:'Peter tells Ananias that the property remained his and, after sale, the money was still at his disposal.'}]},
   {ref:'Acts 4:33-35',title:'Powerful resurrection witness and practical care for the needy belong in the same paragraph.',text:'The apostles give witness to the resurrection with great power, great grace rests on the community, and Luke immediately says there is no needy person among them because believers are sharing. Acts does not force a choice between proclaiming Christ and caring for material need.',cross:[{ref:'Deuteronomy 15:4',label:'Covenant ideal',reason:'Israel’s law held out the hope that there would be no poor among them when the covenant community lived open-handedly before God.'}]},
   {ref:'Acts 4:36-37',title:'Barnabas enters the story through an act of generosity before he becomes a missionary partner.',text:'Luke introduces Joseph—called Barnabas, “son of encouragement”—as a Levite from Cyprus who sells a field and places the money at the apostles’ feet. His example closes Acts 4 positively and also prepares the contrast with Ananias and Sapphira in Acts 5: the issue will not be whether property must be sold, but truthfulness before God.'}
  ],
  reflections:['When pressure rises, do I pray mainly for the pressure to disappear, or also for courage to remain faithful inside it?','Would the way I speak and respond make it believable that I have been with Jesus?','What possession, resource, or convenience do I tend to call “mine” in a way that keeps me from noticing another person’s real need?'],
  commentary:{voice:'John Chrysostom',identity:'Archbishop of Constantinople and early Christian preacher, c. 347–407',quote:'They do not say, “Crush them, cast them down.”',plain:'Chrysostom notices what the threatened church does not ask God to do. They bring the threats to God, but instead of making revenge the prayer’s center, they ask for boldness to keep speaking. Their confidence is not denial of danger; it is a request to remain useful to God while danger is present.',source:'Homily XI on the Acts of the Apostles — Acts 4:23–37',url:'https://www.newadvent.org/fathers/210111.htm'},
  question:{q:'Does Acts 4 teach Christians to disobey the government whenever they believe a law is wrong?',short:'No. Peter and John refuse one specific command because it directly forbids the witness Jesus commanded them to give. Acts 4 gives a real limit to human authority, not a general excuse for lawlessness.',more:'Peter and John do not announce that the council has no authority at all. They ask whether it is right in God’s sight to listen to the council rather than to God when the council commands them to stop speaking about Jesus. Their refusal is tied to a direct divine commission: Jesus told them to be His witnesses, and they have personally seen and heard what they are commanded to proclaim. Elsewhere the New Testament normally calls believers to respect and submit to governing authorities. Christians may disagree about some modern applications, especially where laws and conscience interact, but Acts 4 is clearest where obedience to a human command would require direct disobedience to God.'}
 }
});
render();
