// Acts 19 — Living Bookmark card.
Object.assign(studies,{
 'Acts 19':{body:''}
});

Object.assign(studyMeta,{
 'Acts 19':{
  oneLine:'Paul returns to Ephesus and meets disciples who know only John’s baptism, teaches them fully about Jesus, and sees the Holy Spirit come upon them; after sustained teaching in the hall of Tyrannus, extraordinary healings and the humiliating failure of the sons of Sceva expose the difference between Jesus’ authority and magical technique, leading many believers to renounce occult practices publicly; as the word grows, the gospel threatens the profitable Artemis trade and Demetrius helps ignite a citywide uproar in the theater.',
  write:[
   {ref:'Acts 19:5',title:'Incomplete understanding is not treated as shameful when people are willing to receive more truth.',text:'These disciples learn more fully about Jesus and respond.'},
   {ref:'Acts 19:10',title:'Patient teaching can reach far beyond the room where it begins.',text:'Two years of steady ministry in Ephesus spreads the word throughout Asia.'},
   {ref:'Acts 19:15',title:'Jesus’ name is not spiritual technology.',text:'The evil spirit recognizes Jesus and Paul, but the borrowed formula of the exorcists has no authority of its own.'},
   {ref:'Acts 19:18',title:'Real repentance brings hidden things into the light.',text:'Believers openly confess the practices they are leaving behind.'},
   {ref:'Acts 19:19',title:'Some things are worth abandoning even when they are expensive.',text:'The magic books are destroyed rather than kept because they still have monetary value.'},
   {ref:'Acts 19:20',title:'The chapter’s true measure of power is the growth of God’s word.',text:'After signs, conflict, confession, and costly repentance, Luke says the word grew mightily and prevailed.'}
  ],
  underline:{ref:'Acts 19:20',reason:'Luke summarizes the whole Ephesian struggle this way: the word of the Lord grows in strength and prevails over rival claims to spiritual power.'},
  notice:[
   {ref:'Acts 19:1-3',title:'These “disciples” know John’s baptism but have not yet heard the full Christian message.',text:'Their exact status is debated because Luke calls them disciples, yet their knowledge stops with John the Baptist. They have not even heard that the Holy Spirit has been given in the new-covenant sense. Paul therefore does not assume that religious language always means the same thing; he asks what they actually know.'},
   {ref:'Acts 19:4-5',title:'John’s baptism pointed forward; Christian baptism looks to the Jesus who has now come.',text:'Paul explains that John preached repentance while directing people to believe in the One coming after him—Jesus. These men then receive baptism in the name of the Lord Jesus. Acts presents their earlier experience as preparation, not as a substitute for the fulfilled gospel.'},
   {ref:'Acts 19:6-7',title:'The Spirit’s coming here resembles earlier boundary moments in Acts, but the sequence is not identical everywhere.',text:'Paul lays hands on the men, the Holy Spirit comes upon them, and they speak in tongues and prophesy. Christians differ over whether this supplies a normal pattern for a second experience after conversion or belongs especially to transitional moments in Acts. The book itself records more than one sequence, so the narrative should not be forced into a mechanical formula.'},
   {ref:'Acts 19:8-10',title:'Paul shifts locations when opposition hardens, but he does not abandon Ephesus.',text:'After three months of synagogue reasoning, some become hardened and publicly speak evil of “the Way.” Paul withdraws the disciples and teaches daily in the hall of Tyrannus. A closed door becomes a changed venue, not the end of the mission.'},
   {ref:'Acts 19:9',title:'“The Way” is one of Acts’ recurring names for the Christian movement.',text:'Before “Christianity” became a common label, Acts often describes believers as belonging to “the Way.” The phrase fits a faith centered on following Jesus as Lord, not merely assenting to a list of ideas.'},
   {ref:'Acts 19:10',title:'“All they which dwelt in Asia heard the word” does not mean Paul personally preached to every individual.',text:'Asia here means the Roman province in western Asia Minor, not the modern continent. Ephesus was a major regional center, and Paul’s long teaching ministry evidently multiplied through coworkers and traveling hearers so that the message spread widely from the city.'},
   {ref:'Acts 19:11-12',title:'The handkerchiefs and aprons are extraordinary signs, not a recipe for selling “anointed objects.”',text:'Luke explicitly calls these unusual miracles that God worked through Paul. The power belongs to God, not to fabric, and the next story immediately warns against trying to turn Jesus’ authority into a controllable technique. The passage gives no support to commercializing blessed cloths or promising automatic healing through objects.'},
   {ref:'Acts 19:13-16',title:'The sons of Sceva treat Jesus’ name like an additional incantation in an exorcist’s toolkit.',text:'They invoke “Jesus whom Paul preacheth,” attempting to borrow authority without belonging to Jesus. The evil spirit’s answer is devastating: “Jesus I know, and Paul I know; but who are ye?” In Acts, the name of Jesus means His person and authority, not a magic sequence of syllables.'},
   {ref:'Acts 19:14',title:'“Sceva, a Jew, and chief of the priests” is historically unusual wording.',text:'No Jewish high priest named Sceva is known from the standard lists. The description may refer to someone from a priestly family, a self-styled title used in exorcist circles, or another kind of prominent priestly claim. Luke’s point does not depend on resolving the title: religious pedigree cannot manufacture Jesus’ authority.'},
   {ref:'Acts 19:17',title:'The failed exorcism produces fear and honor for Jesus’ name rather than admiration for Paul.',text:'The story becomes known throughout Ephesus, and the result is that the name of the Lord Jesus is magnified. Acts repeatedly redirects attention away from the human instrument toward Christ Himself.'},
   {ref:'Acts 19:18-19',title:'Some of the people confessing occult practices are already described as believers.',text:'Their conversion has begun, but repentance reaches further into habits and loyalties that still need to be renounced. Acts does not assume every destructive attachment disappears instantly at the first moment of faith.'},
   {ref:'Acts 19:19',title:'Ephesus was famous for magical formulas and “Ephesian letters.”',text:'Ancient sources associate Ephesus with charms, incantations, and written formulas believed to carry supernatural power. The public burning of magic books therefore strikes directly at a practice deeply embedded in the city’s religious culture. The converts do not sell the books to someone else; they destroy what they now believe should not continue circulating.'},
   {ref:'Acts 19:19',title:'The “fifty thousand pieces of silver” describes enormous value, but the exact modern dollar figure cannot be recovered.',text:'Luke does not identify the precise coin. Many interpreters understand the amount in silver drachmas, which would represent many years of ordinary wages. Any modern currency conversion is only approximate because ancient wages, purchasing power, and coin standards do not map neatly onto today’s money.'},
   {ref:'Acts 19:21-22',title:'Paul’s desire to see Rome becomes part of the book’s forward movement.',text:'He resolves to pass through Macedonia and Achaia, go to Jerusalem, and then says, “I must also see Rome.” He will indeed reach Rome, but not by the straightforward itinerary a traveler might imagine. Acts will show God accomplishing the destination through arrest, trials, and shipwreck.'},
   {ref:'Acts 19:23-27',title:'Demetrius’ deepest argument is economic before it becomes religious.',text:'He gathers craftsmen whose income depends on silver shrines of Artemis and first reminds them that “by this craft we have our wealth.” Only then does he expand the warning to the honor of Artemis and her temple. The gospel threatens more than ideas when an industry profits from practices people begin abandoning.'},
   {ref:'Acts 19:24-27',title:'Artemis of Ephesus was not simply the Greek hunting goddess in ordinary form.',text:'Ephesian Artemis had a distinctive local cult and one of the ancient Mediterranean world’s most famous temples. Pilgrims, civic identity, religious devotion, and commerce were intertwined. Challenging handmade gods therefore touched the city’s economy, prestige, and identity all at once.'},
   {ref:'Acts 19:26',title:'“They be no gods, which are made with hands” is a biblical argument as well as an economic threat.',text:'Paul’s preaching exposes the contradiction in manufacturing a deity. Israel’s prophets had long mocked idols made by human hands. In Ephesus, that theology directly threatens a trade built on producing sacred images.',cross:[{ref:'Isaiah 44:9-17',label:'Prophetic background',reason:'Isaiah exposes the absurdity of using part of a piece of wood for ordinary life and another part to manufacture a god.'}]},
   {ref:'Acts 19:28-34',title:'The theater scene shows how quickly economic fear, religious identity, and crowd emotion can fuse together.',text:'The crowd shouts “Great is Diana of the Ephesians,” seizes Paul’s companions, and fills the theater. Luke adds the almost comic detail that many people do not even know why they have assembled. A crowd can become intensely certain before it becomes informed.'},
   {ref:'Acts 19:30-31',title:'Paul wants to enter the theater, but disciples and friendly Asiarchs stop him.',text:'Courage is not the same as ignoring wise restraint. The Asiarchs were prominent provincial figures connected with civic and religious life, and Luke surprisingly calls some of them Paul’s friends. Accepting their warning does not make Paul less bold.'},
   {ref:'Acts 19:35-41',title:'The town clerk calms the riot by appealing to law, evidence, and proper civic process.',text:'He says Paul’s companions are neither temple robbers nor blasphemers of Artemis, points Demetrius toward the courts and lawful assemblies, and warns that the city itself could be accused of rioting without cause. Acts again shows that Christian mission is not identical with mob disorder, even when the gospel disrupts entrenched interests.'},
   {ref:'Acts 19:37',title:'The KJV’s “robbers of churches” means temple robbers, not people stealing from Christian congregations.',text:'In older English, “churches” could be used for sacred buildings. The Greek word hierosylous refers to robbers of temples or sacred places. The town clerk is saying Paul’s companions have not looted Artemis’ temple.'}
  ],
  reflections:['Is there anything I have tried to use spiritually as a technique instead of relating to Jesus Himself?','What would costly repentance look like if I stopped asking what an old habit is worth and started asking whether it should remain in my life?','When faith challenges something profitable, comfortable, or socially admired, which interest usually gets my loyalty first?'],
  commentary:{voice:'Alexander Maclaren',identity:'Scottish Baptist preacher and expositor, 1826–1910',quote:'men are very quick to take alarm when their pockets are threatened',plain:'Maclaren notices the order in Demetrius’ speech. The craftsmen defend Artemis, but the meeting begins because their income is in danger. Acts 19 is a sharp reminder that spiritual resistance can hide inside economic self-interest—and that the gospel becomes disruptive when people actually stop buying what their old worship required.',source:'Expositions of Holy Scripture — Acts 19',url:'https://biblehub.com/commentaries/maclaren/acts/19.htm'},
  question:{q:'Why were people baptized again in Acts 19 if they had already received John’s baptism?',short:'Because John’s baptism was preparatory. These disciples had received his repentance baptism but had not yet understood the completed gospel of Jesus and the giving of the Holy Spirit.',more:'John the Baptist deliberately pointed beyond himself. His baptism called Israel to repentance while preparing people for the One coming after him. By Acts 19, Jesus has died, risen, been exalted, and poured out the Holy Spirit. When Paul discovers that these disciples know only John’s baptism, he supplies the missing center: John told people to believe in the One coming after him, that is, Jesus. They are then baptized in the name of the Lord Jesus, and the Spirit comes upon them as Paul lays hands on them. Christian traditions differ over how this episode relates to later practices of baptism, confirmation, and receiving the Spirit, but the basic reason for the new baptism is clear: John’s preparatory ministry was never meant to remain the final destination once the Messiah had come.'}
 }
});
render();
