// Acts 20 — Living Bookmark card.
Object.assign(studies,{
 'Acts 20':{body:''}
});

Object.assign(studyMeta,{
 'Acts 20':{
  oneLine:'Paul strengthens believers through Macedonia and Greece, travels with a diverse group of companions, restores Eutychus after a fatal fall during a long gathering at Troas, and then summons the Ephesian elders to Miletus for a tearful farewell: he reminds them of his humble public and house-to-house ministry, declares his determination to finish the course Jesus gave him, charges the elders to shepherd God’s flock against wolves from outside and distortion from within, commends them to God and the word of His grace, and leaves them with Jesus’ saying that it is more blessed to give than to receive.',
  write:[
   {ref:'Acts 20:7',title:'The church gathers around word and table.',text:'Teaching and breaking bread belong together in the Troas gathering.'},
   {ref:'Acts 20:20',title:'Paul did not keep back what was useful because it was difficult.',text:'He taught publicly and from house to house.'},
   {ref:'Acts 20:24',title:'Finishing faithfully matters more to Paul than preserving comfort.',text:'His aim is to complete the ministry he received from Jesus.'},
   {ref:'Acts 20:27',title:'Love does not edit out difficult truth.',text:'Paul says he did not shrink from declaring the whole counsel of God.'},
   {ref:'Acts 20:28',title:'Leaders must watch themselves before they watch the flock.',text:'Paul begins, “Take heed therefore unto yourselves.”'},
   {ref:'Acts 20:35',title:'Christian strength bends toward the weak.',text:'Paul remembers Jesus’ words: “It is more blessed to give than to receive.”'}
  ],
  underline:{ref:'Acts 20:24',reason:'Paul knows suffering is ahead, yet measures his life by whether he finishes the course and ministry Jesus entrusted to him.'},
  notice:[
   {ref:'Acts 20:1-3',title:'After the Ephesian riot, Paul strengthens believers and keeps moving.',text:'He travels through Macedonia and into Greece encouraging disciples rather than letting the uproar become the final story. Acts repeatedly shows ministry continuing after disruption without pretending disruption never hurts.'},
   {ref:'Acts 20:3-6',title:'The travel party reflects the widening mission—and probably helps make the Jerusalem collection accountable.',text:'Luke names companions from several regions, then resumes the “we” narration as the group sails from Philippi. Many interpreters connect these representatives with the collection for poor believers in Jerusalem, giving visible accountability for donated money.',cross:[{ref:'2 Corinthians 8:19-21',label:'Financial accountability',reason:'Paul describes a brother chosen by the churches to travel with the gift and stresses handling the collection honorably before God and people.'}]},
   {ref:'Acts 20:7',title:'The first-day gathering joins word, fellowship, and table.',text:'The believers meet on the first day of the week to break bread while Paul teaches before leaving the next day. This is important evidence for early Sunday gathering, though Christians differ over whether “breaking bread” here should be understood mainly as a fellowship meal, the Lord’s Supper, or both. Paul’s unusually long speech belongs to a farewell night, not a rule that faithful sermons must last until midnight.'},
   {ref:'Acts 20:8-12',title:'Luke presents Eutychus as dead and restored—and does not scold him for falling asleep.',text:'The young man falls from the third story and is “taken up dead.” Paul embraces him, his life is restored, and the believers are greatly comforted. The scene recalls Elijah and Elisha without Luke explicitly claiming a direct fulfillment, and it turns a tragic accident into mercy rather than a lesson about lazy listeners.',cross:[{ref:'1 Kings 17:21-22',label:'Elijah and the widow’s son',reason:'Elijah stretches himself upon the child and cries to the LORD before the child’s life returns.'},{ref:'2 Kings 4:34-35',label:'Elisha and the Shunammite’s son',reason:'Elisha similarly embraces the child before the boy revives.'}]},
   {ref:'Acts 20:13-16',title:'The detailed travel notes show urgency toward Jerusalem without erasing Paul’s affection for Ephesus.',text:'Paul travels part of the route on foot, rejoins the ship, and deliberately bypasses Ephesus because he hopes to reach Jerusalem by Pentecost. Rather than entering the city and risking a long delay, he asks the Ephesian elders to meet him at Miletus.'},
   {ref:'Acts 20:17-21',title:'Paul points the elders to the manner and substance of his ministry.',text:'He reminds them of humility, tears, endurance, and teaching both publicly and in homes. What he calls “profitable” is then defined by repentance toward God and faith toward Jesus—not material prosperity or whatever happens to be popular.'},
   {ref:'Acts 20:22-23',title:'“Bound in the spirit” is slightly ambiguous, but the direction is clear.',text:'The phrase can refer to Paul’s own spirit inwardly constrained or to the Holy Spirit compelling him; the next verse explicitly names the Holy Spirit as testifying that imprisonment and suffering await. Paul knows enough to obey without knowing every detail of what will happen.'},
   {ref:'Acts 20:24',title:'The KJV’s “finish my course with joy” has a manuscript note—and Paul’s point is not contempt for life.',text:'“With joy” appears in the KJV and later manuscript tradition but is absent from many early witnesses. The shorter reading may sharpen the thought: Paul values life as God’s gift, but not so highly that he will abandon the ministry Jesus entrusted to him merely to preserve himself.'},
   {ref:'Acts 20:26-27',title:'“Pure from the blood of all men” and “the whole counsel of God” belong together.',text:'Paul echoes Ezekiel’s watchman: he has faithfully given the warning and therefore is not responsible for another person’s refusal. Declaring the whole counsel of God does not mean every sermon contains every doctrine; it means he did not deliberately hide parts of God’s truth because they were difficult or unpopular.',cross:[{ref:'Ezekiel 33:7-9',label:'Watchman responsibility',reason:'The watchman must give the warning; after faithful warning, responsibility rests with the hearer’s response.'}]},
   {ref:'Acts 20:17, 28',title:'The same men are called elders and overseers and are told to shepherd God’s flock.',text:'Paul summons the presbyteroi—elders—and says the Holy Spirit made them episkopoi—overseers—to shepherd or pastor the church. Later traditions developed different structures and titles, but this passage shows significant overlap in first-century elder, overseer, and shepherd language. The flock belongs to God; leaders are stewards, not owners.'},
   {ref:'Acts 20:28',title:'“The church of God … purchased with his own blood” carries an important textual and translation discussion.',text:'The strongest manuscript evidence supports “church of God,” though some witnesses read “church of the Lord.” The final phrase can be rendered “with his own blood” or understood as “with the blood of his own [Son].” Either way, the church’s worth rests on Christ’s costly saving work, not on the status of its leaders.'},
   {ref:'Acts 20:29-31',title:'The flock will face danger from outside and distortion from inside.',text:'Paul warns of savage wolves entering from outside and men arising from among the leaders themselves to draw disciples after them. Office and insider status never make teaching immune from examination. Paul says his own warnings came over years and with tears, showing that vigilance can be tender rather than harsh.'},
   {ref:'Acts 20:32',title:'Paul ultimately entrusts the church to God, not to permanent access to Paul.',text:'He commends the elders to God and to the word of His grace, which is able to build them up and give the promised inheritance. Healthy ministry prepares people to depend on God when a beloved teacher is no longer present.'},
   {ref:'Acts 20:33-35',title:'Paul’s manual labor guards against greed and makes room to help the weak.',text:'He coveted no one’s silver, gold, or clothing and reminds them that his own hands supplied needs. This does not cancel the biblical right of ministers to receive support; here Paul is modeling freedom from greed and generosity toward vulnerable people.'},
   {ref:'Acts 20:35',title:'“It is more blessed to give than to receive” preserves a saying of Jesus not found in the four Gospels.',text:'Paul explicitly attributes these words to the Lord Jesus. They show that authentic sayings of Jesus circulated in early Christian memory beyond those selected for the written Gospel accounts.',cross:[{ref:'John 21:25',label:'Not everything was written',reason:'John closes by saying Jesus did many other things beyond what his Gospel records.'}]},
   {ref:'Acts 20:36-38',title:'The farewell ends on its knees and in tears.',text:'Paul kneels with the elders and prays. They weep, embrace him, and grieve most because he believes they will not see his face again. Acts does not treat deep Christian attachment as weakness; love makes separation painful.'}
  ],
  reflections:['Is there any truth I am tempted to avoid because it feels difficult, unpopular, or personally costly?','If I knew I had limited time with people I loved, what would I most want my life and words to have taught them?','Do I think of Christian leadership as influence I possess, or as people belonging to God whom I am temporarily entrusted to serve?'],
  commentary:{voice:'Charles Simeon',identity:'Anglican evangelical preacher and pastor, 1759–1836',quote:'the trials with which a faithful discharge of our duty is attended are proportionably great',plain:'Simeon notices that Paul’s courage is not courage in an easy assignment. Paul knows bonds and suffering are ahead and still measures success by finishing the ministry Jesus gave him. Faithfulness is not proved by having no cost; sometimes the cost is exactly what reveals what we value most.',source:'Horae Homileticae — Acts 20:24, “Duty of Ministers”',url:'https://www.truthaccordingtoscripture.com/commentaries/shh/acts-20.php'},
  question:{q:'What does Paul mean when he says he declared “all the counsel of God” in Acts 20:27?',short:'He means he did not knowingly withhold the truth God entrusted him to teach. It does not mean every sermon contained every doctrine, but that over his ministry he refused to edit God’s message down to only the comfortable parts.',more:'The surrounding verses explain the phrase. Paul says he kept back nothing that was profitable, taught publicly and from house to house, testified about repentance toward God and faith in Jesus, and warned people with tears. “The whole counsel of God” therefore describes the integrity and breadth of his teaching rather than the impossible idea that every biblical subject appeared in every message. It also gives Christian teachers a guardrail: relevance does not mean avoiding hard truths, and doctrinal thoroughness does not mean dumping every truth into every conversation. Paul knew these believers over years. Faithful teaching gives people what they need across time without deliberately hiding what God has said.'}
 }
});
render();
