// Acts 9 — Living Bookmark card.
Object.assign(studies,{
 'Acts 9':{body:''}
});

Object.assign(studyMeta,{
 'Acts 9':{
  oneLine:'Saul travels toward Damascus to arrest followers of “the Way” but is confronted by the risen Jesus, blinded, led helplessly into the city, welcomed by the disciple Ananias, healed, filled with the Holy Spirit, baptized, and soon preaching the Son of God he once opposed; after danger in Damascus and suspicion in Jerusalem, Barnabas helps the church receive him, while Peter’s ministry in Lydda and Joppa brings healing, Tabitha’s restoration to life, and a quiet final detail that prepares him for the Gentile breakthrough to come.',
  write:[
   {ref:'Acts 9:4-5',title:'Jesus takes persecution of His people personally.',text:'“Why persecutest thou me?” binds the risen Christ to the suffering of His body.'},
   {ref:'Acts 9:11',title:'The feared persecutor is now described with two ordinary words: “he prayeth.”',text:'Before Saul preaches publicly, Luke lets us see him helpless and praying.'},
   {ref:'Acts 9:17',title:'Ananias calls him “Brother Saul” before Saul has had time to prove himself.',text:'Grace enters the room through a disciple who was understandably afraid.'},
   {ref:'Acts 9:20',title:'The man who came to silence Jesus’ name begins proclaiming Him.',text:'Saul’s first message in the synagogues is that Jesus is the Son of God.'},
   {ref:'Acts 9:27',title:'Barnabas stands beside the person everyone else is afraid to trust.',text:'He does not ignore Saul’s past; he tells the apostles what Christ has done.'},
   {ref:'Acts 9:31',title:'The church grows in both fear of the Lord and comfort of the Holy Spirit.',text:'Reverence and consolation are not opposites in a healthy Christian life.'}
  ],
  underline:{ref:'Acts 9:15',reason:'Jesus names the former persecutor as a chosen vessel who will carry His name before Gentiles, kings, and the children of Israel.'},
  notice:[
   {ref:'Acts 9:1-2',title:'Saul is not merely angry; he is using institutional authority to widen the persecution beyond Jerusalem.',text:'He requests letters to Damascus synagogues so that followers of Jesus—men or women—can be bound and taken to Jerusalem. The movement is called “the Way,” an early description that suggests a whole path of allegiance and life, not merely a set of opinions.'},
   {ref:'Acts 9:3-5',title:'The risen Jesus identifies Himself with the disciples Saul is hurting.',text:'Saul has been arresting Christians, yet the heavenly question is “Why persecutest thou me?” Jesus does not erase the distinction between Himself and His people, but He treats violence done to them as violence directed against Him. The church’s suffering matters personally to its Lord.',cross:[{ref:'Matthew 25:40',label:'Christ identifies with His people',reason:'Jesus likewise describes treatment of His brothers and sisters as treatment rendered to Him.'}]},
   {ref:'Acts 9:5-6',title:'Two familiar KJV phrases here come from later textual expansion, though both ideas appear elsewhere in Acts.',text:'“It is hard for thee to kick against the pricks” is strongly attested in Paul’s later account at Acts 26:14, but the earliest and strongest manuscripts do not have it here in Acts 9:5. Likewise “trembling and astonished” and “Lord, what wilt thou have me to do?” in the KJV’s opening of verse 6 appear to have been supplied from the parallel conversion accounts. The sayings are biblical; the textual question is simply where Luke originally wrote them.',cross:[{ref:'Acts 26:14',label:'The goads saying is securely present here',reason:'Paul’s later testimony includes Jesus’ proverb about kicking against the goads.'},{ref:'Acts 22:10',label:'Paul asks what to do',reason:'The question “What shall I do, Lord?” is securely recorded in Paul’s Jerusalem testimony.'}]},
   {ref:'Acts 9:6-9',title:'Saul enters Damascus in the opposite posture from the one he planned.',text:'He intended to arrive with authority, names, letters, and prisoners. Instead he must be led by the hand, cannot see, and eats or drinks nothing for three days. His first experience after meeting Jesus is dependence.'},
   {ref:'Acts 9:7',title:'Acts 9 says Saul’s companions hear the voice, while Acts 22 says they did not hear the voice of the One speaking to him.',text:'The Greek verb for hearing can describe perceiving a sound or understanding an articulated message, and the two passages use different grammatical constructions. A common explanation is that the companions heard the sound but did not comprehend the words addressed to Saul. Some scholars simply acknowledge a minor difference in the retellings. Either way, all three accounts agree that Saul receives the revelatory message in a way his companions do not.',cross:[{ref:'Acts 22:9',label:'Paul retells the event',reason:'Paul says his companions saw the light but did not hear or understand the voice of the One speaking to him.'},{ref:'Acts 26:14',label:'A third retelling',reason:'Paul later says the whole party fell to the ground, while the words from Jesus are addressed to him.'}]},
   {ref:'Acts 9:10-16',title:'Ananias is allowed to tell Jesus why this assignment frightens him.',text:'The Lord does not rebuke Ananias merely for knowing Saul’s reputation. Ananias has heard how much harm Saul has done and knows why he came to Damascus. Jesus answers the fear with information Ananias could not know on his own: Saul is a chosen vessel, his mission will cross enormous boundaries, and suffering will be part of that calling.'},
   {ref:'Acts 9:11',title:'“Behold, he prayeth” is one of the quietest signs that Saul’s direction has changed.',text:'Saul was already religious before Damascus; he knew Scripture and believed he was serving God. Yet Luke marks this particular prayer because Saul is now waiting on the Lord he had opposed, stripped of control and receiving rather than directing the next step.'},
   {ref:'Acts 9:15-16',title:'Saul’s calling includes both enormous usefulness and real suffering.',text:'Jesus does not promise him a protected career as reward for conversion. His name will go before Gentiles, kings, and Israel, and Saul will learn what he must suffer for that name. In Acts, calling is not a guarantee of comfort.'},
   {ref:'Acts 9:17-18',title:'Ananias is a disciple—not one of the Twelve—yet Christ uses him at one of the most important turning points in Acts.',text:'He lays hands on Saul, calls him brother, announces that Jesus sent him, and Saul regains sight and is filled with the Holy Spirit before being baptized. The risen Christ chooses an ordinary faithful disciple to be the first Christian face Saul meets after his encounter.'},
   {ref:'Acts 9:17',title:'“Brother Saul” is not sentimental denial of what Saul has done.',text:'Ananias has just named Saul’s violence in prayer. Calling him brother means Ananias is acting on Jesus’ declaration about Saul rather than requiring Saul to erase his past before being received. Grace tells the truth about the danger and still obeys Christ’s welcome.'},
   {ref:'Acts 9:19-22',title:'Acts compresses Saul’s early years more tightly than Galatians does.',text:'Luke moves quickly from “certain days” in Damascus to Saul’s preaching and later says “after many days” the plot to kill him developed. In Galatians, Paul tells us that he also went into Arabia and returned to Damascus, and that three years passed before his first Jerusalem visit. These accounts can fit if Luke is summarizing a longer period rather than narrating every movement.',cross:[{ref:'Galatians 1:15-18',label:'Paul’s own timeline',reason:'Paul says he went into Arabia, returned to Damascus, and after three years went up to Jerusalem.'}]},
   {ref:'Acts 9:20-22',title:'Saul’s argument is not “I have a new religion”; it is that Jesus is the promised Christ and Son of God.',text:'He enters the very synagogues for which he had requested arrest authority and now proclaims the One he meant to suppress. His knowledge of Israel’s Scriptures has not become useless; it is being re-read around Jesus.'},
   {ref:'Acts 9:23-25',title:'The escape in a basket matches Paul’s own later memory—and it is not a glamorous beginning.',text:'Paul later recalls that an official under King Aretas guarded Damascus to seize him and that he escaped through a window in a basket. The man chosen to stand before kings begins his missionary life being lowered over a wall at night. Divine calling and humiliating dependence can occupy the same story.',cross:[{ref:'2 Corinthians 11:32-33',label:'Paul remembers the escape',reason:'Paul himself later describes being lowered through a window in a basket at Damascus while the city was being watched.'}]},
   {ref:'Acts 9:26-28',title:'The Jerusalem disciples’ fear is reasonable, and Barnabas becomes the bridge between a changed man and a wounded community.',text:'They do not instantly trust the person who had recently terrorized believers. Barnabas brings Saul to the apostles and recounts both Saul’s encounter with the Lord and his bold preaching in Damascus. Forgiveness does not require pretending trust never needs evidence or mediation.'},
   {ref:'Acts 9:29-30',title:'Saul now debates the same Greek-speaking Jewish circles connected with Stephen—and receives the kind of hostility he once supported.',text:'The Hellenists attempt to kill him, so the believers send him through Caesarea to Tarsus. Luke’s symmetry is sobering: Saul has crossed from approving Stephen’s death to risking death for the same Jesus.'},
   {ref:'Acts 9:31',title:'The oldest textual form pictures “the church” in the singular across Judea, Galilee, and Samaria.',text:'The KJV follows a later Greek tradition reading “churches,” while many early manuscripts read the singular. The singular gives a beautiful picture of one church spread across several regions—built up, walking in the fear of the Lord and in the comfort or encouragement of the Holy Spirit.'},
   {ref:'Acts 9:32-35',title:'Peter tells Aeneas that Jesus Christ heals him; Peter does not claim the healing as his own power.',text:'The command “Arise, and make thy bed” displays immediate restoration after eight years of paralysis, but Peter names Jesus as the healer. The sign then turns attention beyond the healed man as people in Lydda and Sharon turn to the Lord.'},
   {ref:'Acts 9:36-39',title:'Tabitha’s ministry is described through the people who actually received it.',text:'Her Aramaic name Tabitha and Greek name Dorcas both mean gazelle. Luke calls her a disciple and says she was full of good works and acts of mercy. When she dies, the widows stand around Peter showing clothing she made while she was with them. Her quiet work has left visible evidence in other people’s lives.'},
   {ref:'Acts 9:40-42',title:'Peter sends everyone out and prays before he speaks to Tabitha.',text:'The scene resembles earlier biblical restoration stories and also Jesus raising Jairus’s daughter, but Peter’s prayer makes the source of power clear. He does not perform a technique. He depends on God, then tells Tabitha to arise, and the restoration leads many in Joppa to believe in the Lord.',cross:[{ref:'Mark 5:40-42',label:'A narrative echo',reason:'Jesus also puts mourners out before speaking to Jairus’s daughter and raising her.'}]},
   {ref:'Acts 9:43',title:'Peter staying with Simon the tanner quietly prepares the reader for Acts 10.',text:'Tanning involved dead animal hides and was regarded by many strict Jews as ceremonially and socially distasteful work. Peter is already willing to lodge for many days in a home connected with an occupation at the edge of purity sensibilities. He still needs the vision of Acts 10, but Luke has placed him in a setting where old boundary assumptions are already being stretched.'}
  ],
  reflections:['Is there someone whose past makes it hard for me to imagine that Christ could truly redirect their life?','When I am afraid of obeying God, can I name the fear honestly as Ananias did and still be willing to go?','Do I leave behind the kind of quiet evidence Tabitha did—ordinary acts of mercy that other people can actually hold in their hands?'],
  commentary:{voice:'Charles John Ellicott',identity:'English bishop and New Testament scholar, 1819–1905',quote:'Silence and submission, and acquiescence in ignorance of the future',plain:'Ellicott notices that Jesus does not hand Saul the whole map on the Damascus road. Saul is told to enter the city and wait. The man who arrived determined to control other people is taught dependence one step at a time. Conversion changes not only what Saul believes but who gets to direct the future.',source:'Commentary for English Readers — Acts 9:6',url:'https://biblehub.com/commentaries/acts/9-6.htm'},
  question:{q:'Did Saul “convert” from Judaism to Christianity, or was Acts 9 mainly a calling?',short:'Acts 9 is both a radical turning to Jesus and a commissioning. Saul does not stop believing in Israel’s God or Scriptures; he becomes convinced that the Jesus he opposed is Israel’s risen Messiah and Lord, and his entire allegiance and mission are redirected around Him.',more:'Modern labels can be awkward here because “Christianity” had not yet become a separate social religion in the way the word often means today. Saul remains Jewish, continues reasoning from Israel’s Scriptures, and later describes himself as an Israelite. Yet Acts clearly portrays a genuine conversion in the ordinary spiritual sense: the persecutor has been wrong about Jesus, encounters the risen Christ, submits, receives the Spirit, is baptized, joins the disciples, and begins proclaiming the One he tried to destroy. At the same time Jesus explicitly calls him as a chosen vessel for a mission to Gentiles, kings, and Israel. Paul himself later emphasizes both divine revelation and divine calling. Calling does not replace conversion here; the two arrive together in one life-reversing encounter.'}
 }
});
render();
