// John 15 — Living Bookmark card.
Object.assign(studies,{
 'John 15':{body:''}
});

Object.assign(studyMeta,{
 'John 15':{
  oneLine:'Jesus identifies Himself as the True Vine whose branches can bear fruit only by abiding in Him, joins abiding with His word, love, obedience, prayer, and joy, calls the disciples friends who must love one another, then prepares them for the world’s hatred and promises the Spirit’s witness.',
  write:[
   {ref:'John 15:1',title:'Jesus is not one vine among many.',text:'He is the True Vine, and the Father tends the branches.'},
   {ref:'John 15:4',title:'Fruit cannot be manufactured by a disconnected branch.',text:'The command is not “try harder alone” but “abide in me.”'},
   {ref:'John 15:5',title:'Dependence on Christ is not beginner Christianity.',text:'“Without me ye can do nothing.”'},
   {ref:'John 15:9',title:'Jesus places His love for His disciples inside the Father’s love for Him.',text:'“As the Father hath loved me, so have I loved you.”'},
   {ref:'John 15:12',title:'Love one another has a cruciform measure.',text:'Jesus says, “as I have loved you.”'},
   {ref:'John 15:16',title:'Fruitfulness begins with Christ’s initiative.',text:'“Ye have not chosen me, but I have chosen you.”'}
  ],
  underline:{ref:'John 15:5',reason:'The Vine and branches picture says plainly where Christian fruit comes from: abiding union with Christ.'},
  notice:[
   {ref:'John 15:1',title:'“The true vine” carries a strong Old Testament echo.',text:'Israel is repeatedly pictured as God’s vine or vineyard, sometimes tragically unfruitful. Jesus now says, “I am the true vine.” He does not discard Israel’s Scriptures; He gathers the image into Himself. Fruitfulness for God is now centered in union with the Messiah.',cross:[{ref:'Psalm 80:8-9',label:'Vine imagery',reason:'The psalm describes God bringing a vine out of Egypt and planting it.'},{ref:'Isaiah 5:1-7',label:'Vineyard background',reason:'Isaiah pictures Israel as God’s carefully tended vineyard that failed to produce the justice He sought.'}]},
   {ref:'John 15:2-3',title:'The vine picture includes both removal and pruning, and Jesus immediately links pruning with His cleansing word.',text:'The Greek verb in “purgeth” means prune or cleanse, and verse 3 uses the related word “clean.” The popular suggestion that the unfruitful branch is merely “lifted up” rather than taken away is possible as a dictionary sense of the verb airō in other contexts, but “takes away” is the natural reading here and fits the warning in verse 6. We should not soften the passage simply because its warning is uncomfortable.'},
   {ref:'John 15:4-6',title:'Abiding is active dependence, not a mystical slogan detached from Jesus’ words.',text:'A branch has no independent fruit-producing life. Jesus says the same of His disciples: “without me ye can do nothing.” Verse 7 immediately describes abiding in terms of His words remaining in them. The picture joins relationship, teaching, obedience, prayer, and fruit rather than setting them against each other.'},
   {ref:'John 15:7',title:'“Ask what ye will” is conditioned by abiding in Christ and His words abiding in us.',text:'The promise is enormous, but it is not permission to turn prayer into self-directed wish fulfillment. The more Christ’s words shape desires, the more prayer itself is being formed by the Vine. The sentence begins with “If ye abide in me.”'},
   {ref:'John 15:8',title:'Fruit glorifies the Father, but the chapter does not reduce “fruit” to one measurable statistic.',text:'Fruit certainly includes lives reached through witness, but the immediate context also names love, obedience, joy, prayer, and faithful testimony. The image is larger than conversion counts or visible ministry success. A quiet life increasingly shaped by Christ is not fruitless merely because nobody can put it on a chart.'},
   {ref:'John 15:9-11',title:'Obedience is placed inside love, not offered as a price paid to make Jesus love us.',text:'Jesus first says He has loved the disciples as the Father loved Him, then tells them to abide in that love by keeping His commandments. The order matters. Obedience is the life of people remaining in received love, and the stated goal is that Christ’s joy may be in them and their joy full.'},
   {ref:'John 15:12-15',title:'Jesus’ friendship language does not make Him merely one equal friend among the group.',text:'He still commands as Lord and chooses as Master, yet He calls them friends because He has made known what He heard from the Father. The supreme definition of love stands beside it: laying down one’s life for friends, which Jesus is about to do.'},
   {ref:'John 15:16',title:'“Ye have not chosen me, but I have chosen you” speaks first to the apostles He personally appointed.',text:'Christ’s initiative is a real Christian truth, but the immediate “you” is the men He chose and appointed to go and bear lasting fruit in the mission that follows. The verse should not be ripped from that setting solely to settle every later debate about election.'},
   {ref:'John 15:18-21',title:'Jesus prepares disciples for hostility without giving Christians permission to manufacture a persecution complex.',text:'The world hated Him and may hate people who belong to Him. That can be costly and real. But not every criticism of a Christian is persecution for righteousness; sometimes criticism is deserved. The test is faithfulness to Christ, not the mere fact that someone is angry with us.'},
   {ref:'John 15:22-25',title:'Greater revelation brings greater responsibility.',text:'Jesus’ words and works have exposed a refusal that can no longer plead the same ignorance. He quotes the line “They hated me without a cause,” placing His rejection inside the righteous-sufferer language of the Psalms.',cross:[{ref:'Psalm 69:4',label:'Scripture fulfilled',reason:'Jesus applies the psalm’s language of causeless hatred to the rejection He receives.'}]},
   {ref:'John 15:26-27',title:'The chapter ends with two witnesses working together.',text:'The Comforter, the Spirit of truth, will testify of Jesus, and the apostles will also testify because they have been with Him from the beginning. Christian witness is neither human technique without the Spirit nor private spirituality without spoken testimony.'}
  ],
  reflections:['Where am I trying to manufacture fruit by effort while neglecting the ordinary ways Christ tells me to abide in Him?','Is Christ’s word actually shaping what I want when I pray, or do I mostly want Him to endorse desires formed somewhere else?'],
  commentary:{voice:'Alexander Maclaren',identity:'Scottish Baptist preacher and expositor, 1826–1910',quote:'the abiding of His words in us is largely the means of His abiding in us',plain:'Maclaren ties the vine image to something very practical. Abiding is not vague spiritual atmosphere; Jesus’ words are meant to live deep enough in us to shape desires, choices, prayer, and fruit. The branch receives life from the Vine rather than merely thinking admiring thoughts about it.',source:'Expositions of Holy Scripture — John 15',url:'https://biblehub.com/commentaries/maclaren/john/15.htm'},
  question:{q:'Does every painful thing that happens to a Christian mean God is “pruning” them?',short:'No. John 15 teaches that the Father truly prunes fruitful branches, but it does not give us permission to label every illness, loss, conflict, or trauma as a specific pruning act whose hidden purpose we can confidently explain.',more:'The pruning image means the Father is actively committed to His people’s fruitfulness, and His cleansing work is linked immediately with Jesus’ word. Scripture elsewhere shows God using trials to mature faith, so suffering can certainly become part of spiritual growth. But the Bible also contains persecution, human sin, ordinary weakness, grief, and a creation subject to decay. “God can use this” is safer than claiming “I know exactly why God sent this.” John 15 invites trust in the Vinedresser, not confident diagnosis of every wound.'}
 }
});
render();