// Acts 18 — Living Bookmark card.
Object.assign(studies,{
 'Acts 18':{body:''}
});

Object.assign(studyMeta,{
 'Acts 18':{
  oneLine:'Paul settles for a long ministry in Corinth, working with Aquila and Priscilla, reasoning in the synagogue and then teaching nearby after opposition; the Lord tells him not to fear because He is with him and has many people in the city, Gallio refuses to turn a Jewish religious dispute into a Roman criminal case, and after Paul leaves, Priscilla and Aquila help the gifted Apollos understand the way of God more accurately before he powerfully demonstrates from Scripture that Jesus is the Messiah.',
  write:[
   {ref:'Acts 18:3',title:'Paul is willing to work with his hands while he ministers.',text:'Ordinary labor and gospel ministry are not enemies.'},
   {ref:'Acts 18:9-10',title:'“Do not be afraid” is spoken to an apostle who apparently needed courage.',text:'Christ’s answer to fear is His presence and a command to keep speaking.'},
   {ref:'Acts 18:11',title:'Paul stays long enough to teach, not merely make converts.',text:'A year and six months in Corinth gives the new church sustained formation.'},
   {ref:'Acts 18:18',title:'Paul’s ministry still grows out of a Jewish world.',text:'The vow and haircut make little sense if we imagine him as simply anti-Jewish after turning to Gentiles.'},
   {ref:'Acts 18:26',title:'A gifted teacher can still receive correction.',text:'Apollos is eloquent and scripturally strong, yet Priscilla and Aquila help him understand more accurately.'},
   {ref:'Acts 18:28',title:'Apollos uses Scripture to point openly to Jesus as the Messiah.',text:'His learning becomes useful when it serves the gospel rather than his reputation.'}
  ],
  underline:{ref:'Acts 18:9-10',reason:'The Lord does not deny Paul’s fear; He answers it with presence, protection, purpose, and the command to keep speaking.'},
  notice:[
   {ref:'Acts 18:1-2',title:'Aquila and Priscilla arrive in Corinth because Claudius expelled Jews from Rome.',text:'Luke places their move under an imperial decree. Suetonius also reports that Claudius expelled Jews from Rome after disturbances connected with someone he calls “Chrestus.” Historians debate whether that confused name refers to disputes about Christ or to another person. Luke himself simply says the couple left because of Claudius’ order.'},
   {ref:'Acts 18:2-3',title:'“Tentmakers” may describe a broader leatherworking trade.',text:'The Greek word skēnopoios is traditionally translated tentmaker, and that may be exactly right. Ancient crafts overlapped, however, and the work may have included leather or woven shelter materials more generally. The important point is that Paul, Aquila, and Priscilla share a manual trade.'},
   {ref:'Acts 18:3',title:'Paul’s paid work is a ministry choice here, not a rule that every minister must always refuse support.',text:'Paul sometimes supported himself so money would not become an obstacle, yet his letters also defend the right of gospel workers to receive material support. Acts 18 honors honest work without turning one missionary strategy into a universal financial command.',cross:[{ref:'1 Corinthians 9:14-15',label:'Paul’s own explanation',reason:'Paul says gospel workers have a right to support even though he sometimes chooses not to use that right.'}]},
   {ref:'Acts 18:4-6',title:'Paul’s turn toward Gentiles in Corinth is local and strategic, not a permanent rejection of Jewish people.',text:'After strong opposition in this synagogue, he says he will go to the Gentiles. Yet Acts soon shows him entering synagogues again in other cities. The statement concerns responsibility for rejecting this message in this setting, not hostility toward Jews as a people.'},
   {ref:'Acts 18:6',title:'“Your blood be upon your own heads” is prophetic responsibility language.',text:'Paul is saying he has faithfully delivered the warning and is not responsible for another person’s refusal. The phrase is not a threat that Paul himself will harm anyone.',cross:[{ref:'Ezekiel 33:7-9',label:'Watchman background',reason:'Ezekiel describes the watchman as responsible to give warning, while the hearer remains responsible for the response.'}]},
   {ref:'Acts 18:7-8',title:'The mission moves next door—and the synagogue ruler himself believes.',text:'Paul teaches in the house of Titius Justus beside the synagogue, while Crispus, the synagogue ruler, believes with his household. Luke places opposition and surprising conversion side by side.'},
   {ref:'Acts 18:8',title:'Crispus is one of the few Corinthians Paul says he personally baptized.',text:'First Corinthians names Crispus, Gaius, and the household of Stephanas among Paul’s own baptisms. That fits Acts: many Corinthians are baptized, but Paul does not have to perform every baptism personally for the mission to be genuinely his.',cross:[{ref:'1 Corinthians 1:14-17',label:'Paul remembers the baptisms',reason:'Paul names Crispus among the few Corinthians he personally baptized and stresses that his primary calling was to preach the gospel.'}]},
   {ref:'Acts 18:9-10',title:'The Lord’s “Be not afraid” implies courage does not require the absence of fear.',text:'Paul has already endured repeated hostility, and First Corinthians later remembers his arrival in weakness, fear, and trembling. The vision does not shame him for needing reassurance. Christ meets fear with “I am with thee,” then tells Paul to continue speaking.'},
   {ref:'Acts 18:10',title:'“I have much people in this city” has been read through different theological lenses.',text:'Many Reformed readers hear God’s electing purpose: people in Corinth belong to Him before their visible conversion. Others emphasize divine foreknowledge or simply the people God intends to gather through Paul’s preaching. Whatever framework is used, the sentence gives Paul confidence that his labor in Corinth will not be empty.'},
   {ref:'Acts 18:11',title:'Eighteen months is unusually long for Paul’s ministry in one place at this stage.',text:'Luke slows the travel narrative down. Corinth needs more than an initial evangelistic burst; Paul remains to teach the word of God among them. The later Corinthian letters show both how much grace took root and how much patient formation the church still needed.'},
   {ref:'Acts 18:12-17',title:'Gallio provides one of Acts’ strongest chronological anchors.',text:'An inscription from Delphi helps date Gallio’s proconsulship of Achaia to about A.D. 51–52. Because Paul appears before him during the Corinthian stay, this scene gives historians an important fixed point for reconstructing Paul’s wider chronology.'},
   {ref:'Acts 18:12-16',title:'Gallio refuses to treat this dispute as ordinary Roman crime.',text:'The accusers say Paul persuades people to worship God contrary to law, but Gallio hears a dispute about words, names, and Jewish law rather than a Roman offense. His ruling gives Paul breathing room, but it should not be exaggerated into a permanent Roman declaration that Christianity is legally protected everywhere.'},
   {ref:'Acts 18:17',title:'Sosthenes is beaten in front of Gallio, but Luke does not clearly identify the attackers.',text:'Some translations and interpreters understand “all of them” as the crowd or Greeks; others connect the violence with members of the synagogue. Luke’s wording leaves the group somewhat unclear. It is also possible—but not certain—that this Sosthenes later became Paul’s Christian coworker named in 1 Corinthians 1:1.'},
   {ref:'Acts 18:18',title:'Paul’s haircut at Cenchrea is connected with a vow, though Acts gives very little detail.',text:'The grammar most naturally points to Paul as the one who had taken the vow. Many interpreters compare it with a temporary Nazirite-type vow of devotion and thanksgiving, though Acts never names the vow. The scene shows Paul can freely practice a Jewish devotion without treating it as a requirement for Gentile salvation.'},
   {ref:'Acts 18:19-21',title:'The KJV includes Paul saying he must keep the coming feast in Jerusalem, but that phrase is absent from many early manuscripts.',text:'The longer wording fits Paul’s Jewish setting and is found in later manuscript tradition. Most modern critical editions omit “I must by all means keep this feast that cometh in Jerusalem.” The firmly attested point is that Paul declines a longer stay in Ephesus, says he will return if God wills, and sails away.'},
   {ref:'Acts 18:21',title:'“If God will” is dependence, not a verbal charm.',text:'Paul makes a real plan to return to Ephesus while openly submitting that plan to God’s providence. The New Testament does not teach that saying the phrase mechanically guarantees humility; it teaches the posture the phrase expresses.',cross:[{ref:'James 4:13-15',label:'The same posture',reason:'James warns against planning as though tomorrow were under human control and says believers should acknowledge the Lord’s will.'}]},
   {ref:'Acts 18:24-26',title:'Apollos already knows much truth, yet his understanding is incomplete.',text:'He is eloquent, powerful in the Scriptures, instructed in the way of the Lord, fervent in spirit, and teaching accurately about Jesus, but he knows only John’s baptism. Acts does not mock him. Priscilla and Aquila recognize both the real gift and the real gap.'},
   {ref:'Acts 18:26',title:'Priscilla and Aquila correct Apollos privately rather than humiliating him publicly.',text:'They take him aside and explain the way of God more accurately. Priscilla is named alongside Aquila—and often before him in the New Testament—so her role should not be erased. At the same time, Acts does not divide the private explanation into a transcript telling us exactly which spouse taught which sentence.'},
   {ref:'Acts 18:27-28',title:'Apollos receives both correction and commendation, then becomes more useful rather than less.',text:'Believers encourage him and write to disciples in Achaia to receive him. There he greatly helps those who had believed through grace and publicly demonstrates from the Scriptures that Jesus is the Christ. Humble correction does not destroy his ministry; it strengthens it.'}
  ],
  reflections:['Am I able to receive reassurance from Christ without pretending I was never afraid in the first place?','When someone is gifted but incomplete in understanding, do I instinctively embarrass them, dismiss them, or help them more accurately and privately?','Do my plans have enough humility in them to remain real plans while still being surrendered to God’s will?'],
  commentary:{voice:'John Wesley',identity:'Anglican minister and founder of the Methodist movement, 1703–1791',quote:'Speak and hold not thy peace - For thy labour shall not be in vain.',plain:'Wesley reads Jesus’ words as encouragement to keep going when fear might make Paul quiet. The promise does not mean ministry will become painless; Acts has already shown otherwise. It means Paul’s work in Corinth is not pointless because Christ is present and intends to gather people through the message.',source:'Explanatory Notes upon the New Testament — Acts 18:9–10',url:'https://www.biblehub.com/commentaries/wes/acts/18.htm'},
  question:{q:'Why did Paul take a Jewish vow after teaching that Gentiles did not need to keep the law to be saved?',short:'Because Acts distinguishes voluntary Jewish practice from making Jewish practice a condition of salvation. Paul can freely keep a vow as a Jewish believer while refusing to impose circumcision or Torah observance on Gentiles as the basis of acceptance with God.',more:'Acts 15 has already settled the gospel issue: Gentiles are saved through the grace of the Lord Jesus and are not required to become Jews. That decision does not require Jewish believers to abandon every Jewish custom. Paul himself continues to move comfortably in synagogues, observes Jewish rhythms, and here apparently completes a vow marked by cutting his hair at Cenchrea. Christians debate the precise kind of vow because Luke does not name it; a temporary Nazirite-type devotion is a common suggestion. The important distinction is between freedom and requirement. Paul can practice a custom voluntarily as an act of devotion or cultural identity while strongly opposing anyone who turns that same kind of practice into a condition for salvation.'}
 }
});
render();
