// John 21 — Living Bookmark card.
Object.assign(studies,{
 'John 21':{body:''}
});

Object.assign(studyMeta,{
 'John 21':{
  oneLine:'The risen Jesus meets seven disciples after an empty night of fishing, gives an abundant catch and breakfast by the sea, restores Peter with three searching questions and a renewed shepherding commission, foretells the cost of Peter’s discipleship, corrects comparison with the beloved disciple, and closes the Gospel with eyewitness testimony too full for one book to contain.',
  write:[
   {ref:'John 21:6',title:'The difference between empty nets and abundance is one word from Jesus.',text:'The disciples cast where He tells them and suddenly cannot draw the net for the multitude of fish.'},
   {ref:'John 21:7',title:'The beloved disciple recognizes Jesus first; Peter moves toward Him first.',text:'Different disciples can love the same Lord with different temperaments.'},
   {ref:'John 21:12',title:'The risen Lord prepares breakfast for tired disciples.',text:'Resurrection glory does not make ordinary care beneath Him.'},
   {ref:'John 21:15',title:'Jesus does not merely ask Peter whether he feels sorry.',text:'He asks, “Lovest thou me?” and then gives him sheep to feed.'},
   {ref:'John 21:19',title:'Restoration returns Peter to the same basic call.',text:'After failure, forgiveness, and future cost, Jesus still says, “Follow me.”'},
   {ref:'John 21:22',title:'Another disciple’s calling is not Peter’s assignment.',text:'“What is that to thee? follow thou me.”'}
  ],
  underline:{ref:'John 21:17',reason:'Peter’s threefold denial is answered by a threefold question of love and a renewed commission: failure is faced honestly without becoming the end of his calling.'},
  notice:[
   {ref:'John 21:1-6',title:'The chapter reads like an epilogue, but it is not a late chapter missing from the manuscript tradition.',text:'John 20 already sounds like a conclusion with its purpose statement, and chapter 21 adds a final resurrection scene focused especially on Peter and the beloved disciple. That literary shape has led scholars to discuss how the epilogue relates to the rest of the Gospel, but there is no ancient manuscript evidence for a Gospel of John circulating without chapter 21. It belongs to the received text from our earliest copies.'},
   {ref:'John 21:3-6',title:'The disciples’ night of fishing is not necessarily proof they abandoned their calling.',text:'They are in Galilee, fishing is familiar work, and Jesus has already risen. The text does not rebuke them for being in the boat. The point is the contrast between a fruitless night and the sudden abundance that comes when the stranger on shore tells them where to cast.'},
   {ref:'John 21:7-8',title:'John and Peter respond differently without John turning the difference into a competition.',text:'The beloved disciple says, “It is the Lord.” Peter immediately throws himself into the sea to get to Jesus. One recognizes quickly; the other acts quickly. The Gospel allows distinct personalities inside genuine discipleship.'},
   {ref:'John 21:9',title:'The second charcoal fire quietly brings Peter back near the setting of his failure.',text:'The Greek word anthrakia appears in John at the fire where Peter denied Jesus and here at the breakfast where Jesus restores him. John never says, “This fire symbolizes the denial,” but the rare repeated detail makes the scene feel intentionally familiar.',cross:[{ref:'John 18:18',label:'Narrative echo',reason:'Peter’s denials unfolded beside the only other charcoal fire named in John.'}]},
   {ref:'John 21:10-11',title:'John gives the exact number—153 fish—but never explains a secret code behind it.',text:'Christians have proposed many symbolic calculations across the centuries, from numbers of nations to mathematical patterns. None has won anything close to consensus, and the text itself supplies no key. The safest observation is the one John makes: the catch is enormous, precisely remembered, and yet the net is not torn.'},
   {ref:'John 21:12-14',title:'Jesus has breakfast ready before the disciples bring their catch.',text:'He invites them to eat and gives them bread and fish. The scene is quiet, bodily, and recognizably resurrection life: the disciples are not communing with a disembodied memory. The Lord who defeated death cooks breakfast by the sea.'},
   {ref:'John 21:15',title:'“Lovest thou me more than these?” is genuinely ambiguous about what “these” refers to.',text:'Jesus may be asking whether Peter loves Him more than the other disciples do—especially poignant after Peter’s earlier boasts—or whether Peter loves Jesus more than the fishing life and its equipment. The grammar does not settle the referent with certainty, so the note should not pretend it does. Either way, Jesus makes love for Himself the foundation of the commission that follows.'},
   {ref:'John 21:15-17',title:'The alternation between agapaō and phileō is probably not a hidden three-level code for different kinds of love.',text:'Older and modern interpreters have sometimes built a major distinction on Jesus using one Greek verb and Peter another. But John regularly varies synonyms for stylistic reasons, and many ancient Greek-speaking interpreters did not hear a sharp contrast here. The clearest emphasis is the threefold questioning itself, Peter’s grief at the third question, and Jesus’ repeated commission to care for His flock.'},
   {ref:'John 21:15-17',title:'Peter is restored publicly to responsibility, not merely privately reassured.',text:'Jesus asks three times and gives three pastoral commands: feed or tend My lambs and sheep. The parallel with Peter’s three denials is hard to miss even though John does not spell it out. Grace does not pretend the failure never happened; it meets Peter at the wound and gives him work to do for Christ’s people.'},
   {ref:'John 21:18-19',title:'Following Jesus will eventually cost Peter his life.',text:'Jesus describes an old age in which Peter will stretch out his hands and be taken where he does not wish to go; John says this signifies the kind of death by which Peter will glorify God. Early Christian tradition associates Peter with crucifixion, but John’s main point is the cost of discipleship. The restored man is called again: “Follow me.”'},
   {ref:'John 21:20-23',title:'Jesus refuses Peter’s invitation to compare callings.',text:'Peter looks at the beloved disciple and asks, “what shall this man do?” Jesus answers, in effect, that the other disciple’s future is Christ’s business; Peter’s task is to follow. John then corrects a rumor that Jesus had promised the beloved disciple would not die. Careful testimony includes correcting what Jesus did not actually say.'},
   {ref:'John 21:24-25',title:'The Gospel closes by identifying testimony and acknowledging selectivity.',text:'The beloved disciple is connected with the witness behind these things, and the community affirms that his testimony is true. Then John ends with deliberate overflow: Jesus did far more than any one book could contain. The purpose was never exhaustive biography but trustworthy witness that leads to life.'}
  ],
  reflections:['When I remember a serious failure, do I imagine Jesus only wants an apology—or can I believe He may also restore me to faithful service?','Whose calling am I watching so closely that I am neglecting Jesus’ simpler word to me: “Follow thou me”?'],
  commentary:{voice:'Alexander Maclaren',identity:'Scottish Baptist preacher and expositor, 1826–1910',quote:'The service of man is the garb of the love of God.',plain:'Maclaren hears Jesus’ threefold commission as the practical shape of Peter’s profession of love. “Lovest thou me?” does not end in private emotion. Love for Christ puts on work clothes and cares for the people Christ calls His lambs and sheep.',source:'Expositions of Holy Scripture — John 21',url:'https://biblehub.com/commentaries/maclaren/john/21.htm'},
  question:{q:'Why does Jesus use two different Greek words for “love” when He questions Peter?',short:'A major spiritual hierarchy between agapaō and phileō is probably more than the passage can bear. John often varies synonyms, and many Greek-speaking ancient interpreters did not treat the two verbs here as sharply different levels of love.',more:'A popular reading says Jesus asks twice for a higher agapē-love while Peter can offer only lower philia-love, until Jesus comes down to Peter’s level on the third question. That can preach powerfully, but the linguistic case is weaker than it is often presented. John varies other paired words in the same scene—feed/tend, lambs/sheep—and elsewhere uses agapaō and phileō for love without maintaining a rigid “divine versus friendly” ladder. The stronger narrative signal is three questions after three denials. Peter is grieved because Jesus asks the third time, appeals to Jesus’ complete knowledge, and receives again the command to care for the flock.'}
 }
});
render();