// Luke 7–9 — Living Bookmark cards.
Object.assign(studies,{
 'Luke 7':{body:''},
 'Luke 8':{body:''},
 'Luke 9':{body:''}
});

Object.assign(studyMeta,{
 'Luke 7':{
  oneLine:'Jesus praises a Gentile centurion’s faith, raises a widow’s only son, answers John the Baptist’s prison questions with kingdom evidence, and receives a notorious woman whose love reveals how deeply she knows she has been forgiven.',
  write:[
   {ref:'Luke 7:6-7',title:'The centurion feels unworthy yet trusts Jesus’ authority.',text:'He does not ask Jesus to prove Himself by proximity; he believes a word is enough.'},
   {ref:'Luke 7:9',title:'Jesus marvels at faith found outside Israel.',text:'A Gentile officer understands authority in a way many covenant insiders have not.'},
   {ref:'Luke 7:13',title:'Jesus acts because He has compassion.',text:'The widow does not first make a speech or demonstrate faith; Jesus sees her grief and moves toward it.'},
   {ref:'Luke 7:22',title:'Jesus answers John by pointing to what the kingdom is actually doing.',text:'Blind see, lame walk, lepers are cleansed, deaf hear, dead are raised, and poor hear good news.'},
   {ref:'Luke 7:35',title:'Wisdom is vindicated by what it produces.',text:'Complaints against both John’s austerity and Jesus’ table fellowship cannot cancel the fruit of God’s wisdom.'},
   {ref:'Luke 7:47',title:'Much love reveals much forgiveness received.',text:'The woman is not buying forgiveness with emotion; her love shows how deeply mercy has reached her.'},
   {ref:'Luke 7:50',title:'Jesus sends her away with salvation and peace.',text:'Her faith has reached toward the One who forgives.'}
  ],
  underline:{ref:'Luke 7:47',reason:'The woman’s love is not payment for grace; it is the visible overflow of knowing how much grace has forgiven.'},
  notice:[
   {ref:'Luke 7:1-10',title:'The centurion understands Jesus through the logic of delegated authority.',text:'He is a man under authority who also gives orders, so he reasons that Jesus does not need physical closeness to command sickness. Luke also tells the story through Jewish elders and then friends; Matthew summarizes the encounter more directly. Ancient narrative could describe a representative’s words as the principal person’s request without requiring a contradiction.'},
   {ref:'Luke 7:2-5',title:'This Gentile officer already has an unusual relationship with the Jewish community.',text:'The elders say he loves their nation and helped build their synagogue. Yet the centurion himself does not rest his appeal on their praise; he says he is not worthy for Jesus to enter his house. Luke places respected reputation beside deep humility.'},
   {ref:'Luke 7:11-17',title:'The widow of Nain receives mercy before she asks for it.',text:'Her only son is dead, which means the grief also carries serious social and economic vulnerability. Jesus sees her, has compassion, tells her not to weep, touches the bier, and gives her son back. Luke’s wording echoes Old Testament raising stories but presents Jesus acting with direct personal authority.',cross:[{ref:'1 Kings 17:17-24',label:'Story parallel',reason:'Elijah raises a widow’s son and gives the child back to his mother; Luke’s scene deliberately recalls that kind of prophetic mercy.'}]},
   {ref:'Luke 7:18-23',title:'John’s question from prison is answered with Scripture-shaped evidence, not ridicule.',text:'John had faithfully announced Jesus, yet imprisonment and unmet expectations create a real question: “Art thou he that should come?” Jesus points to deeds that echo Isaiah’s restoration promises and adds a gentle beatitude for the person who does not stumble over the way He fulfills Messiah’s work.',cross:[{ref:'Isaiah 35:5-6',label:'Messianic background',reason:'Isaiah describes blind eyes opened, deaf ears unstopped, and the lame leaping in the age of God’s salvation.'},{ref:'Isaiah 61:1',label:'Messianic background',reason:'Good news to the poor is part of Isaiah’s Spirit-anointed mission language already used in Luke 4.'}]},
   {ref:'Luke 7:24-30',title:'Jesus defends John after John’s messengers leave.',text:'He does not let the prison question erase John’s calling. John is more than a prophet and the promised messenger who prepares the Lord’s way. Yet Jesus also says the least in God’s kingdom is greater—not because John was spiritually defective, but because the kingdom’s fuller privileges arrive with the Messiah John announces.'},
   {ref:'Luke 7:31-35',title:'The “children in the marketplace” expose people determined not to respond.',text:'John comes fasting and is called demonic; Jesus comes eating and is called a glutton and friend of sinners. Opposite ministry styles receive opposite complaints because the real resistance is not style. A heart unwilling to repent can always invent a reason to reject God’s messenger.'},
   {ref:'Luke 7:36-50',title:'The unnamed woman is not identified by Luke as Mary Magdalene.',text:'Later tradition often merged several women in the Gospels, but Luke does not call this woman Mary. In the next chapter he introduces Mary Magdalene by name and describes her differently. It is safer to let the unnamed woman remain unnamed.'},
   {ref:'Luke 7:44-47',title:'Jesus turns neglected hospitality into a mirror for Simon’s heart.',text:'The woman supplies tears, kisses, and ointment while the host has offered none of the ordinary gestures Jesus names. Her actions do not purchase pardon. Jesus’ little parable makes the order clear: the person who knows a large debt has been cancelled loves deeply; small awareness of forgiveness produces little love.'}
  ],
  reflections:['When God does not act in the way I expected, can I bring Him the question without throwing away everything I already know of Christ?','Does my love for Jesus look like the response of someone who knows she has been forgiven much?'],
  commentary:{voice:'Alexander Maclaren',identity:'Scottish Baptist preacher and expositor, 1826–1910',quote:'her love was the proof of her forgiveness',plain:'Maclaren carefully guards the order in Jesus’ words. The woman’s love is evidence that forgiveness has reached her; it is not the price she pays to persuade God to forgive. Grace comes first, and grateful love follows.',source:'Expositions of Holy Scripture — Luke 7',url:'https://biblehub.com/commentaries/maclaren/luke/7.htm'},
  question:{q:'Was the “woman which was a sinner” Mary Magdalene?',short:'Luke never says that, and there is no good textual reason to identify them as the same woman.',more:'The woman in Luke 7 is deliberately unnamed. Luke 8 then introduces Mary Magdalene by name as a woman from whom seven demons had gone out; he does not say she had been the woman at Simon’s house or describe her as a prostitute. Later Christian tradition often blended separate Gospel women together, but Bookmark should not turn that tradition into a fact the text never states.'}
 },
 'Luke 8':{
  oneLine:'Luke shows women materially supporting Jesus’ mission, warns that the word must be heard with a good and persevering heart, and then displays Jesus’ authority over storm, demons, chronic uncleanness, and death.',
  write:[
   {ref:'Luke 8:3',title:'Women helped finance Jesus’ traveling ministry.',text:'Joanna, Susanna, and many others are named as active supporters, not background scenery.'},
   {ref:'Luke 8:8',title:'Jesus wants hearing that becomes fruit.',text:'The seed is good; the question is what kind of reception the word receives.'},
   {ref:'Luke 8:15',title:'Good soil includes patient endurance.',text:'Fruit grows from hearing, keeping, and persevering—not from one emotional response.'},
   {ref:'Luke 8:21',title:'Jesus defines family around hearing and doing God’s word.',text:'Kingdom kinship is not merely biological closeness to Jesus.'},
   {ref:'Luke 8:25',title:'The storm ends with a question about Jesus’ identity.',text:'The disciples move from fear of the water to awe of the One whom wind and waves obey.'},
   {ref:'Luke 8:39',title:'The delivered man is sent home as a witness.',text:'Jesus turns the man once isolated among tombs into a public teller of mercy.'},
   {ref:'Luke 8:48',title:'Jesus calls the hidden sufferer “Daughter.”',text:'He gives her more than a private cure: He gives public peace and personal recognition.'}
  ],
  underline:{ref:'Luke 8:15',reason:'Luke’s good soil is not merely a person who hears gladly; it is a person who holds the word fast and bears fruit with patience.'},
  notice:[
   {ref:'Luke 8:1-3',title:'Luke deliberately records women as substantial participants in the ministry.',text:'Mary Magdalene, Joanna, Susanna, and many others travel within the wider ministry circle and provide from their own resources. Joanna’s connection to Herod’s household is especially striking. Luke repeatedly preserves women’s names, speech, faith, service, and witness in ways that matter to the story.'},
   {ref:'Luke 8:2',title:'Mary Magdalene’s seven demons are not a coded way of saying she was sexually immoral.',text:'Luke says she had been delivered from severe demonic bondage. Scripture never labels her a prostitute. That later identification should not be read back into the text.'},
   {ref:'Luke 8:4-15',title:'The sower parable is about what happens after people hear.',text:'The devil removes the word from some; some receive with joy but have no root when testing comes; others are choked by cares, riches, and pleasures; good soil holds the word in an honest and good heart and bears fruit with patience. Initial enthusiasm is not Luke’s only measure of hearing.'},
   {ref:'Luke 8:16-18',title:'The lamp sayings make hearing accountable.',text:'Revelation is meant to come into the light, and Jesus warns, “Take heed therefore how ye hear.” The more faithfully light is received and used, the more understanding opens; careless hearing can lose even what a person thinks he possesses.'},
   {ref:'Luke 8:19-21',title:'Jesus’ true family saying is expansion, not contempt for His mother.',text:'He does not deny His natural family. He announces that hearing and doing God’s word creates a covenant family open to people who could never claim blood relation to Him.'},
   {ref:'Luke 8:22-25',title:'The stilling of the storm uses imagery Scripture associates with God’s rule over the sea.',text:'Jesus rebukes wind and raging water, and calm follows. Israel’s Psalms repeatedly praise the LORD as the One who stills stormy seas. Luke leaves the disciples asking the right question: “What manner of man is this?”',cross:[{ref:'Psalm 107:28-29',label:'Storm-stilling background',reason:'The psalm describes the LORD making the storm calm after distressed sailors cry out.'}]},
   {ref:'Luke 8:26-39',title:'The Gerasene man is restored in every direction Jesus’ opponents had failed to restore him.',text:'He had been naked, violent, isolated, and driven among tombs. After Jesus’ command he is clothed, in his right mind, sitting at Jesus’ feet, and finally sent home. The story treats him as a person to be restored, not a frightening problem to be discarded.'},
   {ref:'Luke 8:43-48',title:'The bleeding woman would have lived with physical suffering and ritual uncleanness.',text:'Leviticus treats ongoing blood discharge as unclean, affecting ordinary contact and worship. She reaches secretly, but Jesus draws her into the open and calls her “Daughter.” Her uncleanness does not contaminate Him; His healing restores her.',cross:[{ref:'Leviticus 15:25-27',label:'Law background',reason:'The law explains the ritual uncleanness connected with a prolonged discharge of blood.'}]},
   {ref:'Luke 8:40-56',title:'Jairus’s daughter and the bleeding woman are intentionally woven together.',text:'One is a synagogue ruler’s twelve-year-old only daughter; the other has suffered twelve years and lost her living seeking help. Jesus is not forced to choose whose need matters more. Delay for one does not mean neglect of the other; He has compassion and authority enough for both.'}
  ],
  reflections:['What currently threatens to choke the word in me—pressure, shallow roots, anxiety, money, pleasure, or simple inattention?','Do I believe another person receiving Jesus’ attention means there will somehow be less mercy left for me?'],
  commentary:{voice:'Alexander Maclaren',identity:'Scottish Baptist preacher and expositor, 1826–1910',quote:'We do not rob one another of His gifts.',plain:'Maclaren is reflecting on Jesus stopping for the suffering woman while Jairus waits in agony. Christ’s attention is not a scarce resource. Another person’s mercy does not reduce what He can give, even when His timing feels painfully slow.',source:'Expositions of Holy Scripture — Luke 8',url:'https://biblehub.com/commentaries/maclaren/luke/8.htm'},
  question:{q:'Why did Jesus ask “Who touched me?” if He already knew power had gone out from Him?',short:'The question brings the hidden woman into personal, public encounter; the healing is not allowed to remain an anonymous taking of power.',more:'Luke does not present Jesus as helplessly confused in the crowd. He distinguishes this touch from ordinary jostling and says He knows power has gone out from Him. By calling the woman forward, Jesus lets her tell the truth, publicly confirms the healing, calls her “Daughter,” connects the cure to faith rather than magic, and sends her away in peace. She receives relationship and restoration, not just symptom relief.'}
 },
 'Luke 9':{
  oneLine:'Jesus sends the Twelve, feeds the multitude, receives Peter’s confession, announces the cross and daily discipleship, is transfigured while speaking of His coming “exodus,” corrects the disciples’ pride and vengeance, and resolutely begins the long road toward Jerusalem.',
  write:[
   {ref:'Luke 9:2',title:'The Twelve are sent to preach and heal under Jesus’ authority.',text:'Mission is an extension of what Jesus gives them, not a platform they manufacture for themselves.'},
   {ref:'Luke 9:17',title:'Jesus’ provision leaves twelve baskets over.',text:'The hungry crowd is not barely managed; the sign ends in abundance.'},
   {ref:'Luke 9:20',title:'Peter names Jesus “The Christ of God.”',text:'Luke moves from public speculation to the disciples’ own answer about Jesus’ identity.'},
   {ref:'Luke 9:23',title:'Luke alone adds “daily” to taking up the cross.',text:'Following Jesus is not one dramatic moment; self-denying allegiance becomes a repeated way of life.'},
   {ref:'Luke 9:35',title:'The Father’s command is simple: “hear him.”',text:'Moses and Elijah stand with Jesus, but the divine voice directs the disciples to the Son.'},
   {ref:'Luke 9:48',title:'Greatness is measured by how one receives the little.',text:'Jesus overturns the disciples’ argument about rank by placing a child in their midst.'},
   {ref:'Luke 9:51',title:'Jesus sets His face toward Jerusalem.',text:'Luke’s long travel section begins with deliberate movement toward the suffering Jesus already knows is coming.'}
  ],
  underline:{ref:'Luke 9:51',reason:'This is a hinge in Luke: Jesus consciously turns toward Jerusalem, and the Gospel begins a long journey shaped by the cross ahead.'},
  notice:[
   {ref:'Luke 9:1-6',title:'The Twelve are sent with authority and dependence.',text:'Jesus gives power, commissions proclamation of God’s kingdom, and tells them not to build the mission around stockpiled travel security. The instructions fit this particular Galilean mission and train the apostles to rely on God’s provision and the hospitality of those who receive the message.'},
   {ref:'Luke 9:10-17',title:'The feeding begins with Jesus telling the disciples, “Give ye them to eat.”',text:'They see five loaves, two fish, and an impossible crowd. Jesus organizes the people, gives thanks, breaks, and gives through the disciples until everyone is filled. The twelve leftover baskets underline provision large enough for the people Jesus has gathered.'},
   {ref:'Luke 9:18-27',title:'Peter’s confession is immediately followed by a redefinition of what Messiahship means.',text:'Jesus is the Christ of God, but He will not let that title be filled with expectations of triumph without suffering. He predicts rejection, death, and resurrection, then tells followers that their path also takes the shape of self-denial and cross-bearing.'},
   {ref:'Luke 9:23',title:'“Take up his cross daily” is not a poetic name for every inconvenience.',text:'In the Roman world a cross was an instrument of shame and execution. Jesus is calling for daily surrender of the right to rule one’s own life in opposition to Him. Ordinary hardships can become places of faithful obedience, but the saying should not be reduced to “this annoying thing is my cross.”'},
   {ref:'Luke 9:28-36',title:'Luke says Moses and Elijah speak with Jesus about His “decease”—literally His exodus.',text:'The Greek word is exodos. On the mountain, figures representing Law and Prophets speak about what Jesus will accomplish at Jerusalem. His death is therefore more than an accident awaiting Him; Luke frames it as a saving departure that fulfills God’s story and leads through suffering toward glory.'},
   {ref:'Luke 9:35',title:'The transfiguration does not put Jesus on a three-person level with Moses and Elijah.',text:'Peter proposes three shelters, but the cloud comes and the Father says, “This is my beloved Son: hear him.” When the voice is past, Jesus is found alone. Moses and Elijah matter precisely because they point toward the Son who fulfills the story they represent.'},
   {ref:'Luke 9:46-50',title:'Two disciple problems sit together: craving rank and policing outsiders.',text:'They argue about which of them is greatest, then John objects to someone casting out demons because he does not follow with their group. Jesus answers both instincts by lowering status: receive the child, and do not forbid the outsider who is not against you.'},
   {ref:'Luke 9:51-56',title:'The Samaritan rejection begins the Jerusalem journey by exposing retaliatory zeal in the disciples.',text:'The village refuses Jesus because His face is set toward Jerusalem, reflecting the old Jewish-Samaritan religious divide. James and John want Elijah-like fire. Jesus rebukes them. The KJV includes a fuller wording in verses 55-56 about the spirit they are of and the Son of man coming to save rather than destroy; several early manuscripts lack some of those words, so many modern translations mark or omit the longer form. The rebuke itself is secure.'},
   {ref:'Luke 9:57-62',title:'The three would-be followers show how uncompromising the journey has become.',text:'Jesus offers no comfortable illusion: the Son of man has nowhere to lay His head, kingdom allegiance can outrank even solemn social expectations, and the plowman cannot move straight while constantly looking backward. These sayings are intentionally sharp because the road now points toward Jerusalem.'}
  ],
  reflections:['Where have I tried to keep Jesus as “Christ” while resisting the cross-shaped kind of following He describes?','Do I ever mistake zeal for Jesus with the right to be harsh toward people who reject me or do not belong to my group?'],
  commentary:{voice:'Alexander Maclaren',identity:'Scottish Baptist preacher and expositor, 1826–1910',quote:'Because He chose to die.',plain:'Maclaren is explaining the force of Jesus setting His face toward Jerusalem. Luke presents the cross as something Jesus approaches knowingly and willingly. The journey is not Jesus being trapped by events; it is the Son moving with settled purpose toward the saving death He has already foretold.',source:'Expositions of Holy Scripture — Luke 9',url:'https://biblehub.com/commentaries/maclaren/luke/9.htm'},
  question:{q:'What does Jesus mean by “Let the dead bury their dead” in Luke 9:60?',short:'He uses deliberate shock to say that the kingdom’s call cannot always be postponed until every social obligation feels complete; He is not teaching contempt for parents or funerals.',more:'Honoring parents remains part of biblical obedience, and Jesus Himself condemns religious excuses for neglecting family duty. Here the force is urgency. “Let the dead bury their dead: but go thou and preach the kingdom of God” contrasts ordinary social life with the immediate summons of the kingdom. Some interpreters think the man may be asking for an indefinite delay until an aging father eventually dies; others take an actual burial setting. Either way, Jesus refuses a discipleship that always says “later.”'}
 }
});
render();