// Acts 10 — Living Bookmark card.
Object.assign(studies,{
 'Acts 10':{body:''}
});

Object.assign(studyMeta,{
 'Acts 10':{
  oneLine:'God prepares both a Gentile centurion named Cornelius and the apostle Peter for a barrier-breaking meeting: Peter’s vision teaches him not to call people unclean whom God is receiving, he enters a Gentile home, proclaims Jesus as Lord of all, crucified and risen Judge who grants forgiveness to everyone who believes, and the Holy Spirit falls on the uncircumcised hearers before water baptism, forcing Jewish believers to recognize that God has welcomed Gentiles without first making them Jews.',
  write:[
   {ref:'Acts 10:4',title:'Cornelius’ prayers and generosity are seen by God.',text:'His unseen devotion is not invisible in heaven.'},
   {ref:'Acts 10:15',title:'Peter is not allowed to keep calling unclean what God has cleansed.',text:'God, not inherited prejudice, gets the final word on whom He receives.'},
   {ref:'Acts 10:28',title:'Peter tells us what the vision means for people.',text:'“God hath shewed me that I should not call any man common or unclean.”'},
   {ref:'Acts 10:34-35',title:'God’s welcome is not limited by nationality.',text:'No nation has a built-in advantage that can replace a heart turned toward God.'},
   {ref:'Acts 10:36',title:'The gospel announces peace through Jesus Christ—and He is Lord of all.',text:'The Lord who came through Israel is not Israel’s private possession.'},
   {ref:'Acts 10:43',title:'The promise reaches everyone who believes.',text:'Through Jesus’ name, believers receive forgiveness of sins.'}
  ],
  underline:{ref:'Acts 10:43',reason:'Peter brings the whole message to its invitation: the prophets witness that everyone who believes in Jesus receives forgiveness through His name.'},
  notice:[
   {ref:'Acts 10:1-2',title:'Cornelius is a Roman military officer in Caesarea who already fears Israel’s God.',text:'A centurion normally commanded roughly a hundred soldiers within a cohort. The “Italian cohort” identifies a Roman military unit in Caesarea, the administrative center of Roman Judea. Cornelius is uncircumcised, yet Luke calls him devout, God-fearing, generous to the people, and constant in prayer.'},
   {ref:'Acts 10:3-6',title:'God responds to Cornelius’ seeking by sending him to hear the gospel, not by telling him that sincere devotion makes Jesus unnecessary.',text:'The angel says his prayers and alms have come up as a memorial before God, then directs him to Peter. God honors the light Cornelius has received by giving him more light. Acts 11 will explicitly say Peter brings words by which Cornelius and his household will be saved.',cross:[{ref:'Acts 11:13-14',label:'Why Peter was summoned',reason:'Cornelius later reports that the angel promised Peter would speak words by which he and his household would be saved.'}]},
   {ref:'Acts 10:9-16',title:'The vision uses food categories Peter has obeyed all his life, but the story itself interprets the deepest point as human fellowship.',text:'Peter sees animals described by the old clean/unclean distinctions and hears, “Rise, Peter; kill, and eat.” He protests that he has never eaten anything common or unclean. The answer comes three times: what God has cleansed must not be called common. The food imagery matters, but verse 28 tells us Peter’s decisive lesson—he must no longer treat Gentile people as untouchably unclean.'},
   {ref:'Acts 10:14-16',title:'Peter’s resistance shows how deeply faithful habits can remain even when God is moving the covenant story forward.',text:'Peter is not refusing out of casual stubbornness; he is trying to remain obedient to distinctions rooted in Israel’s law. God therefore repeats the vision three times. A sincere conscience may need patient re-education when God Himself makes the next step unmistakable.'},
   {ref:'Acts 10:15',title:'The vision does not abolish moral holiness.',text:'“What God hath cleansed” concerns ceremonial food distinctions and, above all in Peter’s own interpretation, the Jew–Gentile boundary. It cannot be used to relabel conduct Scripture still calls sinful as automatically clean. The chapter is about God’s authority to remove covenant barriers and cleanse people, not about humans declaring everything morally acceptable.'},
   {ref:'Acts 10:17-23',title:'The Spirit connects the vision to actual people standing at Peter’s door.',text:'While Peter is still puzzled, Cornelius’ messengers arrive. The Spirit tells him to go with them without doubting because God has sent them. Revelation becomes obedience when Peter welcomes the Gentile delegation into the house and then travels with them.'},
   {ref:'Acts 10:23',title:'Peter does not go alone; believers from Joppa come as witnesses.',text:'Acts 11:12 will tell us six brothers accompany Peter. Their presence matters when the Jerusalem church later questions what happened. God provides multiple Jewish Christian witnesses to the Gentile outpouring so the event cannot be reduced to Peter’s private enthusiasm.'},
   {ref:'Acts 10:24-26',title:'Cornelius is devout, but Peter still refuses the posture of worship.',text:'Cornelius falls at Peter’s feet, perhaps expressing extreme reverence toward the messenger he has been told to summon. Peter immediately raises him: “Stand up; I myself also am a man.” Spiritual authority never turns an apostle into an object of worship.'},
   {ref:'Acts 10:28-29',title:'Peter explicitly interprets the vision: “I should not call any man common or unclean.”',text:'The social boundary between Jews and Gentiles had become far stricter than simple business contact; entering a Gentile home and sharing close fellowship could be treated as defiling. Peter now knows God’s command outranks that inherited separation. He comes “without gainsaying.”'},
   {ref:'Acts 10:30-33',title:'Cornelius gathers other people before Peter arrives because he expects God actually has something to say.',text:'His family and close friends are waiting. His sentence—“we are all here present before God, to hear all things that are commanded thee of God”—turns a living room into a congregation. The readiness is not admiration of Peter; it is readiness to hear and obey God’s message.'},
   {ref:'Acts 10:34-35',title:'“God is no respecter of persons” removes ethnic privilege; it does not mean every belief system is equally true.',text:'Peter’s discovery is that God does not favor a person because he is Jewish or reject another because he is Gentile. As Bengel later put it, the issue is impartiality among nations, not indifference among religions. Peter immediately goes on to preach Jesus, His death, resurrection, judgment, and forgiveness.'},
   {ref:'Acts 10:35',title:'“Accepted with him” should be read inside Cornelius’ whole story, not as salvation by moral scorekeeping.',text:'Cornelius fears God and practices righteousness before Peter arrives, and God genuinely regards his prayers and alms. Yet God still sends Peter to announce Jesus and forgiveness through faith. Christian traditions explain the precise relation of Cornelius’ prior grace, faith, and final salvation differently, but the chapter refuses both extremes: his sincere response to God is real, and the gospel of Christ is still necessary good news.'},
   {ref:'Acts 10:36',title:'“He is Lord of all” is the hinge between Israel’s story and Gentile inclusion.',text:'Peter says the word was sent to the children of Israel, preaching peace through Jesus Christ, then immediately declares Jesus Lord of all. The gospel comes through Israel’s Messiah precisely so blessing can reach beyond Israel.'},
   {ref:'Acts 10:37-39',title:'Peter’s gospel is public history, not a private mystical insight.',text:'He assumes Cornelius’ household has heard the broad report of Jesus’ ministry beginning in Galilee after John’s baptism. He then speaks as a witness: God anointed Jesus with the Holy Spirit and power, Jesus went about doing good and healing, and the witnesses saw what happened in Judea and Jerusalem.'},
   {ref:'Acts 10:38',title:'Jesus being “anointed … with the Holy Ghost and with power” describes His messianic mission, not a time when He first became divine.',text:'The eternal Son enters His public ministry as the Spirit-anointed Messiah. Acts is describing the empowerment and public commissioning of Jesus’ human ministry, not suggesting that He was merely human until the Spirit arrived.'},
   {ref:'Acts 10:39-41',title:'The cross and resurrection are both central, and the resurrection has appointed witnesses.',text:'Peter says Jesus was killed by hanging on a tree, God raised Him on the third day, and He appeared—not indiscriminately to everyone—but to witnesses God had chosen, who ate and drank with Him after He rose. The meal language stresses bodily resurrection rather than a vague spiritual survival.'},
   {ref:'Acts 10:42-43',title:'The same Jesus is appointed Judge and is also the One through whom forgiveness is offered.',text:'Peter does not choose between warning and mercy. Jesus is ordained by God as Judge of the living and dead, and the prophets testify that everyone who believes in Him receives forgiveness of sins through His name.'},
   {ref:'Acts 10:44-46',title:'The Holy Spirit interrupts Peter before he can finish the sermon.',text:'The Spirit falls on everyone hearing the word while Peter is still speaking. The Jewish believers are astonished because the gift has been poured out on Gentiles too, and the evidence they recognize is hearing them speak in tongues and magnify God. This is often called the Gentile Pentecost because God gives a visible parallel to Acts 2.'},
   {ref:'Acts 10:44-48',title:'Here the Spirit comes before water baptism, one more reason not to turn Acts into one rigid sequence chart.',text:'In Samaria, baptized believers received the Spirit after Peter and John prayed and laid hands on them. Here uncircumcised Gentiles receive the Spirit while listening, and only afterward does Peter command baptism. Luke’s theology is consistent—salvation and the Spirit are God’s gift—but the narrative order varies at major boundary-crossing moments.'},
   {ref:'Acts 10:47-48',title:'Peter treats the Spirit’s gift as God’s verdict that water baptism must not be withheld.',text:'He does not say baptism has become unnecessary because they already received the Spirit. Instead he asks who can forbid the water and commands them to be baptized in Jesus Christ’s name. Divine inclusion leads to visible incorporation into the Christian community.'}
  ],
  reflections:['Is there any kind of person I have quietly treated as less reachable, less welcome, or less worthy of patient love than God does?','When God corrects one of my long-held assumptions, do I defend the assumption or follow the evidence He has given?','Would I be able to say, like Cornelius’ household, “We are here before God to hear everything He commands,” even if it changes something comfortable?'],
  commentary:{voice:'Johann Albrecht Bengel',identity:'Lutheran scholar and New Testament commentator, 1687–1752',quote:'It is not an indifferentism of religions, but an indifferency … as to the acceptance of nations',plain:'Bengel guards Peter’s discovery from being flattened into “all beliefs are the same.” Peter has learned that ethnicity does not put one person nearer to God than another. That very discovery sends him straight into preaching Jesus as Lord of all, risen Judge, and the One through whom forgiveness is received.',source:'Gnomon of the New Testament — Acts 10:35',url:'https://biblehub.com/commentaries/bengel/acts/10.htm'},
  question:{q:'Was Cornelius already saved before Peter preached Jesus to him?',short:'Christians answer the timing differently, but Acts gives two facts we should keep together: God genuinely receives Cornelius’ prayers and devotion, and God deliberately sends Peter to tell him the saving message about Jesus.',more:'Some interpreters say Cornelius was already responding to God in genuine faith and therefore already stood in saving grace, with Peter bringing fuller knowledge and incorporation into the church. Others point especially to Acts 11:14—Peter will speak words “whereby thou and all thy house shall be saved”—and understand his salvation as occurring when he hears and believes the gospel in Acts 10. Catholic, Orthodox, Wesleyan, Reformed, and other traditions frame the relation between prior grace, implicit faith, explicit faith, and salvation differently. Luke does not stop to give a systematic timeline. He does make clear that Cornelius’ seeking is real, that God takes it seriously, that nationality and circumcision are not barriers, and that God responds by bringing him Jesus rather than leaving him with sincere devotion alone.'}
 }
});
render();
