// John 13 — Living Bookmark card.
Object.assign(studies,{
 'John 13':{body:''}
});

Object.assign(studyMeta,{
 'John 13':{
  oneLine:'On the night before the cross Jesus knowingly washes His disciples’ feet—including within a company that still contains His betrayer—teaches humble service and cleansing, sends Judas into the night, calls the cross His glory, gives the new commandment to love as He has loved, and warns confident Peter that he will deny Him.',
  write:[
   {ref:'John 13:1',title:'Jesus loves His own all the way to the end.',text:'The cross is not a sudden interruption of His love; it is where that love is going.'},
   {ref:'John 13:5',title:'The Lord takes the servant’s place.',text:'Jesus kneels to wash feet before asking His disciples to serve one another.'},
   {ref:'John 13:10',title:'Cleansing is something Peter must receive before it becomes something he imitates.',text:'Jesus first deals with Peter’s need to be washed by Him.'},
   {ref:'John 13:14',title:'No act of needed service is beneath the Master’s disciple.',text:'If the Lord washes feet, His followers cannot build dignity out of refusing lowly work.'},
   {ref:'John 13:34',title:'The measure of Christian love is Jesus Himself.',text:'“As I have loved you” gives the old command a new depth and shape.'},
   {ref:'John 13:38',title:'Strong promises about ourselves are not the same as tested faithfulness.',text:'Peter offers his life confidently; Jesus knows the denial coming before morning.'}
  ],
  underline:{ref:'John 13:34-35',reason:'Jesus makes His own self-giving love the pattern by which His disciples are to become recognizable.'},
  notice:[
   {ref:'John 13:1-5',title:'John frames the footwashing with Jesus’ knowledge, authority, and love.',text:'Jesus knows His hour has come, knows where He came from and where He is going, and knows the Father has given all things into His hands. Then those hands take a towel and wash dirty feet. John does not present service as insecurity or lack of status. Jesus serves from complete knowledge of who He is.'},
   {ref:'John 13:6-10',title:'Peter first refuses the washing, then asks for far too much.',text:'His reactions are sincere but still try to set the terms. Jesus tells him that unless He washes him, Peter has no part with Him. Then He distinguishes a person who has bathed from feet that still need washing. The Greek even uses different verbs for the full bath and the partial washing. The larger point is dependence: discipleship begins by receiving cleansing from Christ, not by impressing Him with our willingness to serve.'},
   {ref:'John 13:10-11',title:'“Ye are clean, but not all” keeps Judas inside the room without confusing outward closeness with inward faithfulness.',text:'Judas has shared meals, ministry, teaching, and the company of the Twelve, yet Jesus knows the betrayal already present. Proximity to holy things is not identical with belonging to Christ in truth.'},
   {ref:'John 13:12-17',title:'Christians have differed over whether footwashing is a continuing literal ordinance, but nobody gets to discard the command to lowly service.',text:'Some Christian communities practice literal footwashing as an ordinance; many others understand Jesus’ act primarily as an enacted pattern that can take whatever humble form love requires. The passage certainly does not allow a disciple to preserve pride while debating the ceremony. “I have given you an example” reaches the posture behind the act.'},
   {ref:'John 13:18-21',title:'Jesus quotes Psalm 41 while making clear that betrayal does not catch Him unaware.',text:'“He that eateth bread with me hath lifted up his heel against me” fits the pain of treachery by a close companion. Jesus is genuinely troubled in spirit, but He tells the disciples beforehand so that, when it happens, betrayal will not look like evidence that He lost control of His mission.',cross:[{ref:'Psalm 41:9',label:'Scripture fulfilled',reason:'Jesus applies the psalm’s language of betrayal by a trusted table companion to Judas.'}]},
   {ref:'John 13:21-30',title:'Satan’s involvement does not erase Judas’s responsibility.',text:'John has already described Judas’s choices and corruption, and now says Satan enters him as he commits himself to betrayal. Scripture can describe real spiritual evil without turning a human betrayer into a morally neutral puppet. The terrible closing words are simply, “and it was night.”'},
   {ref:'John 13:31-33',title:'Judas leaves, and Jesus immediately speaks of glory.',text:'The cross is only hours away, yet Jesus says, “Now is the Son of man glorified.” John has been preparing us for this paradox all Gospel long: Jesus’ humiliation, self-giving death, obedience, and return to the Father belong to His hour of glory.'},
   {ref:'John 13:34-35',title:'Love is not new because nobody had ever been commanded to love before.',text:'Leviticus already commands love of neighbor. The newness is bound to Jesus’ own coming and example: “as I have loved you.” The community shaped by the crucified Lord is to display His kind of love so visibly that it becomes part of its public witness.',cross:[{ref:'Leviticus 19:18',label:'Earlier command',reason:'Love of neighbor was already commanded; Jesus now places His own self-giving love at the center of the disciples’ pattern.'}]},
   {ref:'John 13:36-38',title:'Peter’s courage is real, but his self-knowledge is not yet deep enough.',text:'He insists he will lay down his life for Jesus. Before long he will deny Him three times. The irony is painful because the chapter has just shown the opposite direction of salvation: Jesus is the One who will lay down His life for Peter.'}
  ],
  reflections:['What needed, unglamorous act of service do I resist because it feels beneath me?','Where might I be making confident promises to God instead of depending humbly on the grace I will need to keep them?'],
  commentary:{voice:'Johann Albrecht Bengel',identity:'German Lutheran pastor and New Testament scholar, 1687–1752',quote:'the lesson of humble love',plain:'Bengel sees the footwashing as more than a memorable object lesson in manners. Jesus joins cleansing and humble love: the disciples first receive His service, then learn that no loving task is too low for those who call Him Lord and Master.',source:'Gnomon of the New Testament — John 13',url:'https://biblehub.com/commentaries/bengel/john/13.htm'},
  question:{q:'Does Jesus command Christians to wash one another’s feet literally?',short:'Some Christian traditions do practice literal footwashing as an ordinance; others understand Jesus’ command as a concrete example of the broader obligation to humble, practical service. Either way, the passage does not let us evade the humility Jesus requires.',more:'Jesus says both “ye also ought to wash one another’s feet” and “I have given you an example, that ye should do as I have done to you.” Christians have therefore differed over whether the exact action should be regularly repeated or whether the culturally specific act embodies a principle that must be expressed in whatever lowly service is actually needed. Bookmark does not need to erase that history. The safest center is clear: the Lord stooped to meet an ordinary bodily need, and no disciple may claim a status that makes such love beneath them.'}
 }
});
render();